### ISSUE TITLE
singop matmul.pb conver to tnnmodel error

### ISSUE THREAD

**Issue by sunjiweiswift** [Tencent/TNN#1003]
**1. 使用环境（environment）**
 - OS: Mac/Ubuntu/Centos/Docker:Ubuntu
 - OS Version:18.04

  **2. Github版本**
 - branch：Master
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 编译问题（Build failed）/ 模型转换失败（converter failed）/ 模型不对齐（model misalignment）
 - original model： Caffe/ONNX/TensorFlow/TensorFlowLite 
 （如果可以的话，请上传原始的模型文件）Tensorflow

def gen_pb(M, K, N, deploy_dir):
    pb_file = os.path.join(deploy_dir, 'matmul.pb')
    with tf.Session(config=tf.ConfigProto(gpu_options=gpu_options), graph=tf.Graph()) as sess:
        a = tf.placeholder(tf.float32, shape=(M, K), name='input_a')
        b = tf.placeholder(tf.float32, shape=(K, N), name='input_b')
        c = tf.matmul(a, b, name='output_c')
        sess.run(tf.global_variables_initializer())
        # convert_variables_to_constants 需要指定output_node_names，list()，可以多个
        constant_graph = graph_util.convert_variables_to_constants(
            sess, sess.graph_def, ['output_c'])
        # 写入序列化的 PB 文件
        with tf.gfile.FastGFile(pb_file, mode='wb') as f:
            f.write(constant_graph.SerializeToString())

    print('############pb file: ', pb_file)
    if not os.path.exists(pb_file):
        print('############no pb_file ')
        return False, pb_file

    return True, pb_file

  **4. 日志（Log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```
![image](https://user-images.githubusercontent.com/16934286/120431993-d8db3280-c3ab-11eb-80b0-a0432760ca58.png)

  **5. 截图（Screenshots）**
![image](https://user-images.githubusercontent.com/16934286/120431895-b8ab7380-c3ab-11eb-9953-e7cf58b29947.png)
onnx:
![image](https://user-images.githubusercontent.com/16934286/120432045-e8f31200-c3ab-11eb-8c7b-c3c2afccb581.png)
tnn:
![image](https://user-images.githubusercontent.com/16934286/120432082-f7d9c480-c3ab-11eb-85c0-440b73ed4d50.png)

**Comment by gttiankai** [comment]
相关代码已经 merge 到 master 分支。
