### ISSUE TITLE
__pthread_atfork被多次定义

### ISSUE THREAD

**Issue by PanJinquan** [Tencent/TNN#1009]
在Ubuntu18.04尝试打开多进程，进行编译，如下设置：
`set(TNN_OPENMP_ENABLE ON CACHE BOOL "" FORCE)  `
出现如下错误：
```
/usr/lib/x86_64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS)：在函数‘__pthread_atfork’中：
/build/glibc-S9d2JN/glibc-2.27/nptl/pthread_atfork.c:51: `__pthread_atfork'被多次定义
/usr/lib/x86_64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS):/build/glibc-S9d2JN/glibc-2.27/nptl/pthread_atfork.c:51：第一次在此定义
/usr/lib/x86_64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS)：在函数‘__pthread_atfork’中：
/build/glibc-S9d2JN/glibc-2.27/nptl/pthread_atfork.c:51: `pthread_atfork'被多次定义
/usr/lib/x86_64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS):/build/glibc-S9d2JN/glibc-2.27/nptl/pthread_atfork.c:51：第一次在此定义
```
如果不开启TNN_OPENMP_ENABLE，则正常编译通过
` set(TNN_OPENMP_ENABLE OFF CACHE BOOL "" FORCE) `

![image](https://user-images.githubusercontent.com/31611317/120616528-e7008000-c48b-11eb-8f12-da2b74131d17.png)

**Comment by powerpwang** [comment]
Hi,
1. 能否提供一些更详细的编译配置信息？例如gcc版本，编译TNN时的cmake配置项
2. 通过截图中的信息，这个错误是在链接TNN和你自己的项目时发生的，如果打开OMP单独编译TNN和运行TNN自带的测试程序TNNTest是OK的吗？以及链接TNN的Cmake配置是怎么样的？

**Comment by PanJinquan** [comment]
这是补充的信息：
`
/home/dm/app/clion-2020.1.2/bin/cmake/linux/bin/cmake -E cmake_link_script CMakeFiles/dmcv.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC -Wall -std=c++11 -g  -shared -Wl,-soname,libdmcv.so -o libdmcv.so CMakeFiles/dmcv.dir/src/object_detection.cpp.o CMakeFiles/dmcv.dir/src/Interpreter.cpp.o  -Wl,-rpath,/home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug/3rdparty/TNN:/usr/local/lib -Wl,--whole-archive 3rdparty/TNN/libTNN.so.0.1.0.0 -Wl,--no-whole-archive /usr/local/lib/libopencv_dnn.so.4.3.0 /usr/local/lib/libopencv_gapi.so.4.3.0 /usr/local/lib/libopencv_highgui.so.4.3.0 /usr/local/lib/libopencv_ml.so.4.3.0 /usr/local/lib/libopencv_objdetect.so.4.3.0 /usr/local/lib/libopencv_photo.so.4.3.0 /usr/local/lib/libopencv_stitching.so.4.3.0 /usr/local/lib/libopencv_video.so.4.3.0 /usr/local/lib/libopencv_videoio.so.4.3.0 base_build/libbase_utils.a /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so -lpthread /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so -lpthread -ldl /usr/local/lib/libopencv_imgcodecs.so.4.3.0 /usr/local/lib/libopencv_calib3d.so.4.3.0 /usr/local/lib/libopencv_features2d.so.4.3.0 /usr/local/lib/libopencv_flann.so.4.3.0 /usr/local/lib/libopencv_imgproc.so.4.3.0 /usr/local/lib/libopencv_core.so.4.3.0 
make[3]: 离开目录“/home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug”
[100%] Built target dmcv
/usr/bin/make -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/depend
make[3]: 进入目录“/home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug”
cd /home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug && /home/dm/app/clion-2020.1.2/bin/cmake/linux/bin/cmake -E cmake_depends "Unix Makefiles" /home/dm/project/SDK/object-detection-tnn-sdk /home/dm/project/SDK/object-detection-tnn-sdk /home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug /home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug /home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug/CMakeFiles/Detector.dir/DependInfo.cmake --color=
make[3]: 离开目录“/home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug”
/usr/bin/make -f CMakeFiles/Detector.dir/build.make CMakeFiles/Detector.dir/build
make[3]: 进入目录“/home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug”
[100%] Linking CXX executable Detector
/home/dm/app/clion-2020.1.2/bin/cmake/linux/bin/cmake -E cmake_link_script CMakeFiles/Detector.dir/link.txt --verbose=1
/usr/bin/c++  -Wall -std=c++11 -g   CMakeFiles/Detector.dir/src/main.cpp.o  -o Detector  -Wl,-rpath,/home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug:/home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug/3rdparty/TNN:/usr/local/lib libdmcv.so -Wl,--whole-archive 3rdparty/TNN/libTNN.so.0.1.0.0 /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so -lpthread /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so -lpthread -ldl -Wl,--no-whole-archive /usr/local/lib/libopencv_dnn.so.4.3.0 /usr/local/lib/libopencv_gapi.so.4.3.0 /usr/local/lib/libopencv_highgui.so.4.3.0 /usr/local/lib/libopencv_ml.so.4.3.0 /usr/local/lib/libopencv_objdetect.so.4.3.0 /usr/local/lib/libopencv_photo.so.4.3.0 /usr/local/lib/libopencv_stitching.so.4.3.0 /usr/local/lib/libopencv_video.so.4.3.0 /usr/local/lib/libopencv_calib3d.so.4.3.0 /usr/local/lib/libopencv_features2d.so.4.3.0 /usr/local/lib/libopencv_flann.so.4.3.0 /usr/local/lib/libopencv_videoio.so.4.3.0 /usr/local/lib/libopencv_imgcodecs.so.4.3.0 /usr/local/lib/libopencv_imgproc.so.4.3.0 /usr/local/lib/libopencv_core.so.4.3.0 base_build/libbase_utils.a 
/usr/lib/x86_64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS)：在函数‘__pthread_atfork’中：
/build/glibc-S9d2JN/glibc-2.27/nptl/pthread_atfork.c:51: `__pthread_atfork'被多次定义
/usr/lib/x86_64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS):/build/glibc-S9d2JN/glibc-2.27/nptl/pthread_atfork.c:51：第一次在此定义
/usr/lib/x86_64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS)：在函数‘__pthread_atfork’中：
/build/glibc-S9d2JN/glibc-2.27/nptl/pthread_atfork.c:51: `pthread_atfork'被多次定义
/usr/lib/x86_64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS):/build/glibc-S9d2JN/glibc-2.27/nptl/pthread_atfork.c:51：第一次在此定义
collect2: error: ld returned 1 exit status
CMakeFiles/Detector.dir/build.make:108: recipe for target 'Detector' failed
make[3]: *** [Detector] Error 1
make[3]: 离开目录“/home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug”
CMakeFiles/Makefile2:164: recipe for target 'CMakeFiles/Detector.dir/all' failed
make[2]: *** [CMakeFiles/Detector.dir/all] Error 2
make[2]: 离开目录“/home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug”
CMakeFiles/Makefile2:171: recipe for target 'CMakeFiles/Detector.dir/rule' failed
make[1]: *** [CMakeFiles/Detector.dir/rule] Error 2
make[1]: 离开目录“/home/dm/project/SDK/object-detection-tnn-sdk/cmake-build-debug”
Makefile:121: recipe for target 'Detector' failed
make: *** [Detector] Error 2
`
看样子， /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so -lpthread /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so -lpthread 被链接了两次

**Comment by PanJinquan** [comment]
@powerpwang 
错误复现代码：https://github.com/PanJinquan/TNN-Demo （已经把项目精简了，方便复现问题）
- 修改`CMakeLists.txt`设置TNN_OPENMP_ENABLE=OFF,正常编译使用，亲测，模型推理正常
        
        set(TNN_OPENMP_ENABLE OFF CACHE BOOL "" FORCE)  # Multi-Thread
        
- 修改`CMakeLists.txt`设置TNN_OPENMP_ENABLE=ON，出现'__pthread_atfork'被多次定义的错误
        
        set(TNN_OPENMP_ENABLE ON CACHE BOOL "" FORCE)  # Multi-Thread

**Comment by powerpwang** [comment]
Hi,

该问题是由于TNN-Demo项目中的CMakeLists.txt中链接选项错误导致的。TNN默认编译为动态库，即TNN_BUILD_SHARED选项默认为ON。因此，在链接TNN库时，直接使用 `target_link_libraries(dmcv TNN)`。

如果是将TNN编译为静态库，那么链接时才需要`-Wl,--whole-archive TNN -Wl,--no-whole-archive`。
例如对于TNN-Demo，编译静态库并链接的方式为如下所示。
```
set(TNN_BUILD_SHARED OFF CACHE BOOL "" FORCE)
# target_link_libraries(dmcv ${TNN})
# target_link_libraries(Detector dmcv)
target_link_libraries(Detector -Wl,--whole-archive TNN -Wl,--no-whole-archive dmcv)
```
