### ISSUE TITLE
Failed type not support: Crop  模型转换出错 caffe2tnn

### ISSUE THREAD

**Issue by damon-93** [Tencent/TNN#101]
使用docker  caffe转tnn模型的时候报错：
Failed type not support: Crop

Oh No, caff2onnx failed
the /workspace/mnet.25.onnx does not exist! please make sure the file exist!

我运行的命令是：
docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py caffe2tnn /workspace/mnet.25.prototxt /workspace/mnet.25.caffemodel -optimize -v=v1.0

是目前还不支持Crop？

**Comment by damon-93** [comment]
我是想把RetinaFace的模型转换成TNN的

**Comment by gttiankai** [comment]
是的，目前还不支持Crop，后面我们支持下。

**Comment by gttiankai** [comment]
目前直接支持了Crop算子，并且使用的FCN模型进行了对齐，更新下docker image 就可以使用了。

**Comment by yyqgood** [comment]
@damon-93 你好, RetinaFace模型你那边转换成功了吗?

**Comment by yyqgood** [comment]
Pytorch RetinaFace转换成功

**Comment by damon-93** [comment]
> @damon-93 你好, RetinaFace模型你那边转换成功了吗?

抱歉这么晚才给您回复,我今天拉取最新的docker,重新跑了一下,还是同样的问题,报错信息不一样了,如下:

----------  convert model, please wait a moment ----------

Converter Caffe to ONNX Model

Congratulations! caffe2onnx succeed!

Converter ONNX to TNN Model

Converter ONNX to TNN model failed!


我的镜像信息:
REPOSITORY                TAG                      IMAGE ID            CREATED             SIZE
turandotkay/tnn-convert   latest                   eb1db67ab01c        5 days ago          3.53GB

**Comment by damon-93** [comment]
> Pytorch RetinaFace转换成功

抱歉这么晚才给您回复,我今天拉取最新的docker,重新跑了一下,还是同样的问题,报错信息不一样了,如下:

---------- convert model, please wait a moment ----------

Converter Caffe to ONNX Model

Congratulations! caffe2onnx succeed!

Converter ONNX to TNN Model

Converter ONNX to TNN model failed!

我的镜像信息:
REPOSITORY TAG IMAGE ID CREATED SIZE
turandotkay/tnn-convert latest eb1db67ab01c 5 days ago 3.53GB
