### ISSUE TITLE
请问官方的face_alignment的demo该怎么编译得到呢？现在的demo示例里面编译完成后没有face_alignment的体验.exe文件。盼复

### ISSUE THREAD

**Issue by Wastoon** [Tencent/TNN#1014]
**1. 环境（environment）**
 - Build OS and Version: Mac/Ubuntu/Centos/Windows
 - RunTime OS Version: Linux/Android/IOS
 - RunTime DEVICE: ARM/OPENCL/METAL

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**

  **6. 运行日志（runtime log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **7. 截图（Screenshots）**
 ```txt
 将截图粘贴在这里
 Paste screenshorts here or pastebin
 ```

**Comment by Maosquerade** [comment]
功能开发中，想使用 demo 的话可以先拉取 feature_demo_stream 分支

**Comment by Wastoon** [comment]
非常感谢回复，我去尝试一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月7日(周一) 晚上8:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/TNN] 请问官方的face_alignment的demo该怎么编译得到呢？现在的demo示例里面编译完成后没有face_alignment的体验.exe文件。盼复 (#1014)




 
功能开发中，想使用 demo 的话可以先拉取 feature_demo_stream 分支
