### ISSUE TITLE
xcrun: error: unable to find utility "metal", not a developer tool or in PATH

### ISSUE THREAD

**Issue by majunfu** [Tencent/TNN#1015]
**1. 环境（environment）**
 - Build OS and Version: Mac

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
mac 平台 ，编译 build_macos_native.sh  报错

  **6. 运行日志（runtime log）**

  **7. 截图（Screenshots）**
xcrun: error: unable to find utility "metal", not a developer tool or in PATH

**Comment by seanxcwang** [comment]
Which path is printed with 'xcode-select --print-path'?
