### ISSUE TITLE
int8 vs fp32  量化結果無法對齊

### ISSUE THREAD

**Issue by joytsay** [Tencent/TNN#1017]
**1. 使用环境（environment）**
 - OS: Ubuntu/Docker 
 - OS Version: 20.04/docker pull turandotkay/tnn-convert

  **2. Github版本**
 - branch：Author: seanxcwang <66675860+seanxcwang@users.noreply.github.com>
Date:   Fri Jun 4 11:56:07 2021 +0800 
 - commit 844b0a889aacab57b17c1b8af5c25509e89059c0 (HEAD -> master, origin/master, origin/HEAD)

  **3. 详细描述bug 情况 (Describe the bug)**
 - 之前其實我有提到過 #945  退回舊版是有比較好一點 但還是無法真正對齊
 - 目前用最新TNN convert2tnn onnx2tnn 開 -align檢查TNN fp32是有對齊 
 - 然後用以下參數進行TNN fp32 -> int8 進行量化(mask112資料夾放100張圖)：
`./quantization_cmd -p /workspace/model.tnnproto  -m /workspace/model.tnnmodel  -i /workspace/mask112/  --scale 0.0078125 0.0078125 0.0078125 --bias 127.5,127.5,127.5`
 - 利用之前 @quinnrong94 提供的 int8vsfp32 工具進行量化結果的對齊 結果不盡理想(Log)
 - 下面Log可以看到fp32與int8的cosine距離無法對齊 應該在0.99左右 最新的量化對於同一張圖int8 vs fp32 cosine最高只有0.11
 - 如果方便的話 這裡提供TNN fp32 與 int8 模型 及 對齊工具：
[int8vsfp32_0608.zip](https://github.com/joytsay/lfs/raw/main/int8vsfp32_0608.zip) 請 @quinnrong94 @seanxcwang  幫忙看一下 感恩！！！

  **4. 日志（Log）**
```
 int8 vs fp32
(512,)  vs  (512,)
[cosine distance]  [0.116969485] = 2.575375/(1.010408*21.790705) [max_diff: 3.244277] output/face01_int8.out vs output/face01_fp32.out
(512,)  vs  (512,)
[cosine distance]  [-0.066368425] = -1.533548/(1.010408*22.868583) [max_diff: 2.893839] output/face02_int8.out vs output/face02_fp32.out
(512,)  vs  (512,)
[cosine distance]  [0.085922627] = 1.899032/(1.010408*21.873989) [max_diff: 3.327957] output/face03_int8.out vs output/face03_fp32.out
(512,)  vs  (512,)
[cosine distance]  [0.091322231] = 2.048966/(1.010408*22.205557) [max_diff: 3.363704] output/mask01_int8.out vs output/mask01_fp32.out
(512,)  vs  (512,)
[cosine distance]  [-0.033081225] = -0.749458/(1.010408*22.421728) [max_diff: 2.606768] output/mask02_int8.out vs output/mask02_fp32.out
(512,)  vs  (512,)
[cosine distance]  [-0.043648708] = -0.994056/(1.010408*22.539426) [max_diff: 3.227138] output/mask03_int8.out vs output/mask03_fp32.out
```

**Comment by quinnrong94** [comment]
@joytsay 模型链接无法打开，麻烦重新上传

**Comment by joytsay** [comment]
> @joytsay 模型链接无法打开，麻烦重新上传

現在链接應該可以了 不好意思 麻煩您了！

**Comment by quinnrong94** [comment]
> > @joytsay 模型链接无法打开，麻烦重新上传
> 
> @quinnrong94 現在链接應該可以了: [int8vsfp32_0608.zip](https://github.com/joytsay/lfs/raw/main/int8vsfp32_0608.zip) 不好意思 麻煩您了！

通过git lfs clone报错：
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/joytsay/lfs.git/info/lfs'
可能是文件大小超过限制，可以直接发送到我的邮箱：quinnrong@tencent.com

**Comment by joytsay** [comment]
@quinnrong94 Ok 我寄到您的邮箱了! 謝謝您

**Comment by quinnrong94** [comment]
@joytsay 已复现问题，并修复量化工具相关问题。
可切换至hotfix_issue_1017分支，重新编译量化工具，再进行模型量化。
测试结果：使用两张图片做校准，量化模型输出结果和原始fp32模型的余弦相似度在95%以上。

**Comment by joytsay** [comment]
@quinnrong94  好我試看看 順帶問一下 
相似度由 fp32 99% 掉到 int8 95% 
這樣的誤差是在合理範圍內？ (速度跟精準度的取捨嗎)

**Comment by quinnrong94** [comment]
@joytsay 由于测试中只使用两张人脸图片做校准（余弦相似度分别为95.6%和98.3%），结果可能无法准确反映量化误差。
误差可能是由多方面引起的：
1. 校准图片数量不够
2. 默认的Min-Max量化方法受异常值的影响较大，可以尝试KL和ADMM方法，参考 https://github.com/Tencent/TNN/blob/master/doc/en/user/quantization_en.md#2-parameter-description
3. 余弦相似度指标不一定能正确衡量模型真正的误差

建议使用更多图片校准和测试，并尝试不同的量化方法，看模型的预测结果是否达标。

**Comment by joytsay** [comment]
@quinnrong94 看起來結果正確許多：
```
int8 vs fp32
(512,)  vs  (512,)
[cosine distance]  [0.977559282] = 464.977494/(21.828181*21.790705) [max_diff: 0.623751] output/face01_int8.out vs output/face01_fp32.out
(512,)  vs  (512,)
[cosine distance]  [0.986123709] = 515.118281/(22.842115*22.868583) [max_diff: 0.497656] output/face02_int8.out vs output/face02_fp32.out
(512,)  vs  (512,)
[cosine distance]  [0.974088442] = 450.552796/(21.145566*21.873989) [max_diff: 0.695028] output/face03_int8.out vs output/face03_fp32.out
(512,)  vs  (512,)
[cosine distance]  [0.971851242] = 463.705130/(21.487230*22.205557) [max_diff: 0.832944] output/mask01_int8.out vs output/mask01_fp32.out
(512,)  vs  (512,)
[cosine distance]  [0.967077089] = 465.374626/(21.462116*22.421728) [max_diff: 0.753237] output/mask02_int8.out vs output/mask02_fp32.out
(512,)  vs  (512,)
[cosine distance]  [0.972067810] = 487.813216/(22.264562*22.539426) [max_diff: 0.811198] output/mask03_int8.out vs output/mask03_fp32.out
```
那我先把issue close掉 感謝您的幫助！
