### ISSUE TITLE
converter工具tflite2tnn模型转换时不支持gather算子

### ISSUE THREAD

**Issue by djrjm** [Tencent/TNN#1018]
**1. 使用环境（environment）**
 - OS: Mac
 - OS Version:

  **2. Github版本**
 - branch：master
 - commit(optional):775d124351ea2f02daa7cbbc09d459def86a8ca6

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型转换失败（converter failed）
 - 使用converter将tf-lite模型转换为tnn模型时不支持gather算子。

  **4. 日志（Log）**
 ```txt
 E/tnn: Convert2Tnn [File /TNN/tools/converter/source/tflite/tflite_converter.cc][Line 111] The TFLiteConverter do not support layer:sparse_feature/embedding_lookup
E/tnn: Convert2Tnn [File /TNN/tools/converter/source/tflite/tflite_converter.cc][Line 113] The unsupported operator type is:GATHER
E/tnn: Run [File /TNN/tools/converter/source/tnn_converter.cc][Line 48] Converter: converter tf_lite_model/gather_model..tflite failed!

 ```

  **5. 截图（Screenshots）**
![企业微信截图_316df5a4-c2a2-4bc9-b95a-0e2f0145be32](https://user-images.githubusercontent.com/19925998/121178257-e2bfd280-c890-11eb-8bea-dc80918960ad.png)

**Comment by gttiankai** [comment]
已支持。
