### ISSUE TITLE
onnx转tnn报错

### ISSUE THREAD

**Issue by GlennLoveZhen0124** [Tencent/TNN#1020]
**1. 使用环境（environment）**
网页版onnx2tnn

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型转换失败（converter failed）
 - original model： ONNX

  **4. 日志（Log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 截图（Screenshots）**
![onnx_error](https://user-images.githubusercontent.com/76581762/121349769-7ad6be00-c95c-11eb-80fe-d5caeb08113c.PNG)

**Comment by seanxcwang** [comment]
这个可能是因为没有及时更新到最新的，也有可能是本身转模型工具就不支持
你可以尝试用docker，或者自己编译转模型工具
方便的话把模型附上，我们这边试一下

**Comment by GlennLoveZhen0124** [comment]
@seanxcwang 感谢回复，找到问题了，是permute算子不支持，去掉之后就能转了
