### ISSUE TITLE
linux cuda 10.2 cudnn8.0.5 tensorRT7.2.3 yolo infer

### ISSUE THREAD

**Issue by gjj123** [Tencent/TNN#1021]
报错：
ERROR: ../rtSafe/cuda/cudaConvolutionRunner.cpp (483) - Cudnn Error in executeConv: 8 (CUDNN_STATUS_EXECUTION_FAILED)

**Comment by johnzlli-tencent** [comment]
可以把cuda升级到11.0看看是否还有此问题

**Comment by gjj123** [comment]
> 可以把cuda升级到11.0看看是否还有此问题
好像不是cuda的问题，直接调tensorrt可以起来。放弃tnn了。。。
