### ISSUE TITLE
tnn 编译出错

### ISSUE THREAD

**Issue by peyer** [Tencent/TNN#1022]
build_ios.sh 中把 DEVICE_PLATFORM = 'Mac'打开，编译出错， 'armv8.2-a+fp16+nolse' not recognized

**Comment by seanxcwang** [comment]
build ios为什么需要把mac打开，如果你是想编译mac M1上的程序，可以用build_aarch64_macos.sh

**Comment by peyer** [comment]
是的，确实是想编译mac M1上的程序，明白了
