### ISSUE TITLE
GPU上2个三维数据MatMul出来的值都是0

### ISSUE THREAD

**Issue by Orangeyzao** [Tencent/TNN#1023]
**1. 环境（environment）**
 - Build OS and Version: Windows
 - RunTime OS Version: Android
 - RunTime DEVICE: ARM GPU

  **2. Github版本**
 - branch：stable_v0.3
 - commit(optional):

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
我们模型里面有个MatMul,输入的矩阵分别是（1x32x32x1）和（1x32x1x32），且输入的值不为0，但是输出的值全部是0

  **6. 运行日志（runtime log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **7. 截图（Screenshots）**
 ```txt
 将截图粘贴在这里
 Paste screenshorts here or pastebin
 ```

**Comment by Orangeyzao** [comment]
我们已经找到了一个bug，修改后，（1x32x32x1）和（1x32x1x32）的MatMul正确了，但是（1x128x20x20）和（1x128x20x20）的结果不对

**Comment by shaundai-tencent** [comment]
能否提供一下可以复现问题的模型？

**Comment by Orangeyzao** [comment]
> 能否提供一下可以复现问题的模型？可以发送到我的邮箱 [shaundai@tencent.com](mailto:shaundai@tencent.com)

不好意思，我们的模型不能对外提供，你可以做个单元测试，只要是3维或者4维矩阵乘法，都不对

**Comment by shaundai-tencent** [comment]
好的，谢谢。我们已经可以复现问题，会尽快修复。

**Comment by shaundai-tencent** [comment]
修复已经合入master，可以试试问题是否解决了。

**Comment by JuiceLemonLemon** [comment]
我测试了多个模型，MatMul都是正确的，谢谢
