### ISSUE TITLE
ARM linux跨平台编译报错

### ISSUE THREAD

**Issue by chushouwuzhao** [Tencent/TNN#1029]
按照TNN/doc/cn/user/compile.md 下的描述，
三、ARM Linux跨平台交叉编译
编译报错
[ 47%] Building ASM object source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm64/CONV_DW_3X3_FLOAT_SLIDEW.S.o
[ 47%] Building ASM object source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm64/CONV_DW_3x3_BFP16_SLIDEW.S.o
[ 47%] Building ASM object source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm64/CONV_DW_5X5_FLOAT_SLIDEW.S.o
[ 47%] Building ASM object source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm64/CONV_DW_5x5_BFP16_SLIDEW.S.o
[ 47%] Building CXX object source/tnn/device/opencl/CMakeFiles/TNNOpenCL.dir/opencl_wrapper.cc.o
[ 47%] Building ASM object source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm64/CONV_FLOAT_O4.S.o
[ 47%] Building ASM object source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm64/CONV_FLOAT_SLIDEW_C3.S.o
[ 47%] Building ASM object source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm64/DECONV_FLOAT_O4.S.o
[ 48%] Building ASM object source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm64/GEMM_BFP16_N8.S.o
[ 48%] Building ASM object source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm64/GEMM_FLOAT_N8.S.o
[ 48%] Building ASM object source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm64/GEMM_INT8_4X4.S.o
[ 48%] Building ASM object source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm64/GEMM_INT8_8X8.S.o
[ 48%] Built target TNNArm
[ 48%] Built target TNNOpenCL
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

请问该如何解决，盼回复

**Comment by shaundai-tencent** [comment]
能否贴出完整的编译信息，这个信息不全，看不出错误信息

**Comment by mryoungci** [comment]
source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm32/CONV_BFP16_SLIDEW_C3.S.o: In function `GemmBfp16SlidewC3':
(.text+0x0): multiple definition of `GemmBfp16SlidewC3'
source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/compute.cc.o:compute.cc:(.text+0x648): first defined here
source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm32/CONV_FLOAT_SLIDEW_C3.S.o: In function `GemmFloatSlidewC3':
(.text+0x0): multiple definition of `GemmFloatSlidewC3'
source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/compute.cc.o:compute.cc:(.text+0x3e0): first defined here
source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm32/DECONV_FLOAT_O4.S.o: In function `DeconvFloatO4':
(.text+0x0): multiple definition of `DeconvFloatO4'
source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/compute.cc.o:compute.cc:(.text+0x0): first defined here
source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm32/GEMM_BFP16_N4.S.o: In function `GEMM_BFP16_N4':
(.text+0x0): multiple definition of `GEMM_BFP16_N4'
source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/compute.cc.o:compute.cc:(.text+0xb78): first defined here
source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/arm32/GEMM_FLOAT_N4.S.o: In function `GEMM_FLOAT_N4':
(.text+0x0): multiple definition of `GEMM_FLOAT_N4'
source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/compute/compute.cc.o:compute.cc:(.text+0xb84): first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/TNN.dir/build.make:5320: recipe for target 'libTNN.so.0.1.0.0' failed


应该是重复定义的问题，屏蔽acc/compute.cc 对应重复定义的部分可以编译通过
