### ISSUE TITLE
linux ARM RK平台编译错误

### ISSUE THREAD

**Issue by chushouwuzhao** [Tencent/TNN#1030]
[  1%] Building CXX object source/tnn/device/cpu/CMakeFiles/TNNCpu.dir/acc/cpu_abs_layer_acc.cc.o
[  1%] Building CXX object source/tnn/device/rknpu/CMakeFiles/TNNRKNPU.dir/rknpu_network.cc.o
In file included from /home/liukp/on_work/new_project/TNN/TNN-master/TNN-master/source/tnn/device/rknpu/rknpu_network.h:20:0,
                 from /home/liukp/on_work/new_project/TNN/TNN-master/TNN-master/source/tnn/device/rknpu/rknpu_network.cc:15:
/home/liukp/on_work/new_project/TNN/TNN-master/TNN-master/source/tnn/device/rknpu/convert/rknpu_base_layer.h:25:29: fatal error: rknpu/rknpu_pub.h: No such file or directory
 #include "rknpu/rknpu_pub.h"
                             ^
compilation terminated.
source/tnn/device/rknpu/CMakeFiles/TNNRKNPU.dir/build.make:158: recipe for target 'source/tnn/device/rknpu/CMakeFiles/TNNRKNPU.dir/rknpu_network.cc.o' failed
make[2]: *** [source/tnn/device/rknpu/CMakeFiles/TNNRKNPU.dir/rknpu_network.cc.o] Error 1
CMakeFiles/Makefile2:290: recipe for target 'source/tnn/device/rknpu/CMakeFiles/TNNRKNPU.dir/all' failed
make[1]: *** [source/tnn/device/rknpu/CMakeFiles/TNNRKNPU.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  1%] Building CXX object source/tnn/device/arm/CMakeFiles/TNNArm.dir/acc/arm_arg_max_or_min_layer_acc.cc.o

目前下找不到 rknpu_pub.h，确实没有这个文件，请问怎么解决

**Comment by seanxcwang** [comment]
https://github.com/Tencent/TNN/blob/master/doc/cn/faq.md#如何创建rknpu编译环境
另外，rknpu只支持rk1808

**Comment by 0312birdzhang** [comment]
> [https://github.com/Tencent/TNN/blob/master/doc/cn/faq.md#如何创建rknpu编译环境](https://github.com/Tencent/TNN/blob/master/doc/cn/faq.md#%E5%A6%82%E4%BD%95%E5%88%9B%E5%BB%BArknpu%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83) 另外，rknpu只支持rk1808

请问什么时候支持rk3588？
