### ISSUE TITLE
TNNTest和unit_test调用同一个op,  lantency差值较大

### ISSUE THREAD

**Issue by peyer** [Tencent/TNN#1032]
测试算子：convolution input(1, 64, 96, 96), kernel(32, 64, 3, 3), output(1, 32, 96, 96)
测试backend: opencl
测试设备： snap 845

unit_test: wc 1000 ic 1000 th 4, 结果是 4.2ms
TNNtest:  wc 1000 ic 1000 th 4, 结果是 1.9ms

我使用SnapDragon Profiler采集opencl的相关数据，结果和tnn的profilerData基本一致

很不理解unit_test和TNNTest的gap在哪里？

**Comment by shaundai-tencent** [comment]
请问，你这个性能测试的数据，4.3ms和1.9ms，都是端到端的数据吗？是构造了一层的网络来侧的吗？

**Comment by peyer** [comment]
测量的时间都是打开 TNN_PROFILE和CL_QUEUE_PROFILING_ENABLE以后，基于 cl event 统计出的 queue time + submit time + kernel time；
测试的方法是unit_test测试单独的一个op, TNNTest测试包含这种op+同样输入的模型，没有单独构建一个只有一层的网络

**Comment by shaundai-tencent** [comment]
有以下几个注意点：
1、如果要测试layer的性能，建议使用TNN/benchmark/benchmark_android/benchmark_layer.sh脚本，里面也是利用的是UnitTest对单层进行性能测试，这里面打开了以下开关：TNN_BENCHMARK_MODE，TNN_UNIT_TEST_ENABLE，TNN_UNIT_TEST_BENCHMARK，TNN_PROFILER_ENABLE，而你可能没有打开TNN_UNIT_TEST_BENCHMARK，这会导致跑OpenCL的时候使用的是FP32的精度去跑的，而TNNTest跑性能使用的是FP16精度去跑的，所以性能不一致。
2、分析OpenCL的性能，如果打开Profiling，那关注Kernel time就可以了，其他的时间在实际执行网络的时候可以掩藏。单独跑一层有可能queue time和submit time加起来还比kernel time时间长。
（此外，发现目前master（commit 7452417487c8ff478bd053a2daa4ea11911430db）上的代码，跑benchmark_layer.sh有点小问题，跑不成功，等待修复之后我会同步一下）

**Comment by peyer** [comment]
多谢回复
1. 我在编译unit_test时确实没有打开 "TNN_UNIT_TEST_BENCHMARK"
2. 但是这个 "TNN_UNIT_TEST_BENCHMARK"我全局搜索了一下，应该不会控制data_type是不是CL_HALF_FLOAT吧？或者说我没有找到对应的代码
[图片]

**Comment by peyer** [comment]
多谢回复
1. 我在编译unit_test时确实没有打开 "TNN_UNIT_TEST_BENCHMARK" 选项
2. 但是这个 "TNN_UNIT_TEST_BENCHMARK"我全局搜索了一下，应该不会控制data_type是不是CL_HALF_FLOAT吧？或者说我没有找到对应的代码
![ut_bench](https://user-images.githubusercontent.com/19945545/122330999-b417bb00-cf66-11eb-8996-3f643abfdc55.jpg)

**Comment by shaundai-tencent** [comment]
TNN_UNIT_TEST_BENCHMARK这个宏是控制在UnitTest的时候使用什么精度跑的，如果打开则精度是默认值AUTO，由各个平台决定默认精度，OpenCL平台中就是跑FP16的精度（因为在正常做UT的结果校验时，为了和Naive的结果对齐，强制把精度设置为了HIGH）。此外打开这个宏之后，不会校验最终结果，并且只跑对应Device的Forward。

**Comment by peyer** [comment]
确实，我查看了logcat的信息，unit_test外围传参我强制走half，但是时间的kernel还是走float，明白了
![knk_2021-06-24  22-53-49](https://user-images.githubusercontent.com/19945545/123284766-17918200-d53f-11eb-865d-1e69cc7e2095.jpg)
