### ISSUE TITLE
Winograd for 3x3 conv

### ISSUE THREAD

**Issue by liorkad3** [Tencent/TNN#1033]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu
 - RunTime OS Version: Android
 - RunTime DEVICE: OPENCL

I would like test a VGG like net architecture mostly contains conv operator with 3x3 kernel.
My hardware is Android with OPENCL.
Winograd conv, is known to optimize this kind of operation very well.
Does TNN support winograd?
When initiating an instance object, does winograd is the default optimization? Or is there an option to set the optimization preference? (in case memory footprint is more important than latency)

**Comment by lnmdlong** [comment]
The OPENCL backend supports winograd. And winograd conv is enabled by default when creating the instance. There is no need to specify any optimization preference.
