### ISSUE TITLE
OpenCL1.1版本兼容性问题

### ISSUE THREAD

**Issue by sosopop** [Tencent/TNN#1037]
安卓运行提示UpsampleCubicInterpolation的static关键字不支持
static inline float4 UpsampleCubicInterpolation(float4 A, float4 B, float4 C, float4 D, float factor)
修改为
inline float4 UpsampleCubicInterpolation(float4 A, float4 B, float4 C, float4 D, float factor)
后正常

**Comment by lnmdlong** [comment]
麻烦提供下测试的设备型号和安卓版本

**Comment by sosopop** [comment]
这个是设备的信息

OpenCL-Z-Android Report

Phone/Tablet Information
--------------------------------
Device model: KONKA A7-KJ05E02
Android OS version: 5.1.1
Kernel version: 3.10.0, 周二 2月 23 12:02:02 2021
Build number: rk3288-userdebug 5.1.1 LMY49F eng.zjf.20210223.125100 test-keys
CPU ABI: armeabi-v7a
CPU ABI 2: armeabi
OpenCL library location: /system/vendor/lib/egl/libGLES_mali.so

OpenCL Information
-------------------------
Found 1 OpenCL platforms.
[Platform] INDEX: 1
[Platform] NAME: ARM Platform
[Platform] VENDOR: ARM
[Platform] PROFILE: FULL_PROFILE
[Platform] VERSION: OpenCL 1.1 v1.r6p0-02rel0.c849a292a43ed4cb990a8ceb30c1097c
[Platform] EXTENSIONS: cl_khr_global_int32_base_atomics;cl_khr_global_int32_extended_atomics;cl_khr_local_int32_base_atomics;cl_khr_local_int32_extended_atomics;cl_khr_byte_addressable_store;cl_khr_fp64;cl_khr_int64_base_atomics;cl_khr_int64_extended_atomics;cl_khr_fp16;cl_khr_gl_sharing;cl_khr_icd;cl_khr_egl_event;cl_khr_egl_image;cl_arm_core_id;cl_arm_printf;cl_arm_thread_limit_hint


Found 1 devices:
	[Device] INDEX: 1
	[Device] TYPE: GPU
	[Device] NAME: Mali-T760
	[Device] VENDOR: ARM
	[Device] VENDOR_ID: 0x7501000
	[Device] DRIVER_VERSION: 1.1
	[Device] PROFILE: FULL_PROFILE
	[Device] VERSION: OpenCL 1.1 v1.r6p0-02rel0.c849a292a43ed4cb990a8ceb30c1097c
	[Device] MAX_CLOCK_FREQUENCY: 5 MHz
	[Device] MAX_COMPUTE_UNITS: 4
	[Device] AVAILABLE: true
	[Device] COMPILER_AVAILABLE: true
	[Device] EXTENSIONS: cl_khr_global_int32_base_atomics;cl_khr_global_int32_extended_atomics;cl_khr_local_int32_base_atomics;cl_khr_local_int32_extended_atomics;cl_khr_byte_addressable_store;cl_khr_fp64;cl_khr_int64_base_atomics;cl_khr_int64_extended_atomics;cl_khr_fp16;cl_khr_gl_sharing;cl_khr_icd;cl_khr_egl_event;cl_khr_egl_image;cl_arm_core_id;cl_arm_printf;cl_arm_thread_limit_hint
	[Device] MAX_WORK_ITEM_DIMENSIONS: 3
	[Device] MAX_WORK_ITEM_SIZES: (256, 256, 256)
	[Device] MAX_WORK_GROUP_SIZE: 256
	[Device] ADDRESS_BITS: 64
	[Device] MAX_READ_IMAGE_ARGS: 128
	[Device] MAX_WRITE_IMAGE_ARGS: 8
	[Device] MAX_MEM_ALLOC_SIZE: 527574016
	[Device] IMAGE2D_MAX_WIDTH: 65536
	[Device] IMAGE2D_MAX_HEIGHT: 65536
	[Device] IMAGE3D_MAX_WIDTH: 65536
	[Device] IMAGE3D_MAX_HEIGHT: 65536
	[Device] IMAGE3D_MAX_DEPTH: 65536
	[Device] IMAGE_SUPPORT: true
	[Device] MAX_PARAMETER_SIZE: 1024
	[Device] MAX_SAMPLERS: 16
	[Device] MEM_BASE_ADDR_ALIGN: 1024
	[Device] MIN_DATA_TYPE_ALIGN_SIZE: 128
	[Device] SINGLE_FP_CONFIG: CL_FP_DENORM;CL_FP_INF_NAN;CL_FP_ROUND_TO_NEAREST;CL_FP_ROUND_TO_ZERO;CL_FP_ROUND_TO_INF;CL_FP_FMA;
	[Device] HOST_UNIFIED_MEMORY: Unified
	[Device] GLOBAL_MEM_CACHE_TYPE: read/write cache
	[Device] GLOBAL_MEM_CACHELINE_SIZE: 64
	[Device] GLOBAL_MEM_CACHE_SIZE: 262144
	[Device] GLOBAL_MEM_SIZE: 2110296064
	[Device] MAX_CONSTANT_BUFFER_SIZE: 65536
	[Device] MAX_CONSTANT_ARGS: 8
	[Device] LOCAL_MEM_TYPE: global
	[Device] LOCAL_MEM_SIZE: 32768
	[Device] ERROR_CORRECTION_SUPPORT: false
	[Device] PROFILING_TIMER_RESOLUTION: 1000 nanoseconds
	[Device] ENDIAN_LITTLE: true
	[Device] EXECUTION_CAPABILITIES: CL_EXEC_KERNEL;
	[Device] QUEUE_PROPERTIES: CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE;CL_QUEUE_PROFILING_ENABLE;
	[Device] PREFERRED_VECTOR_WIDTH_CHAR: 16
	[Device] PREFERRED_VECTOR_WIDTH_SHORT: 8
	[Device] PREFERRED_VECTOR_WIDTH_INT: 4
	[Device] PREFERRED_VECTOR_WIDTH_LONG: 2
	[Device] PREFERRED_VECTOR_WIDTH_FLOAT: 4
	[Device] PREFERRED_VECTOR_WIDTH_DOUBLE: 2
	[Device] PREFERRED_VECTOR_WIDTH_HALF: 8
	[Device] NATIVE_VECTOR_WIDTH_CHAR: 16
	[Device] NATIVE_VECTOR_WIDTH_SHORT: 8
	[Device] NATIVE_VECTOR_WIDTH_INT: 4
	[Device] NATIVE_VECTOR_WIDTH_LONG: 2
	[Device] NATIVE_VECTOR_WIDTH_FLOAT: 4
	[Device] NATIVE_VECTOR_WIDTH_DOUBLE: 2
	[Device] NATIVE_VECTOR_WIDTH_HALF: 8

**Comment by lnmdlong** [comment]
@sosopop 在 https://github.com/Tencent/TNN/pull/1120 上修复上述问题，感谢反馈!
