### ISSUE TITLE
咨询一个opencl的问题

### ISSUE THREAD

**Issue by peyer** [Tencent/TNN#1044]
1. TNN在创建Instance时，device选择opencl，AllocateBlobMemory会根据desc信息 new 出 cl::Image2D 对象，这个image2d_t 型的对象的data_type有可能是CL_HALF_FLOAT，如果device支持cl_khr_fp16且precision不强制设置为High的话

2. 然后在主机端malloc出NCHW, float型输入，再调用OpenCLBlobConverterAcc的ConvertFromMat，OpenCLBlobConverterAcc的构造函数会强制申请一个data_type为DATA_TYPE_FLOAT的cl::Buffer，通过enqueueWriteBuffer将主机内存写入buffer_

3. 最后再调用“ConvertFromNCHW” kernel 将NCHW float型的cl::buffer转成 cl::Image，但是这个 kernel里直接使用了write_imagef来store数据，如果kernel的入参 image2d_t output申请时是CL_HALF_FLOAT型，这样难道不会出错吗？

**Comment by shaundai-tencent** [comment]
这是没有问题的，write_imagef这个接口表示传入的值是float，和image的数据类型没有关系，这个函数会自己做数据类型的转换。

**Comment by peyer** [comment]
意思是write_imagef 也可以把 float的数据存入 CL_HALF_FLOAT的image2d_t型的output？且CL_HALF_FLOAT的image2d_t型的output最终是float对应的half数据吗？

**Comment by peyer** [comment]
write_imagef can only be used with image objects created with image_channel_data_type set to one of the pre-defined packed formats or set to CL_SNORM_INT8, CL_UNORM_INT8, CL_SNORM_INT16, CL_UNORM_INT16, CL_HALF_FLOAT or CL_FLOAT. Appropriate data format conversion will be done to convert channel data from a floating-point value to actual data format in which the channels are stored.

刚才又看了khr的官方文档，确实会自动转换，明白了
