### ISSUE TITLE
更新最新代码编译后onnx转tnn报错

### ISSUE THREAD

**Issue by bestpower** [Tencent/TNN#1052]
**1. 使用环境（environment）**
 - OS: Ubuntu
 - OS Version: 18.04

  **2. Github版本**
 - branch：master
 - commit(optional): 79e3a748bc4811c8e276a457a60047fd03d173ea

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型转换失败（converter failed）
 - original model： ONNX
 （如果可以的话，请上传原始的模型文件）

  **4. 日志（Log）**

 将日志粘贴在这里
Compiled onnx2tnn successfully !
----------  convert model, please wait a moment ----------
Converter ONNX to TNN Model...
Converter ONNX to TNN check_onnx_dim...
Converter ONNX to TNN check_onnx_dim...
The onnx2tnn command:python3 onnx2tnn.py /home/wyu/github_projects/onnx_models/faceDetect.onnx -version=v3.0.0 -optimize=1 -half=0 -o /home/wyu/github_projects/tnn_out/models/
0.----onnx version:1.7.0
algo_optimize 1
onnx_net_opt_path /home/wyu/github_projects/onnx_models/faceDetect.opt.onnx
1.----onnx_optimizer: /home/wyu/github_projects/onnx_models/faceDetect.onnx
/home/wyu/github_projects/TNN/tools/onnx2tnn/onnx-converter
----load onnx model: /home/wyu/github_projects/onnx_models/faceDetect.onnx
----export optimized onnx model: /home/wyu/github_projects/onnx_models/faceDetect.opt.onnx
----export optimized onnx model done
Traceback (most recent call last):
  File "onnx2tnn.py", line 137, in main
    input_shape)
TypeError: convert(): incompatible function arguments. The following argument types are supported:
    1. (arg0: str, arg1: str, arg2: str, arg3: str, arg4: int) -> int
Invoked with: '/home/wyu/github_projects/onnx_models/faceDetect.opt.onnx', '/home/wyu/github_projects/tnn_out/models/', 'v3.0.0', '20210622 11:09:16', 0, 1, ''
2.----onnx2tnn: /home/wyu/github_projects/onnx_models/faceDetect.opt.onnx
Converter ONNX to TNN model failed!

  **5. 截图（Screenshots）**

更新代码后出现的问题，之前的代码转换该模型时并没有问题，怀疑是更新改出的bug，麻烦分析修正一下。
[onnx_model.zip](https://github.com/Tencent/TNN/files/6690761/onnx_model.zip)

**Comment by bestpower** [comment]
再附上编译和转换命令：
$ cd $WORK_DIR/TNN/tools/onnx2tnn/onnx-converter
$ ./build.sh
$ cd $WORK_DIR/TNN/tools/convert2tnn/
$ python3 converter.py onnx2tnn onnx_model_path -optimize -v v3.0.0 -o output_model_path -debug

**Comment by 1627180283** [comment]
方便看一下转换工具编译完成之后 <tnn-root>/tools/onnx2tnn/onnx-converter/onnx2tnn*.so有更新吗？

**Comment by bestpower** [comment]
> 方便看一下转换工具编译完成之后 tnn/tools/onnx2tnn/onnx-converter/onnx2tnn*.so有更新吗？

onnx2tnn.cpython-36m-x86_64-linux-gnu.so没有更新，看生成日期还是我之前编译的时间

**Comment by 1627180283** [comment]
那应该是 onnx2tnn*.so 编译之后没有更新导致的，这个目录下有其他新的 onnx2tnn*.so 生成吗？

**Comment by bestpower** [comment]
> 那应该是 onnx2tnn*.so 编译之后没有更新导致的，这个目录下有其他新的 onnx2tnn*.so 生成吗？

没有

**Comment by 1627180283** [comment]
你试一下把 TNN/tools/convert2tnn/build.sh 里 64 行注释掉，重新执行 TNN/tools/convert2tnn/build.sh 编译转换工具，然后把 TNN/tools/convert2tnn/build/tools/onnx2tnn/onnx-converter/onnx2tnn*.so 手动拷贝到 TNN/tools/onnx2tnn/onnx-converter/

你试一下这样手动更新 onnx2tnn*.so 看能不能正常转换模型

**Comment by bestpower** [comment]
> 你试一下把 TNN/tools/convert2tnn/build.sh 里 64 行注释掉，重新执行 TNN/tools/convert2tnn/build.sh 编译转换工具，然后把 TNN/tools/convert2tnn/build/tools/onnx2tnn/onnx-converter/onnx2tnn*.so 手动拷贝到 TNN/tools/onnx2tnn/onnx-converter/
> 
> 你试一下这样手动更新 onnx2tnn*.so 看能不能正常转换模型

TNN/tools/convert2tnn/build.sh这个脚本没问题，我之前用的是TNN/tools/onnx2tnn/onnx-converter/build.sh这个脚本，专门编译onnx转tnn模型的工具，发现是so文件的拷贝目标路径有问题，把TNN/tools/onnx2tnn/onnx-converter/build.sh
第60行：cp ${onnx2nn_files[i]} ../../../../../onnx-converter
改为：cp ${onnx2nn_files[i]} ../../onnx-converter
就可以了

**Comment by 1627180283** [comment]
这个问题已经在 master 分支中修复

**Comment by 1627180283** [comment]
这个问题已经在 master 分支中修复，issue 暂时先关闭了，如果有新的问题可以重新打开
