### ISSUE TITLE
android 模型inference每次输出结果不一样

### ISSUE THREAD

**Issue by RedFree** [Tencent/TNN#1053]
模型每次推理输出结果不一样，请教这个问题如何解决呢。附件是我转换的模型文件。
[CDCN.zip](https://github.com/Tencent/TNN/files/6692059/CDCN.zip)

**Comment by RedFree** [comment]
android 32位和64位输出不一样，64位输出正常，32输出不正常

**Comment by RedFree** [comment]
补充文件：
附件包含了onnx文件，以及转换之后的tnn模型。
说明：上次上传的模型是去掉了一些层，仍然是输出不一致。补充模型是完整模型。
[CDCN.zip](https://github.com/Tencent/TNN/files/6706293/CDCN.zip)

**Comment by quinnrong94** [comment]
> 补充文件：
> 附件包含了onnx文件，以及转换之后的tnn模型。
> 说明：上次上传的模型是去掉了一些层，仍然是输出不一致。补充模型是完整模型。
> [CDCN.zip](https://github.com/Tencent/TNN/files/6706293/CDCN.zip)

在华为P20上测试，ARM CPU上运行，32位和64位的输出结果都可以和onnx对齐，测试方法见附件[onnx_vs_tnn.zip](https://github.com/Tencent/TNN/files/6707225/onnx_vs_tnn.zip)。脚本中的PathToTNN需要修改为TNN仓库真实路径。TNN使用最新的master分支，commit it 2591526

运行结果如下：
> (1024,)  vs  (1024,)
[cosine distance]  [0.999998828] = 26.276859/(5.129994*5.122207) [max_diff: 0.001572] outputs/onnx/onnx.txt vs outputs/android/android_32.txt

> (1024,)  vs  (1024,)
[cosine distance]  [0.999998826] = 26.276774/(5.129994*5.122190) [max_diff: 0.001567] outputs/onnx/onnx.txt vs outputs/android/android_64.txt

> (1024,)  vs  (1024,)
[cosine distance]  [1.000000000] = 26.236918/(5.122207*5.122190) [max_diff: 0.000016] outputs/android/android_32.txt vs outputs/android/android_64.txt

建议按照附件方法重新测试，如果推理结果仍不对齐，再提供详细的测试环境以及可复现问题的步骤。

**Comment by RedFree** [comment]
@quinnrong94 感谢您解答。目前测试情况如下：
1. 华为荣耀，小米9手机测试都正常，64位机器，但是息屏之后输出错误(这个刚发现，因为我们有项目需要息屏拍照处理。)
2. 我们工程测试机器是32位，测试输出仍然不对。多次反复测试，偶尔会在前几帧输出正确结果，后面结果出错。机器信息如图：
![选区_578](https://user-images.githubusercontent.com/5827427/123243438-9b367900-d515-11eb-9dd0-b391aac17c9f.png)

**Comment by seanxcwang** [comment]
> @quinnrong94 感谢您解答。目前测试情况如下：
> 
> 1. 华为荣耀，小米9手机测试都正常，64位机器，但是息屏之后输出错误(这个刚发现，因为我们有项目需要息屏拍照处理。)
> 2. 我们工程测试机器是32位，测试输出仍然不对。多次反复测试，偶尔会在前几帧输出正确结果，后面结果出错。机器信息如图：
>    ![选区_578](https://user-images.githubusercontent.com/5827427/123243438-9b367900-d515-11eb-9dd0-b391aac17c9f.png)
> 3. 64位测试多个不同输入，有的输入对应的输出会出现无效值：nan。

麻烦保存下，错误输出时对应的输入，方便我们复现

**Comment by RedFree** [comment]
测试数据补充：
[测试.zip](https://github.com/Tencent/TNN/files/6713145/default.zip)
附件中包含了onnx模型，TNN模型，输入图片，两个32位机器的输出（都是无效值），一个64位机器输出（正常值）。readme是说明文件，如果还需要什么信息，可以随时补充。
@quinnrong94

**Comment by quinnrong94** [comment]
> 测试数据补充：
> [测试.zip](https://github.com/Tencent/TNN/files/6713145/default.zip)
> 附件中包含了onnx模型，TNN模型，输入图片，两个32位机器的输出（都是无效值），一个64位机器输出（正常值）。readme是说明文件，如果还需要什么信息，可以随时补充。
> @quinnrong94

我们在32位机器上，使用该测试数据进行测试，未能复现问题，cpu信息：
![image](https://user-images.githubusercontent.com/67782915/123573218-1cd12400-d800-11eb-9f4e-ee62e30d8853.png)

测试脚本：
[default.zip](https://github.com/Tencent/TNN/files/6723026/default.zip)

测试结果：
> (1024,)  vs  (1024,)
[cosine distance]  [0.999998916] = 24.896702/(4.990818*4.988507) [max_diff: 0.000950] output_onnx.txt vs ../out_normal.txt

> (1024,)  vs  (1024,)
[cosine distance]  [0.999998917] = 24.896665/(4.990818*4.988499) [max_diff: 0.000951] output_onnx.txt vs android_32.txt

onnx的结果和正常值可以对齐，android 32位的结果和onnx的结果也能对齐。

建议先按照测试脚本中的步骤，检查工程测试机器对单张图片输入的计算结果是否正常。

**Comment by RedFree** [comment]
使用您提供的脚本和测试步骤，在测试机上测试结果是正确的。
但是在Android里面的结果仍然不正确，我使用的推理过程是tnn_sdk_sample.cc里面的函数：
``` C++
TNN_NS::Status TNNSDKSample::Predict(std::shared_ptr<TNNSDKInput> input, std::shared_ptr<TNNSDKOutput> &output) {
    Status status = TNN_OK;

    if(!input)
    {
        LOGE("input image is empty ,please check!\n");
        return status;
    }
    if (!input || input->IsEmpty()) {
        status = Status(TNNERR_PARAM_ERR, "input image is empty ,please check!");
        LOGE("input image is empty ,please check!\n");
        return status;
    }

    
#if TNN_SDK_ENABLE_BENCHMARK
    bench_result_.Reset();
    for (int fcount = 0; fcount < bench_option_.forward_count; fcount++) {
        timeval tv_begin, tv_end;
        gettimeofday(&tv_begin, NULL);
#endif
        // step 1. set input mat
        auto input_names = GetInputNames();
        if (input_names.size() == 1) {
            auto input_mat = input->GetMat();
            input_mat = ProcessSDKInputMat(input_mat);
            auto input_convert_param = GetConvertParamForInput();
            auto status = instance_->SetInputMat(input_mat, input_convert_param);
//++++++++++++++++++++++++++获取设置的输入数据++++++++++++++++++++++++++++
            BlobMap inputData;
            instance_->GetAllInputBlobs(inputData);
            auto BlobData = inputData[input_names[0]];
            float* saveData = (float*)BlobData->GetHandle().base;
            static int xx = 0;
            std::string path = "/data/data/com.sprocomm.mpfusys/app_execdir/" + std::to_string(100) + "_input_mat.txt";
            std::ofstream out(path);
            for (int i = 0; i < 4*256*256; i += 4) {
                auto data = (float*)input_mat->GetData();
                out << (float)saveData[i] << std::endl;
                out << (float)saveData[i+1] << std::endl;
                out << (float)saveData[i+2] << std::endl;
            }
            out.close();

//
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
            RETURN_ON_NEQ(status, TNN_NS::TNN_OK);
        } else {
            for (auto name : input_names) {
                auto input_mat = input->GetMat(name);
//                LOGE("Name: %s", name.c_str());
                input_mat = ProcessSDKInputMat(input_mat, name);
                auto input_convert_param = GetConvertParamForInput(name);
                auto status = instance_->SetInputMat(input_mat, input_convert_param, name);
                RETURN_ON_NEQ(status, TNN_NS::TNN_OK);
            }
        }

        // step 2. Forward
        status = instance_->ForwardAsync(nullptr);
        if (status != TNN_NS::TNN_OK) {
            LOGE("instance.Forward Error: %s\n", status.description().c_str());
            return status;
        }

        // step 3. get output mat
        output = CreateSDKOutput();
        auto output_names = GetOutputNames();
        if (output_names.size() == 1) {
            auto output_convert_param = GetConvertParamForOutput();
            std::shared_ptr<TNN_NS::Mat> output_mat = nullptr;
            status = instance_->GetOutputMat(output_mat, output_convert_param);

//            static int xx = 0;
            std::string path = "/data/data/com.sprocomm.mpfusys/app_execdir/" + std::to_string(100) + "_output_mat.txt";
            std::ofstream out(path);
            for (int i = 0; i < 32*32; ++i) {
                auto data = (float*)output_mat->GetData();
                out << (float)data[i] << std::endl;
            }
            out.close();
            exit(0);

            RETURN_ON_NEQ(status, TNN_NS::TNN_OK);
            output->AddMat(output_mat, output_names[0]);

        } else {
            for (auto name : output_names) {
                  auto output_convert_param = GetConvertParamForOutput(name);
                  std::shared_ptr<TNN_NS::Mat> output_mat = nullptr;
                  status = instance_->GetOutputMat(output_mat, output_convert_param, name);
                  auto type = output_mat->GetMatType();
                  RETURN_ON_NEQ(status, TNN_NS::TNN_OK);
                  output->AddMat(output_mat, name);
              }
        }


#if TNN_SDK_ENABLE_BENCHMARK
        gettimeofday(&tv_end, NULL);
        double elapsed = (tv_end.tv_sec - tv_begin.tv_sec) * 1000.0 + (tv_end.tv_usec - tv_begin.tv_usec) / 1000.0;
        bench_result_.AddTime(elapsed);
#endif
        
        ProcessSDKOutput(output);
#if TNN_SDK_ENABLE_BENCHMARK
    }
#endif
    // Detection done
    
    return status;
}
``` 
其中在“获取设置的输入数据”中保存了输入数据的原始值，结果和输入图片的数据一致。(此处之前的"b47d065e"这个分支是正确的，今天更新tnn代码重新编译之后保存结果的前面3位结果是0，0，0，与之前保存结果不一致，后面结果是一样的，对比结果见图
![选区_581](https://user-images.githubusercontent.com/5827427/123601268-0dff6700-d82a-11eb-9ae0-9635073aea02.png)
)
使用相同结果的输入文件
[live_input.txt](https://github.com/Tencent/TNN/files/6724527/live_input.txt)
输出结果全部是0，也就是代码中"100_output_mat.txt"保存的结果是全0.
这个测试也能确保输入的数据是正确的，推理过程也没有出错，只是结果不对。模型加载也没有出现异常。
还请帮忙分析下可能出错的原因。

**Comment by quinnrong94** [comment]
@RedFree 在保存输入数据的代码中，不应该从blob指针（saveData）读取数据，应该改成从mat中读取
>
            for (int i = 0; i < 4*256*256; i += 4) {
                auto data = (float*)input_mat->GetData();
                out << (float)saveData[i] << std::endl;
                out << (float)saveData[i+1] << std::endl;
                out << (float)saveData[i+2] << std::endl;
            }

另外，要确保input_convert_param和output_convert_param设置正确，否则也会导致结果出错

**Comment by RedFree** [comment]
> @RedFree 在保存输入数据的代码中，不应该从blob指针（saveData）读取数据，应该改成从mat中读取
> 
> > 
> 
> ```
>         for (int i = 0; i < 4*256*256; i += 4) {
>             auto data = (float*)input_mat->GetData();
>             out << (float)saveData[i] << std::endl;
>             out << (float)saveData[i+1] << std::endl;
>             out << (float)saveData[i+2] << std::endl;
>         }
> ```
> 
> 另外，要确保input_convert_param和output_convert_param设置正确，否则也会导致结果出错

scale和bias设置如图：
![选区_588](https://user-images.githubusercontent.com/5827427/123757785-e7583380-d8f0-11eb-9747-1ee0fd7a1ecb.png)

输出结果不对的这个还需要怎么测试呢，同样代码在armv8上面可以正常工作。用你给的测试脚本在armeabiv7上测试结果也是正确的，不知道现在问题出在什么地方。

**Comment by quinnrong94** [comment]
> 输出结果不对的这个还需要怎么测试呢，同样代码在armv8上面可以正常工作。用你给的测试脚本在armeabiv7上测试结果也是正确的，不知道现在问题出在什么地方。

@RedFree 由于测试脚本可以得到正确结果，大概率是外部代码引起的问题。测试脚本是基于TNNTest运行的，可以对照TNN/test/test.cc的使用方式，检查sdk对tnn的使用是否有问题。
如果仍然无法定位问题，麻烦缩小范围并提供可复现问题的完整代码。

**Comment by RedFree** [comment]
@quinnrong94 
我读了TNNTest的代码和Android tnn_sdk_sample.cc中的初始化以及前向做了比较。
1.初始化参数一致。
2.前向的区别是tnn_sdk_sample采用instance中的接口设置输入数据，TNNTest是采用blob数据绑定的方式。
我按照TNNTest中的方式修改了tnn_sdk_sample的设置方式，问题还是存在。
3.将TNNTest程序push到Android设备上执行，结果正确。
我将我的Android工程传上去，里面可执行的模型就是出问题的这个模型。
jni接口调用：
spro_face_detector_jni.cc中的detectFromImage函数->spro_pipeline.cpp中的liveDetectForward函数。
模型执行过程是在liveDetectForward函数中。测试图片也放到附件中了。
文件较大，我把工程放到云盘中。
链接: https://pan.baidu.com/s/1VvvA90gQuWVlhbvIZ9ABdw  密码: 2usg

**Comment by RedFree** [comment]
使用分支hotfix_issue_1070的Android tnn_sdk_sample,上述问题解决。
