### ISSUE TITLE
op convert failed onnx :LogSoftmax

### ISSUE THREAD

**Issue by qingwwlong** [Tencent/TNN#1058]
Ubuntu

        python转化为onnx，然后通过Tnn模型转化出现异常，op convert failed onnx :LogSoftmax，在onnx2tnn.cc line 303处报错，是Logsoftmax还不支持么

**Comment by 1627180283** [comment]
是的，暂时还不支持，你可以试一下把 LogSoftmax 拆为 Log 和 Softmax 两个算子再转一下试试看
我稍后支持一下这个算子

**Comment by qingwwlong** [comment]
好的 ，解决了之后通知下，多谢了

**Comment by 1627180283** [comment]
这个算子在 dev_logsoftmax 分支上支持了，你试一下看

**Comment by 1627180283** [comment]
> 这个算子在 dev_logsoftmax 分支上支持了，你试一下看

这个代码已经合入 master 了，issue 先关闭了，如果有新的问题还可以再打开
