### ISSUE TITLE
咨询个opecl binary问题

### ISSUE THREAD

**Issue by peyer** [Tencent/TNN#1059]
https://github.com/Tencent/TNN/blob/259152671c3d0bf99b6ae55690df1f90ce6d5ed2/source/tnn/device/opencl/acc/opencl_binary_layer_acc.cc#L187
这里应该缺少BinaryNHW的支持吧？就是一个输入为N(N >= 2), C(>1), H, W, 另一个输入为N(N >= 2), 1, H, W时，会调用BinaryHW的kernel，但是实际上BinaryHW的kernel只能读取N(N >= 2), 1, H, W的输入的第一个batch的数据，造成输出结果是错误的

**Comment by lnmdlong** [comment]
@peyer BinaryHW的Kernel做了对上述场景的支持，在一个输入为N(N >= 2), C(>1), H, W, 另一个输入为N(N >= 2), 1, H, W时，第二个输入做广播会根据实际的batch维度去读取数据，不会只取第一个batch

**Comment by peyer** [comment]
是的，新代码更正了BinaryHW kernel，以前的老代码是
const int h_idx = bh % height;
const int w_idx = cw % width;
FLOAT4 in0      = RI_F(input, SAMPLER, (int2)(cw, bh));
FLOAT in1       = RI_F(param, SAMPLER, (int2)(w_idx, h_idx)).x;

看到了
