### ISSUE TITLE
使用官方镜像并且通过docker run --volume挂载依然出现文件不存在报错

### ISSUE THREAD

**Issue by DRosemei** [Tencent/TNN#106]
所使用命令：
 docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py onnx2tnn /workspace/MobileNetV2.onnx -in input[1,3,224,224] -optimize -v v1.0.0 -align
报错：
the onnx2tnn command:python3 onnx2tnn.py /workspace/MobileNetV2.onnx -version=v1.0 -optimize=1 -half=0 -o /workspace
0.----onnx version:1.7.0
algo_optimize 1
onnx_net_opt_path /workspace/MobileNetV2.opt.onnx
1.----onnx_optimizer: /workspace/MobileNetV2.onnx
/opt/TNN/tools/onnx2tnn/onnx-converter
----load onnx model: /workspace/MobileNetV2.onnx
----export optimized onnx model: /workspace/MobileNetV2.opt.onnx
----export optimized onnx model done

weight = 478
weight = classifier.1.bias
weight = classifier.1.weight
weight = features.0.0.weight
weight = features.0.1.bias
...
...
const node = node_464
const node = node_465
const node = node_466
const node = node_467
const node = node_468
const node = node_469
const node = node_471
const node = node_472
const node = node_474
python3: /opt/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc:226: int Onnx2TNN::TNNWriteProto(): Assertion `0' failed.
Aborted (core dumped)

onnx2tnn failed!
the /workspace/MobileNetV2.opt.tnnmodel does not exist! please make sure the file exist!
请问是什么问题呢？

**Comment by gttiankai** [comment]
我自己用mobilenetv2测试了一下，并没有出现这个问题。从日志中看，是因为转换失败了，并不是没有找到文件。你测试的mobiletnetV2 是修改过的？能否提供下模型？

**Comment by DRosemei** [comment]
> 我自己用mobilenetv2测试了一下，并没有出现这个问题。从日志中看，是因为转换失败了，并不是没有找到文件。你测试的mobiletnetV2 是修改过的？能否提供下模型？

为了能够转换成onnx模型，确实是修改过的，只是将
“x = nn.functional.adaptive_avg_pool2d(x, 1).reshape(x.shape[0], -1)”替换成了
b, c, _, _ = x.size()
x = torch.mean(x.reshape(b, c, -1), -1)
模型最后分类数4，其他没有改动
下面是原始pth模型和onnx模型链接
https://share.weiyun.com/OkQ9uaLB
https://share.weiyun.com/XXqRUKxJ

**Comment by gttiankai** [comment]
问题是因为转出来的onnx的w方向上是不固定的。目前还不支持这种模型的转换。你可以导出onnx模型时，指定w方向为224， 在前向过程中是支持可变shap的的。

![企业微信截图_4dcf5e4f-34a6-4f1c-91ca-df98a39c0004](https://user-images.githubusercontent.com/5379313/85496798-7c09c080-b60f-11ea-98aa-a72ecfefaf0d.png)

**Comment by gttiankai** [comment]
你能转换出来的？ 我测试了，转换不出来的。 代码中有对shape信息的校验啊， 你改了校验逻辑？

**Comment by DRosemei** [comment]
> 我自己用mobilenetv2测试了一下，并没有出现这个问题。从日志中看，是因为转换失败了，并不是没有找到文件。你测试的mobiletnetV2 是修改过的？能否提供下模型？


> 你能转换出来的？ 我测试了，转换不出来的。 代码中有对shape信息的校验啊， 你改了校验逻辑？
我使用的这个脚本
python3 converter.py onnx2tnn ~/download/MobileNetV2.onnx -in input[1,3,224,224] -optimize -v v1.0.0 -o ~/download/ -half

**Comment by gttiankai** [comment]
在TNN/tools/onnx2tnn/src/core/onnx2tnn.cc 的224行到226行是有校验代码的，这个模型还是转不成功。你可以试下转换处出来的模型是否能运行吧
```cc
if (shape_c <= 0 || shape_h <= 0 || shape_w <= 0) {
    DLog("intput shape is invalid\n");
    assert(0);
}
```

**Comment by DRosemei** [comment]
我把模型w固定就ok了，感谢🙏

**Comment by DRosemei** [comment]
> 在TNN/tools/onnx2tnn/src/core/onnx2tnn.cc 的224行到226行是有校验代码的，这个模型还是转不成功。你可以试下转换处出来的模型是否能运行吧
> 
> ```c++
> if (shape_c <= 0 || shape_h <= 0 || shape_w <= 0) {
>     DLog("intput shape is invalid\n");
>     assert(0);
> }
> ```

我把模型w固定就ok了，感谢🙏
