### ISSUE TITLE
TNN 模型转换成功，不能对齐

### ISSUE THREAD

**Issue by NewCoderQ** [Tencent/TNN#1069]
**1. 使用环境（environment）**
 - OS: Mac/Ubuntu/Centos/Docker
 - OS Version:Ubuntu

  **2. Github版本**
 - branch：
 - commit(optional):  1e3c9f377c282bafb084ef9cac773a9e28b33cbb

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型不对齐（model misalignment）
 - original model： ONNX 模型文件如附件所示
[tnn_models.zip](https://github.com/Tencent/TNN/files/6713729/tnn_models.zip)

  **5. 截图（Screenshots）**
![reliao_img_1624598683075](https://user-images.githubusercontent.com/25003964/123373863-befecb00-d5b8-11eb-9169-c8ab90787f85.png)

**Comment by 1627180283** [comment]
![image](https://user-images.githubusercontent.com/37806708/123375412-4f3e0f80-d5bb-11eb-893e-819c65292313.png)

你试一下最新的 master 分支，我这边是可以转换对齐的

**Comment by NewCoderQ** [comment]
好的，多谢，我这边试下

**Comment by 1627180283** [comment]
> 好的，多谢，我这边试下

你好，你这边可以对齐吗

**Comment by NewCoderQ** [comment]
> > 好的，多谢，我这边试下
> 
> 你好，你这边可以对齐吗

可以对齐了，已经可以在 iphone 端跑起来了，多谢
