### ISSUE TITLE
模型量化输出全为0

### ISSUE THREAD

**Issue by RedFree** [Tencent/TNN#1070]
**1. 环境（environment）**
转换环境：Ubuntu 18.04
TNN: master f308ab18
运行环境：Android 10

**2. 转换命令
```
./build/quantization_cmd -p /home/wd/data/pro/sproai/projects/AILock/network/retinaface/tnn/retinaface.tnnproto \
-m /home/wd/data/pro/sproai/projects/AILock/network/retinaface/tnn/retinaface.tnnmodel \
-i /home/wd/data/DataSets/TNN_quantization/retinaface1 \
-n 104,117,123 \
-s 1.0,1.0,1.0 \
-t 1
```

输出结果全为0.

原始模型和转换后的模型如附件：
[retinaface.zip](https://github.com/Tencent/TNN/files/6714597/retinaface.zip)

请帮忙看下问题，谢谢。

**Comment by quinnrong94** [comment]
@RedFree 量化工具最近有所更新，请切换至master分支的 ca26a1b5 尝试，看问题是否仍然存在。

**Comment by RedFree** [comment]
@quinnrong94 
代码已经更新到ca26a1b5个分支，量化结果输出仍然是0.
量化前模型如下：
[retinaface_uq.zip](https://github.com/Tencent/TNN/files/6731590/retinaface_uq.zip)
量化后模型：
[model.quantized.zip](https://github.com/Tencent/TNN/files/6731592/model.quantized.zip)

**Comment by quinnrong94** [comment]
@RedFree 问题已复现，并在 hotfix_issue_1070 分支修复，请切换至该分支重新量化并测试。

注意到量化模型转换命令中设置了`-t 1`参数，该参数表示weight采用per-channel方式，blob采用per-tensor方式。对该模型测试发现，使用默认的`-t 0`参数，即weight和blob都采用per-channel方式，精度更高。

使用附件中的20张图片做校准，用余弦相速度衡量模型输出的精度，int8和fp32结果可以得到~98%相似度，测试脚本：
[scripts.zip](https://github.com/Tencent/TNN/files/6739419/scripts.zip)

**Comment by RedFree** [comment]
@quinnrong94 我更新了hotfix_issue_1070分支，添加OpenCL支持时，Android编译出错，出错信息如下：
![选区_591](https://user-images.githubusercontent.com/5827427/124213077-8e6fe180-db22-11eb-8746-2b504ab60212.png)

**Comment by quinnrong94** [comment]
@RedFree 编译出错的问题在master分支已修复。目前量化模型只在低端机型有明显性能提升，高端机型性能加速正在开发。
