### ISSUE TITLE
可以出一个像ncnn一样的示例吗？

### ISSUE THREAD

**Issue by TD-wzw** [Tencent/TNN#1077]
https://github.com/Tencent/ncnn/wiki
就类似于这样的一个连贯一点从创建网络到获取输出的简单示例，我是个刚入门的小白，想用tnn看一下，目前的api文档有点看不懂

**Comment by darrenyao87** [comment]
TNNSDKSample（https://github.com/Tencent/TNN/blob/master/examples/base/tnn_sdk_sample.cc）已经封装了调用方式，
你可以继承这个类生成自己的sdk，只要按需重载几个函数（初始化Init，输入预处理ProcessSDKInputMat，输出后处理ProcessSDKOutput）就可以。参看blazeface_detector的实现（https://github.com/Tencent/TNN/blob/master/examples/base/blazeface_detector.cc）

**Comment by TD-wzw** [comment]
非常感谢！
