### ISSUE TITLE
opencl_tile_layer_acc.cc中变量重复定义

### ISSUE THREAD

**Issue by zhiyuyan** [Tencent/TNN#1081]
最新版本中，编译TNN时报错
TNN/source/tnn/device/opencl/acc/opencl_tile_layer_acc.cc:46:17: error: redefinition of 'kernel_name'
    std::string kernel_name = "Tile";

/TNN/source/tnn/device/opencl/acc/opencl_tile_layer_acc.cc:39:17: note: previous definition is here
    std::string kernel_name;

**Comment by shaundai-tencent** [comment]
已经复现问题，会尽快修复
