### ISSUE TITLE
TNN opencl converttoMat 和 covertfrommat windows 上分别接近400ms，时间过长，需要解决。

### ISSUE THREAD

**Issue by stephehuang** [Tencent/TNN#1091]
win10 平台 3.60GHZ 4核 Intel i7
输入 nchw 1x4x192 x 192
输出 nchw 1x4x224x224

**Comment by shaundai-tencent** [comment]
ConvertFromMat和ConvertToMat接口耗时问题，是第一次调用耗时较高，因为要编译kernel，后面调用耗时很小。这是正常现象。
