### ISSUE TITLE
opencl_profiler 一个小问题

### ISSUE THREAD

**Issue by peyer** [Tencent/TNN#1094]
https://github.com/Tencent/TNN/blob/69f27bf38c5577a5f9d62a1ff609d347c6419134/source/tnn/device/opencl/acc/opencl_inner_product_layer_acc.cc#L240
这一行的命名应该改成 reshape_param_.name = layer_name_ + "_Reshape"，否则最后summary显示的时候，后面需要reshape的innerProduct层之前调用的reshape_layer不会在summary里显示出来

**Comment by shaundai-tencent** [comment]
你好，我没有复现你说的问题，我使用BenchmarkLayer测试了一层的InnerProduct，结果如下：
![innerproduct_profiling](https://user-images.githubusercontent.com/66760945/124251845-ef1a1100-db58-11eb-840e-ca9cb95a6722.png)
在summary里面有reshape的耗时。

**Comment by peyer** [comment]
我可能没有说清楚，我遇到一个模型有多层InnerProduct，第一个innerProduct之后的 innerProduct 里面的reshape_layer不会在它前面显示出来；
单层innerProduct看不出来

**Comment by shaundai-tencent** [comment]
哦，明白了，是因为名字一样，那这里确实有问题，多谢提出此问题。

**Comment by shaundai-tencent** [comment]
是否可以提供一下proto文件，可以复现问题的部分结构就行，我复现一下问题。谢谢！shaundai@tencent.com

**Comment by dqliu15** [comment]
公司的原因，内部文件不好公开；复现的话可以在onnx里构建网络

**Comment by peyer** [comment]
公司的原因，不方便上传内部文件。onnx构造很快的

**Comment by shaundai-tencent** [comment]
已经复现问题，会尽快合入master，非常感谢！
