### ISSUE TITLE
量化模型报错

### ISSUE THREAD

**Issue by gray2bgr** [Tencent/TNN#1098]
你好，我照着教程取转换模型会报错，请问一下是什么原因，该怎么解决
root@0e03d30639c4:/inference/TNN/platforms/linux/build# ./quantization_cmd -p /inference/models/tnn_models/mobilenet_v3_large_opti.opt.tnnproto -m /inference/models/tnn_models/mobilenet_v3_large_opti.opt.tnnmodel -i ../quant_images/
proto: /inference/models/tnn_models/mobilenet_v3_large_opti.opt.tnnproto
model: /inference/models/tnn_models/mobilenet_v3_large_opti.opt.tnnmodel
input path: ../quant_images/
init model config success!
        import: 0851b133b01b67fe6b0f9512a18b7bc0.jpeg  type: 3
        import: 10a9ee758e4d35ab0812c5df0e13a8e2.jpeg  type: 3
        import: 16240a8c30fd679847833822a76f9260.jpeg  type: 3
        import: 2b3554c286e15c2499b53537971b68b4.jpeg  type: 3
        import: 2f6aea197d64772999ca845218891d94.jpeg  type: 3
        import: 30208425e8eb7f07eb98b6fb67bfc9b5.jpeg  type: 3
        import: 49f495533aa3ca3952e65e63a99d3d7d.jpeg  type: 3
        import: 4de4d680fa3b4e5d4304092116d92b1c.jpeg  type: 3
        import: 55f6d28a175459b581f0e6eeda2cca82.jpeg  type: 3
        import: 57d02740360e4e9b92bb18d8f3e8a229.jpeg  type: 3
        import: 5b1fcf929b83c3e9063af746d55734b8.jpeg  type: 3
        import: 5ea1925b72311995840ae8443312aa07.jpeg  type: 3
        import: 6ef72a739db0eb7d14d0b27d17823320.jpeg  type: 3
        import: 71df59e7866ba9c4ae7141d61c28c2b4.jpeg  type: 3
        import: 9e8d001b3b8d1b317fb67ee576b17c2d.jpeg  type: 3
        import: b051baf47f1118f05eaa271d87c904da.jpeg  type: 3
        import: ba6d6aab6b96bc54ff9151a902c89998.jpeg  type: 3
        import: c1bab77415128b9cf9ebbf03c04890a7.jpeg  type: 3
        import: c9273465dac73e7ecd0fa4a36cbb8b45.jpeg  type: 3
        import: d30bcaa7fbfdfdebe67eb3e92c4ace98.jpeg  type: 3
        import: ebf217c2e9b91929c0265275d06c6923.jpeg  type: 3
import total 21 files
import data set success!
Start to calculate blob scale ...
        Init Feature Map done!
        Collect Blob Range done!
        Collect Blob Distribution done!
        ====> Calculate (328_scale_data_) done!
        ====> Calculate (331_scale_data_) done!
        ====> Calculate (322_scale_data_) done!
        ====> Calculate (325_scale_data_) done!
        ====> Calculate (342_scale_data_) done!
        ====> Calculate (352_scale_data_) done!
        ====> Calculate (345_scale_data_) done!
        ====> Calculate (348_scale_data_) done!
        ====> Calculate (339_scale_data_) done!
        ====> Calculate (386_scale_data_) done!
        ====> Calculate (383_scale_data_) done!
        ====> Calculate (384_scale_data_) done!
        ====> Calculate (380_scale_data_) done!
        ====> Calculate (381_scale_data_) done!
        ====> Calculate (377_scale_data_) done!
        ====> Calculate (371_scale_data_) done!
        ====> Calculate (374_scale_data_) done!
        ====> Calculate (369_scale_data_) done!
        ====> Calculate (368_scale_data_) done!
        ====> Calculate (366_scale_data_) done!
        ====> Calculate (362_scale_data_) done!
        ====> Calculate (365_scale_data_) done!
        ====> Calculate (357_scale_data_) done!
        ====> Calculate (354_scale_data_) done!
        ====> Calculate (355_scale_data_) done!
        ====> Calculate (351_scale_data_) done!
        ====> Calculate (334_scale_data_) done!
        ====> Calculate (389_scale_data_) done!
        ====> Calculate (399_scale_data_) done!
        ====> Calculate (409_scale_data_) done!
        ====> Calculate (421_scale_data_) done!
        ====> Calculate (431_scale_data_) done!
        ====> Calculate (434_scale_data_) done!
        ====> Calculate (444_scale_data_) done!
        ====> Calculate (454_scale_data_) done!
        ====> Calculate (457_scale_data_) done!
        ====> Calculate (467_scale_data_) done!
        ====> Calculate (477_scale_data_) done!
        ====> Calculate (480_scale_data_) done!
        ====> Calculate (490_scale_data_) done!
        ====> Calculate (500_scale_data_) done!
        ====> Calculate (501_scale_data_) done!
        ====> Calculate (503_scale_data_) done!
        ====> Calculate (504_scale_data_) done!
        ====> Calculate (506_scale_data_) done!
        ====> Calculate (518_scale_data_) done!
        ====> Calculate (528_scale_data_) done!
        ====> Calculate (529_scale_data_) done!
        ====> Calculate (531_scale_data_) done!
        ====> Calculate (532_scale_data_) done!
        ====> Calculate (534_scale_data_) done!
        ====> Calculate (537_scale_data_) done!
        ====> Calculate (547_scale_data_) done!
        ====> Calculate (557_scale_data_) done!
        ====> Calculate (558_scale_data_) done!
        ====> Calculate (560_scale_data_) done!
        ====> Calculate (561_scale_data_) done!
        ====> Calculate (563_scale_data_) done!
        ====> Calculate (575_scale_data_) done!
        ====> Calculate (585_scale_data_) done!
        ====> Calculate (586_scale_data_) done!
        ====> Calculate (588_scale_data_) done!
        ====> Calculate (589_scale_data_) done!
        ====> Calculate (591_scale_data_) done!
        ====> Calculate (594_scale_data_) done!
        ====> Calculate (604_scale_data_) done!
        ====> Calculate (614_scale_data_) done!
        ====> Calculate (615_scale_data_) done!
        ====> Calculate (617_scale_data_) done!
        ====> Calculate (618_scale_data_) done!
        ====> Calculate (620_scale_data_) done!
        ====> Calculate (623_scale_data_) done!
        ====> Calculate (633_scale_data_) done!
        ====> Calculate (634_scale_data_) done!
E/tnn: RunCalibration [File /inference/TNN/tools/quantization/calibration.cc][Line 144] calcluate blob scale failed!
calibration run failed!
root@0e03d30639c4:/inference/TNN/platforms/linux/build#

**Comment by shaundai-tencent** [comment]
这个错误信息很难定位问题，能否发一下出错的模型文件？shaundai@tencent.com

**Comment by shaundai-tencent** [comment]
模型已经收到，我复现了一下问题，发现输入是0~255时确实会出现你说的错我，而根本原因是，Gemm_277这一层的输入全部是0导致的，这也无法量化。我将输入归一化之后，可以得到结果。看你的执行命令，没有归一化的参数。请问，模型实际执行的输入是否需要归一化之类的预处理操作？
