### ISSUE TITLE
Find a bug in TNN/tools/onnx2tnn/onnx-converter/build.sh (line:61)

### ISSUE THREAD

**Issue by yank666** [Tencent/TNN#1100]
You guys take a mistake in copy *.so ,the line:61 in TNN/tools/onnx2tnn/onnx-converter/build.sh is wrong:
```
  cp ${onnx2nn_files[i]} ../../../../../onnx-converter

```
![image](https://user-images.githubusercontent.com/79586188/124249185-36eb6900-db56-11eb-8c25-a2f022da1166.png)

if not correct cp path, after ./build.sh, exce "pythononnx2tnn.py "  will report "You should compile onnx2tnn first !!!"

**Comment by TonyChouZJU** [comment]
OMG

**Comment by 1627180283** [comment]
Thanks, this bug has been fixed in the master branch.

**Comment by yank666** [comment]
ok
