### ISSUE TITLE
集成TNN预测引擎后，工程中使用opencv的warpAffine崩溃。

### ISSUE THREAD

**Issue by jianzfb** [Tencent/TNN#1110]
**1. 环境（environment）**
 - Build OS and Version: Mac
 - RunTime OS Version: Android
 - RunTime DEVICE: OPENCL

  **2. Github版本**
 - branch：master
 - commit(optional):

  **5. 详细描述bug 情况 (Describe the bug)**

集成TNN后，工程中使用了opencv的cv::warpAffine(AA, dst_mat, M_mat, dst_mat.size()); 对图像做预处理，直接产生segment fault。不清楚原因，已经测试如果不加载tnn 模型，仅使用cv::warpaffine没有任何问题。 

这个问题很奇怪？是不是 冲突啊。 希望大神 帮忙解答一下。

**Comment by shaundai-tencent** [comment]
在接口上面是不会有冲突的，可以调试一下，看是否有内存的非法访问。

**Comment by shaundai-tencent** [comment]
请问问题解决了吗？
