### ISSUE TITLE
tnn实现细节问题

### ISSUE THREAD

**Issue by 1icas** [Tencent/TNN#1111]
最近正在阅读tnn里面封装tensorrt部分的代码，目前有一些疑问，请求大佬们解答。
问题1：
为什么tnn要对tensorrt所有算子单独做一次封装呢（TNN/source/tnn/network/tensorrt/layer_builder/文件夹下面）？目的是什么呢？

**Comment by shaundai-tencent** [comment]
对TRT算子进行封装有以下原因：
1、为了可以使用TNN模型格式作为输入，这样对使用者而言，在不同的平台只要使用相同的模型就行了。
2、可以利用TNN的模型格式，进行模型结构的优化。
3、可以利用TRT一些高性能的算子，而对于TRT不支持的算子，可以通过插件的方式，自己实现。

**Comment by 1icas** [comment]
> 对TRT算子进行封装有以下原因：
> 1、为了可以使用TNN模型格式作为输入，这样对使用者而言，在不同的平台只要使用相同的模型就行了。
> 2、可以利用TNN的模型格式，进行模型结构的优化。
> 3、可以利用TRT一些高性能的算子，而对于TRT不支持的算子，可以通过插件的方式，自己实现。

非常感谢，关于您说的第三条原因。目前是否支持 “TRT不支持的算子，默认使用tnn算子替代呢？”

**Comment by shaundai-tencent** [comment]
是支持的，可以查看目录TNN/source/tnn/device/cuda/acc，这个目录下面的实现都是cudnn实现或者cuda实现。如果TRT不支持，会调用到这里的实现。

**Comment by 1icas** [comment]
好的。感谢
