### ISSUE TITLE
opencl_profile一个小建议

### ISSUE THREAD

**Issue by peyer** [Tencent/TNN#1114]
https://github.com/Tencent/TNN/blob/981e4c84581b9779ccf1eecd1ee28d842fc647b3/source/tnn/device/opencl/opencl_context.h#L30
提个建议，这里改成std::vector<cl::Event> events会更好？有可能遇到这种情况，ocl warmup以后，对同一个ocl op运行多次，但是OpenCLProfilingData只会对同一个ID添加最后运行的一次event，无法对这个多次运行的ocl op的 ocl kernel runtime取均值

**Comment by shaundai-tencent** [comment]
是个不错的建议，但是需要评估一下，如果这样改之后event数目会骤增，会不会有影响。此外，是否有必要计算kernel的平均值。
目前做profiling是warm up之后，取得第一次的event来统计的，以我们实验的经验，性能还是比较稳定的。通过instance->StartProfile()和instance->FinishProfile(true)两个接口来控制开始统计和结束统计的时间点。
