### ISSUE TITLE
测试安卓的benchmark卡住

### ISSUE THREAD

**Issue by gripdestiny** [Tencent/TNN#1118]
**1. 环境（environment）**
 - Build OS and Version: Mac
 - RunTime OS Version: Android
 - RunTime DEVICE: ARM/OPENCL/METAL
华为mate 40  pro ，麒麟9000
  **2. Github版本**
 - branch：hotfix_issue_1109
 - commit(optional):

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)
sh benchmark_models.sh -c -32
带不带-32都会卡住

  **4. 编译日志(build log)**
 ```txt
[build.txt](https://github.com/Tencent/TNN/files/6774275/build.txt)
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
1、使用默认参数跑benchmark，弹出在手机上安装了一个app就卡住了，结果文件只有一个手机型号
2、用-bs参数跑安卓benchmark，提示找不到libomp.so

  **6. 运行日志（runtime log）**
 ```txt
 Performing Streamed Install
Success
/Users/gray2rgb/hdw/TNN/benchmark/benc...d. 22.2 MB/s (2233453 bytes in 0.096s)
./test/libTNNBenchmarkTest.so: 1 file pushed, 0 skipped. 486.0 MB/s (153292 bytes in 0.000s)
./libTNN.so: 1 file pushed, 0 skipped. 71.5 MB/s (3229524 bytes in 0.043s)
./build_app/libtnn_wrapper.so: 1 file pushed, 0 skipped. 837.4 MB/s (441216 bytes in 0.001s)
-e 
benchmark device: ARM

Stopping: com.tencent.tnn.benchmark
Starting: Intent { cmp=com.tencent.tnn.benchmark/.MainActivity (has extras) }
Status: ok
LaunchState: COLD
Activity: com.tencent.tnn.benchmark/.MainActivity
TotalTime: 432
WaitTime: 4884
Complete
 Paste log here or pastebin
 ```

  **7. 截图（Screenshots）**
这个图是-bs的结构
<img width="570" alt="WX20210707-115108@2x" src="https://user-images.githubusercontent.com/23710846/124697902-3cf89580-df1a-11eb-974f-00922a334dd7.png">
这个是不带-bs的截图，在手机上安装了app以后就卡着不动，也不会有结果
<img width="570" alt="WX20210707-115036@2x" src="https://user-images.githubusercontent.com/23710846/124697913-43870d00-df1a-11eb-8ec4-f66cfd11593b.png">
这个txt是-bs结果，不带参数就只有第一行
[benchmark_models_result.txt](https://github.com/Tencent/TNN/files/6774137/benchmark_models_result.txt)

编译测试用的脚本
[benchmark_models.sh.txt](https://github.com/Tencent/TNN/files/6788513/benchmark_models.sh.txt)

**Comment by quinnrong94** [comment]
@gripdestiny hotfix_issue_1109已合入主分支。基于master分支commit id d402556 测试：使用ndk-r18b编译，在华为mat40 pro上运行，使用benchmark_models.sh脚本，测试结果app和shell两种方式都能正常运行。
建议切换至master分支重新测试，如果问题仍然存在，麻烦提供出现问题的ndk版本号，测试机型，编译日志和测试模型，以便我们复现。

**Comment by gripdestiny** [comment]
谢谢，用ndk-18b就可以了。我之前用的是21e会不行
