### ISSUE TITLE
virtual tnn::Status tnn::OpenCLDevice::Allocate(void **, tnn::MatType, tnn::DimsVector) [File /home/runner/work/TNN/TNN/source/tnn/device/opencl/opencl_device.cc][Line 59] opencl allocator not support this mat type: 0

### ISSUE THREAD

**Issue by TD-wzw** [Tencent/TNN#1121]
请问在安卓平台推理时Device_Type设为opencl报这个错是因为什么呀？Mat类型不支持

**Comment by TD-wzw** [comment]
再补充一下，Device_Type设置为arm平台是可以的，换成opencl的时候会报错，是不是opencl平台下代码需要做些小调整，在文档里没有找到相关的。。。

**Comment by shaundai-tencent** [comment]
在Mat构造的时候，当device_type设置为OpenCL的时候，MatType目前只支持N8UC4，这是为了支持从安卓的Texture数据(RGBA格式)直接转为clImage数据，避免从GPU到CPU再到GPU的拷贝。一般情况下，使用OpenCL平台，如果传入的数据是cpu的数据，那Mat使用device_type为ARM即可。内部会自动将cpu的数据转换为gpu数据。

**Comment by TD-wzw** [comment]
跪拜大佬，非常感谢！
