### ISSUE TITLE
NetOptimizerInsertLayoutReformat Error: empty implemented_layouts

### ISSUE THREAD

**Issue by jonbakerfish** [Tencent/TNN#1122]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu
 - RunTime OS Version: Android
 - RunTime DEVICE: ARM/OPENCL

  **2. Github版本**
 - branch：master

  **3. 编译方式(compile method)**
./build_android.sh (with OPENMP="OFF")

  **4. 编译日志(build log)**
 ```txt
E/tnn: std::shared_ptr<const ImplementedLayout> tnn::optimizer::NetOptimizerInsertLayoutReformat::GetLayoutsByLayerType(tnn::LayerType) [File TNN_latest_/source/tnn/optimizer/net_optimizer_insert_layout_reformat.cc][Line 127] NetOptimizerInsertLayoutReformat Error: empty adaptor device layouts of 203
    virtual tnn::Status tnn::optimizer::NetOptimizerInsertLayoutReformat::Optimize(tnn::NetStructure *, tnn::NetResource *) [File TNN_latest_/source/tnn/optimizer/net_optimizer_insert_layout_reformat.cc][Line 247] NetOptimizerInsertLayoutReformat Error: empty implemented_layouts of layer 203
E/tnn: jint Java_test_init(JNIEnv *, jobject, jstring, jint, jint, jfloat, jfloat, jint) [File ../../../../src/main/jniLibs/cc/test_jni.cc][Line 104] test init failed 12288
    jint Java_test_init(JNIEnv *, jobject, jstring, jint, jint, jfloat, jfloat, jint) [File ../../../../src/main/jniLibs/cc/test_jni.cc][Line 105] code: 0x3000 msg: NetOptimizerInsertLayoutReformat Error: empty implemented_layouts
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
在安卓上加载自定义模型时出现以上错误，看了一下tnnproto的网络层，并没有发现不支持的。

tnnproto文件：
[test.zip](https://github.com/Tencent/TNN/files/6780838/test.zip)

**Comment by fire717** [comment]
我也遇到了，onnx转tnn都没报错还显示aligned，上安卓跑init的时候就崩了

```
NetOptimizerInsertLayoutReformat Error: empty adaptor device layouts of 326

E/tnn: virtual tnn::Status tnn::optimizer::NetOptimizerInsertLayoutReformat::Optimize(tnn::NetStructure *, tnn::NetResource *) [File /home/runner/work/TNN/TNN/source/tnn/optimizer/net_optimizer_insert_layout_reformat.cc][Line 234] NetOptimizerInsertLayoutReformat Error: empty implemented_layouts of layer 326

create instance type 20 failed

JNI detector init failed 12288
```

**Comment by quinnrong94** [comment]
从日志上看，分别是layer 203和layer 326不支持，可以从layer_type.h查到分别是LAYER_CONVOLUTION_1D和LAYER_LAYER_NORM，这两个算子目前只在服务端（CUDA或X86）支持，移动端暂不支持。
算子支持情况请参考https://github.com/Tencent/TNN/blob/master/doc/en/user/support_en.md

**Comment by fire717** [comment]
收到，的确有LAYER_NORM，我研究下如何替换。谢谢！

**Comment by cbingdu** [comment]
> 我的模型结构就这么简单，也遇到了类似报错： ![image](https://user-images.githubusercontent.com/43233772/203198123-b3ab9885-a11d-4fd7-a2cd-8d9a648ddd65.png)
> 
> ```
> E/tnn: std::shared_ptr<const ImplementedLayout> tnn::optimizer::NetOptimizerInsertLayoutReformat::GetLayoutsByLayerType(tnn::LayerType) [File source/tnn/optimizer/net_optimizer_insert_layout_reformat.cc][Line 126] NetOptimizerInsertLayoutReformat Error: empty adaptor device layouts of 333
> E/tnn: virtual tnn::Status tnn::optimizer::NetOptimizerInsertLayoutReformat::Optimize(tnn::NetStructure *, tnn::NetResource *) [File source/tnn/optimizer/net_optimizer_insert_layout_reformat.cc][Line 246] NetOptimizerInsertLayoutReformat Error: empty implemented_layouts of layer 333
> ```
> 
> 经查，layer 333是`LAYER_GREATER = 333`，我的设备是DEVICE_ARM

NetOptimizerInsertLayoutReformat Error: empty adaptor device layouts of 327
看到这个错误是327层的问题，但是怎么找到第327层对应的是哪一个算子呢
