### ISSUE TITLE
You should compile onnx2tnn first !!!

### ISSUE THREAD

**Issue by sjtu-nobody** [Tencent/TNN#1123]
**1. 使用环境（environment）**
 - OS: Mac/Ubuntu/Centos/Docker
 - OS Version:

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
使用官方docker镜像转换onnx模型，报错You should compile onnx2tnn first !!!，应该怎么处理？

  **4. 日志（Log）**
root@389ba1dd948f:/opt/TNN/tools/convert2tnn# python3 ./converter.py onnx2tnn /workspace/dcscnn.onnx  -in in_0:1,3,960,540 in_1:1,3,960,540 in_2:1,3,960,540 in_3:1,3,960,540 in_4:1,3,960,540 -debug

----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN check_onnx_dim...

The onnx2tnn command:python3 onnx2tnn.py /workspace/dcscnn.onnx -version=202107080747 -optimize=0 -half=0 -o /workspace -input_shape in_0:1,3,960,540 in_1:1,3,960,540 in_2:1,3,960,540 in_3:1,3,960,540 in_4:1,3,960,540

You should compile onnx2tnn first !!!

You can find more compilation details in <path-to-tnn>/doc/cn/user/convert.md

Converter ONNX to TNN model failed!

**Comment by 1627180283** [comment]
你好，我这边测试了一下，没有复现这个问题
方便进入 docker，查看一下 TNN/tools/onnx2tnn/onnx-converter 目录下有没有 onnx2tnn*.so 类似的文件吗

**Comment by sjtu-nobody** [comment]
找到问题了，用的是一周以前down的版本，搜到了commit了里已经修复了这个问题 #1062

**Comment by lao-wang123** [comment]
用的最新版本yolov5，compiled onnx2nn successfully，但我只要开始运行 python3 onnx2tnn.py yolov5s_sim.onnx -version=v1.0 -optimize=1 -half=0 -o ~/TNN-master/tools/onnx2tnn  -input_shape input:1,3,448,640或者 python3 onnx2tnn.py yolov5s.onnx -version=v1.0 -optimize=1 -half=0 -o ~/TNN-master/tools/onnx2tnn  -input_shape input:1,3,448,640，就一直报错，
You should compile onnx2tnn first !!!

**Comment by 1627180283** [comment]
> 用的最新版本yolov5，compiled onnx2nn successfully，但我只要开始运行 python3 onnx2tnn.py yolov5s_sim.onnx -version=v1.0 -optimize=1 -half=0 -o ~/TNN-master/tools/onnx2tnn -input_shape input:1,3,448,640或者 python3 onnx2tnn.py yolov5s.onnx -version=v1.0 -optimize=1 -half=0 -o ~/TNN-master/tools/onnx2tnn -input_shape input:1,3,448,640，就一直报错， You should compile onnx2tnn first !!!

应该是编译的 python 和调用的 python 不是一个，可以检查一下 python。如果觉得比较麻烦，可以直接使用 tnn 提供的 docker 镜像进行模型转换。

**Comment by hymanxia** [comment]
请问，如何在rk3399部署模型？
