### ISSUE TITLE
TNN实现细节之TensorRT动态输入

### ISSUE THREAD

**Issue by 1icas** [Tencent/TNN#1124]
抱歉，又来打扰了。
想咨询一下关于TNN中TensorRT是否支持动态输入/输出的处理问题。目前有以下几个问题：
1. TNN中的TensorRT模块是否支持动态输入和动态输出
2. 如果问题1中都支持的话。请问对于动态输出来说，在代码的什么地方计算的“针对于不同的输入大小，真实的输出大小是多少”？

**Comment by johnzlli-tencent** [comment]
支持的，TensorRT对于动态输入支持可以参考官方文档
https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work_dynamic_shapes。
简单来说就是将输入的shape指定为dynamic的，并为每个输入设定一个[min, max]的范围，然后在执行forward之前，调用setBindingDimensions指定各个输入的实际shape，TensorRT会在内部会对实际的shape做推导。
