### ISSUE TITLE
[Benchmark] TNN benchmark  reported segment fault with official models

### ISSUE THREAD

**Issue by wejoncy** [Tencent/TNN#1137]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu 20.04
 - RunTime OS Version: Linux
 - RunTime DEVICE: X86 CPU

  **2. Github版本**
 - branch：master
 - commit(optional): latest 

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)
TNN/benchmark/benchmark_x86_linux/benchmark_models.sh

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
运行官方benchmark 脚本，编译成功，下载模型成功，但是执行报错

  **6. 运行日志（runtime log）**
 ```txt
 将日志粘贴在这里
E/tnn: Init [FileTNN/source/tnn/core/instance.cc][Line 68] ERROR: network_ is nil, network_type may not support
E/tnn: CheckResult [FileTNN/test/test.cc][Line 338] create instance failed: code: 0x2000 msg: network_ is nil, network_type may not support 
E/tnn: Init [FileTNN/source/tnn/core/instance.cc][Line 68] ERROR: network_ is nil, network_type may not support
E/tnn: CheckResult [FileTNN/test/test.cc][Line 338] create instance failed: code: 0x2000 msg: network_ is nil, network_type may not support 
E/tnn: Init [FileTNN/source/tnn/core/instance.cc][Line 68] ERROR: network_ is nil, network_type may not support
E/tnn: CheckResult [FileTNN/test/test.cc][Line 338] create instance failed: code: 0x2000 msg: network_ is nil, network_type may not support 
benchmark device: X86 
 Paste log here or pastebin
 ```

  **7. 截图（Screenshots）**
 ```txt
 将截图粘贴在这里
![image](https://user-images.githubusercontent.com/9417365/125276925-644cc980-e343-11eb-966d-1d876223084e.png)

 Paste screenshorts here or pastebin
 ```

**Comment by Maosquerade** [comment]
可以贴一下具体的命令吗？benchmark_model 脚本在不打开 DOWNLOAD_MODEL 选项时时不会自动下载模型，需要指定模型目录，且目录下需要包含 proto 和 model 文件。
我这边刚刚测试的打开 DOWNLOAD_MODEL 选项跑是可以的，请问你跑的是什么目录下的模型呢？

**Comment by wejoncy** [comment]
> 可以贴一下具体的命令吗？benchmark_model 脚本在不打开 DOWNLOAD_MODEL 选项时时不会自动下载模型，需要指定模型目录，且目录下需要包含 proto 和 model 文件。
> 我这边刚刚测试的打开 DOWNLOAD_MODEL 选项跑是可以的，请问你跑的是什么目录下的模型呢？

你好，感谢回复。
模型已经全部下载下来了，
![image](https://user-images.githubusercontent.com/9417365/125405937-d9bfa500-e3ea-11eb-9c46-82911c2f7e45.png)
 409091976 7月  12 18:27 bert-based.tnnmodel
     37373 7月  12 18:27 bert-based.tnnproto
 434818907 7月  12 18:27 bertsquad10_clean.tnnmodel
    169074 7月  12 18:27 bertsquad10_clean.tnnproto
 102127847 7月  12 18:27 resnet50.opt.tnnmodel
     11718 7月  12 18:26 resnet50.opt.tnnproto
，然后直接运行 bash benchmark_models.sh.
我同时编译了andriod版本，andriod下没有问题
谢谢

**Comment by wejoncy** [comment]
我重新拉代码，再编译，就可以了，应该是我环境的原因，多谢支持。
