### ISSUE TITLE
请问TNN支持底层算子在推理代码中单独拿出来用吗？

### ISSUE THREAD

**Issue by TD-wzw** [Tencent/TNN#1139]
void transpose(const ncnn::Mat& in, ncnn::Mat& out)
{
    ncnn::Option opt;
    opt.num_threads = 2;
    opt.use_fp16_storage = false;
    opt.use_packing_layout = true;

    ncnn::Layer* op = ncnn::create_layer("Permute");

    // set param
    ncnn::ParamDict pd;
    pd.set(0, 1);// order_type

    op->load_param(pd);

    op->create_pipeline(opt);

    ncnn::Mat in_packed = in;
    {
        // resolve dst_elempack
        int dims = in.dims;
        int elemcount = 0;
        if (dims == 1) elemcount = in.elempack * in.w;
        if (dims == 2) elemcount = in.elempack * in.h;
        if (dims == 3) elemcount = in.elempack * in.c;

        int dst_elempack = 1;
        if (layer->support_packing)
        {
            if (elemcount % 8 == 0 && ncnn::cpu_support_x86_avx2())
                dst_elempack = 8;
            else if (elemcount % 4 == 0)
                dst_elempack = 4;
        }

        if (in.elempack != dst_elempack)
        {
            convert_packing(in, in_packed, dst_elempack, opt);
        }
    }

    // forward
    op->forward(in_packed, out, opt);

    op->destroy_pipeline(opt);

    delete op;
}
就类似于ncnn这样的

**Comment by shaundai-tencent** [comment]
TNN没有提供这样的接口

**Comment by TD-wzw** [comment]
好的，谢谢耐心回答，我去看下TNN的premute实现
