### ISSUE TITLE
Windows 指令兼容性判断

### ISSUE THREAD

**Issue by gttiankai** [Tencent/TNN#1144]
**1. 环境（environment）**
 - Build OS and Version: Windows
 - RunTime OS Version: Windows
 - RunTime DEVICE: Windows

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 运行时 crash，判断是 有 avx 指令在 windows 上不支持。

**Comment by seanxcwang** [comment]
#1162
