### ISSUE TITLE
关于量化工具与单通道输入的模型的问题

### ISSUE THREAD

**Issue by moyuanye** [Tencent/TNN#115]
问题描述如下
模型：pytorch训练之输入为 1，112，112的模型，转换为tnn float 格式。
输入图片：24位jpg图片
转换错误：
E/tnn: tnn::Status tnn::FileReader::PreProcessImage(unsigned char*, tnn::Blob*, int, int, int) [File /home/ppt/TNN/tools/common/file_reader.cc][Line 113] input channel not match!
E/tnn: int tnn::Calibration::UpdateBlobRange(tnn::DataSet&) [File /home/ppt/TNN/tools/quantization/calibration.cc][Line 328] read input file (/home/ppt/3/16.png) falied!

代码位置：/home/ppt/TNN/tools/common/file_reader.cc 105
Status FileReader::PreProcessImage(unsigned char* img_data, Blob* blob,
                                   int width, int height, int channel) {
    float* data_ptr = static_cast<float*>(blob->GetHandle().base);
    if (blob->GetBlobDesc().data_format == DATA_FORMAT_NCHW) {
        int blob_c = blob->GetBlobDesc().dims[1];
        int blob_h = blob->GetBlobDesc().dims[2];
        int blob_w = blob->GetBlobDesc().dims[3];

        if (blob_c != channel) {
            LOGE("input channel not match!\n");
            return TNNERR_INVALID_INPUT;
        }

出错原因：模型输入 blob_c==1，图片channel==3

期望解决问题：可否自动检测模型输入为单通道，而输入图片为3通道时，将输入图片自动转换为单通道。

谢谢~

**Comment by shaundai-tencent** [comment]
好的，会尽快加入这个功能。

**Comment by shaundai-tencent** [comment]
已经添加支持

**Comment by moyuanye** [comment]
> 已经添加支持

Thanks.:)
