### ISSUE TITLE
请问TNN的Mat遍历方式有几种呀？

### ISSUE THREAD

**Issue by TD-wzw** [Tencent/TNN#1154]
auto *data = static_cast<float *>(output_mat->GetData());
data[i * n + j] * img.cols;
除了目前我所知道的这种方式，有没有类似于opencv或者ncnn的Mat的遍历方式？

**Comment by shaundai-tencent** [comment]
mat就提供了如下接口，
`    DeviceType GetDeviceType();
     MatType GetMatType();
     void* GetData();
     int GetBatch();
     int GetChannel();
     int GetHeight();
     int GetWidth();
     int GetDim(int index);
     DimsVector GetDims();
`
以及一些处理mat数据的函数：
`class PUBLIC MatUtils {
 public:
     //copy cpu <-> device, cpu<->cpu, device<->device, src and dst dims must be equal.
     static Status Copy(Mat& src, Mat& dst, void* command_queue);

     //src and dst device type must be same. when param scale_w or scale_h is 0, it is computed as
     // (double)dst.GetWidth() / src.GetWidth() or (double)dst.GetHeight() / src.GetHeight().
     static Status Resize(Mat& src, Mat& dst, ResizeParam param, void* command_queue);

     //src and dst device type must be same. when param width or height is 0, it is equal to
     //dst.GetWidth() or dst.GetHeight().
     static Status Crop(Mat& src, Mat& dst, CropParam param, void* command_queue);

     //src and dst device type must be same.
     static Status WarpAffine(Mat& src, Mat& dst, WarpAffineParam param, void* command_queue);

     //src and dst device type must be same.
     static Status CvtColor(Mat& src, Mat& dst, ColorConversionType type, void* command_queue);

     //src and dst device type must be same. param top, bottom, left and right must be non-negative.
     static Status CopyMakeBorder(Mat& src, Mat& dst, CopyMakeBorderParam param, void* command_queue);
 };
`

如果要直接获取Mat的数据，目前只能通过GetData()接口拿到数据指针进行操作，请问，你指的mat遍历方式是那种？

**Comment by TD-wzw** [comment]
嗯嗯，那了解了，非常感谢您！
