### ISSUE TITLE
请问android demo多线程是怎么设置的

### ISSUE THREAD

**Issue by gripdestiny** [Tencent/TNN#1155]
我在tnn_sdk_sample.cc
instance = net_->createInst(xxxx
instance->setcpunumthread(4)
数字设置1,2,3,4貌似运行都不影响forward的结果

**Comment by powerpwang** [comment]
检查一下编译时是否打开多线程。
TNN根目录下CMakeLists.txt，检查TNN_OPENMP_ENABLE是否设置为ON。如果没有，打开后重新编译，然后再尝试用SetCpuNumThreads设置线程数。
