### ISSUE TITLE
int 8 模型运行安卓demo ，手机上实测没有加速效果

### ISSUE THREAD

**Issue by GoldenSpark** [Tencent/TNN#1158]
骁龙865运行安卓demo，用量化工具量化模型，然后替换。int8的模型没有加速效果？

**Comment by shaundai-tencent** [comment]
量化模型的加速效果需要更具具体模型来看，有些模型可能量化之后由于插入了较多的reformat层，导致效果不明显。而且目前ARM在高端机中使用fp16的精度执行，性能也很好。

**Comment by gttiankai** [comment]
补充一点内容：在中高端机型上，int8 模型对比 float 模型 没有明显的优势。还有一个原因是 TNN 在中高端机型会使用 fp16 进行计算，而 int8 在运行时会转换成 int16 计算（保证精度），int8 的计算量比 fp16 还要大一点，所以在中高端机型上int8 模型没有性能优势。当时在低端机型上 int8 模型还是有性能优势的。

**Comment by RedFree** [comment]
@gttiankai 
我的模型量化之后在低端机上也没有加速效果，我的模型是跑在GPU中。如何查看量化之后的模型和量化之前的区别呢。

**Comment by shaundai-tencent** [comment]
目前TNN移动端的GPU不支持量化模型。请确认一下（检查返回值），是否正确执行。
