### ISSUE TITLE
TensorRT后端推理报错

### ISSUE THREAD

**Issue by StrugglingForBetter** [Tencent/TNN#1159]
**1. 环境（environment）**
 - Build OS and Version: Mac/Ubuntu/Centos/Windows
 - RunTime OS Version: Linux/Android/IOS
 - RunTime DEVICE: ARM/OPENCL/METAL

  **2. Github版本**
 - branch： [OPENCL] fix upsample kernel for OpenCL 1.1 (#1120)
 - commit(optional): 2e9e97cc4ef479af1e820f0c24c03ffa21926540

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
TensorRT后端推理， Predict()做推理报错

  **6. 运行日志（runtime log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **7. 截图（Screenshots）**
 ```txt
 将截图粘贴在这里
 Paste screenshorts here or pastebin
 ```
![image](https://user-images.githubusercontent.com/20771340/126097348-9468c5de-77ae-4394-88f6-a944608242d4.png)
![image](https://user-images.githubusercontent.com/20771340/126097398-3749ef41-d8ed-432a-a459-b158c4cd6908.png)

**Comment by Maosquerade** [comment]
这个用的是TNN自带的demo吗？环境分支等参数麻烦也提供一下

**Comment by shaundai-tencent** [comment]
环境请参考https://github.com/Tencent/TNN/blob/master/doc/en/user/compile_en.md#v-compilelinux-cuda
看上去是cudnn报错，可能是环境问题。

**Comment by shaundai-tencent** [comment]
这个问题解决了吗？
