### ISSUE TITLE
GetOutputMat中MatConvertParam参数不起作用

### ISSUE THREAD

**Issue by darrenyao87** [Tencent/TNN#117]
在FaceGrayTransfer示例中发现下面代码中output_cvt_param赋值不起作用

       // step 3. get output mat
        TNN_NS::MatConvertParam output_cvt_param;
//        output_cvt_param.scale = {255 / 2.0, 255 / 2.0, 255 / 2.0, 0.0};
//        output_cvt_param.bias  = {255 / 2.0, 255 / 2.0, 255 / 2.0, 0.0};
        status = instance_->GetOutputMat(output_mat, output_cvt_param);
        RETURN_ON_NEQ(status, TNN_NS::TNN_OK);

**Comment by PanJinquan** [comment]
TNN MatConvertParam参数scale和bias设置方法：https://panjinquan.blog.csdn.net/article/details/111259876
