### ISSUE TITLE
TNN量化模型如何设置前传模式？

### ISSUE THREAD

**Issue by lidehuihxjz** [Tencent/TNN#1174]
在NCNN里，可以用.opt.use_int8_inference来设置量化前传模式，TNN里该如何设定呢？
另外TNN支持读入NCNN量化后的模型吗？
谢谢！

**Comment by quinnrong94** [comment]
需要用TNN的量化工具对模型做量化，参考文档https://github.com/Tencent/TNN/blob/master/doc/en/user/quantization_en.mdTNN运行时读取到量化模型，会自动进行量化计算，不需要额外设置。

**Comment by quinnrong94** [comment]
需要用TNN的量化工具对模型进行量化，参考文档https://github.com/Tencent/TNN/blob/master/doc/en/user/quantization_en.md
TNN如果读入量化模型，会自动做量化前传。TNN目前不支持读入ncnn量化模型
