### ISSUE TITLE
模型太大，ARM开发板上加载时内存出错

### ISSUE THREAD

**Issue by zacks417** [Tencent/TNN#118]
开发板 IMX6ULL, 内存512MB
模型大小278MB
armlinux/src/main.cc基础上修改， 在板子上执行程序加载模型时内存出错，
![image](https://user-images.githubusercontent.com/40654162/85989283-e614d200-ba22-11ea-89ae-d831dafdff7b.png)
fileContent.assign(content, size);
        delete[] content;
        file.close();
        return fileContent;
将上述代码修改为如下
![image](https://user-images.githubusercontent.com/40654162/85989338-f6c54800-ba22-11ea-88e9-7887c9a0ce20.png)
// fileContent.assign(content, size);
        // delete[] content;
        file.close();
        // return fileContent;
        return content;
直接返回content，进入模型初始化后报错，层不支持。
使用的模型为vgg，所有层应该都是支持的

**Comment by seanxcwang** [comment]
可以试下新版本，内存优化过一次，或者可以将在转模型工具时指定保存成half格式
