### ISSUE TITLE
TNN ARM FP16 V7 编译支持

### ISSUE THREAD

**Issue by chenjiaoAngel** [Tencent/TNN#1184]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
请问TNN是怎么支持V7 FP16 编译和运行呢？ARMv8.2 指令集不是只能在ARMv8架构运行吗？
查看TNN CMakeList.txt 也木有找到V7 FP16 编译区别；但compute_arm82/asm_32.目录下有V7 FP16 指令支持。
CMake List 内容：
<img width="786" alt="image" src="https://user-images.githubusercontent.com/38650344/126993888-78d2fba0-7e59-4871-8083-41be34ed9059.png">

**Comment by seanxcwang** [comment]
fp16的指令是确实是armv8.2才有的，但是armv8下面可分为aarch64和aarch32，TNN把armv7和aarch32下面的fp16指令都编译到了一个32位的库里，在运行时去根据芯片型号决定是否运行fp16的代码

**Comment by chenjiaoAngel** [comment]
请问armv7 和 aarch32.的FP16 是怎么编译呢？V7下怎么识别FP16指令如vmla.f16、 vmax.f16等
armv8下面可分为aarch64和aarch32 --- 这个是指？v8指令集可以在64 和32 位平台运行？

**Comment by quinnrong94** [comment]
编译选项参考compute_arm82下的CMakeLists。运行时如果检测到是armv7平台，就不会执行fp16指令。

**Comment by chenjiaoAngel** [comment]
但是看这个CMakeList.txt 截图，如果是aarch64 v8 则用v8.2 FP16实现；否则，用V7实现，但是asm_32 下包含V7 的FP16指令，这个请问是怎么编译过呢？

**Comment by chenjiaoAngel** [comment]
另外，打开ARMV8.2 FP16开关，源码编译V7预测库，发现可以运行FP16精度，且性能优于FP32. 这个是不是说明TNN支持V7 ARMV8.2 指令集额？现在问题是：TNN怎么在V7下编译支持FP16指令集

**Comment by seanxcwang** [comment]
并不是armv7支持fp16的指令，是将armv7和aarch32里的fp16指令都编译到了一个32位的库里，如果芯片不支持fp16，还是走原来的armv7指令，所以只有在高端一点的机型上面才会有效果

**Comment by chenjiaoAngel** [comment]
en 高端机也可以跑V7 FP16 指令是吧？那这个是怎么编译支持的呢？

**Comment by nihui** [comment]
若不是业务需要死硬着32位库，直接用64位库不是更好。。

**Comment by chenjiaoAngel** [comment]
那如果芯片支持FP16，它会走V7 的FP16指令？

**Comment by gttiankai** [comment]
> 那如果芯片支持FP16，它会走V7 的FP16指令？

armv7a 并不支持 fp16 指令。如果芯片支持 fp16，走 aarch32 的fp16的指令。

**Comment by chenjiaoAngel** [comment]
好，收到。非常感谢
