### ISSUE TITLE
TNNSDKUtils::GetFallBackDeviceType(DeviceType dev)

### ISSUE THREAD

**Issue by StrugglingForBetter** [Tencent/TNN#1185]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

为什么 TNNSDKUtils::GetFallBackDeviceType(DeviceType dev)这个函数里面如果是CUDA就返回DEVICE_NAIVE? 感觉有点不合理。这样导致tnn的输出不在device上面？假如我的输入是在device上面，而且我希望输出也在device上面

**Additional context**
![277E Z_RKI3VG3U 5)GY@ 6](https://user-images.githubusercontent.com/20771340/127087983-270e8d85-2fef-4970-a5f5-ba17fb53d3fc.png)

**Comment by shaundai-tencent** [comment]
这里的DeviceType主要用于GetOutputMat中Mat的device type，因为这个sample场景下，需要拿到的是CPU的数据，所以就这样写了，仅供参考。如果实际使用中，整个pipeline需要直接使用Device侧内存，那这个Mat的DeviceType设置为对应device则效率更高。

**Comment by StrugglingForBetter** [comment]
那如果我希望输出的数据在device上面，这个地方需要我手动修改吗？我感觉用户一般不需要修改源码吧？

**Comment by shaundai-tencent** [comment]
这个只是示例代码，是对TNN的API的调用示例，仅供参考。实际使用时按照自己的场景做修改，或者自己封装TNN的API。
