### ISSUE TITLE
TFLite 转TNN模型出错，算子不支持

### ISSUE THREAD

**Issue by lhxy1991** [Tencent/TNN#1186]
将TFLite模型转化为TNN模型时报错,错误如下:
[File /home/xxx/TNN/tools/converter/source/tflite/tflite_converter.cc][Line 112] The TFLiteConverter do not support layer:ArgMax
E/tnn: tnn::Status TNN_CONVERTER::TFLite2Tnn::Convert2Tnn(tnn::NetStructure&, tnn::NetResource&) [File /home/xxxx/TNN/tools/converter/source/tflite/tflite_converter.cc][Line 114] The unsupported operator type is:ARG_MAX
请问下这个如何解决呢?

**Comment by gttiankai** [comment]
1. 请切换到分支： https://github.com/Tencent/TNN/tree/hotfix_issue_1186 尝试一下。
2. 我看了下模型：红色框中的 argmax 的参数建议调整成：keep_dims = true,也就说不要将 channel 维度去掉，要不然模型转换对齐的时候，会报错。
<img width="664" alt="image" src="https://user-images.githubusercontent.com/5379313/127298935-79d8137c-006b-4fcb-b2fd-1fb6de9bf780.png">

**Comment by lhxy1991** [comment]
可用了

**Comment by lhxy1991** [comment]
不知道为什么，将模型移植到android设备的时候，报错：Error : arm layer acc got unsupported data type 3。 请问下这是输入类型出错吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/TNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 下午5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/TNN] TFLite 转TNN模型出错，算子不支持 (#1186)





  
请切换到分支： https://github.com/Tencent/TNN/tree/hotfix_issue_1186 尝试一下。
 
我看了下模型：红色框中的 argmax 的参数建议调整成：keep_dims = true,也就说不要将 channel 维度去掉，要不然模型转换对齐的时候，会报错。

**Comment by lhxy1991** [comment]
> 1. 请切换到分支： https://github.com/Tencent/TNN/tree/hotfix_issue_1186 尝试一下。
> 2. 我看了下模型：红色框中的 argmax 的参数建议调整成：keep_dims = true,也就说不要将 channel 维度去掉，要不然模型转换对齐的时候，会报错。
> 
> <img alt="image" width="664" src="https://user-images.githubusercontent.com/5379313/127298935-79d8137c-006b-4fcb-b2fd-1fb6de9bf780.png">
> 
> 3. 如果对齐了，请回复下，我好PR 到 master 分支。

@gttiankai 按照修改，成功转换为模型，也能成功加载，但是执行forward() 的时候，报错：
Error : arm layer acc got unsupported data type 3
 code: 0x3000 msg: Error: arm layer acc got unsupported data type.
请问下这是什么情况？我查看您增加的算子里，只有ARG 的data type=3 符合这个错误，请问这个怎么修改？

**Comment by lhxy1991** [comment]
[lane.zip](https://github.com/Tencent/TNN/files/6905471/lane.zip)

**Comment by lhxy1991** [comment]
根据调试应该是Cast算子未起作用。 Netron查看虽然有Cast算子，但是加载算子的时候cast算子没了，导致ArgMax直接就到binary_output37 ，中间少了int到float的转换。烦请帮忙看下？

**Comment by gttiankai** [comment]
已修改，你再试一下。

**Comment by lhxy1991** [comment]
hi,新修改的有如下错误：
default_network.cc][Line 319] Error Init layer binary_output (err: 4096 or 0x1000)






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/TNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月30日(星期五) 下午5:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/TNN] TFLite 转TNN模型出错，算子不支持 (#1186)





 
已修改，你再试一下。

**Comment by lhxy1991** [comment]
> 已修改，你再试一下。

@gttiankai
