### ISSUE TITLE
在widows下编译opencl报这样的错误

### ISSUE THREAD

**Issue by gray2bgr** [Tencent/TNN#1193]
在widows下编译opencl报这样的错误，请问是什么原因，怎么解决。
.\build_win_x86_opencl.bat x64
.\build_win_x86_opencl.bat x86
用以上两个指令都会出现这个错误。
用的x86 native tools command prompt for vs 2017 的 cmd
脚本里的vcvars32.bat路劲修改了

 [662/664] Building CXX object source\tnn\device\opencl\CMakeFiles\TNNOpenCL.dir\cl\opencl_program.cc.obj
FAILED: source/tnn/device/opencl/CMakeFiles/TNNOpenCL.dir/cl/opencl_program.cc.obj
C:\PROGRA~2\MICROS~2\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo /TP -DBUILDING_DLL -DTNN_USE_OPENCL_WRAPPER -IF:\inference\TNN\include -IF:\inference\TNN\source -IF:\inference\TNN\source\tnn\device\opencl\..\..\..\..\third_party\opencl\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /wd4003 /wd4819 /wd4244 /wd4018 /utf-8 -DTNN_METAL_FULL_PRECISION=1 /openmp /MD /O2 /Ob2 /DNDEBUG /showIncludes /Fosource\tnn\device\opencl\CMakeFiles\TNNOpenCL.dir\cl\opencl_program.cc.obj /Fdsource\tnn\device\opencl\CMakeFiles\TNNOpenCL.dir\ /FS -c F:\inference\TNN\source\tnn\device\opencl\cl\opencl_program.cc
F:\inference\TNN\source\tnn\device\opencl\cl\opencl_program.cc(248): fatal error C1060: 编译器的堆空间不足
ninja: build stopped: subcommand failed.
 ```

**Comment by yinghuang** [comment]
碰到了一样的问题，编译32位opencl报错 fatal error C1060: 编译器的堆空间不足，请问你是怎么解决的
