### ISSUE TITLE
请问TNN opencl是不支持x86么

### ISSUE THREAD

**Issue by gray2bgr** [Tencent/TNN#1194]
你好，
关于opencl的编译
编译x86过程发现占用内存会超过4G导致编译失败，改用x64就可以正常编译。
请问opencl在windows上是仅支持32位不支持64位么

**Comment by shaundai-tencent** [comment]
opencl在windows上面32位和64位都支持的。

**Comment by gray2bgr** [comment]
> opencl在windows上面32位和64位都支持的。

我又尝试了确实是可以编译成功，生成的库确认是x86的，谢谢

**Comment by yinghuang** [comment]
> > opencl在windows上面32位和64位都支持的。
> 
> 我又尝试了确实是可以编译成功，生成的库确认是x86的，谢谢

碰到了一样的问题，fatal error C1060: 编译器的堆空间不足，请问后来是怎么解决的

**Comment by yinghuang** [comment]
使用VS2017，碰到堆空间不足问题；使用VS2019，可以通过
