### ISSUE TITLE
请问TNN的benchmark怎么使用openvino

### ISSUE THREAD

**Issue by gray2bgr** [Tencent/TNN#1206]
我windows使用的build_msvc.bat编译64成功
运行命令如下
.\TNNTest.exe -wc 10 -ic 10 -mp ..\openvino_models\alexnet.xml -mt OPENVINO -dt X86
报错如下
E/tnn: tnn::TNN::Init [File F:\inference\TNN\source\tnn\core\tnn.cc][Line 29] Error: not support mode type: 4096. If TNN is a static library, link it with option -Wl,--whole-archive tnn -Wl,--no-whole-archive on android or add -force_load on iOS
E/tnn: tnn::test::CheckResult [File F:\inference\TNN\test\test.cc][Line 363] init tnn failed: code: 0x2000 msg: unsupported mode type, If TNN is a static library, link it with option -Wl,--whole-archive tnn -Wl,--no-whole-archive on android or add -force_load on iOS

**Comment by seanxcwang** [comment]
TNN使用openvino的方式，并不直接读入openvino的模型，而是用tnn的模型去构建ngraph，再利用openvino去加速，所以命令应该是：./TNNTest -dt X86 -nt OPENVINO -mp xxx.tnnproto -wc 10 -ic 10
