### ISSUE TITLE
tnn支持以外部的cl_mem来创建Mat吗

### ISSUE THREAD

**Issue by likefxz2009** [Tencent/TNN#1209]
就是想直接以cl_mem来作为推理的输入和输出，而不是cpu内存。

**Comment by shaundai-tencent** [comment]
可以使用cl_mem作为输入和输出，作为输入的时候，声明Mat时的device_type设置为DEVICE_OPENCL，然后传入内存地址就行。输出的话，device_type也设置为DEVICE_OPENCL，可以得到cl_mem的内存。但是注意的是，输入和输出mat仅支持N8UC4的格式。

**Comment by likefxz2009** [comment]
@shaundai-tencent 感谢回复
还有一些问题：
- 1、tnn的opencl context是在内部创建的，我在外部创建一个的话，会不会冲突。
- 2、我看blob是可以支持很多种format的，是可以直接通过output的BlobMap来直接获取输出的cl_mem内存，即不通过getOuputMat接口，因为mat仅支持N8UC4的话，比较有局限性。
- 3、如果2中的行为是可行的话，input的BlobMap可不可以通过setHandle来把我的cl_mem设置进去（这个倒不是很关键，因为输入一般来说是图片，N8UC4还是能处理的）

**Comment by shaundai-tencent** [comment]
问题1：
确实需要同一个context才能进行内存的操作，TNN可以获取到内部的context，通过Instance->GetCommandQueue()接口拿到OpenCL的cl_command_queue，可以通过clGetCommandQueueInfo 在获取对应的context；
问题2：
是可以通过接口Instance->GetAllOutputBlobs()获取，如果直接操作这个cl_mem，需要对内部的存储格式比较了解，目前内部存储是使用的Image2D，排布方式（NH，C/4W）.
问题3:
可以的，同样是格式需要统一。

**Comment by likefxz2009** [comment]
@shaundai-tencent 感谢回复，我先按照你的说法试试看

**Comment by likefxz2009** [comment]
@shaundai-tencent 
我尝试了一下，出现了一些困惑，正如你所说，仅支持N8UC4+DEVICE_OPENCL的方式来创建Mat，我先试了用如下方式创建cl_Image:
```
    int cal_num = 4 * 128 * 128;
    uint8_t *clptr = new uint8_t[cal_num];
    for (int i = 0; i < cal_num; i++)
    {
        clptr[i] = 188;
    }
    tnn::MatConvertParam param;
    param.scale = {2.0 / 255, 2.0 / 255, 2.0 / 255, 2.0 / 255};
    param.bias = {-1.0, -1.0, -1.0, -1.0};

    cl_image_format image_format;
    image_format.image_channel_data_type = CL_UNSIGNED_INT8;
    image_format.image_channel_order = CL_RGBA;
    cl_mem clIn = clCreateImage2D(context, CL_MEM_READ_WRITE, &image_format, 128, 128, 0, nullptr, &err);
    if (err != CL_SUCCESS)
    {
        std::cout << "clCreateImage2D failed code = " << err << std::endl;
        return -1;
    }
    const size_t origin[3] = {0,0,0};
 	const size_t region[3] = {128,128,1};
    err = clEnqueueWriteImage(queue, clIn, true, origin,region,0,0, clptr,0,nullptr,nullptr);
    tnn::Mat in_cl(tnn::DEVICE_OPENCL, tnn::N8UC4, {1, 4, 128, 128}, &clIn);
    instance_->SetInputMat(std::make_shared<tnn::Mat>(in_cl), param);
```
然而发现这样用是不正确的，然后我发现ConvertFromMat用到的opencl kernel里是用read_imagef来读mat(cl::Image)的，所以我创建cl_image的时候cl_image_format该如何设置？或者我的代码里是不是存在其他的问题，能否提供一个示例代码，感谢你的回复🙏

**Comment by likefxz2009** [comment]
试了一下，把cl_image_format的channel_data_type改成CL_UNORM_INT8就可以了，这样会被read_imagef读取的时候自动归一化到[0,1]，自己根据这个把MatConvertParam相应调整一下，使得从[0,1]量化到我想要的输入即可，比如我想要[-1,1]，这里乘以2再减去1就行了。
```
    tnn::MatConvertParam param;
    param.scale = {2.0, 2.0, 2.0, 2.0};
    param.bias = {-1.0, -1.0, -1.0, -1.0};
    cl_image_format image_format;
    image_format.image_channel_data_type = CL_UNORM_INT8;
    image_format.image_channel_order = CL_RGBA;
```

**Comment by shaundai-tencent** [comment]
TNN内部的cl_mem的data_type是CL_FLOAT或者CL_HALF_FLOAT或者CL_SIGNED_INT32，channel_order是CL_RGBA。但是这个和Mat传入的格式关系不大，因为ConvertFromMat这个本身是做格式转换的。read_imagef只是表示读出来的数据是FLOAT的，至于这个src的格式是什么没有关系，这个接口内部会做格式转换。你用CL_UNSIGNED_INT8来处理不对，可以调试一下，看看kernel里面read_imagef读出来的数据是不是正确。

**Comment by hcv1027** [comment]
@shaundai-tencent

**Comment by hcv1027** [comment]
@shaundai-tencent 
我也有同样的需求，但是目前我无法成功把我配置出来的`cl_mem image`塞进`TNN::Mat`里
下面是我的作法
```c++
  cl_int err_num = CL_SUCCESS;
  // 我在device端配置出一个存image的cl_mem
  cl_mem_flags flags_rgba = CL_MEM_READ_WRITE | CL_MEM_ALLOC_HOST_PTR;
  cl_image_desc desc_rgba = {CL_MEM_OBJECT_IMAGE2D, width, height, 0, 0, 0, 0, 0, 0, 0};
  cl_image_format format_rgba;
  format_rgba.image_channel_order = CL_RGBA;
  format_rgba.image_channel_data_type = CL_UNSIGNED_INT8;
  cl_mem rgba_img = clCreateImage(context, flags_rgba, &format_rgba, &desc_rgba, NULL, &err_num);
  if (err_num != CL_SUCCESS) {
      std::cerr << "Failed to create device memory, err_num: " << err_num << std::endl;
  }
  // 这边会做填内容到rgba_img的动作
  // Do something to write to rgba_img

  // 这边这段纯粹是验证rgba_img的影像是正常的
  cv::Mat cv_rgba_img = cv::Mat(imH, imW, CV_8UC4);
  cv::Mat cv_img_debug = cv::Mat(imH, imW, CV_8UC4);
  size_t origin[3];
  origin[0] = 0;
  origin[1] = 0;
  origin[2] = 0;
  // This is the region to read, i.e. the whole image
  size_t region[3];
  region[0] = imW;
  region[1] = imH;
  region[2] = 1;
  err_num = clEnqueueReadImage(
      *cmd_queue, rgba_img, CL_TRUE, origin, region, 0, 0, cv_rgba_img.data, 0, NULL, 0);
  cv::cvtColor(cv_rgba_img, cv_img_debug, cv::COLOR_RGBA2BGRA);
  cv::imwrite("../debug_img/" + std::to_string(debug_name++) + ".png", cv_img_debug);

  // 把准备好的rgba_img放进TNN_NS::Mat里
  TNN_NS::DimsVector input_dims = {1, 4, (int)height, (int)width};
  auto input_mat = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_OPENCL, TNN_NS::N8UC4, input_dims, &rgba_img);
  // Resize
  TNN_NS::DimsVector net_dims = {1, 4, (int)net_height, (int)net_width};
  auto resized_mat = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_OPENCL, TNN_NS::N8UC4, net_dims);
  TNN_NS::MatUtils::Resize(*(input_mat.get()), *(resized_mat.get()), param, command_queue_);

  // 给模型做推导
  TNN_NS::MatConvertParam IN_CVT_PARAM;
  IN_CVT_PARAM.scale = {1.0f, 1.0f, 1.0f, 1.0f};
  IN_CVT_PARAM.bias = {-123.0f, -117.0f, -104.0f, 0.0f};
  instance_->SetInputMat(resized_mat, IN_CVT_PARAM);
  instance_->Forward();
```

模型推导后的输出结果并不正确(什么东西都没找到)
想问一下，像我这样把`cl_mem`放进`TNN_NS:Mat`的方式是正确的吗？
我要怎么验证`TNN_NS:Mat`的内容是正确的？
有方法可是像`cv::Mat`那样输出图档来验证内容是否正常吗？

**Comment by shaundai-tencent** [comment]
请检查：
1、传入Mat的data使用cl::Image的数据类型
2、创建cl::Image的Context需要和TNN一致；
此外，验证传入的cl::Image是否正确，只能将数据拷贝回CPU测来检查。

**Comment by hcv1027** [comment]
Hi @shaundai-tencent ，感谢你的回复
我想要确认一下
1、传入Mat的data使用cl::Image的数据类型
```c++
auto input_mat = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_OPENCL,
            TNN_NS::N8UC4, input_dims, &rgba_img);
```
所以像这个例子里传入的`rgba_img`的型态，必须是OpenCL c++ wrapper的`cl::Image`，而不是c的`cl_mem`吗？因为我看原发文者的例子传进去的应该是`cl_mem`而不是`cl::Image`。

2、创建cl::Image的Context需要和TNN一致；
```c++
instance_->GetCommandQueue(&command_queue_);
cl_command_queue* cmd_queue = reinterpret_cast<cl_command_queue*> (command_queue_);
size_t returned_size = 0;
clGetCommandQueueInfo(*cmd_queue, CL_QUEUE_CONTEXT, sizeof(cl_context), &context, &returned_size);
std::cout << "get " << returned_size / sizeof(cl_context) << " context" << std::endl;
if (returned_size == 0) {
    std::cout << "Fail to get cl_context used in TNN" << std::endl;
    return;
}
```
我是用上面的方式取得`cl_context`，想确认一下这是否为TNN内部的`cl_context`？

**Comment by likefxz2009** [comment]
@hcv1027 
我是直接传入cl_mem，你看代码就会发现cl::Image是对cl_mem的封装，但是这个地方需要修改一下
```
format_rgba.image_channel_data_type = CL_UNSIGNED_INT8;
-> format_rgba.image_channel_data_type = CL_UNORM_INT8;
```
因为TNN里面是用read_imagef来读你的输入cl_mem，如果是CL_UNSIGNED_INT8就会全被读成0（你可以打开tnn的dump来把中间层的输入输出都保存下来，看一下第一层的输入应该全是0），如果用CL_UNORM_INT8就会自动把你的 0 - 255的定点数据归一化到 0 - 1.0，当然你这个后续的这个地方也得相应改一下：
```
TNN_NS::MatConvertParam IN_CVT_PARAM;
IN_CVT_PARAM.scale = {1.0f, 1.0f, 1.0f, 1.0f};
IN_CVT_PARAM.bias = {-123.0f, -117.0f, -104.0f, 0.0f};
```
因为你的数据已经被归一化到 0-1.0了，所以这里可以改成
```
TNN_NS::MatConvertParam IN_CVT_PARAM;
IN_CVT_PARAM.scale = {255.0f,255.0f,255.0f,255.0f};
IN_CVT_PARAM.bias = {-123.0f, -117.0f, -104.0f, 0.0f};
```
然后再用上述方法保存一下第一层的输入，看下是否跟你的预期一致。
建议模型结果不正确的时候使用tnn的dump功能，从数据出发，仔细看一下是哪一层的问题。

**Comment by shaundai-tencent** [comment]
> Hi @shaundai-tencent ，感谢你的回复
> 我想要确认一下
> 1、传入Mat的data使用cl::Image的数据类型
> 
> ```c++
> auto input_mat = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_OPENCL,
>             TNN_NS::N8UC4, input_dims, &rgba_img);
> ```
> 
> 所以像这个例子里传入的`rgba_img`的型态，必须是OpenCL c++ wrapper的`cl::Image`，而不是c的`cl_mem`吗？因为我看原发文者的例子传进去的应该是`cl_mem`而不是`cl::Image`。
> 
> 2、创建cl::Image的Context需要和TNN一致；
> 
> ```c++
> instance_->GetCommandQueue(&command_queue_);
> cl_command_queue* cmd_queue = reinterpret_cast<cl_command_queue*> (command_queue_);
> size_t returned_size = 0;
> clGetCommandQueueInfo(*cmd_queue, CL_QUEUE_CONTEXT, sizeof(cl_context), &context, &returned_size);
> std::cout << "get " << returned_size / sizeof(cl_context) << " context" << std::endl;
> if (returned_size == 0) {
>     std::cout << "Fail to get cl_context used in TNN" << std::endl;
>     return;
> }
> ```
> 
> 我是用上面的方式取得`cl_context`，想确认一下这是否为TNN内部的`cl_context`？

cl::Image和cl_mem应该可以相互转换，但是建议用cl::Image.
此外，你获取context的方式没有问题。可以尝试 @likefxz2009 的建议。

**Comment by hcv1027** [comment]
@likefxz2009 ，謝謝你的分享
我目前还是尝试失败，想请问一下，你说开启TNN的dump是如何开启？

**Comment by likefxz2009** [comment]
> @likefxz2009 ，謝謝你的分享
> 我目前还是尝试失败，想请问一下，你说开启TNN的dump是如何开启？

在blob_dump_utils.h里把下面这两个修改成1
```
#define DUMP_INPUT_BLOB 0
#define DUMP_OUTPUT_BLOB 0
```
然后把blob_dump_utils.cc根据需要修改g_tnn_dump_directory
重新编译tnn，再运行就会得到中间层的结果。
@hcv1027

**Comment by likefxz2009** [comment]
另外我觉得你可以先尝试一下把resize放在cpu上做好了再传到opencl，看看有没有可能是这一步导致的，我之前的做法跟你唯一的区别就是我没有在opencl里做resize
@hcv1027

**Comment by hcv1027** [comment]
Hi @likefxz2009 
非常謝謝你的建議，問題已經解決，有成功了
我們之前就是用OpenCV在做resize，目前是想要加速所以正在嘗試改用openCL在GPU做resize
所以才會有這個從外部cl_mem設定進去給TNN的需求

**Comment by shaundai-tencent** [comment]
> Hi @likefxz2009
> 非常謝謝你的建議，問題已經解決，有成功了
> 我們之前就是用OpenCV在做resize，目前是想要加速所以正在嘗試改用openCL在GPU做resize
> 所以才會有這個從外部cl_mem設定進去給TNN的需求

能分享一下问题的原因吗？可以给大家参考一下。

**Comment by hcv1027** [comment]
Hi @shaundai-tencent 
基本上就是根据 @likefxz2009 在[这个回复](https://github.com/Tencent/TNN/issues/1209#issuecomment-917320675)里的建议修改后就成功了
建议你们可以把这部份写进document里
因为这会连用来做前处理的openCL kernel程式码也要做对应修改
例如我的kernel就做了下面这样的修改：

```c
// 原本的
// uchar b = src_buffer[buffer_idx];
// uchar g = src_buffer[buffer_idx + 1];
// uchar r = src_buffer[buffer_idx + 2];
// write_imageui(dst_image, output_coordinate, (uint4)(r, g, b, 255));

// 修改后的
float b = src_buffer[buffer_idx] / 255.0;
float g = src_buffer[buffer_idx + 1] / 255.0;
float r = src_buffer[buffer_idx + 2] / 255.0;
write_imagef(dst_image, output_coordinate, (float4)(r, g, b, 1.0));
```

但是我现在有遇到另外一个问题，
就是我们的model目前inference time反而变长了
我们原先的作法如下：
```c++
// input_mat是用openCV做完resize前处理的TNN_NS::Mat
auto input_mat = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_NAIVE, TNN_NS::N8UC4, input_dims_, reinterpret_cast<void *>(netim.data));
// 接着拷贝到gpu memory
auto input_mat_ocl_ = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_OPENCL, TNN_NS::N8UC4, input_dims_);
TNN_NS::MatUtils::Copy(*(input_mat.get()), *(input_mat_ocl_.get()), command_queue_);
std::chrono::steady_clock::time_point t4 = std::chrono::steady_clock::now();

instance_->SetInputMat(input_mat_ocl_, IN_CVT_PARAM_);
std::chrono::steady_clock::time_point t5 = std::chrono::steady_clock::now();

// 做inference
instance_->Forward();
std::chrono::steady_clock::time_point t6 = std::chrono::steady_clock::now();
```

目前改用openCL做前处理
```c++
// resized_mat就像前面所描述的，事先配置好的cl_mem透过openCL kernel做前处理，再创建TNN_NS::Mat
auto resized_mat = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_OPENCL,
            TNN_NS::N8UC4, net_dims, &resized_img);
    
std::chrono::steady_clock::time_point t4 = std::chrono::steady_clock::now();
// Step 4: Parsing to TNN
instance_->SetInputMat(resized_mat, IN_CVT_PARAM_);

std::chrono::steady_clock::time_point t5 = std::chrono::steady_clock::now();
instance_->Forward();
std::chrono::steady_clock::time_point t6 = std::chrono::steady_clock::now();
```

修改后，虽然`instance_->Forward();`的结果是正确的，但是时间却从215 ms增加到260 ms
目前完全没有头绪，想问一下有哪些可能的原因？

**Comment by shaundai-tencent** [comment]
是Forward的时间从215ms增加到260ms还是整个pipeline的时间?
此外，原先的做法，没有必要将input_mat拷贝到input_mat_ocl，可以直接将input_mat送入SetInputMat接口。

**Comment by hcv1027** [comment]
> 是Forward的时间从215ms增加到260ms还是整个pipeline的时间?
单纯`Forward`的时间增加了，完全想不明白

> 此外，原先的做法，没有必要将input_mat拷贝到input_mat_ocl，可以直接将input_mat送入SetInputMat接口。
原本的`input_mat`是`TNN_NS::DEVICE_NAIVE`，这样会用到gpu去做`Forward`吗？

额外问个问题，`TNN_NS::DEVICE_NAIVE`和`TNN_NS::DEVICE_ARM`差别在哪？

**Comment by shaundai-tencent** [comment]
> 是Forward的时间增加了，我上面寫的t6-t5這段時間，完全想不明白理由

因为这里的SetInputMat接口是异步接口，做增加的耗时可能不是Forward增加的，可能是SetInputMat中的ConvertFromMat增加的。

> 额外问个问题，TNN_NS::DEVICE_NAIVE和TNN_NS::DEVICE_ARM差别在哪？

对于OpenCL平台没有区别，都是属于CPU的内存。

> 原本的input_mat是TNN_NS::DEVICE_NAIVE，这样会用到gpu去做Forward吗？

input_mat的device_type影响的只是在做预处理的时候，是否需要将cpu内存拷贝到GPU，不影响Forward执行的平台，forward执行的平台是instance初始化时指定的device_type决定的。所以，此处如果是设置为DEVICE_NAIVE或DEVICE_ARM，那SetInputMat的时候内部会做内存的拷贝。

看你的应用场景，主要是想加速Resize，TNN内部提供了Resize接口，在ARM CPU端有过优化，可以尝试一下。CPU的内存处理完了之后直接调用SetInputMat，避免一些不必要的内存拷贝。

**Comment by hcv1027** [comment]
Hi @shaundai-tencent 

> > 是Forward的时间增加了，我上面寫的t6-t5這段時間，完全想不明白理由
> 
> 因为这里的SetInputMat接口是异步接口，做增加的耗时可能不是Forward增加的，可能是SetInputMat中的ConvertFromMat增加的。

```c++
std::chrono::steady_clock::time_point t4 = std::chrono::steady_clock::now();
// Step 4: Parsing to TNN
instance_->SetInputMat(resized_mat, IN_CVT_PARAM_);

std::chrono::steady_clock::time_point t5 = std::chrono::steady_clock::now();
instance_->Forward();
std::chrono::steady_clock::time_point t6 = std::chrono::steady_clock::now();
```

1. 所以你的意思是说，我夹`t5-t4`来看`SetInputMat`所花掉的时间是没有意义的，这段时间有可能会被隐含到`t6-t5`里去吗？
2. 如果是因为`ConvertFromMat`而增加，是指下面这一段设定scale和bias吗？
```c++
TNN_NS::MatConvertParam IN_CVT_PARAM;
IN_CVT_PARAM.scale = {255.0f, 255.0f, 255.0f, 255.0f};
IN_CVT_PARAM.bias = {-123.0f, -117.0f, -104.0f, 0.0f};
instance_->SetInputMat(resized_mat, IN_CVT_PARAM);
```

> input_mat的device_type影响的只是在做预处理的时候，是否需要将cpu内存拷贝到GPU，不影响Forward执行的平台，forward执行的平台是instance初始化时指定的device_type决定的。所以，此处如果是设置为DEVICE_NAIVE或DEVICE_ARM，那SetInputMat的时候内部会做内存的拷贝。
> 

那是不是像我们修改后的例子，直接用外部`cl_mem`来创建Mat就会省掉一次memory copy的动作？
```c++
cl_mem resized_img;
// Initialize resized_img
auto resized_mat = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_OPENCL,
            TNN_NS::N8UC4, net_dims, &resized_img);
instance_->SetInputMat(resized_mat, IN_CVT_PARAM_);
```

**Comment by shaundai-tencent** [comment]
> 所以你的意思是说，我夹t5-t4来看SetInputMat所花掉的时间是没有意义的，这段时间有可能会被隐含到t6-t5里去吗？

是的，t5-t4会只有函数调用时间，实际执行时间有部分在t6-t5中。

> 如果是因为ConvertFromMat而增加，是指下面这一段设定scale和bias吗？

原来代码的IN_CVT_PARAM是什么样子的？如果是默认参数，那就不会做计算，在执行kernel的时候回少了计算的步骤。参考kernel代码：
```
__kernel void ConvertFromN32FC4Image(
     GLOBAL_SIZE_2_DIMS __read_only image2d_t input,
     __write_only image2d_t output, __private const int channels, __private const float4 scale,
     __private const float4 bias) {
     int image_width_idx  = get_global_id(0);
     int image_height_idx = get_global_id(1);

     DEAL_NON_UNIFORM_DIM2(image_width_idx, image_height_idx);

     int2 coord    = (int2)(image_width_idx, image_height_idx);
     float4 values = read_imagef(input, SAMPLER, coord);

     if (channels == 3) {
         values.w = 0;
     }

 #ifdef SWAP_RB
     float temp = values.x;
     values.x   = values.z;
     values.z   = temp;
 #endif

 #ifdef ENABLE_SCALE_BIAS
     values = values * scale + bias;
 #endif

     write_imagef(output, coord, values);
 }
```
如果不是默认值，则宏ENABLE_SCALE_BIAS会打开，会多执行一步。此外，之前的代码走的kernel是ConvertFromN8UC4，而后面的代码走的kernel是ConvertFromN32FC4Image，两个实现不一样，可能性能有差异。
如果想确定SetInputMat的耗时，可以改动一下TNN内部的代码，将SetInputMat中的接口改成同步接口（将ConvertFromMatAsync改为ConvertFromMat），再测一下时间。

> 那是不是像我们修改后的例子，直接用外部cl_mem来创建Mat就会省掉一次memory copy的动作？

是有些区别的，就是上面所述的kernel选择的差异，ConvertFromN8UC4是将cpu的数据拷贝进buffer，然后读buffer数据，写入image；而ConvertFromN32FC4Image，是读的image数据，然后写入image。
