### ISSUE TITLE
在windows上有多个显卡设备怎么切换

### ISSUE THREAD

**Issue by gray2bgr** [Tencent/TNN#1211]
例如我的电脑上有intel的集显和1050的显卡，我想跑opencl，怎么确定代码跑到GPU上，用的是哪个设备再跑

**Comment by shaundai-tencent** [comment]
TNN内部的逻辑是优先使用NV的GPU，然后的Intel的GPU。可以参考opencl_runtime.cc中SearchGpuDevice()这个函数的逻辑。
