### ISSUE TITLE
c++ api infer lstm tnnmodel  failed 

### ISSUE THREAD

**Issue by liziru** [Tencent/TNN#1227]
**1. 环境（environment）**
 - Build OS and Version: Linux ubuntu 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - RunTime OS Version: Linux ubuntu 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - RunTime DEVICE: x86_64

  **2. Github版本**
 - branch：master
 - commit(optional): 

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

  **4. 编译日志(build log)**
![image](https://user-images.githubusercontent.com/34911790/128987961-c20435d8-f9d5-4d1d-b1d7-5069394e8c4f.png)

  **5. 详细描述bug 情况 (Describe the bug)**
我利用tf.keras训练两层lstm+一层全连接模型，并利用keras2onnx转为onnx模型，然后成功的将onnx模型转换为tnn model。基于TNNObjectDetector.cc， 我做了修改，来推理lstm tnn model ， 但是失败了，失败日志如下。

  **6. 运行日志（runtime log）**
![image](https://user-images.githubusercontent.com/34911790/128988569-d26e9d7a-e13b-4d1d-95ef-2422c7f2c632.png)

![image](https://user-images.githubusercontent.com/34911790/128988458-c51ab4bc-6758-4cdc-9b34-4ee0de903f8e.png)
gdb log: 
![image](https://user-images.githubusercontent.com/34911790/128989767-5ecdc510-45ae-428d-b004-36795eafbe06.png)

  **7. 截图（Screenshots）**

推理代码：
`#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include "../flags.h"
#include "macro.h"
// #include "object_detector_ssd.h"
#include "tnn_sdk_sample.h"
#include "utils/utils.h"

#define STB_IMAGE_IMPLEMENTATION
#include "../../../../third_party/stb/stb_image.h"
#define STB_IMAGE_RESIZE_IMPLEMENTATION
#include "../../../../third_party/stb/stb_image_resize.h"
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "../../../../third_party/stb/stb_image_write.h"

using namespace TNN_NS;

int main(int argc, char **argv) {
    if (!ParseAndCheckCommandLine(argc, argv)) {
        ShowUsage(argv[0]);
        return -1;
    }

    auto proto_content = fdLoadFile(FLAGS_p.c_str());
    auto model_content = fdLoadFile(FLAGS_m.c_str());

    auto option = std::make_shared<TNN_NS::TNNSDKOption>();
    {
        option->proto_content = proto_content;
        option->model_content = model_content;
        option->compute_units = TNN_NS::TNNComputeUnitsCPU;
// if enable openvino/tensorrt, set option compute_units to openvino/tensorrt
#ifdef _CUDA_
        option->compute_units = TNN_NS::TNNComputeUnitsTensorRT;
#elif _OPENVINO_
        option->compute_units = TNN_NS::TNNComputeUnitsOpenvino;
#endif
    }

    char img_buff[256];
    char *input_imgfn = img_buff;
    strncpy(input_imgfn, FLAGS_i.c_str(), 256);

    int image_width, image_height, image_channel;
    unsigned char *data = new unsigned char[257];
    // unsigned char *data = stbi_load(input_imgfn, &image_width, &image_height, &image_channel, 3);
    image_width           = 257;
    image_height          = 1;
    image_channel         = 1;
    std::vector<int> nchw = {1, 1, image_height, image_width};

    if (!data) {
        fprintf(stderr, "Object-Detector open file %s failed.\n", input_imgfn);
    }

    auto predictor = std::make_shared<TNNSDKSample>();
    auto status    = predictor->Init(option);
    if (status != TNN_NS::TNN_OK) {
        std::cout << "Predictor Initing failed, please check the option parameters" << std::endl;
    }

    std::shared_ptr<TNN_NS::TNNSDKOutput> sdk_output = nullptr;

    auto image_mat  = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_NAIVE, TNN_NS::N8UC3, nchw, data);
    auto resize_mat = predictor->ProcessSDKInputMat(image_mat, "data_input");
    CHECK_TNN_STATUS(predictor->Predict(std::make_shared<TNN_NS::TNNSDKInput>(resize_mat), sdk_output));

    CHECK_TNN_STATUS(predictor->ProcessSDKOutput(sdk_output));
    // std::vector<TNN_NS::ObjectInfo> object_list;
    // if (sdk_output && dynamic_cast<TNN_NS::ObjectDetectorSSDOutput *>(sdk_output.get())) {
    //     auto obj_output = dynamic_cast<TNN_NS::ObjectDetectorSSDOutput *>(sdk_output.get());
    //     object_list     = obj_output->object_list;
    // }

    int ow = sdk_output.get()->GetMat()->GetWidth();
    int oh = sdk_output.get()->GetMat()->GetHeight();
    int oc = sdk_output.get()->GetMat()->GetChannel();
    int ob = sdk_output.get()->GetMat()->GetBatch();
    printf("INFO: %d, %d, %d, %d\n", ob, oc, ow, oh);

    delete[] data;

    return 0;
}`

期待任何回复，感谢。

**Comment by powerpwang** [comment]
请问可以麻烦提供一下模型（onnx + tnnproto + tnnmodel）吗？我尝试复现一下。
从报错信息来看，可能和Permute层的参数有关系。

**Comment by liziru** [comment]
> 请问可以麻烦提供一下模型（onnx + tnnproto + tnnmodel）吗？我尝试复现一下。
> 从报错信息来看，可能和Permute层的参数有关系。

好的，这是三个模型下载链接：链接：https://pan.baidu.com/s/1d19VyIjU0YXsFmGrXrdiQQ 
提取码：l787 

期待您的答复，感谢。

**Comment by powerpwang** [comment]
链接好像无效，麻烦重新提供一下

**Comment by liziru** [comment]
> 链接好像无效，麻烦重新提供一下

链接：https://pan.baidu.com/s/1FRatNuyNmR80cArun_FPWg 
提取码：18f8 

这是百度云盘链接。 这个可以吗

**Comment by powerpwang** [comment]
这个也不行...

**Comment by liziru** [comment]
百度云盘下载链接：
链接：https://pan.baidu.com/s/1YE6uqgJeooEwovFv8cvr6A 
提取码：asd1 

腾讯微云下载链接：
https://share.weiyun.com/YeFF7D4A 

看看哪个能用。

> 这个也不行...

**Comment by 1627180283** [comment]
> 百度云盘下载链接：
> 链接：https://pan.baidu.com/s/1YE6uqgJeooEwovFv8cvr6A
> 提取码：asd1
> 
> 腾讯微云下载链接：
> https://share.weiyun.com/YeFF7D4A
> 
> 看看哪个能用。
> 
> > 这个也不行...

这个问题应该是模型转换的时候 LSTM 算子没有被正确融合导致的，你试一下看这个 TNN 模型，应该是可以跑的
[model.zip](https://github.com/Tencent/TNN/files/6999418/model.zip)

**Comment by liziru** [comment]
感谢，我使用你提供的模型推理，报下面这个错误：
![image](https://user-images.githubusercontent.com/34911790/129741383-46964f18-d8f0-4a0b-9990-b159ae5e52f1.png)
这是怎么回事？
此外，如果是模型转换的问题，我应该使用哪版的转换工具，或者我该如何转换？

**Comment by liziru** [comment]
> **1. 环境（environment）**
> 
> * Build OS and Version: Linux ubuntu 4.4.0-142-generic [fix bugs in ssd model #168](https://github.com/Tencent/TNN/pull/168)-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> * RunTime OS Version: Linux ubuntu 4.4.0-142-generic [fix bugs in ssd model #168](https://github.com/Tencent/TNN/pull/168)-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> * RunTime DEVICE: x86_64
> 
> **2. Github版本**
> 
> * branch：master
> * commit(optional):
> 
> **3. 编译方式(compile method)**
> CMake完整编译参数(full cmake arguments)
> 
> **4. 编译日志(build log)**
> ![image](https://user-images.githubusercontent.com/34911790/128987961-c20435d8-f9d5-4d1d-b1d7-5069394e8c4f.png)
> 
> **5. 详细描述bug 情况 (Describe the bug)**
> 我利用tf.keras训练两层lstm+一层全连接模型，并利用keras2onnx转为onnx模型，然后成功的将onnx模型转换为tnn model。基于TNNObjectDetector.cc， 我做了修改，来推理lstm tnn model ， 但是失败了，失败日志如下。
> 
> **6. 运行日志（runtime log）**
> ![image](https://user-images.githubusercontent.com/34911790/128988569-d26e9d7a-e13b-4d1d-95ef-2422c7f2c632.png)
> 
> ![image](https://user-images.githubusercontent.com/34911790/128988458-c51ab4bc-6758-4cdc-9b34-4ee0de903f8e.png)
> gdb log:
> ![image](https://user-images.githubusercontent.com/34911790/128989767-5ecdc510-45ae-428d-b004-36795eafbe06.png)
> 
> **7. 截图（Screenshots）**
> 
> 推理代码：
> `#include
> #include
> #include
> #include
> 
> #include "../flags.h"
> #include "macro.h"
> // #include "object_detector_ssd.h"
> #include "tnn_sdk_sample.h"
> #include "utils/utils.h"
> 
> #define STB_IMAGE_IMPLEMENTATION
> #include "../../../../third_party/stb/stb_image.h"
> #define STB_IMAGE_RESIZE_IMPLEMENTATION
> #include "../../../../third_party/stb/stb_image_resize.h"
> #define STB_IMAGE_WRITE_IMPLEMENTATION
> #include "../../../../third_party/stb/stb_image_write.h"
> 
> using namespace TNN_NS;
> 
> int main(int argc, char **argv) {
> if (!ParseAndCheckCommandLine(argc, argv)) {
> ShowUsage(argv[0]);
> return -1;
> }
> 
> ```
> auto proto_content = fdLoadFile(FLAGS_p.c_str());
> auto model_content = fdLoadFile(FLAGS_m.c_str());
> 
> auto option = std::make_shared<TNN_NS::TNNSDKOption>();
> {
>     option->proto_content = proto_content;
>     option->model_content = model_content;
>     option->compute_units = TNN_NS::TNNComputeUnitsCPU;
> ```
> 
> // if enable openvino/tensorrt, set option compute_units to openvino/tensorrt
> #ifdef _CUDA_
> option->compute_units = TNN_NS::TNNComputeUnitsTensorRT;
> #elif _OPENVINO_
> option->compute_units = TNN_NS::TNNComputeUnitsOpenvino;
> #endif
> }
> 
> ```
> char img_buff[256];
> char *input_imgfn = img_buff;
> strncpy(input_imgfn, FLAGS_i.c_str(), 256);
> 
> int image_width, image_height, image_channel;
> unsigned char *data = new unsigned char[257];
> // unsigned char *data = stbi_load(input_imgfn, &image_width, &image_height, &image_channel, 3);
> image_width           = 257;
> image_height          = 1;
> image_channel         = 1;
> std::vector<int> nchw = {1, 1, image_height, image_width};
> 
> if (!data) {
>     fprintf(stderr, "Object-Detector open file %s failed.\n", input_imgfn);
> }
> 
> auto predictor = std::make_shared<TNNSDKSample>();
> auto status    = predictor->Init(option);
> if (status != TNN_NS::TNN_OK) {
>     std::cout << "Predictor Initing failed, please check the option parameters" << std::endl;
> }
> 
> std::shared_ptr<TNN_NS::TNNSDKOutput> sdk_output = nullptr;
> 
> auto image_mat  = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_NAIVE, TNN_NS::N8UC3, nchw, data);
> auto resize_mat = predictor->ProcessSDKInputMat(image_mat, "data_input");
> CHECK_TNN_STATUS(predictor->Predict(std::make_shared<TNN_NS::TNNSDKInput>(resize_mat), sdk_output));
> 
> CHECK_TNN_STATUS(predictor->ProcessSDKOutput(sdk_output));
> // std::vector<TNN_NS::ObjectInfo> object_list;
> // if (sdk_output && dynamic_cast<TNN_NS::ObjectDetectorSSDOutput *>(sdk_output.get())) {
> //     auto obj_output = dynamic_cast<TNN_NS::ObjectDetectorSSDOutput *>(sdk_output.get());
> //     object_list     = obj_output->object_list;
> // }
> 
> int ow = sdk_output.get()->GetMat()->GetWidth();
> int oh = sdk_output.get()->GetMat()->GetHeight();
> int oc = sdk_output.get()->GetMat()->GetChannel();
> int ob = sdk_output.get()->GetMat()->GetBatch();
> printf("INFO: %d, %d, %d, %d\n", ob, oc, ow, oh);
> 
> delete[] data;
> 
> return 0;
> ```
> 
> }`
> 
> 期待任何回复，感谢。

这里有我的推理代码，基于目标检测修改。 顺便提一句，你们方便的话可以提供一个mini inference demo，方便其他人拓展。

**Comment by 1627180283** [comment]
> 感谢，我使用你提供的模型推理，报下面这个错误：
> ![image](https://user-images.githubusercontent.com/34911790/129741383-46964f18-d8f0-4a0b-9990-b159ae5e52f1.png)
> 这是怎么回事？
> 此外，我是通过官方提供的docker虚拟环境进行的模型转换。如果是模型转换的问题，我应该使用哪版的转换工具，或者我该如何转换？ @1627180283

这个问题应该是没有正确设置输入导致的。
转换工具修复的代码稍后会提交到 master 分支，后续你如果需要转换新的模型可以用最新的 master 分支编译模型转换工具进行转换。（docker 暂时没办法自动更新，所以 master 分支新的改动可能不会更新到 docker 里）

这个是我这边参考你的代码修改之后的推理代码，输入用的是全 0。
```
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include "../flags.h"
#include "macro.h"
#include "object_detector_ssd.h"
#include "tnn_sdk_sample.h"
#include "utils/utils.h"
//
#define STB_IMAGE_IMPLEMENTATION
#include "../../../../third_party/stb/stb_image.h"
#define STB_IMAGE_RESIZE_IMPLEMENTATION
#include "../../../../third_party/stb/stb_image_resize.h"
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "../../../../third_party/stb/stb_image_write.h"

using namespace TNN_NS;

int main(int argc, char **argv) {
    if (!ParseAndCheckCommandLine(argc, argv)) {
        ShowUsage(argv[0]);
        return -1;
    }

    auto proto_content = fdLoadFile(FLAGS_p.c_str());
    auto model_content = fdLoadFile(FLAGS_m.c_str());

    auto option = std::make_shared<TNN_NS::TNNSDKOption>();
    {
        option->proto_content = proto_content;
        option->model_content = model_content;
        option->compute_units = TNN_NS::TNNComputeUnitsCPU;
#ifdef CUDA
option->compute_units = TNN_NS::TNNComputeUnitsTensorRT;
#elif OPENVINO
option->compute_units = TNN_NS::TNNComputeUnitsOpenvino;
#endif
    }

    char img_buff[256];
    char *input_imgfn = img_buff;
    strncpy(input_imgfn, FLAGS_i.c_str(), 256);

    const std::vector<int> input_2_shape = {1, 1, 257};
    const std::vector<int> input_3_shape = {1, 2, 128, 2};

    std::vector<float> input_2_data(257, 0);
    std::vector<float> input_3_data(1 * 2 * 128 * 2, 0);
    float* input_2_data_ptr = input_2_data.data();
    float* input_3_data_ptr = input_3_data.data();

    auto predictor = std::make_shared<TNNSDKSample>();
    auto status    = predictor->Init(option);
    if (status != TNN_NS::TNN_OK) {
        std::cout << "Predictor Initing failed, please check the option parameters" << std::endl;
    }

    std::shared_ptr<TNN_NS::TNNSDKOutput> sdk_output = nullptr;

    auto input_2_mat  = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_NAIVE, TNN_NS::NCHW_FLOAT, input_2_shape, input_2_data_ptr);
    auto input_3_mat  = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_NAIVE, TNN_NS::NCHW_FLOAT, input_3_shape, input_3_data_ptr);
    auto tnn_sdk_input = std::make_shared<TNN_NS::TNNSDKInput>();
    tnn_sdk_input->AddMat(input_2_mat, "input_2");
    tnn_sdk_input->AddMat(input_3_mat, "input_3");
    CHECK_TNN_STATUS(predictor->Predict(tnn_sdk_input, sdk_output));

    CHECK_TNN_STATUS(predictor->ProcessSDKOutput(sdk_output));

    int ow = sdk_output.get()->GetMat()->GetWidth();
    int oh = sdk_output.get()->GetMat()->GetHeight();
    int oc = sdk_output.get()->GetMat()->GetChannel();
    int ob = sdk_output.get()->GetMat()->GetBatch();
    printf("INFO: %d, %d, %d, %d\n", ob, oc, ow, oh);

    return 0;
}

```

**Comment by liziru** [comment]
好的，感谢。@1627180283 
但是我遇到了另一个问题，输出结果不对, 输出的形状是对的（1, 1, 0, 257）。 
我想请教两个问题，第一个是debug输出结果和对齐结果这方面，有什么好的建议吗？ 第二个，我想获取另外一个输出，我该如何获取？ 
获取输出结果方式：
`for (int i = 0; i < oh; i++) {
        std::cout << ((float*)sdk_output.get()->GetMat()->GetData())[i] << ' ';
 }
 std::cout << std::endl;`
两个输出：
![image](https://user-images.githubusercontent.com/34911790/130010969-b2b8ac24-f26e-4dd6-ba39-91311179543f.png)

**Comment by 1627180283** [comment]
你可以用 tnn 的 model_check 工具 ( https://github.com/Tencent/TNN/blob/master/doc/cn/development/model_check.md#2-linux ) 测试一下，TNN 得到的输出是否正确，如果正确的话你检验一下看你的输入是否设置正确。
多输出的话应该可以通过 GeMat 指定输出 name 来获得，例如 GetMat("activation_2") 这样。具体的你可以参考一下 tnn demo 里的代码，应该是有多输出的例子的。

**Comment by 1627180283** [comment]
你好，这个模型现在还有问题吗，如果没有的话我把 issue 先 close 了
