### ISSUE TITLE
在安卓端如何对TNN推理输出Mat进行Softmax并得到最终输出

### ISSUE THREAD

**Issue by bestpower** [Tencent/TNN#1229]
**1. 环境**
 - RunTime OS Version: Android
 - RunTime DEVICE: ARM

  **2. Github版本**
 - branch：master

  **3. 详细描述问题 **
某些模型在推理出结果后需要对Mat再进行一步Softmax操作才能得出最终结果，请问在TNN的安卓端中如何实现类似如下ncnn示例的方法？
ncnn softmax代码示例：
```cpp
{
   //模型推理，得到一个结果Mat out
    ......
    ncnn::Layer* softmax = ncnn::create_layer("Softmax");
    ncnn::ParamDict pd;
    softmax->load_param(pd);
    softmax->forward_inplace(out, *net.opt);
   //最后得到的out即为所需结果
   ......
}
```

**Comment by shaundai-tencent** [comment]
目前TNN不支持这种用法，像这种操作建议直接加到模型中去，如果是Softmax这样的算子也可以手动改写tnnproto文件来支持，但是需要对tnnproto的格式比较熟悉。此外，加在模型里面对性能优化也有帮助，不需要内存的重排。

**Comment by bestpower** [comment]
可以帮忙修改一下tnnproto文件来添加Softmax算子吗，不胜感激，详见附件
[model.zip](https://github.com/Tencent/TNN/files/6973086/model.zip)

**Comment by shaundai-tencent** [comment]
需要知道具体在哪个维度上面做softmax，附件中是axis=1，即在Channel方向上面做softmax的例子，你可以参考一下。
[model_new.zip](https://github.com/Tencent/TNN/files/6973553/model_new.zip)

**Comment by bestpower** [comment]
> 需要知道具体在哪个维度上面做softmax，附件中是axis=1，即在Channel方向上面做softmax的例子，你可以参考一下。
> [model_new.zip](https://github.com/Tencent/TNN/files/6973553/model_new.zip)

当前做的这个维度是就可以，可以输出正确结果，非常感谢！
