### ISSUE TITLE
onnx转tnn data_type:0

### ISSUE THREAD

**Issue by ccslience** [Tencent/TNN#1239]
**1. 使用环境（environment）**
 - OS: Mac

  **2. Github版本**
 - branch：dev-greater

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型转换失败（converter failed）
 - original model：ONNX
模型在这里：https://drive.google.com/file/d/1SM5bhQnAfzStHThAM3Y17ngWBpO9V6Wt/view?usp=sharing

  **4. 截图（Screenshots）**
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/30198850/129849070-a30f93e9-ecab-4ee3-b812-d45d12f2e5aa.png">

**Comment by 1627180283** [comment]
模型里有 GatherElements 这样的算子 tnn 暂时还不支持，可能需要等后续 tnn 的适配支持
![image](https://user-images.githubusercontent.com/37806708/130381258-449af214-c2f8-44ea-bf8b-695dd4257ec8.png)

**Comment by ccslience** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/TNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月23日(星期一) 上午10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/TNN] onnx转tnn data_type:0 (#1239)





 
模型里有 GatherElements 这样的算子 tnn 暂时还不支持，可能需要等后续 tnn 的适配支持
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by latermarch** [comment]
GatherElements 还没有适配吗，拉最新的master分支还是转换不了
