### ISSUE TITLE
yolo5s  onnx::::::::::::The onnx model is not aligned with tnn model

### ISSUE THREAD

**Issue by henbucuoshanghai** [Tencent/TNN#1241]
**1. 使用环境（environment）**
 - OS: Ubuntu/     Docker
 - OS Version:

  **2. Github版本**
 - branch：
 - commit(optional):

my model is yolo5s,i change nothing of the yolo5s network,  why?
the error is :

--------  convert model, please wait a moment ----------
Converter ONNX to TNN Model...
Converter ONNX to TNN check_onnx_dim...
Converter ONNX to TNN check_onnx_dim...
Converter ONNX to TNN model succeed!
----------  align model (tflite or ONNX vs TNN),please wait a moment ----------
images: input shape of onnx and tnn is aligned!
Run tnn model_check...
----------   Unfortunately   ----------
The onnx model is not aligned with tnn model

**Comment by 1627180283** [comment]
Can you provide your onnx model?

**Comment by henbucuoshanghai** [comment]
/home/li/TNN/yolov5s.onnx

**Comment by henbucuoshanghai** [comment]
[yoloonnx.zip](https://github.com/Tencent/TNN/files/7006257/yoloonnx.zip)

**Comment by henbucuoshanghai** [comment]
tks      i trained yolo5 with only one class,    i did not change others

**Comment by 1627180283** [comment]
You can try the latest master branch, I can successfully convert on this branch

![image](https://user-images.githubusercontent.com/37806708/130346054-22968820-0e74-49ba-a004-de8b0461f707.png)
