### ISSUE TITLE
convert failed onnx:ImageScaler

### ISSUE THREAD

**Issue by zhaoyk1986** [Tencent/TNN#125]
大佬：

我的模型是 kreas->coremltools-> onnx->tnn
转tnn的时候出错

TNNWriteProto [Line 222] input_blob 0(image) channel order:1(DATA_BATCH) 3(DATA_CHANNEL) 128(DATA_FEATURE) 128(DATA_FEATURE)
TNNWriteProto [Line 310] error::op convert failed onnx:ImageScaler

忘大佬指点。

**Comment by darrenyao87** [comment]
ImageScaler是coreml模型特有的层，出现在第一层，负责把图像数据就行归一化，与TNN的BlobConverter作用一致。
TNN转模型的时候会自动去掉ImageScaler，开发人员可通过SetInputMat的接口传入MatConvertParam参数来完成ImageScaler的功能。

**Comment by darrenyao87** [comment]
// step 1. set input mat
        TNN_NS::MatConvertParam input_convert_param;
        input_convert_param.scale = {1.0 / 128, 1.0 / 128, 1.0 / 128, 0.0};
        input_convert_param.bias  = {-127.0 / 128, -127.0 / 128, -127.0 / 128, 0.0};
        auto status = instance_->SetInputMat(image_mat, input_convert_param);
        if (status != TNN_NS::TNN_OK) {
            LOGE("input_blob_convert.ConvertFromMatAsync Error: %s\n", status.description().c_str());
            return status;
        }

**Comment by gttiankai** [comment]
已支持。
