### ISSUE TITLE
.onnx does not exist

### ISSUE THREAD

**Issue by henbucuoshanghai** [Tencent/TNN#1254]
**1. 使用环境（environment）**
 - OS: ubuntu18.04
 - OS Version:

  **2. Github版本**
 - branch   latest

  **3. 详细描述bug 情况 (Describe the bug)**
docker image is right,the test command  resout is right :
docker run  -it tnn-convert:latest  python3 ./converter.py tf2tnn -h
the resout is the same as the README.
but run the code :
sudo docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py onnx2tnn     /home/lili/Downloads/yolov5s.onnx     -optimize     -v v3.0     -align output     -input_file /workspace/in.txt     -ref_file /workspace/ref.txt

  **4. 日志（Log）**
 ----------  convert model, please wait a moment ----------
Converter ONNX to TNN Model...
The //home/lili/Downloads/yolov5s.onnx does not exist! please make sure the file exist!

I only change the path of onnx,i have the onnx  but the error is yolov5s.onnx does not exist
why   tks

**Comment by shaundai-tencent** [comment]
The path should be the path in docker, not in the host. So, you should use the path: /workspace/xxxx.
