### ISSUE TITLE
ARM版本编译不通过

### ISSUE THREAD

**Issue by wuang55555** [Tencent/TNN#1255]
在x86 linux PC机上交叉编译arm版本不能有效通过，报错如下：

![image](https://user-images.githubusercontent.com/44832101/130761425-106624ec-5680-4b8a-bb80-a89866c1be72.png)

![image](https://user-images.githubusercontent.com/44832101/130761462-1270802f-520a-411a-a78c-f7764d1f97eb.png)
![image](https://user-images.githubusercontent.com/44832101/130761496-0e548e69-eb99-4126-9dd2-e9461ad6bb89.png)

**Comment by quinnrong94** [comment]
@wuang55555 麻烦提供编译器以及tnn的版本信息，以便问题复现。

**Comment by wuang55555** [comment]
> @wuang55555 麻烦提供编译器以及tnn的版本信息，以便问题复现。
谢谢回复

arm-linux-gnueabihf-gcc --version
arm-linux-gnueabihf-gcc (crosstool-NG linaro-1.13.1-4.7-2013.03-20130313 - Linaro GCC 2013.03) 4.7.3 20130226 (prerelease)
Copyright (C) 2012 Free Software Foundation, Inc.

root@dsplinux-server:/home/wuang/15_NCNN/ncnn-master# arm-linux-gnueabihf-g++ --version
arm-linux-gnueabihf-g++ (crosstool-NG linaro-1.13.1-4.7-2013.03-20130313 - Linaro GCC 2013.03) 4.7.3 20130226 (prerelease)
Copyright (C) 2012 Free Software Foundation, Inc.

TNN为最新版本：
https://gitee.com/mirrors/TNN?utm_source=alading&utm_campaign=repo

**Comment by wuang55555** [comment]
![image](https://user-images.githubusercontent.com/44832101/131201452-a685c81e-d7a0-49a7-bd70-306b81d80687.png)
还是有一处告警，需继续支持分析；谢谢。

**Comment by quinnrong94** [comment]
@wuang55555 已修复，用该版本编译器验证可以编过，请更新。
