### ISSUE TITLE
pls help, why my .onnx can't convert to .tnn， yolov5s 模型

### ISSUE THREAD

**Issue by he13689** [Tencent/TNN#1264]
使用环境（environment）**
 - OS: Windows

详细描述bug 情况 (Describe the bug)**
模型转换失败（converter failed）

我的模型转为 onnx 时的输出为 ：
F:\anaconda\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2021-08-31 11:29:53.916 | INFO     | __main__:<module>:59 - Saved model as train2best ! 
2021-08-31 11:29:54.510 | INFO     | __main__:<module>:68 - simply
2021-08-31 11:29:56.022 | INFO     | __main__:<module>:78 - Saved model as train2best_simple ! 

我的Onnx转为tnn时出现了这个问题，通过convertmodel.com进行的转换：
遇到了未知错误：“RuntimeError: abort(Assertion failed: 0, at: /home/dev/files/repos/web-model-converter/third_party/TNN/tools/onnx2tnn/src/core/onnx_utility.cc,556,get_tensor_proto_data). Build with -s ASSERTIONS=1 for more info.”，可以尝试向 tnn 开发者反馈

ONNX文件在百度网盘
链接：https://pan.baidu.com/s/1clMDjCCquFYb3S56S5Bvtw 
提取码：gey8

模型在百度网盘
链接：https://pan.baidu.com/s/1kkzq5_AxLb-SDblOST7VOQ 
提取码：qhmt

代码为：
链接：https://pan.baidu.com/s/1oSYxPlawYrlCYDSrFiG0SA 
提取码：t46b

这是什么问题，求大佬解答一下，谢谢

**Comment by he13689** [comment]
百度云中模型传错了，这里再传一遍
链接：https://pan.baidu.com/s/1clMDjCCquFYb3S56S5Bvtw 
提取码：gey8

**Comment by 1627180283** [comment]
convertmodel.com 的转换工具可能没有及时更新，你可以尝试本地编译 tnn 模型转换工具或者使用 docker 模型转换工具再重新转换看一下

**Comment by he13689** [comment]
It works， thanks. 就是用windows docker配置的时候真费劲啊，问题解决了，谢谢
