### ISSUE TITLE
请教一下：通过TNNTest 测试 LeNet；是否有运行的配置参数可以参考。

### ISSUE THREAD

**Issue by wuang55555** [Tencent/TNN#1274]
目前已基于build_armhf_linux完成编译，想在arm v7平台上验证一下LeNet网络的性能。
是否可以提供测试用例。
非常感谢。

**Comment by shaundai-tencent** [comment]
可以参考：https://github.com/Tencent/TNN/blob/master/doc/cn/development/profiling.md
在 TNN/benchmark目录下有各个平台的benchmark脚本。

**Comment by wuang55555** [comment]
![image](https://user-images.githubusercontent.com/44832101/131990985-863863b5-41b9-457c-a808-9ed1e2ee3219.png)
目前这个采用arm V7的编译器 编译是失败的。
---
./benchmark_models.sh -32

**Comment by shaundai-tencent** [comment]
请问使用的是哪个目录下的benchmark_models.sh？是否使用最新的master代码编译的？
