### ISSUE TITLE
Dcoker 转换onnx模型时，结果对不齐

### ISSUE THREAD

**Issue by LitLeo** [Tencent/TNN#1281]
**1. 环境（environment）**
 - Build OS and Version: Centos
 - RunTime OS Version: Linux
 - RunTime DEVICE: X86

  **2. Github版本**
 - branch：master
 - commit(optional): 40b88cefa087e26caf68d9dc204ec9735a1d8a3e

  **3. 详细描述bug 情况 (Describe the bug)**
Dcoker 转换onnx模型时，
#### -align output时的输出是
docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py onnx2tnn     /wor
kspace/model.onnx     -optimize     -v v3.0     -align output     -input_file /workspace/tnn_inputs.bin     -ref_file /workspace/tnn_outputs.bin                                                       

----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN model succeed!

----------  align model (tflite or ONNX vs TNN),please wait a moment ----------

input: input shape of onnx and tnn is aligned!

hn: input shape of onnx and tnn is aligned!

cn: input shape of onnx and tnn is aligned!

Run tnn model_check...
----------   Unfortunately   ----------
The onnx model is not aligned with tnn model

#### -align all时的输出是
D/tnn: ReshapeLayers [File /opt/TNN/source/tnn/core/default_network.cc][Line 708] ReshapeLayers Output Shape: [name: output data type: 0 shape: [ 30 1000 1 ]]

D/tnn: RunModelCheckerFromDumpFile [File /opt/TNN/tools/model_check/model_checker.cc][Line 201] ModelChecker::RunModelCheckerFromDumpFile

model check pass!

----------  Congratulations!   ----------
The onnx model is aligned with tnn model

命令：

docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py onnx2tnn     /workspace/model.onnx     -optimize     -v v3.0     -align output     -input_file /workspace/tnn_inputs.bin     -ref_file /workspace/tnn_outputs.bin

转换命令所需文件
链接：https://share.weiyun.com/hVheUNSw 密码：a5pfr5

**Comment by 1627180283** [comment]
-align output 不使用 -input_file 和 -ref_file 这两个参数，可以对齐吗
