### ISSUE TITLE
Tnn是否支持华为HarmonyOS 2.0操作系统

### ISSUE THREAD

**Issue by lucheng0522** [Tencent/TNN#1284]
开发的demo在Android系统中可正常运行，但是在HarmonyOS 2.0操作系统上使用Npu推理计算，崩溃了。请问TNN是否支持鸿蒙操作系统

**Comment by shaundai-tencent** [comment]
在安卓系统中正常执行的也是NPU吗？

**Comment by lucheng0522** [comment]
是支持鸿蒙系统的。
