### ISSUE TITLE
量化后的模型进行推理时直接报Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lg920810** [Tencent/TNN#1289]
环境为 Linux ubuntu18.04 桌面版， Github版本使用最新的版本，使用pytorch->onnx->tnn，都没有报错，tnn模型正常运行，但是使用量化工具后再进行推理报Segmentation fault (core dumped)，在编译及量化的过程中没有任何错误。
量化命令为：
./quantization_cmd -p /codes/pretrained/model.tnnproto -m /codes/pretrained/model.tnnmodel -i /codes/image/ -b 2 -w 0 -n 127.5,127.5,127.5 -s 0.007843,0.007843,0.007843

求大神赐教~

**Comment by shaundai-tencent** [comment]
跑的时候选择的是什么平台，NAIVE还是ARM还是X86？能否提供一下出错的模型来复现问题？
