### ISSUE TITLE
转换支持batch的ONNX模型失败

### ISSUE THREAD

**Issue by chwma0** [Tencent/TNN#1290]
**1. 使用环境（environment）**
 - OS: Docker
 - OS Version:latest

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型转换失败（converter failed）
 - original model：ONNX
 （如果可以的话，请上传原始的模型文件）
- ONNX模型是通过相关API生成的：
```python
# 根据节点构建图
g1 = h.make_graph(
    [a1],
    'ABS',
    [h.make_tensor_value_info('x', tp.DOUBLE, shape=['N', 1650])],
    [h.make_tensor_value_info('fx', tp.DOUBLE, shape=['N', 1650])],
)
```

  **4. 日志（Log）**
 ```txt
 docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py onnx2tnn /workspace/model/am-v2-quant.onnx -v v2.0.0 -align output -input_file /workspace/model/input.txt -ref_file /workspace/model/output.txt

----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN current_shape...

You should use -in to specify input's name and shape. e.g.: -in name:1,3,32,32
Current shape: x: ['N', 1650]
 ```

  **5. 截图（Screenshots）**

**Comment by 1627180283** [comment]
可以在模型转换命令里用 -in 指定输入 shape 之后再转换。例如，如果只有一个输入的话可以用 -in 1,1650

**Comment by chwma0** [comment]
> 可以在模型转换命令里用 -in 指定输入 shape 之后再转换。例如，如果只有一个输入的话可以用 -in 1,1650

新的log：

**Comment by 1627180283** [comment]
你把 -input_file 和 -ref_file 这两个参数去掉，看是否能成功转换
如果不行的话，你在转换命令里加上 -debug，这样会显示完整日志，你把日志贴一下

**Comment by chwma0** [comment]
docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py onnx2tnn /workspace/model/am-v2-quant.onnx -v v2.0.0 -align output -input_file /workspace/model/input.txt -ref_file /workspace/model/output.txt -in x:100,1650 -debug

----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN check_onnx_dim...

The onnx2tnn command:python3 onnx2tnn.py /workspace/model/am-v2-quant.onnx -version=v2.0.0 -optimize=0 -half=0 -o /workspace/model -input_shape x:100,1650



You should compile onnx2tnn first !!!

You can find more compilation details in <path-to-tnn>/doc/cn/user/convert.md


Converter ONNX to TNN model failed!

**Comment by chwma0** [comment]
onnx模型是动态定点化为int8的模型，不知道这个是否有影响

**Comment by 1627180283** [comment]
> docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py onnx2tnn /workspace/model/am-v2-quant.onnx -v v2.0.0 -align output -input_file /workspace/model/input.txt -ref_file /workspace/model/output.txt -in x:100,1650 -debug
> 
> ---------- convert model, please wait a moment ----------
> 
> Converter ONNX to TNN Model...
> 
> Converter ONNX to TNN check_onnx_dim...
> 
> Converter ONNX to TNN check_onnx_dim...
> 
> The onnx2tnn command:python3 onnx2tnn.py /workspace/model/am-v2-quant.onnx -version=v2.0.0 -optimize=0 -half=0 -o /workspace/model -input_shape x:100,1650
> 
> You should compile onnx2tnn first !!!
> 
> You can find more compilation details in /doc/cn/user/convert.md
> 
> Converter ONNX to TNN model failed!

看样子可能是 tnn 转换工具没有成功编译或者链接，这个是你基于 tnn 提供的 docker 进行转换的吗

**Comment by 1627180283** [comment]
> onnx模型是动态定点化为int8的模型，不知道这个是否有影响

这样的模型当前暂时不支持转换

**Comment by chwma0** [comment]
> 看样子可能是 tnn 转换工具没有成功编译或者链接，这个是你基于 tnn 提供的 docker 进行转换的吗

是的，我用的官网推荐的docker

**Comment by 1627180283** [comment]
> > > onnx模型是动态定点化为int8的模型，不知道这个是否有影响
> > 
> > 
> > 这样的模型当前暂时不支持转换
> 
> 好的多谢，如果是原始模型转成TNN，TNN支持模型的定点化及其inference吗？

int8 的话可以参考这个文档 https://github.com/Tencent/TNN/blob/master/doc/cn/user/quantization.md

**Comment by 1627180283** [comment]
> > 看样子可能是 tnn 转换工具没有成功编译或者链接，这个是你基于 tnn 提供的 docker 进行转换的吗
> 
> 是的，我用的官网推荐的docker

好的，我稍后看一下 docker 的问题

**Comment by chwma0** [comment]
我看有人说是这个问题：https://github.com/Tencent/TNN/pull/1062
能否修改后更新下docker

**Comment by 1627180283** [comment]
你使用的镜像是从腾讯云拉取的吗
![image](https://user-images.githubusercontent.com/37806708/132473538-8c91a667-8179-4cad-b503-a9d1e1631cfc.png)

**Comment by chwma0** [comment]
> 你使用的镜像是从腾讯云拉取的吗

是的，就是这个

**Comment by 1627180283** [comment]
我这边拉取了最新的 docker 镜像测试了一下是可以成功转换的，没有复现这个问题，你可以更新一下你那边的看一下，或者可以尝试本地编译转换工具（本地编译 onnx 版本有问题的话可以尝试使用最新版本的 onnx）

**Comment by chwma0** [comment]
> 我这边拉取了最新的 docker 镜像测试了一下是可以成功转换的，没有复现这个问题，你可以更新一下你那边的看一下，或者可以尝试本地编译转换工具（本地编译 onnx 版本有问题的话可以尝试使用最新版本的 onnx）

本地编译成功了，但还是这个问题：

python converter.py onnx2tnn model/am-v2-dnn.onnx -v v2.0.0 -align output -input_file model/input.txt -ref_file model/output.txt -in x:100,1650 -debug

----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN check_onnx_dim...

The onnx2tnn command:python3 onnx2tnn.py /data1/machangwei/tnn/tools/TNN/tools/convert2tnn/model/am-v2-dnn.onnx -version=v2.0.0 -optimize=0 -half=0 -o /data1/machangwei/tnn/tools/TNN/tools/convert2tnn/model -input_shape x:100,1650



You should compile onnx2tnn first !!!

You can find more compilation details in <path-to-tnn>/doc/cn/user/convert.md


Converter ONNX to TNN model failed!

**Comment by 1627180283** [comment]
onnx2tnn*.so 应该是放在 TNN/tools/onnx2tnn/onnx-converter 目录下，你检查一下，如果在这个目录下有 onnx2tnn*.so 的话，应该是编译 onnx2tnn*.so 的 python 和调用 onnx2tnn*.so 的 python 不一致导致的

**Comment by chwma0** [comment]
> tools/onnx2tnn/onnx-converter

TNN/tools/onnx2tnn/onnx-converter 目录下有这个lib：onnx2tnn.cpython-38-x86_64-linux-gnu.so
python调用不一致怎么改呢？

**Comment by 1627180283** [comment]
你的 python3 是3.8 版本的吗，如果不是的话你执行 
python3.8 converter.py onnx2tnn model/am-v2-dnn.onnx -align -in x:100,1650 -debug 
看能不能成功转换

**Comment by chwma0** [comment]
> 你的 python3 是3.8 版本的吗，如果不是的话你执行
> python3.8 converter.py onnx2tnn model/am-v2-dnn.onnx -align -in x:100,1650 -debug
> 看能不能成功转换

我的是python3.6，3.8的python安装不了onnx，问题出的是环环相扣啊

**Comment by chwma0** [comment]
用一个python3.6的环境编译这个lib，然后用python3.8的环境执行convert，现在log如下：

----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN model succeed!

----------  align model (tflite or ONNX vs TNN),please wait a moment ----------

x: input shape of onnx and tnn is aligned!

Run tnn model_check...
----------   Unfortunately   ----------
The onnx model is not aligned with tnn model


debug log：

----------  align model (tflite or ONNX vs TNN),please wait a moment ----------

x: input shape of onnx and tnn is aligned!

Run tnn model_check...
/data1/machangwei/tnn/tools/TNN/tools/convert2tnn


/data1/machangwei/tnn/tools/TNN/tools/convert2tnn/bin/model_check -e -p  /data1/machangwei/tnn/tools/TNN/tools/convert2tnn/model/am-v2-dnn.tnnproto -m /data1/machangwei/tnn/tools/TNN/tools/convert2tnn/model/am-v2-dnn.tnnmodel -i /data1/machangwei/tnn/tools/TNN/tools/convert2tnn/model/input.txt -f /data1/machangwei/tnn/tools/TNN/tools/convert2tnn/model/output.txt -d NAIVE
proto: /data1/machangwei/tnn/tools/TNN/tools/convert2tnn/model/am-v2-dnn.tnnproto

model: /data1/machangwei/tnn/tools/TNN/tools/convert2tnn/model/am-v2-dnn.tnnmodel

device: NAIVE

input file: /data1/machangwei/tnn/tools/TNN/tools/convert2tnn/model/input.txt

	file name: /data1/machangwei/tnn/tools/TNN/tools/convert2tnn/model/input.txt  type: 1

reference output file: /data1/machangwei/tnn/tools/TNN/tools/convert2tnn/model/output.txt

	file name: /data1/machangwei/tnn/tools/TNN/tools/convert2tnn/model/output.txt  type: 1

compare output only

init model config success!

D/tnn: Interpret [File /data1/machangwei/tnn/tools/TNN/source/tnn/interpreter/tnn/model_interpreter.cc][Line 103] model params md5: 731f9d5761f300540508ced6b9c195bb

D/tnn: Interpret [File /data1/machangwei/tnn/tools/TNN/source/tnn/interpreter/tnn/model_interpreter.cc][Line 103] model params md5: b01f9a6312af1b2eae2020c8cc1b9e6b

D/tnn: CpuSupportFp16 [File /data1/machangwei/tnn/tools/TNN/source/tnn/utils/cpu_utils.cc][Line 350] CpuUtils::CpuSupportFp16, TNN_ARM82 is off, fp16arith = 0.

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 86] support fp 16: 0

D/tnn: CpuSupportFp16 [File /data1/machangwei/tnn/tools/TNN/source/tnn/utils/cpu_utils.cc][Line 350] CpuUtils::CpuSupportFp16, TNN_ARM82 is off, fp16arith = 0.

D/tnn: CpuSupportFp16 [File /data1/machangwei/tnn/tools/TNN/source/tnn/utils/cpu_utils.cc][Line 350] CpuUtils::CpuSupportFp16, TNN_ARM82 is off, fp16arith = 0.

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: o1 data type: 0 shape: [ 100 768 ]

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: o2 data type: 0 shape: [ 100 768 ]

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: o3 data type: 0 shape: [ 100 512 ]

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: o4 data type: 0 shape: [ 100 512 ]

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: o5 data type: 0 shape: [ 100 512 ]

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: o6 data type: 0 shape: [ 100 512 ]

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: o7 data type: 0 shape: [ 100 512 ]

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: o8 data type: 0 shape: [ 100 512 ]

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: o9 data type: 0 shape: [ 100 512 ]

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: o10 data type: 0 shape: [ 100 512 ]

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: o11 data type: 0 shape: [ 100 512 ]

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: o12 data type: 0 shape: [ 100 512 ]

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: o13 data type: 0 shape: [ 100 12744 ]

D/tnn: Init [File /data1/machangwei/tnn/tools/TNN/source/tnn/layer/base_layer.cc][Line 63] InferOutputShape: name: y data type: 0 shape: [ 100 12744 ]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: o1 data type: 0 shape: [ 100 768 ]]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: o2 data type: 0 shape: [ 100 768 ]]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: o3 dataE/tnn: ExtendMatMap [File /data1/machangwei/tnn/tools/TNN/tools/model_check/model_checker.cc][Line 408] mat map don't has blob data (name: x)

 type: 0 shape: [ 100 512 ]]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: o4 data type: 0 shape: [ 100 512 ]]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: o5 data type: 0 shape: [ 100 512 ]]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: o6 data type: 0 shape: [ 100 512 ]]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: o7 data type: 0 shape: [ 100 512 ]]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: o8 data type: 0 shape: [ 100 512 ]]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: o9 data type: 0 shape: [ 100 512 ]]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: o10 data type: 0 shape: [ 100 512 ]]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: o11 data type: 0 shape: [ 100 512 ]]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: o12 data type: 0 shape: [ 100 512 ]]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: o13 data type: 0 shape: [ 100 12744 ]]

D/tnn: ReshapeLayers [File /data1/machangwei/tnn/tools/TNN/source/tnn/core/default_network.cc][Line 693] ReshapeLayers Output Shape: [name: y data type: 0 shape: [ 100 12744 ]]

D/tnn: RunModelCheckerOutput [File /data1/machangwei/tnn/tools/TNN/tools/model_check/model_checker.cc][Line 259] ModelChecker::RunModelCheckerOutput

model check failed! (error: code: 0x6000 msg: extend falied: mat map is not match with blobs map)


----------   Unfortunately   ----------
The onnx model is not aligned with tnn model

**Comment by 1627180283** [comment]
你使用 -input_file 和 -ref_file 这两个参数了吗，如果使用了的话，可能是文件格式不对引起的，把这两个参数去除之后再试一下

**Comment by chwma0** [comment]
> 你使用 -input_file 和 -ref_file 这两个参数了吗，如果使用了的话，可能是文件格式不对引起的，把这两个参数去除之后再试一下

OK，去掉后好了，这两个文件的格式是什么样子的？想跑一下inference是否OK

**Comment by 1627180283** [comment]
转换工具会用随机数据自己生成数据进行验证的，一般可以不用加这两个参数
文件格式可以参考这个文档 
https://github.com/Tencent/TNN/blob/master/doc/cn/user/convert.md#%E8%BE%93%E5%85%A5%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F%E7%A4%BA%E4%BE%8B
如果是 pytorch 或者 TensorFlow 的输入输出可以直接用这个代码生成
https://github.com/Tencent/TNN/blob/master/doc/cn/user/convert.md#%E7%94%9F%E6%88%90%E8%BE%93%E5%85%A5%E6%88%96%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81

**Comment by chwma0** [comment]
> https://github.com/Tencent/TNN/blob/master/doc/cn/user/convert.md#%E7%94%9F%E6%88%90%E8%BE%93%E5%85%A5%E6%88%96%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81

好的谢谢，如果说能转换成功就是inference没问题的吗？-align 就是做这个的吧？

我用的命令：python converter.py onnx2tnn model/am-v2-dnn.onnx -v v2.0.0 -align output -in x:100,1650

**Comment by 1627180283** [comment]
是的，使用 -input_file，-ref_file 是用自己的数据去进行推理对齐，如果不使用的话是转换工具自己生成随机数据进行推理对齐

**Comment by 1627180283** [comment]
模型转换没有问题的话我把 issue 先关了，如果有问题的话可以重新打开
