### ISSUE TITLE
Profiling Failing 

### ISSUE THREAD

**Issue by madhu-korada** [Tencent/TNN#1296]
I am trying to use the default model `mobilenet_V2.tnnproto` as given in the `benchmark-model` directory to find my device capability, however, I am not able to use the given model. I followed the same instructions as given in the documentation. Do I need to do something else?? and why is there only a proto file and not tnnmodel file during profiling?? 

```
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /mnt/disk/aware_disk/TNN/test/test.cc][Line 338] init tnn failed: code: 0x1002 msg: proto content is empty

unknown_device

benchmark device: ARM 

read proto_file failed!

benchmark device: OPENCL 

read proto_file failed!

Thu Sep  9 17:30:07 IST 2021
```

This says the proto is empty, but my proto file has some model info in it. Am I missing something ???

**Comment by shaundai-tencent** [comment]
Please provide the command you execute and path you put the given model.

**Comment by madhu-korada** [comment]
As given in the [documentation](https://github.com/Tencent/TNN/blob/master/doc/en/development/profiling_en.md) I added my tnnproto file in `benchmark_models.sh` file like this.  
```
benchmark_model_list=(
mobilenet_v2.tnnproto
)
```
connected my android device using usb and executed benchmark_models.sh file using `./benchmark_models.sh -c`

**Comment by shaundai-tencent** [comment]
> documentation

where did you put the given tnnproto file? And the given tnnproto file should be put in <path_to_tnn>/benchmark/benchmark-model.

**Comment by madhu-korada** [comment]
My model is present at this location only. Do I checkout some other branch and try??

**Comment by shaundai-tencent** [comment]
I have tried the latest master and can't reproduce your problem. You can update the code and try again.
By the way, you can also add the parameter "-bs" to run the benchmark scripts on device with shell cmd. By default, the benchmark program runs in app.

**Comment by madhu-korada** [comment]
Apparently, the ADB from my system was installed using apt (it installs the old version), which was creating all the problems. 
```
sudo apt-get install android-tools-adb
```
After reading the [documentation](https://github.com/Tencent/TNN/blob/master/doc/en/development/profiling_en.md#12-execute) again, I reverified and found that ADB was causing all sorts of issues. When I changed it to the latest one everything is working fine.

**Comment by madhu-korada** [comment]
Can you explain more on the `-bs` parameter exactly for android?? What's the advantage ?? No need to connect the device or it just won't use the app??

**Comment by shaundai-tencent** [comment]
> Can you explain more on the `-bs` parameter exactly for android?? What's the advantage ?? No need to connect the device or it just won't use the app??

Just won't use the app. The execution cmd will be pushed into /data/local/tmp/tnn-benchmark. You can debug it more conveniently.
