### ISSUE TITLE
请问如何生成动态的tnn模型

### ISSUE THREAD

**Issue by float123** [Tencent/TNN#1300]
**1. 使用环境（environment）**
Centos8，cuda10.2，cudnn8.2.0，tensorrt8.0.16，

**2. Github版本**
v0.3.0版本

请问如何生成动态的tnn模型？我试图将tnn chainese-ocr案例中的dbnet模型替换为自己训练的模型。使用onnx2tnn工具，指定-input_shape为1,3,1024,1024。根据运行提示，这种情况似乎是静态的固定尺寸。如果指定height、width为-1，会提示shape需要大于等于0，如果指定height、width为0，在加载模型的时候会出错。

所以tnn支持动态shape吗？具体要如何转换？

**Comment by shaundai-tencent** [comment]
TNN是支持动态输入shape的，在转模型的时候可以不做特殊操作，在CreateInstance的时候传入shape的最大值和最小值，后面做Forward之前，通过Reshape接口来改变输入大小就行。

**Comment by float123** [comment]
> TNN是支持动态输入shape的，在转模型的时候可以不做特殊操作，在CreateInstance的时候传入shape的最大值和最小值，后面做Forward之前，通过Reshape接口来改变输入大小就行。

你好，我现在的onnx模型input shape是（1,3,512,512），是否可以直接生成动态模型，还是说我需要先创建动态的onnx，然后才能生成动态的tnn模型
![image](https://user-images.githubusercontent.com/39334643/133384579-717fd71d-d1ea-47df-bb6a-3da64d99c82b.png)

**Comment by shaundai-tencent** [comment]
可以直接转换到TNN模型

**Comment by float123** [comment]
> 可以直接转换到TNN模型

十分感谢，我已经把动态和静态的模型都成功运行了。
我现在需要把模型的输出用cuda来处理，是不是instance_->GetOutputMat中的DeviceType设置为DEVICE_CUDA，返回的结果就保存在device上的。TNN有没有对应的案例参考？

**Comment by shaundai-tencent** [comment]
> 我现在需要把模型的输出用cuda来处理，是不是instance_->GetOutputMat中的DeviceType设置为DEVICE_CUDA，返回的结果就保存在device上的。

是的，这样取出来的结果是放在GPU内存中。

调用可以参考example下面的代码。

**Comment by TD-wzw** [comment]
> > 可以直接转换到TNN模型
> 
> 非常感谢，我已经把动态和三维的模型都成功运行了。 我现在需要把模型的输出用cuda来处理，不是instance_->GetOutputMat中的DeviceType设置为DEVICE_CUDA，返回的结果就保存在device上的。TNN 有没有的案例参考？

请问一下您的这个动态输入尺寸是怎么做的呢？我也遇到一样的问题了，是直接转为静态输入尺寸的tnn模型，然后通过修改推理代码来实现动态输入吗？
