### ISSUE TITLE
Tensorflow2 to onnx to TNN failed

### ISSUE THREAD

**Issue by madhu-korada** [Tencent/TNN#1303]
**1. 使用环境（environment）**
 - OS: Ubuntu
 - OS Version: 16.04
 - For conversion: Docker given 

  **2. Github版本**
 - branch： master

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型转换失败（converter failed)
 - original model： TensorFlow2
 （如果可以的话，请上传原始的模型文件）

the link of colab:- https://colab.research.google.com/drive/1_GhO4805M_aSk1kIOVDFlVA-b1nGusBi?usp=sharing
I was able to convert the model to onnx. 
the model file of [TF]( https://drive.google.com/file/d/1TCDgR9g_3WyuOORkZEgCSlAckoOcB71g/view?usp=sharing) and [onnx](https://drive.google.com/file/d/1fqbbzvr1tSnoCYHfHxaMBg1tu69hPUQl/view?usp=sharing)

but not able to convert onnx model to TNN, I used the command `python3 converter.py onnx2tnn /disk/mnist-network-2.onnx -optimize -v=v3.0  -in input_input:1,28,28,1`
```
----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN model failed!

```
Please let me know if I am doing anything wrong.

**Comment by 1627180283** [comment]
Repeated with issue1305
