### ISSUE TITLE
Pytorch to onnx to TNN failing

### ISSUE THREAD

**Issue by madhu-korada** [Tencent/TNN#1304]
**1. 使用环境（environment）**
 - OS: Ubuntu
 - OS Version: 16.04
 - For Conversion: Docker given

  **2. Github版本**
 - branch： master

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型转换失败（converter failed)
 - original model： Pytorch
 （如果可以的话，请上传原始的模型文件）

I used the mnist script of PyTorch examples repo. the file used to train the model is [here](https://drive.google.com/file/d/1ZGIPjnE8_VAiUNptOKbAgsLf_LJKFBFe/view?usp=sharing) and conversion file [here](https://drive.google.com/file/d/1gDebWO_nnbuLaOJuqVJVqPUE9Cv-GLIP/view?usp=sharing). 

I was able to convert the model to onnx. 
the model file of [Pytorch]( https://drive.google.com/file/d/1-Sr7dKRi6YzWJhmibWqvx4Txjt61BkO7/view?usp=sharing) and [onnx](https://drive.google.com/file/d/1cp6TjaHG55qbm9EuZtSzMnvuxxdh4J54/view?usp=sharing)

but not able to convert onnx model to TNN, I used the command `python3 converter.py onnx2tnn /disk/mnist_cnn_new.onnx -optimize -v=v3.0  -in x.1:1,28,28,1`

```
----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN model failed!

```
Please let me know if I am doing anything wrong.

**Comment by 1627180283** [comment]
Can you add -debug to the command? This will show the complete log.

**Comment by madhu-korada** [comment]
The command
```
madhu@madhu-Latitude-E5570:~/aware_disk/model_zoo_TNN$ docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py onnx2tnn /workspace/mnist_cnn_new.onnx -in=x.1:1,28,28,1 -optimize -v=v3.0 -debug
```
Output
```
----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN check_onnx_dim...

The onnx2tnn command:python3 onnx2tnn.py /workspace/mnist_cnn_new.onnx -version=v3.0 -optimize=1 -half=0 -o /workspace -input_shape x.1:1,28,28,1



You should compile onnx2tnn first !!!

You can find more compilation details in <path-to-tnn>/doc/cn/user/convert.md


Converter ONNX to TNN model failed!
```
I am already using docker, do I still need to compile something??

**Comment by madhu-korada** [comment]
Thanks a lot @1627180283. After pulling the latest docker It is working.
