### ISSUE TITLE
Basic MNIST model from onnx-models repo failing to convert

### ISSUE THREAD

**Issue by madhu-korada** [Tencent/TNN#1305]
**1. 使用环境（environment）**
 - Conversion OS - Docker given
 - OS: Ubuntu
 - OS Version: 16.04

  **2. Github版本**
 - branch： master

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型转换失败（converter failed)
 - original model： TensorFlow2
 （如果可以的话，请上传原始的模型文件）

Not able to convert basic [mnist](https://github.com/onnx/models/tree/master/vision/classification/mnist) model from onnx-models [repo](https://github.com/onnx/models) to TNN. I am using the given docker image and created a container. 

I used the command 
`root@root:/opt/TNN/tools/convert2tnn# python3 converter.py onnx2tnn /disk/mnist-1.onnx -optimize -v=v3.0  -in Input73:1,28,28,1 `
```
----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN model failed!

```
Please let me know if I am doing anything wrong.

**Comment by 1627180283** [comment]
You can try mnist-8.onnx, mnist-1.onn cannot be run with onnxruntime

**Comment by madhu-korada** [comment]
I tried with mnist-8.onnx with debug option in docker, this is what I am getting. Do I need to compile even if I use docker??
`docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py onnx2tnn /workspace/mnist-8.onnx -in=Input3:1,28,28,1 -optimize -v=v3.0 -debug`
```
----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN check_onnx_dim...

The onnx2tnn command:python3 onnx2tnn.py /workspace/mnist-8.onnx -version=v3.0 -optimize=1 -half=0 -o /workspace -input_shape Input3:1,28,28,1



You should compile onnx2tnn first !!!

You can find more compilation details in <path-to-tnn>/doc/cn/user/convert.md


Converter ONNX to TNN model failed!
```

**Comment by 1627180283** [comment]
It can be successfully converted on my laptop.
![image](https://user-images.githubusercontent.com/37806708/133576436-508a6791-a6af-4895-bcfa-9a44132cfb4c.png)
You can try to re-pull the docker image or the local compilation TNN Model Converter.

**Comment by madhu-korada** [comment]
Thanks a lot @1627180283. It seems to be working by using the latest pulled docker image.

**Comment by madhu-korada** [comment]
as per [documentation](https://github.com/Tencent/TNN/blob/master/doc/en/user/convert_en.md#2-convert-the-tensorflow-model-optional)
> -tensorflow (version == 1.15.0) It is recommended to use tensorflow version 1.15.0. The current version of tensorflow 2.+ is not compatible and is not recommended.

So TF2 to onnx converted models won't work??

**Comment by 1627180283** [comment]
It works, but there may be problems.

**Comment by madhu-korada** [comment]
Okay, thanks @1627180283
