### ISSUE TITLE
请问TNN目前支持transoformer的结构吗？pytorch 自带的tranformer  api   请问可以转换为TNN?

### ISSUE THREAD

**Issue by henbucuoshanghai** [Tencent/TNN#1306]
请问TNN目前支持transoformer的结构吗？pytorch 自带的tranformer  api   请问可以转换为TNN?

**Comment by 1627180283** [comment]
你可以导出到 onnx 转换一下看，应该是支持的，之前有支持过一个 transformer 的模型。如果不支持的话可以在 issue 里提出来。

**Comment by 1627180283** [comment]
关于 transformer 的模型转换有遇到新的问题吗，如果没有的话我把 issue 先关闭了，后续有需要还可以打开
