### ISSUE TITLE
convertmodel.com报错Runtime error

### ISSUE THREAD

**Issue by mZhenz** [Tencent/TNN#1307]
**1. 使用环境（environment）**
 - OS: Mac/Ubuntu/Centos/Docker
 - OS Version:

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
使用convertmodel.com将onnx模型转成tnn模型，遇到如下报错

  **4. 日志（Log）**
 ```txt
遇到了未知错误：“RuntimeError: abort(Assertion failed: 0, at: /home/dev/files/repos/web-model-converter/third_party/TNN/tools/onnx2tnn/src/core/onnx_utility.cc,556,get_tensor_proto_data). Build with -s ASSERTIONS=1 for more info.”，可以尝试向 tnn 开发者反馈
 ```

  **5. 截图（Screenshots）**
![image](https://user-images.githubusercontent.com/52862642/132947335-e1e630f3-d01a-4610-b086-47c8ad2b9584.png)

**Comment by 1627180283** [comment]
convertmodel.com 转换工具可能没有更新，可以试试 TNN 提供的 docker 镜像或者本地编译转换工具来转模型

**Comment by mZhenz** [comment]
好的，谢谢
