### ISSUE TITLE
物体检测的模型下载失败

### ISSUE THREAD

**Issue by YuiStar-Lin** [Tencent/TNN#1312]
下载 yolov5 tnn model 的时候，出现404，其他的模型下载的时候没有问题

**Comment by GitHubLuGeng** [comment]
试试这个：
https://raw.githubusercontent.com/darrenyao87/tnn-models/master/model/yolov5/yolov5s-permute.tnnproto
https://media.githubusercontent.com/media/darrenyao87/tnn-models/master/model/yolov5/yolov5s.tnnmodel

**Comment by darrenyao87** [comment]
From now on, you can also download the models from AliYun Disk https://www.aliyundrive.com/s/MSmarP3zqrb 
模型也可以阿里云盘下载，https://www.aliyundrive.com/s/MSmarP3zqrb
