### ISSUE TITLE
tflite转tnn提示 The /opt/TNN/tools/convert2tnn/bin/TnnConverter does not exist! please make sure the file exist!

### ISSUE THREAD

**Issue by gepu0221** [Tencent/TNN#1313]
**1. 使用环境（environment）**
 - OS: Ubuntu
 - OS Version: 18.04

  **2. Github版本**
 - branch：master

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type:  模型转换失败（converter failed）
 拉取docker，进行tflite2tnn转换，会提示The /opt/TNN/tools/convert2tnn/bin/TnnConverter does not exist! please make sure the file exist!，进入docker环境后确实无法看到此文件
 - original model： Caffe/ONNX/TensorFlow/TensorFlowLite 
 （如果可以的话，请上传原始的模型文件）
模型文件链接：https://tfhub.dev/google/lite-model/movenet/singlepose/lightning/3

  **4. 日志（Log）**
 ```txt
 将日志粘贴在这里
docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py tflite2tnn \
>     /workspace/model_self/lite-model_movenet_singlepose_lightning_3.tflite \
> 


----------  convert model, please wait a moment ----------

The /opt/TNN/tools/convert2tnn/bin/TnnConverter does not exist! please make sure the file exist!


  **5. 截图（Screenshots）**
 If applicable, add screenshots to help explain your problem.

**Comment by 1627180283** [comment]
你可以试一下重新拉取 docker 镜像或者本地编译 TNN 模型转换工具

**Comment by gttiankai** [comment]
已修复。对应的 PR：https://github.com/Tencent/TNN/pull/1361

具体原因是：构建机性能比较差，编译时内存不足，就失败了。
