### ISSUE TITLE
reference quantized model with TRT, but get ERROR: Parameter check failed at: ../builder/Network.cpp::addConvolutionNd::715, condition: biasWeights.count > 0 ? (biasWeights.values != nullptr) : (biasWeights.values == nullptr) error

### ISSUE THREAD

**Issue by wowo200** [Tencent/TNN#1334]
ERROR: Parameter check failed at: ../builder/Network.cpp::addConvolutionNd::715, condition: biasWeights.count > 0 ? (biasWeights.values != nullptr) : (biasWeights.values == nullptr)

quantization parameters:
./quantization_cmd -p backbone.opt.tnnproto  -m backbone.opt.tnnmodel -i new_quan_images  -r 0 -n 127.5 -s 0.0078125 -b 2 -t 2

**Comment by shaundai-tencent** [comment]
Please describe the issue according to the template.
