### ISSUE TITLE
物体检测yolov5模型推理失败

### ISSUE THREAD

**Issue by GitHubLuGeng** [Tencent/TNN#1335]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu 20.04
 - RunTime OS Version: Linux
 - RunTime DEVICE: X86

  **2. Github版本**
 - branch：master
 - commit(optional):2521043c20cc8c37aa673a3f2f90168e012106ae

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
使用yolov5模型推理：
"运行./demo_x86_objectdetector -p ../../../../model/yolov5/yolov5s-permute.tnnproto -m ../../../../model/yolov5/yolov5s.tnnmodel  -i ../../../assets/004545.jpg"报段错误

  **6. 运行日志（runtime log）**
 ```txt
推理日志：
Face-detector is about to start, and the picrture is ../../../assets/004545.jpg
E/tnn: InterpretModel [File /home/lu/project/TNN/source/tnn/interpreter/tnn/model_interpreter.cc][Line 361] tnnmodel is invalid, maybe you should upgrade TNN
E/tnn: Init [File /home/lu/project/TNN/examples/base/tnn_sdk_sample.cc][Line 570] instance.net init failed 16385Predictor Initing failed, please check the option parameters
Segmentation fault (core dumped)
 ```

  **7. 截图（Screenshots）**
 ```txt
 将截图粘贴在这里
 Paste screenshorts here or pastebin
 ```

**Comment by powerpwang** [comment]
yolov5模型更新了下，麻烦重新下载再尝试。
https://raw.githubusercontent.com/darrenyao87/tnn-models/master/model/yolov5/yolov5s-permute.tnnproto
https://media.githubusercontent.com/media/darrenyao87/tnn-models/master/model/yolov5/yolov5s.tnnmodel

**Comment by GitHubLuGeng** [comment]
新模型可以
