### ISSUE TITLE
quantization_cmd calibration init failed!

### ISSUE THREAD

**Issue by whattheweather** [Tencent/TNN#1346]
'''
./quantization_cmd -p ~/Downloads/sr-2.tnnmodel -m ~/Downloads/sr-2.tnnproto -i ~/Downloads/imagenet-sample-images-master

import total 1000 files
import data set success!
E/tnn: Init [File Workspace/TNN/tools/quantization/calibration.cc][Line 104] tnn init failed!
calibration init failed!
'''

这个模型的输入是 hwc = 180x320x62，calibration.cc 104 行是 `tnn.CreateInst(net_config, status);` 导致的失败，请问这种模型该如何量化呢

附上模型文件，谢谢！
[sr2.zip](https://github.com/Tencent/TNN/files/7250431/sr2.zip)

**Comment by darrenyao87** [comment]
@1627180283 看看是不是模型转得有问题？tnn.CreateInst失败还没到量化。我看转模型出了个Reorg算子，这个应该移动端都还没有

**Comment by darrenyao87** [comment]
@whattheweather onnx模型最后有个 reshape(6) - transpose - reshape(4) 组合，这个应该是个复合算子，具体的pytorch的算子能否给下？

**Comment by 1627180283** [comment]
你好，方便提供一下 使用的 tnn 的 commit 吗，我这边没有复现这个问题

**Comment by 1627180283** [comment]
另外方便重新提供一下 onnx 模型吗，提供的 onnx 模型 opset version 小于 11，会出现输出结果不对齐的问题

**Comment by whattheweather** [comment]
> 另外方便重新提供一下 onnx 模型吗，提供的 onnx 模型 opset version 小于 11，会出现输出结果不对齐的问题

指定了 `opset_version=11` 的模型
[sr4.zip](https://github.com/Tencent/TNN/files/7321173/sr4.zip)

commit 7032084a240a495ca4b754507c3652afcb78d7e9

**Comment by 1627180283** [comment]
可以试一下最新的 master 分支，是可以正常 init 的
