### ISSUE TITLE
About pose estimation model conversion

### ISSUE THREAD

**Issue by CheungBH** [Tencent/TNN#1350]
Hello. I am going to deploy our pose model with TNN. 
I found that your "heatmap regression" procedure has been integrated as a layer. However, when I am converting our trained pose model, I found that there is no regression layer.
I wonder what I should do to convert with an additional regression layer?

_"Concat classificators_concat 2 1 reshape reshape_2 classificators_concat 2 ,"
"Reshape classificators_reshape 1 1 classificators_concat classificators 0 4 4 0 -1 1 1 1 ,"
"Concat regressors_concat 2 1 reshape_1 reshape_3 regressors_concat 2 ,"
"Permute regressors_permute 1 1 regressors_concat regressors 4 0 2 1 3 ,"_

**Comment by 1627180283** [comment]
What format is your pose model, onnx, caffe, or tensorflow? 
Could you give me original your pose model?

**Comment by 1627180283** [comment]
After opening the onnx model with netron, I didn't find the regression layer. It may be replaced by other operators when converted to onnx.

**Comment by 1627180283** [comment]
Is the output of onnx consistent with the output of the regression layer in pytorch？ If they are consistent, the regression layer  is replaced by other operations in onnx, you don't need to embed the regression layer into onnx model.

**Comment by 1627180283** [comment]
You can add the post-process code to your tnn project, after the tnn model is inferred.
If you want to embed the regression layer into the onnx-format model, you should embed the regression layer into Pytorch version model. Maybe you can use torch.max and torch.argmax to replace this part of post-process code.

**Comment by CheungBH** [comment]
> You can add the post-process code to your tnn project, after the tnn model is inferred. If you want to embed the regression layer into the onnx-format model, you should embed the regression layer into Pytorch version model. Maybe you can use torch.max and torch.argmax to replace this part of post-process code.

Thank you for your reply. I am currently clear about it.
