### ISSUE TITLE
TNN如何实现BiLSTM

### ISSUE THREAD

**Issue by float123** [Tencent/TNN#1353]
**1. 使用环境（environment）**
centos7.6 cuda10.1 torch 1.3.0 onnx 1.4.0

在crnn中使用了bilstm，为了转化为TNN模型，我将bilstm拆分为了两个lstm，一个正向传播，一个反向传播。其中反向传播的时候，将input进行倒序翻转，输入LSTM，然后将结果再倒序翻转，与正向传播的LSTM结果进行拼接，torch代码如下：
input_fw = input  # size=[128, 1, 256]
input_bw = torch.flip(input, [0])
recurrent_fw, _ = fw_LSTM(input_fw)
recurrent_bw, _ = bw_LSTM(input_bw)
recurrent_bw = torch.flip(recurrent_bw, [0])
recurrent = torch.cat((recurrent_fw, recurrent_bw), 2)

在导出为ONNX格式以及ONNX转TNN的步骤都没有问题，但是加载模型的时候会报错：
ERROR: 3: [network.cpp::addConstant::1053] Error Code 3: Internal Error (Parameter check failed at: optimizer/api/network.cpp::addConstant::1053, condition: allDimsGtEq(dimensions, 0))

经过研究，发现去掉torch.flip()就能完成模型加载，但是推理结果是错误的。
请问TNN是否支持flip算子？我需要如何修改，才能实现翻转功能，正确完成推理。

**Comment by 1627180283** [comment]
模型转换的时候在转换命令里加上 -align 可以成功转换吗？

**Comment by float123** [comment]
> 模型转换的时候在转换命令里加上 -align 可以成功转换吗？

加上 -align能成功转化为TNN模型，加载的时候同样会报ERROR: 3错误。
我尝试不拆分bilstm为两个lstm，直接把包含完整bilstm的crnn转化为onnx模型，然后转为TNN模型，发现能成功运行。但是还不确定结果是否正确
