### ISSUE TITLE
Are there any reference about the .tnnproto file?

### ISSUE THREAD

**Issue by NoLookDefense** [Tencent/TNN#1354]
BTW, are there any yolov3 demo?

**Comment by 1627180283** [comment]
This is the reference about the .tnnproto file:

1st line: "1 <blob_size> 1 <magic_num> ,"
2nd line: "input_name size n c h w date_type : input_name size n c h w data_type ... ,"
3rd line: all blobs  " <blob1> <blob2> ... ,"
4th line: "<output_blob1> <output_blob2> .., ,"
5th line: " <layer_count> ,"
each layer info
......
