### ISSUE TITLE
量化成功，模型推理直接报Segmentation fault

### ISSUE THREAD

**Issue by Xudoudou1996** [Tencent/TNN#1386]
**1. 环境（environment）**
 - Build OS and Version: Centos
 - RunTime OS Version: Linux

  **2. Github版本**
 - branch：master
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
使用pytorch->onnx->tnn，都没有报错，tnn模型正常运行，但是使用量化工具后再进行推理报Segmentation fault，在编译及量化的过程中没有任何错误。

量化命令为：
./quantization_cmd -p /data/tnn/TNN/model/sr/Tiny.opt.tnnproto -m /data/tnn/TNN/model/sr/Tiny.opt.tnnmodel -i /data/tnn/images/ -s 0.00392157,0.00392157,0.00392157 -o ./int8model

**Comment by seanxcwang** [comment]
![image](https://user-images.githubusercontent.com/66675860/140021525-95a17018-afb1-41ac-aa95-1e9a347a2675.png)
量化输入同时给了qunatconv和upsample
