### ISSUE TITLE
What method are you using for face alignment? Any reference paper?

### ISSUE THREAD

**Issue by wangziren1** [Tencent/TNN#1399]
Thank you for the wonderful work. 
I use your linux demo, and the face keypoints look like very accurate, are robust to large head pose and have good performace for the closed eyes. I see it uses two phase model. I want know what method are you using for face alignment? Any reference paper? Thank you.

**Comment by darrenyao87** [comment]
the model for face alignment is developed by tencent youtu lab，right now the original training code is not publically distributed。
