### ISSUE TITLE
使用example中分类模型demo，编译不了静态库

### ISSUE THREAD

**Issue by shadowwu1** [Tencent/TNN#1413]
**1. 环境（environment）**
 - Build OS and Version: Mac/Ubuntu/Centos/Windows
 - RunTime OS Version: Linux/Android/IOS
 - RunTime DEVICE: ARM/OPENCL/METAL
linux 交叉编译
  **2. Github版本**
 - branch：master
 - commit(optional):

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments):交叉编译，用的linux_aarch64下的build.sh

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
collect2:error:ld returned 1 exit status

  **6. 运行日志（runtime log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **7. 截图（Screenshots）**
 ```txt
 将截图粘贴在这里
 Paste screenshorts here or pastebin
 ```

**Comment by darrenyao87** [comment]
iOS或者Mac的库不支持交叉编译，目前只能在mac上编译，使用build_framework_ios.sh或者build_framework_macos.sh

**Comment by darrenyao87** [comment]
@quinnrong94 确认下linux下编译arm的脚本

**Comment by quinnrong94** [comment]
@shadowwu1 请用上述分支再尝试下。
