### ISSUE TITLE
se

### ISSUE THREAD

**Issue by GYxiaOH** [Tencent/TNN#145]
se模块中adaptiveavgpooling操作，转换成tnn后，tnn报错output dim is invalid。

**Comment by GYxiaOH** [comment]
刚才试了一下这个问题还没有解决。。。
/userdata/zhy/tnn/build_aarch64_linux/test # ./TNNTest -mp ../../../TNN-master/s
cripts/build_aarch64_linux/out/recslimmingsmall2tnn.opt.tnnproto -dt ARM
E/tnn: tnn::Status tnn::BaseLayer::Init(tnn::Context*, tnn::LayerParam*, tnn::LayerResource*, std::vector<tnn::Blob*>&, std::vector<tnn::Blob*>&, tnn::AbstractDevice*) [File /search/odin/xdrao/envs/813/TNN-master/source/tnn/layer/base_layer.cc][Line 59] Error: layer(752) output dims is invalid
E/tnn: virtual tnn::Status tnn::DefaultNetwork::InitLayers(tnn::NetStructure*, tnn::NetResource*) [File /search/odin/xdrao/envs/813/TNN-master/source/tnn/core/default_network.cc][Line 229] Error Init layer 752 (err: 12288 or 0x3000)
E/tnn: bool tnn::test::CheckResult(std::__cxx11::string, tnn::Status) [File /search/odin/xdrao/envs/813/TNN-master/test/test.cc][Line 309] create instance failed: code: 0x3000 msg: layer output dims is invalid

**Comment by gttiankai** [comment]
目前已经支持了带有 se 模块的模型。
