### ISSUE TITLE
TNN Reshape failed, Concat Layer Error

### ISSUE THREAD

**Issue by DefTruth** [Tencent/TNN#1464]
**1. 环境（environment）**
 - Build OS and Version: Mac
 - RunTime OS Version: Mac
 - RunTime DEVICE: CPU

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
在推理时，想使用动态维度，调用Reshape后报错。  目前调用instance->Reshape是会有什么限制吗？使用onnxruntime能正常使用动态维度。在转换成tnn时，使用了 --optimize -in input1:1,3,1024,1024 input2:1,1,1024,1024; 不调用Reshape，而是按照固定维度输入推，可以正常推理，只是效果变差。想调用instance->Reshape后进行动态维度推理，但是报以下错误。

  **6. 运行日志（runtime log）**
 ```txt
 将日志粘贴在这里
 ========================================
E/tnn: ConcatLayerCheckShape [File /xxx/third_party/library/TNN/source/tnn/layer/concat_layer.cc][Line 33] dim[2] not match (shape1:36, shape2:32)
E/tnn: InferOutputShape [File /xxx/library/TNN/source/tnn/layer/concat_layer.cc][Line 79] Error: ConcatLayer's (layer name: Concat_512) inputs can not be concatenated with axis=1
instance Reshape failed 
 ```

  **7. 截图（Screenshots）**
 ```txt
 将截图粘贴在这里
 Paste screenshorts here or pastebin
 ```

**Comment by 1627180283** [comment]
如果要使用动态维度推理，模型转换时不能使用 -optimize

**Comment by DefTruth** [comment]
好的，感谢

**Comment by DefTruth** [comment]
重新转换模型后，Reshape不会报错，但是instance->Forward()直接segmentation fault了。我用的onnx文件是动态维度的，在转换的tnn的时候指定-in input1:1,3,1024,1024 input2:1,1,1024,1024; 没有指定--optimize，这样有问题吗

**Comment by DefTruth** [comment]
依然是不Reshape的话是可以推的，Reshape通过了，但是推理出错了

**Comment by 1627180283** [comment]
方便提供一下 onnx 模型和 tnn 的 commit 吗

**Comment by DefTruth** [comment]
模型太大了，上传不了。感谢回复

**Comment by 1627180283** [comment]
> 模型太大了，上传不了。感谢回复

你可以试试 Reshape 设置的 shape 比模型转换时的小，看能不能解决这个问题
如果不能的话可以提供一个能够复现这个问题的简化模型（这个模型包含能够复现这个问题的最小单元）
