### ISSUE TITLE
caffe2tnn模型部分算子转换失败问题

### ISSUE THREAD

**Issue by zhangwei147258** [Tencent/TNN#149]
关于转换caffemodel的过程中发现如下问题：
1、Scale层的支持有问题
 caffe部分的转换代码，查看python源码关于Scale部分，仅支持biase为true的情况，对该处稍微调整下即可，写一个elif len(param_shape) == 1部分（或者对原caffe模型调整，Scale中bias原本为false的地方设置为true,修改caffemodel中对应bias的参数全部设置为0）；
2、Axpy层问题
本人实践在模型转换完成后，onnx模型保存出现了问题（由于公司内部管理问题，暂时无法提供模型）
注：在caffe转换代码中看到支持Axpy的转换，但是支持算子中未看到对该层的支持。

**Comment by gttiankai** [comment]
非常感谢反馈问题，我们确定下反馈问题。

**Comment by masterwan96** [comment]
1.关于Scale层的问题，在#171中更新了bias为false的情况，再次感谢您的反馈。
2.针对Apxy层，使用SENet模型尝试重现问题，未能成功重现问题。转换完成的模型时对齐的，且Apxy层的转换caffe2onnx是完全支持的。

**Comment by WilliamKyle** [comment]
https://github.com/Tencent/TNN/blob/3a7c05417b7e3aa614f25417a9a0bff03d00b6ae/tools/caffe2onnx/src/caffe2onnx.py#L932-L944


https://github.com/Tencent/TNN/blob/3a7c05417b7e3aa614f25417a9a0bff03d00b6ae/tools/caffe2onnx/src/OPs/Axpy.py#L52-L62


https://github.com/Tencent/TNN/blob/3a7c05417b7e3aa614f25417a9a0bff03d00b6ae/tools/caffe2onnx/src/OPs/Axpy.py#L70-L77


     new_output_name = [output_name[0] + "_mul"] 

     new_input_name = [node_name + "_mul", input_name[2]] 


这俩可能不对应，可能导致onnx模型保存出错。
