### ISSUE TITLE
caffe2tnn模型转换FCN 报错

### ISSUE THREAD

**Issue by masterwan96** [Tencent/TNN#150]
1.模型如下
[deploy_up.txt](https://github.com/Tencent/TNN/files/4868294/deploy_up.txt)
2.由于onnx版本更新，dropout层参数类型变化，无法过模型检测，但是onnxruntime支持老版本
3.解决办法为将caffe2onnx.py中的SaveOnnxModel(onnx_model, save_path, need_polish=True)中的ture 改为false，取消模型检测

**Comment by gttiankai** [comment]
1. 目前已经在docker 镜像中将onnx的版本固定住，所以不会再出现该问题，使用前请更新docker image
2. 如果自行安装onnx，请将onnx的版本固定为1.6.0.
