### ISSUE TITLE
遇到了未知错误：“RuntimeError: abort(Assertion failed: 0, at: /home/dev/files/repos/web-model-converter/third_party/TNN/tools/onnx2tnn/src/core/onnx_utility.cc,252,get_node_attr_af). Build with -s ASSERTIONS=1 for more info.”，可以尝试向 tnn 开发者反馈

### ISSUE THREAD

**Issue by linghugoogle** [Tencent/TNN#1504]
**1. 使用环境（environment）**
 - https://convertmodel.com/#outputFormat=tnn

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型转换失败（converter failed）
 - original model： ONNX
 - model：https://github.com/FongYoong/u2net-tfjs/tree/master/export/exported/onnx

  **4. 日志（Log）**
 ```txt
遇到了未知错误：“RuntimeError: abort(Assertion failed: 0, at: /home/dev/files/repos/web-model-converter/third_party/TNN/tools/onnx2tnn/src/core/onnx_utility.cc,252,get_node_attr_af). Build with -s ASSERTIONS=1 for more info.”，可以尝试向 tnn 开发者反馈
 ```

  **5. 截图（Screenshots）**
![image](https://user-images.githubusercontent.com/18373427/147853935-7eeb2beb-8874-425d-aa6d-a78917f6a551.png)

**Comment by gttiankai** [comment]
这个网页上的版本不一定是 tnn 转换工具最新版本，建议使用 tnn 最新版本的转换工具转换下。如果还有问题，可以提 issue；
