### ISSUE TITLE
coreml2onnx模型转换出错

### ISSUE THREAD

**Issue by psiydown** [Tencent/TNN#1506]
用最新的：https://github.com/AsuharietYgvar/TNN/blob/master/tools/onnx2tnn/onnx-coreml/coreml2onnx.py
Error: unsupported layer type: deconvolution  line 507 提示不支持反卷积类型，希望增强。
ValueError：cannot reshape array of size 10752 into shape (672,4)  line 415 需将4改为16，但不知这样改正确不？
最后line 527，line 531-533，check_model、inferred_model出错，期待解决，需要可联系pmsy@qq.com发模型你们测试，非常感谢！

**Comment by darrenyao87** [comment]
coreml2onnx是我们的一个测试工具，并没有正式对外，目前暂无计划继续完善，建议尝试其它工具如微软的ONNXMLTools或MMdnn
