### ISSUE TITLE
一个动态输入尺寸的onnx模型转换出错

### ISSUE THREAD

**Issue by TD-wzw** [Tencent/TNN#1533]
转换命令使用  python onnx2tnn.py input/inference.onnx -version=algo_version -half=0 -optimize=0 -o output/
<img width="773" alt="捕获" src="https://user-images.githubusercontent.com/57340568/150476943-2df51e93-4be2-4772-a815-3e0e055a172e.PNG">

**Comment by TD-wzw** [comment]
[inference.zip](https://github.com/Tencent/TNN/files/7910865/inference.zip)
模型在这里

**Comment by darrenyao87** [comment]
对于动态输入尺寸，转换模型的时候需要通过 -in 选项给定输入， 运行时需要改动尺寸的话，可以调用reshape接口。
 -in input_info [input_info ...]
                        specify the input name and shape of the model. e.g.,
                        -in input1_name:1,3,128,128 input2_name:1,3,256,256

你的模型用如下命令行测试通过
python3 converter.py onnx2tnn inference.onnx -in x:1,3,64,64
