### ISSUE TITLE
opencl fp16报错

### ISSUE THREAD

**Issue by nicheng0019** [Tencent/TNN#1539]
自己实现的一个三线性插值层，opencl代码如下：

`
#include "base.inc"

__kernel void TriLinear(GLOBAL_SIZE_3_DIMS __read_only image2d_t input,
                  __write_only image2d_t output, __global const FLOAT* lut, 
				  int dim, float binsize, int shift) {
    const int w                 = get_global_id(0);
    const int channel_block_idx = get_global_id(1);
    const int hb                = get_global_id(2);

	DEAL_NON_UNIFORM_DIM3(w, channel_block_idx, hb);
    const int width = global_size_dim0;
	
	const int pos = mad24(channel_block_idx, width, w);
    FLOAT4 in     = RI_F(input, SAMPLER, (int2)(pos, hb));
	
	FLOAT4 rgbbin = in / (FLOAT4)(binsize, binsize, binsize, binsize);
	
	int4 rgbid = convert_int4(floor(rgbbin));
	
	FLOAT4 rgbd = rgbbin - CONVERT_FLOAT4(rgbid);

	int id000 = rgbid.x + rgbid.y * dim + rgbid.z * dim * dim;
	int id100 = id000 + 1;
	int id010 = id000 + dim;
	int id110 = id010 + 1;
	int id001 = id000 + dim * dim;
	int id101 = id001 + 1;
	int id011 = id001 + dim;
	int id111 = id011 + 1;
	

	float rg_d = rgbd.x * rgbd.y;
	float rb_d = rgbd.x * rgbd.z;
	float gb_d = rgbd.y * rgbd.z;
	float rgb_d = rgbd.y * rgbd.z * rgbd.x;
	
	float w101 = rb_d - rgb_d;
	float w110 = rg_d - rgb_d;
	float w011 = gb_d - rgb_d;
	float w111 = rgb_d;	
	float w100 = rgbd.x - w101 - rg_d;
	float w010 = rgbd.y - w110 - gb_d;		
	float w001 = rgbd.z - w011 - rb_d;
	float w000 = 1 - (rgbd.x + rgbd.y ) + rg_d - w001;

	int xyindex = rgbid.x + rgbid.y * dim;
	
	int shift2 = shift << 1;
	FLOAT4 out = (FLOAT4)(w000 * lut[id000] + w100 * lut[id100] + 
                            w010 * lut[id010] + w110 * lut[id110] + 
                            w001 * lut[id001] + w101 * lut[id101] + 
                            w011 * lut[id011] + w111 * lut[id111],
							w000 * lut[id000 + shift] + w100 * lut[id100 + shift] + 
							w010 * lut[id010 + shift] + w110 * lut[id110 + shift] + 
							w001 * lut[id001 + shift] + w101 * lut[id101 + shift] + 
							w011 * lut[id011 + shift] + w111 * lut[id111 + shift],
							w000 * lut[id000 + shift2] + w100 * lut[id100 + shift2] + 
                            w010 * lut[id010 + shift2] + w110 * lut[id110 + shift2] + 
							w001 * lut[id001 + shift2] + w101 * lut[id101 + shift2] + 
							w011 * lut[id011 + shift2] + w111 * lut[id111 + shift2],
							0);
							
	WI_F(output, (int2)(pos, hb), out);
}
`

硬件：RK3399pro,，GPU：Mali-T860，使用PRECISION_HIGH （fp32）时结果正常，使用PRECISION_AUTO(fp16)时报错：
E/tnn: CopyScaleBiasToBuffer [File source/tnn/device/opencl/opencl_blob_converter.cc][Line 598] OpenCL ERROR CODE : -14 
E/tnn: CopyScaleBiasToBuffer [File source/tnn/device/opencl/opencl_blob_converter.cc][Line 605] OpenCL ERROR CODE : -14 
E/tnn: CopyBufferToMat [File source/tnn/device/opencl/opencl_utils.cc][Line 476] OpenCL ERROR CODE : -14 
E/tnn: GetOutputMat [File source/tnn/core/instance.cc][Line 307] output_blob_convert.ConvertFromMat Error: code: 0xA009 msg: OpenCL enqueueReadBuffer failed

图像输入分辨率为1280x720x3，TNN是0.3.0版本。

**Comment by nicheng0019** [comment]
> @nicheng0019 您好，我最近的项目刚好也要用这个三线性插值层，但是我目前遇到了一些问题，请问你可以提供一下这个.cl的完整实现吗？想借鉴一下，谢谢~

#include "base.inc"

__kernel void TriLinear(GLOBAL_SIZE_3_DIMS __read_only image2d_t input,
                  __write_only image2d_t output, __global const FLOAT* lut, 
				  int dim, float binsize, int shift) {
    const int w                 = get_global_id(0);
    const int channel_block_idx = get_global_id(1);
    const int hb                = get_global_id(2);

    DEAL_NON_UNIFORM_DIM3(w, channel_block_idx, hb);
    const int width = global_size_dim0;
	
    const int pos = mad24(channel_block_idx, width, w);
    FLOAT4 in     = RI_F(input, SAMPLER, (int2)(pos, hb));
	
    FLOAT4 rgbbin = in / (FLOAT4)(binsize, binsize, binsize, binsize);
	
    int4 rgbid = convert_int4(floor(rgbbin));
	
    FLOAT4 rgbd = rgbbin - CONVERT_FLOAT4(rgbid);

    int id000 = rgbid.x + rgbid.y * dim + rgbid.z * dim * dim;
    int id100 = id000 + 1;
    int id010 = id000 + dim;
    int id110 = id010 + 1;
    int id001 = id000 + dim * dim;
    int id101 = id001 + 1;
    int id011 = id001 + dim;
    int id111 = id011 + 1;
	

    float rg_d = rgbd.x * rgbd.y;
    float rb_d = rgbd.x * rgbd.z;
    float gb_d = rgbd.y * rgbd.z;
    float rgb_d = rgbd.y * rgbd.z * rgbd.x;
	
    float w101 = rb_d - rgb_d;
    float w110 = rg_d - rgb_d;
    float w011 = gb_d - rgb_d;
    float w111 = rgb_d;	
    float w100 = rgbd.x - w101 - rg_d;
    float w010 = rgbd.y - w110 - gb_d;		
    float w001 = rgbd.z - w011 - rb_d;
    float w000 = 1 - (rgbd.x + rgbd.y ) + rg_d - w001;

    int xyindex = rgbid.x + rgbid.y * dim;
    int shift2 = shift << 1;
	
    FLOAT4 out = 0;
    if(id000 < shift)
    {
        out += (FLOAT4)(w000 * lut[id000], w000 * lut[id000 + shift],w000 * lut[id000 + shift2], 0);
    }
 
    if (id100 < shift)
    {
        out += (FLOAT4)(w100 * lut[id100], w100 * lut[id100 + shift],w100 * lut[id100 + shift2], 0);
    }
	
    if (id001 < shift)
    {
        out += (FLOAT4)(w001 * lut[id001], w001 * lut[id001 + shift],w001 * lut[id001 + shift2], 0);
    }
	
    if (id010 < shift)
    {
        out += (FLOAT4)(w010 * lut[id010], w010 * lut[id010 + shift],w010 * lut[id010 + shift2], 0);
    }
	
    if (id011 < shift)
    {
        out += (FLOAT4)(w011 * lut[id011], w011 * lut[id011 + shift],w011 * lut[id011 + shift2], 0);
    }
	
    if (id101 < shift)
    {
        out += (FLOAT4)(w101 * lut[id101], w101 * lut[id101 + shift],w101 * lut[id101 + shift2], 0);
    }
	
    if (id110 < shift)
    {
        out += (FLOAT4)(w110 * lut[id110], w110 * lut[id110 + shift],w110 * lut[id110 + shift2], 0);
    }
      
    if (id111 < shift)
    {
        out += (FLOAT4)(w111 * lut[id111], w111 * lut[id111 + shift],w111 * lut[id111 + shift2], 0);
    }
							
    WI_F(output, (int2)(pos, hb), out);
}


__kernel void TriLinear_image(GLOBAL_SIZE_3_DIMS __read_only image2d_t input,
                  __write_only image2d_t output, __read_only image2d_t lut, 
				  int dim, float binsize, int shift)
{
    const int w                 = get_global_id(0);
    const int channel_block_idx = get_global_id(1);
    const int hb                = get_global_id(2);

    DEAL_NON_UNIFORM_DIM3(w, channel_block_idx, hb);
    const int width = global_size_dim0;
	
    const int pos = mad24(channel_block_idx, width, w);
    FLOAT4 in     = RI_F(input, SAMPLER, (int2)(pos, hb));
	
    FLOAT4 rgbbin = in / (FLOAT4)(binsize, binsize, binsize, binsize);
	
    int4 rgbid = convert_int4(floor(rgbbin));
	
    FLOAT4 rgbd = rgbbin - CONVERT_FLOAT4(rgbid);

    FLOAT rg_d = rgbd.x * rgbd.y;
    FLOAT rb_d = rgbd.x * rgbd.z;
    FLOAT gb_d = rgbd.y * rgbd.z;
    FLOAT rgb_d = rgbd.y * rgbd.z * rgbd.x;

    FLOAT w101 = rb_d - rgb_d;
    FLOAT w110 = rg_d - rgb_d;
    FLOAT w011 = gb_d - rgb_d;
    FLOAT w111 = rgb_d;	
    FLOAT w100 = rgbd.x - w101 - rg_d;
    FLOAT w010 = rgbd.y - w110 - gb_d;		
    FLOAT w001 = rgbd.z - w011 - rb_d;
    FLOAT w000 = 1 - (rgbd.x + rgbd.y ) + rg_d - w001;
	
    int xyindex = rgbid.x + rgbid.y * dim;
    FLOAT4 out = w000 * RI_F(lut, SAMPLER, (int2)(xyindex, rgbid.z)) +
		w100 * RI_F(lut, SAMPLER, (int2)(xyindex + 1, rgbid.z)) + 
		w010 * RI_F(lut, SAMPLER, (int2)(xyindex + dim, rgbid.z)) +
		w110 * RI_F(lut, SAMPLER, (int2)(xyindex + dim + 1, rgbid.z)) +
		w001 * RI_F(lut, SAMPLER, (int2)(xyindex, rgbid.z + 1)) + 
		w101 * RI_F(lut, SAMPLER, (int2)(xyindex + 1, rgbid.z + 1)) +
		w011 * RI_F(lut, SAMPLER, (int2)(xyindex + dim, rgbid.z + 1)) +
		w111 * RI_F(lut, SAMPLER, (int2)(xyindex + dim + 1, rgbid.z + 1));
	
    WI_F(output, (int2)(pos, hb), out);									  
}


lut 是look-up table，这两个实现分别是把lut 用float buffer和image2d_t 存储，TNN的代码也要修改一下。
希望能帮到你。

**Comment by wsycl** [comment]
非常感谢🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nicheng0019 ***@***.***&gt;
发送时间: 2022年6月10日 15:45
收件人: Tencent/TNN ***@***.***&gt;
抄送: wsycl ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Tencent/TNN] opencl fp16报错 (Issue #1539)





  
@nicheng0019 您好，我最近的项目刚好也要用这个三线性插值层，但是我目前遇到了一些问题，请问你可以提供一下这个.cl的完整实现吗？想借鉴一下，谢谢~
  
#include "base.inc"
 
__kernel void TriLinear(GLOBAL_SIZE_3_DIMS __read_only image2d_t input,
 __write_only image2d_t output, __global const FLOAT* lut,
 int dim, float binsize, int shift) {
 const int w                 = get_global_id(0);
 const int channel_block_idx = get_global_id(1);
 const int hb                = get_global_id(2);
 DEAL_NON_UNIFORM_DIM3(w, channel_block_idx, hb); const int width = global_size_dim0; const int pos = mad24(channel_block_idx, width, w); FLOAT4 in     = RI_F(input, SAMPLER, (int2)(pos, hb)); FLOAT4 rgbbin = in / (FLOAT4)(binsize, binsize, binsize, binsize); int4 rgbid = convert_int4(floor(rgbbin)); FLOAT4 rgbd = rgbbin - CONVERT_FLOAT4(rgbid); int id000 = rgbid.x + rgbid.y * dim + rgbid.z * dim * dim; int id100 = id000 + 1; int id010 = id000 + dim; int id110 = id010 + 1; int id001 = id000 + dim * dim; int id101 = id001 + 1; int id011 = id001 + dim; int id111 = id011 + 1; float rg_d = rgbd.x * rgbd.y; float rb_d = rgbd.x * rgbd.z; float gb_d = rgbd.y * rgbd.z; float rgb_d = rgbd.y * rgbd.z * rgbd.x; float w101 = rb_d - rgb_d; float w110 = rg_d - rgb_d; float w011 = gb_d - rgb_d; float w111 = rgb_d; float w100 = rgbd.x - w101 - rg_d; float w010 = rgbd.y - w110 - gb_d; float w001 = rgbd.z - w011 - rb_d; float w000 = 1 - (rgbd.x + rgbd.y ) + rg_d - w001; int xyindex = rgbid.x + rgbid.y * dim; int shift2 = shift << 1; FLOAT4 out = 0; if(id000 < shift) {     out += (FLOAT4)(w000 * lut[id000], w000 * lut[id000 + shift],w000 * lut[id000 + shift2], 0); } if (id100 < shift) {     out += (FLOAT4)(w100 * lut[id100], w100 * lut[id100 + shift],w100 * lut[id100 + shift2], 0); } if (id001 < shift) {     out += (FLOAT4)(w001 * lut[id001], w001 * lut[id001 + shift],w001 * lut[id001 + shift2], 0); } if (id010 < shift) {     out += (FLOAT4)(w010 * lut[id010], w010 * lut[id010 + shift],w010 * lut[id010 + shift2], 0); } if (id011 < shift) {     out += (FLOAT4)(w011 * lut[id011], w011 * lut[id011 + shift],w011 * lut[id011 + shift2], 0); } if (id101 < shift) {     out += (FLOAT4)(w101 * lut[id101], w101 * lut[id101 + shift],w101 * lut[id101 + shift2], 0); } if (id110 < shift) {     out += (FLOAT4)(w110 * lut[id110], w110 * lut[id110 + shift],w110 * lut[id110 + shift2], 0); }    if (id111 < shift) {     out += (FLOAT4)(w111 * lut[id111], w111 * lut[id111 + shift],w111 * lut[id111 + shift2], 0); } WI_F(output, (int2)(pos, hb), out);  
}
 
__kernel void TriLinear_image(GLOBAL_SIZE_3_DIMS __read_only image2d_t input,
 __write_only image2d_t output, __read_only image2d_t lut,
 int dim, float binsize, int shift)
 {
 const int w                 = get_global_id(0);
 const int channel_block_idx = get_global_id(1);
 const int hb                = get_global_id(2);
 DEAL_NON_UNIFORM_DIM3(w, channel_block_idx, hb); const int width = global_size_dim0; const int pos = mad24(channel_block_idx, width, w); FLOAT4 in     = RI_F(input, SAMPLER, (int2)(pos, hb)); FLOAT4 rgbbin = in / (FLOAT4)(binsize, binsize, binsize, binsize); int4 rgbid = convert_int4(floor(rgbbin)); FLOAT4 rgbd = rgbbin - CONVERT_FLOAT4(rgbid); FLOAT rg_d = rgbd.x * rgbd.y; FLOAT rb_d = rgbd.x * rgbd.z; FLOAT gb_d = rgbd.y * rgbd.z; FLOAT rgb_d = rgbd.y * rgbd.z * rgbd.x; FLOAT w101 = rb_d - rgb_d; FLOAT w110 = rg_d - rgb_d; FLOAT w011 = gb_d - rgb_d; FLOAT w111 = rgb_d; FLOAT w100 = rgbd.x - w101 - rg_d; FLOAT w010 = rgbd.y - w110 - gb_d; FLOAT w001 = rgbd.z - w011 - rb_d; FLOAT w000 = 1 - (rgbd.x + rgbd.y ) + rg_d - w001; int xyindex = rgbid.x + rgbid.y * dim; FLOAT4 out = w000 * RI_F(lut, SAMPLER, (int2)(xyindex, rgbid.z)) + w100 * RI_F(lut, SAMPLER, (int2)(xyindex + 1, rgbid.z)) +  w010 * RI_F(lut, SAMPLER, (int2)(xyindex + dim, rgbid.z)) + w110 * RI_F(lut, SAMPLER, (int2)(xyindex + dim + 1, rgbid.z)) + w001 * RI_F(lut, SAMPLER, (int2)(xyindex, rgbid.z + 1)) +  w101 * RI_F(lut, SAMPLER, (int2)(xyindex + 1, rgbid.z + 1)) + w011 * RI_F(lut, SAMPLER, (int2)(xyindex + dim, rgbid.z + 1)) + w111 * RI_F(lut, SAMPLER, (int2)(xyindex + dim + 1, rgbid.z + 1)); WI_F(output, (int2)(pos, hb), out);    
}
 
lut 是look-up table，这两个实现分别是把lut 用float buffer和image2d_t 存储，TNN的代码也要修改一下。
 希望能帮到你。
