### ISSUE TITLE
amlogic a311d NPU MODEL INFERENCE 

### ISSUE THREAD

**Issue by 2050airobert** [Tencent/TNN#1542]
**Is your feature request related to a problem? Please describe.**

I do not know if  TNN could suppport the cnn model running on the platform of amlogic a311d?
Is there any NPU driver for this platform? 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chenglinlv** [comment]
anybody here？
TNN is just the upgrade version of ncnn with the same underlying principle and method? "NCNN could not work with NPU" means TNN could not also, right?

**Comment by darrenyao87** [comment]
If amlogic is arm or X86 based chip, then it is support, however we don't hava any amlogic device to test. So if you have any problem when depolying TNN on amlogic device, welcome to open issue again with detailed descrption
