### ISSUE TITLE
iOS benchmark工程能打印Profiling Data吗，比如层信息、耗时？

### ISSUE THREAD

**Issue by Smeegol** [Tencent/TNN#1575]
iOS benchmark工程能打印Profiling Data吗？目前看安卓可以，期望像安卓benchmark工程一样，多谢！
https://github.com/Tencent/TNN/blob/master/doc/cn/development/profiling.md
![68747470733a2f2f67697465652e636f6d2f64617272656e33642f746e6e2d7265736f757263652f7261772f6d61737465722f646f632f636e2f646576656c6f706d656e742f7265736f757263652f6f70656e636c5f70726f66696c696e672e6a7067](https://user-images.githubusercontent.com/1212201/157586865-07997b66-3141-454d-a9fa-24ab084f99b8.jpeg)

**Comment by darrenyao87** [comment]
@Smeegol 
tnn/core/macro.h中29hang，把宏TNN_PROFILE的默认值从0改为1即可。

**Comment by darrenyao87** [comment]
@Smeegol 
补充说明，iOS中需要设置两个地方：
1. tnn/core/macro.h中29行，把宏TNN_PROFILE的默认值从0改为1
2. BenchmarkController.mm中306行profile_layer_time变量设置为true
