### ISSUE TITLE
macOS M1上tnn的性能和onnxruntime 相差多大？

### ISSUE THREAD

**Issue by jinfagang** [Tencent/TNN#1576]
macOS M1上tnn的性能和onnxruntime 相差多大？

**Comment by zhiqwang** [comment]
盲猜是 TNN 快，ONNX Runtime 似乎还没发布正式的的 ARM 版本推理。

**Comment by jinfagang** [comment]
但是我看tnn mac下只有x84版本呢

**Comment by zhiqwang** [comment]
https://github.com/pytorch/pytorch/issues/47702#issuecomment-1064636064

>  [YOLOv5](https://github.com/ultralytics/yolov5) inference (but not training) is currently supported on Apple M1 neural engine. Results show 13X speedup vs CPU. Results reported on benchmarks run today 11 March 2022 on a 2020 M1 Macbook Air --batch-size 1 --imgsz 640:

<!DOCTYPE html><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; caret-color: rgb(36, 41, 47); color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">YOLOv5<span class="Apple-converted-space"> </span><g-emoji class="g-emoji" alias="rocket" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f680.png" style="box-sizing: border-box; display: inline-block; min-width: 1ch; font-family: &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 1.25em; font-weight: 400; line-height: 1; vertical-align: -0.075em; font-style: normal !important;">🚀</g-emoji><span class="Apple-converted-space"> </span>v6.1-25-gcaf7ad0 torch 1.11.0 CPU</p>

YOLOv5s | inference time640x640 image bs1
-- | --
PyTorch 1.11.0 | 344 ms
CoreML 5.2.0 | 27 ms

<br class="Apple-interchange-newline">

**Comment by gttiankai** [comment]
@jinfagang 在 mac m1 上你可以打开 ARM 的编译宏，然后就可以在 m1 上使用 arm 机型推理。至于具体的性能，你可以使用自己的模型试下。
