### ISSUE TITLE
how to build macOS with corml on M1 arm?

### ISSUE THREAD

**Issue by jinfagang** [Tencent/TNN#1584]
how to build macOS with corml on M1 arm?

**Comment by nicklezheng** [comment]
I have problems while build using scripts\build_macos.sh on M1 macbook pro:

scripts/build_macos/openvinoInstallShared/deployment_tools/inference_engine/lib**/intel64/**plugins.xml: No such file or directory

"intel64" is for intel chip mac.
I found "arm64" under "openvinoInstallShared/deployment_tools/inference_engine/lib/"

I think we should modfiy build_macos.sh to distinguish intel64 or arm64.

By the way, i wonder what difference between "build_macos.sh" and "build_macos_native.sh" under scripts dir

**Comment by jinfagang** [comment]
I know there is a build_macos_aarch64.sh to build on M1, but the code can not pass building https://github.com/Tencent/TNN/issues/1589

**Comment by nicklezheng** [comment]
> I know there is a build_macos_aarch64.sh to build on M1, but the code can not pass building #1589

thanks for reminding, i can build with 'build_macos_aarch64.sh' successfully on my 14-inch M1 Macbook pro.

**Comment by jinfagang** [comment]
@nicklezheng did u met the problem I mentioned above?

**Comment by nicklezheng** [comment]
> @nicklezheng did u met the problem I mentioned above?


I have met similar problem like your problem mentioned in #1589 while doing cross compile
see this: [#1588 multiple definition between c code and assembly code](https://github.com/Tencent/TNN/issues/1588#issuecomment-1069043186)

I suggest you remove the conflicting code in `gemm_function.cc`

**Comment by jinfagang** [comment]
@nicklezheng what do u mean cross compile? I just compile on arm M1 Mac native get into that error. Editing the code seems not a good way to do, the tnn author should pay some attention to this issue unless they have a more proper way to build on arm m1 Mac

**Comment by nicklezheng** [comment]
> what do u mean cross compile? I just compile on arm M1 Mac native get into that error. Editing the code seems not a good way to do, the tnn author should pay some attention to this issue unless they have a more proper way to build on arm m1 Mac

I cross compile for some ARM chip embedded linux system.
yeah, I agree with you that editing the code is not perfect way.

**Comment by nicklezheng** [comment]
I meet same problem mentioned in  #1589 after update macOS from 12.1 to 12.2

**Comment by ruichaowang** [comment]
> 

Hi, 
Did you successfuly compiled the TNN on M1 mac？
I am facing the same issues.

and by the way. 
where did you get this "build_macos_aarch64.sh" file

Thanks!

**Comment by jinfagang** [comment]
@ruichaowang I switched to mnn, mnn is great.

**Comment by ruichaowang** [comment]
> @ruichaowang I switched to mnn, mnn is great.

Okay, I will have a look!

**Comment by Smeegol** [comment]
遇到同样的问题。我也是在M1 Mac上编译build_aarch_macos.sh，TNN维护者都没有复现出来吗？不用在Linux上交叉编译，直接在M1 [Mac上编译，必定报错，跟 #1589 一样。
