### ISSUE TITLE
模型初始化，调用CreateInst方法失败

### ISSUE THREAD

**Issue by KevinZ-718** [Tencent/TNN#1586]
**1. 环境（environment）**
 - Build OS and Version: Mac
 - RunTime OS Version: IOS
 - RunTime DEVICE: ARM

  **2. Github版本**
 - branch：master

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments):default

  **4. 编译日志(build log)**

  **5. 详细描述bug 情况 (Describe the bug)**
模型初始化，调用CreateInst方法失败

  **6. 运行日志（runtime log）**
 ```
benchmark(5967,0x1030f4580) malloc: Heap corruption detected, free list is damaged at 0x282f080e0
*** Incorrect guard value: 4518879885114728832
benchmark(5967,0x1030f4580) malloc: *** set a breakpoint in malloc_error_break to debug
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/usr/lib/libMTLCapture.dylib
benchmark(5967,0x1030f4580) malloc: Heap corruption detected, free list is damaged at 0x282f080e0
*** Incorrect guard value: 4518879885114728832
 ```

  **7. 截图（Screenshots）**

**Comment by darrenyao87** [comment]
@KevinZ-718 Mac上测试iOS建议按文档直接使用benchmark的Xcode工程，而不是走cmake。https://github.com/Tencent/TNN/blob/master/doc/cn/development/profiling.md
