### ISSUE TITLE
macOS aarc64 源码编译失败

### ISSUE THREAD

**Issue by jinfagang** [Tencent/TNN#1589]
<img width="889" alt="image" src="https://user-images.githubusercontent.com/21303438/158185183-8063b306-28d6-4871-994e-aad45fa45472.png">

**Comment by Smeegol** [comment]
遇到同样的问题。我也是在M1 Mac上编译build_aarch_macos.sh，TNN维护者都没有复现出来吗？不用在Linux上交叉编译，直接在M1 Mac上编译，必定报上面的错误。

**Comment by jinfagang** [comment]
我已放弃，mnn is all you need.

**Comment by Smeegol** [comment]
@jinfagang 已经成功了 #1713

**Comment by jinfagang** [comment]
你最终还是会选择mnn
