### ISSUE TITLE
run IOS TNNExamples demo always fail

### ISSUE THREAD

**Issue by lmq5294249** [Tencent/TNN#1611]
**1. 环境（environment）**
 - RunTime OS Version: IOS

run TNNExamples demo

I have checked the added model,it‘s OK.But it is also failure

  **5. 详细描述bug 情况 (Describe the bug)**
E/tnn: InterpretModel [File /Users/lin/Desktop/TNN-master/source/tnn/interpreter/tnn/model_interpreter.cc][Line 426] tnnmodel is invalid, maybe you should upgrade TNN
E/tnn: Init [File /Users/lin/Desktop/TNN-master/examples/base/tnn_sdk_sample.cc][Line 573] instance.net init failed 163852022-03-31 13:50:34.390600+0800 TNNExamples[39963:6684736] Error: code: 0x4001 msg: Error: model is illegal

**Comment by darrenyao87** [comment]
@lmq5294249 参见https://github.com/Tencent/TNN/issues/1702。
肯定是tnnmodel文件下载出的问题，建议直接git clone https://github.com/darrenyao87/tnn-models，这个耗时比较久，或者github网页上找到对应model原文件点击Download下载。
