### ISSUE TITLE
change the dimension in model forward function in nlp

### ISSUE THREAD

**Issue by jianbofrank** [Tencent/TNN#1622]
![image](https://user-images.githubusercontent.com/44988544/162369283-6df763f3-9c57-4ebe-b2fc-63bb4ed13b39.png)
the question is very simple , when I expend the shape of x from [256,64,1] to [256,64,9], I can transform pytorch model to onnx and tnn successfully,  but get error when loading the tnn model in Android Studio. I get the NULL return to the instance.

**Comment by gttiankai** [comment]
please upload your ONNX mode first！

**Comment by darrenyao87** [comment]
you should upload the error log which usually describes the details

**Comment by darrenyao87** [comment]
We test your code with branch master 20220628，it shows nothing wrong. could you please upload yout onnx model
