### ISSUE TITLE
padding function 在nlp 中的问题。

### ISSUE THREAD

**Issue by jianbofrank** [Tencent/TNN#1623]
![image](https://user-images.githubusercontent.com/44988544/162415251-af84dea1-2d3c-438c-a1ce-641e742445d1.png)
请问一下 这个F.padding 函数 使用完，发现模型转tnn 成功了，但是在Android studio 中load 模型的时候失败了，返回空，显示 layer CONCAT 这个地方报错，然后 就直接跳槽，返回空 并赋值给 instance。

**Comment by darrenyao87** [comment]
![1656246633441](https://user-images.githubusercontent.com/62542779/175814227-d0ebf610-e899-4396-8f8a-234b62e43f9f.jpg)
按照你的代码，我们生成模型后测试时通过的，模型转换工具显示对齐，没有发现问题。
