### ISSUE TITLE
as_strided function 在nlp 应用中的问题

### ISSUE THREAD

**Issue by jianbofrank** [Tencent/TNN#1624]
![image](https://user-images.githubusercontent.com/44988544/162417630-779b0c12-5150-437a-bb3e-843c128959e5.png)
请问一下 这个as_strided 函数 使用完，发现模型转tnn 成功了，但是在Android studio 中load 模型的时候失败了，返回空，显示 layer CONCAT 这个地方报错，然后 就直接跳槽，返回空 并赋值给 instance。

**Comment by darrenyao87** [comment]
ONNX export failed on ATen operator as_strided because torch.onnx.symbolic_opset11.as_strided does not exist.
We suggest using tensor slice opration like [:, :, 0:128]
