### ISSUE TITLE
改变维度导致tnn load 模型发生错误

### ISSUE THREAD

**Issue by jianbofrank** [Tencent/TNN#1625]
![image](https://user-images.githubusercontent.com/44988544/162418018-69f07e49-dd9b-4d36-ac91-adfd4a17c1a5.png)
请问一下，这里就是简单的改变一下 原有x的维度， 这个模型转tnn 成功了，没有报错，但是 Android studio 读模型的时间 instance 返回分的是空，也是load 模型时候其中有算子有问题，请问怎么解决呢

**Comment by darrenyao87** [comment]
我们用mater20220637的代码按照你上面的模型代码进行了测试，显示正常。麻烦你重新测试下，如果还是有问题，辛苦上传下模型文件，并注明输入是否是可变维度的，谢谢
