### ISSUE TITLE
Cross-platform compile error

### ISSUE THREAD

**Issue by mike-2020** [Tencent/TNN#1664]
x86 (Ubuntu 20.04)上跨平台编译arm，出现大量类似下面的编译错误：

/usr/lib/gcc-cross/arm-linux-gnueabihf/9/../../../../arm-linux-gnueabihf/bin/ld: error: libTNN.so.0.3.0.0 uses VFP register arguments, source/tnn/device/arm/CMakeFiles/TNNArm.dir/arm_util.cc.o does not

**Comment by quinnrong94** [comment]
@mike-2020 对于该编译器，可以关闭-mfloat-abi=softfp选项，解决链接中出现的问题
