### ISSUE TITLE
MatMul算子错误

### ISSUE THREAD

**Issue by TD-wzw** [Tencent/TNN#1666]
ubuntu18.04 
git clone TNN最新节点的代码
模型转化能成功
运行代码初始化网络时错误
Error Init layer MatMul_1 (err: 4096 or 0x1000)

**Comment by darrenyao87** [comment]
运行在ARM上还是OPENCL上？另外能否提供测试模型

**Comment by TD-wzw** [comment]
在x86上，模型是paddleocrv3的识别模型
[rec-sim.zip](https://github.com/Tencent/TNN/files/8850548/rec-sim.zip)

**Comment by darrenyao87** [comment]
@Maosquerade 模型在iOS用device arm、metal and apple NPU.测试正常，你检查下X86.
