### ISSUE TITLE
怎么实现TNN输入为（8,3,224,224）的推理？

### ISSUE THREAD

**Issue by FinnSu** [Tencent/TNN#1667]
你好，我想确认下TNN的input mat的dims设置为{8,3,224,224}可以正常推理吗？
unsigned char *rgbaData = new unsigned char[height * width * 3 * 8];
TNN_NS::DeviceType dt = TNN_NS::DEVICE_ARM;
TNN_NS::DimsVector input_dims = {8, 3, width, height};
auto input_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC3, input_dims, rgbaData);
我是这么写的，不确定对不对，还有一点需要确认的是rgbaData数据的填充是堆叠8个图片的数据吗？
麻烦知道的同学可以评论下，提前谢谢了~

**Comment by darrenyao87** [comment]
目前TNN暂时不支持batch的图片输入，考虑到移动端上性能和内存问题，暂时也不建议采用batch。如果一定要用batch，需要自行转float并用nchw的格式进行传入。
