### ISSUE TITLE
cpu、gpu正常推理，Apple NPU 报错

### ISSUE THREAD

**Issue by minushuang** [Tencent/TNN#1668]
**1. 环境（environment）**
 - Build OS and Version: MAC
 - RunTime OS Version: IOS
 - RunTime DEVICE: Apple NPU

  **2. Github版本**
 - branch：master
 - commit(optional):

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
跑demo当中的图像人脸检测的项目，cpu、gpu都可以正常推理，切换到npu时，程序挂掉。截图如下

  **7. 截图（Screenshots）**
![60091653536522_ pic](https://user-images.githubusercontent.com/5811852/170411559-e82615b8-a045-4c38-9108-a40044e7a1ff.jpg)

**Comment by teslawho** [comment]
https://github.com/Tencent/TNN/tree/dev_metal_ngray  bug 在这个分支修复了，可以尝试一下

**Comment by minushuang** [comment]
ok，可以了，谢谢。
