### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by sunbinbin1991** [Tencent/TNN#1669]
https://github.com/Tencent/TNN/blob/ca24e91429f8e89d8dc2f55663bf723df1bef29f/doc/en/user/demo_en.md?plain=1#L259

it seems readme need update, this file is not found when build linux

**Comment by darrenyao87** [comment]
@seanxcwang 确认下

**Comment by seanxcwang** [comment]
> https://github.com/Tencent/TNN/blob/ca24e91429f8e89d8dc2f55663bf723df1bef29f/doc/en/user/demo_en.md?plain=1#L259
> 
> it seems readme need update, this file is not found when build linux

编译脚本执行了吗，执行后才会生成这个目录
