### ISSUE TITLE
onnx模型转换报错

### ISSUE THREAD

**Issue by CallMeEricChiu** [Tencent/TNN#167]
报错内容如下：
const node = Constant_279
const node = Constant_281
const node = Constant_282
const node = Constant_283
const node = Constant_287
python3: /opt/TNN/tools/onnx2tnn/src/core/layer/onnx_converter_reduce.cc:34: virtual std::__cxx11::string OnnxConverterReduce::TNNLayerParam(onnx::NodeProto&, OnnxNetInfo&): Assertion `0' failed.
Aborted (core dumped)

converter ONNX to TNN model failed!
Conversion to  tnn failed :(

--------------------------------------
请问大佬这报错是什么原因。。。不知道是不是pth转onnx问题。
网络结构是bisenetv2(单输入多输出)，.pth和.onnx文件连接：https://drive.google.com/drive/folders/1znAJS95Un49-OhV8topmuDb6lO2Ehjpz?usp=sharing
网络结构：
![image](https://user-images.githubusercontent.com/51788361/86990405-17359500-c1cf-11ea-855c-dbe6e2a87c34.png)

**Comment by 1627180283** [comment]
Hello，你的模型里面 reducemean 算子的 axes 的维度是 2，这种情况 TNN 暂时还不支持，你可以把他拆成两个算子再进行转换
![image](https://user-images.githubusercontent.com/37806708/87006992-1c590b00-c1f4-11ea-900c-4729ba930d8f.png)

**Comment by CallMeEricChiu** [comment]
@1627180283  soga,感谢大佬

**Comment by CallMeEricChiu** [comment]
> Hello，你的模型里面 reducemean 算子的 axes 的维度是 2，这种情况 TNN 暂时还不支持，你可以把他拆成两个算子再进行转换
> ![image](https://user-images.githubusercontent.com/37806708/87006992-1c590b00-c1f4-11ea-900c-4729ba930d8f.png)

@1627180283 
大佬，上面问题已经解决了，但是又出现了如下报错，这又是什么原因呢o(╥﹏╥)o
const node = Constant_215
const node = Constant_216
const node = Constant_220
python3: /opt/TNN/tools/onnx2tnn/src/core/onnx_utility.cc:119: std::vector<long int> get_node_attr_ai(const onnx::NodeProto&, const char*, const OnnxNetInfo&, int): Assertion `0' failed.
Aborted (core dumped)

converter ONNX to TNN model failed!

Conversion to  tnn failed :(

**Comment by CallMeEricChiu** [comment]
群里已经问了，解决了感谢

**Comment by xchen13** [comment]
> 群里已经问了，解决了感谢

所以是如何解决的呢？
