### ISSUE TITLE
X86 带openvino下编译，使用时报错无法解析外部符号

### ISSUE THREAD

**Issue by wuyong139** [Tencent/TNN#1680]
环境：windows
方式1：使用build_msvc.bat编译生成的带openvino的lib文件和dll文件
方式2：直接下载release, tnn-v0.3.0-windows.zip
使用VS2019，导入include和lib包，使用win32编译，会报错一堆无法解析外部符号。
使用x64编译则不会报错。
请问在使用openvino的情况下，不支持win32的编译么？

**Comment by seanxcwang** [comment]
openvino不支持32位

**Comment by seanxcwang** [comment]
openvino不支持32位

**Comment by wuyong139** [comment]
好的，谢谢啦
