### ISSUE TITLE
pytorch  op  nn.LayerNorm  is supported?

### ISSUE THREAD

**Issue by henbucuoshanghai** [Tencent/TNN#1689]
tks

**Comment by darrenyao87** [comment]
layernorm已经支持，example里面有用tiny-bert做阅读理解的demo，这个模型里就有layernorm

**Comment by henbucuoshanghai** [comment]
tks,i see.
 from timm.models.layers import DropPath, to_2tuple, trunc_normal_
others like timm or einops is supported?
