### ISSUE TITLE
windows网页转换onnx模型到TNN报错

### ISSUE THREAD

**Issue by QuinnCoder** [Tencent/TNN#1690]
[windows网页转换onnx模型到TNN报错](https://convertmodel.com/#outputFormat=tnn)

  详细描述bug 情况 (Describe the bug)
遇到了未知错误：“RuntimeError: abort(Assertion failed: 0, at: /home/dev/files/repos/web-model-converter/third_party/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc,314,TNNWriteProto). Build with -s ASSERTIONS=1 for more info.”，可以尝试向 tnn 开发者反馈

模型上传链接: https://pan.baidu.com/s/1424E9JCgX3pJG_myNHI4ZA 提取码: mzxk 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by 1627180283** [comment]
网页转换工具暂时没有更新，可以尝试 TNN 提供的 docker 镜像或者本地编译模型转换工具

**Comment by QuinnCoder** [comment]
@1627180283 谢谢，已经本地部署编译转换成功啦
