### ISSUE TITLE
iOS sample运行报错 

### ISSUE THREAD

**Issue by fredmouse** [Tencent/TNN#1702]
刚入坑。成功跑起ios sample。但是model list里基本上摄像头相关的类目点击进去都无法启动，都在CreateInst这边报错了。具体如下
<img width="1270" alt="截屏2022-06-28 下午9 20 12" src="https://user-images.githubusercontent.com/16265185/176189238-10de74e9-c2aa-45ab-b69a-bad0aa3fc803.png">
图

查看了，模型文件都在，路径有获得。
不知道有碰到过类似问题的吗？不知道如何解决，多谢各位大神帮忙解答！

**Comment by darrenyao87** [comment]
请问你是在真机上测试的么？手机型号是？我这边测试了下是可以的？

**Comment by darrenyao87** [comment]
@fredmouse

**Comment by fredmouse** [comment]
是在真机上测试的，手机是iphone xr 操作系统版本是13.5.1。不过经过你提醒，我换了一台iphone X 版本15.5，可以运行。大概估计和操作系统有关？

**Comment by darrenyao87** [comment]
iphonex可以，按理讲iphonexr在硬件上应该没问题。那就只有操作系统的原因了。我们自测下，到时候有可能需要找你验证，谢谢

**Comment by fredmouse** [comment]
好的 没问题。另外虽然iphone x跑起来了，但是有些选项还是处理不了模型的情况，如下
<img width="418" alt="截屏2022-06-29 下午1 46 27" src="https://user-images.githubusercontent.com/16265185/176360871-2eb6e9cf-0229-492b-a751-bc384de79482.png">
：

**Comment by darrenyao87** [comment]
@fredmouse ，你用的是branch master分支么？
另外看了下上面XR手机的错误截图，应该是进camera人脸检测出问题，帮忙看下demo列表里面第一个-图像类的人脸检测是否一样有问题？如果有报错的话，也辛苦截图下。

**Comment by fredmouse** [comment]
@darrenyao87  是branch master。前面几个图像类的都没有问题，的确是camera检测这块 包括物体检测。

**Comment by darrenyao87** [comment]
@fredmouse model is illegal这种错误和手机型号以及系统版本无关，你先把模型都删除，用download_model.sh下载的最新模型看看。我们这边用Xs还没复现你上面的两个问题。

**Comment by fredmouse** [comment]
@darrenyao87 我们用download_model.sh下载模型一直失败。所以我用的是你这的模型https://github.com/darrenyao87/tnn-models。但是还是解析错误

**Comment by fredmouse** [comment]
我们总结了一下。有这么两种情况，如果用tnn-models/master/model里的模型，解析模型会有问题，所有的项目都不能用包括图片类的（说我们工程好像太老要升级，但我们用的是最新的branch master)。我们在其他来源找的第三方的模型文件（估计也是之前从tnn-models/master/model里收集来的）就可以解析，图片类的没有问题。但是涉及到摄像头类的就有第二个问题，也就是上面最早提出的问题，模型解析没问题。
[model.zip](https://github.com/Tencent/TNN/files/9015850/model.zip)

**Comment by darrenyao87** [comment]
@fredmouse 看了下你的模型tnnmodel文件都有问题，以blazeface.tnnmodel为例，文件大小都只有131字节，实际文件是408KB。所以肯定是tnnmodel文件下载出的问题，建议直接git clone https://github.com/darrenyao87/tnn-models，这个耗时比较久，或者github网页上找到对应model原文件点击Download下载。

**Comment by darrenyao87** [comment]
@fredmouse 确认下模型按照上面说的下载后是否还有model is illegal的问题？

**Comment by fredmouse** [comment]
我们现在用git clone重新拉了整个项目并且用下载脚本下载了模型文件，现在都能运行。但是用git clone拉tnn-models/master/model的模型文件，出来的文件大小仍然不符合实际，运行解析失败。

**Comment by darrenyao87** [comment]
@fredmouse 好的，这个issue我close了，多谢。
