### ISSUE TITLE
[OP]支持算子Swish和groupnorm

### ISSUE THREAD

**Issue by darrenyao87** [Tencent/TNN#1707]
20220704master上已经实现cpu版本的groupnorm和swish算子，需要添加arm、x86、opencl、metal、coreml、cuda等实现。
onnx模型如下，转模型时，需要注释掉onnx2tnn_fuse_swish.cc文件28行和onnx2tnn_fuse_group_normalization.cc文件176行中的return 0语句，让转模型成功。正确的tnn模型也在zip文件中。
[groupnorm.zip](https://github.com/Tencent/TNN/files/9038735/groupnorm.zip)

**Comment by darrenyao87** [comment]
@Maosquerade X86 @quinnrong94 arm @teslawho metal 和 coreml @1627180283 opencl
swish是个激活函数，需要有单独实现，同时需要在卷积里面也支持，类似relu

**Comment by 1627180283** [comment]
opencl 实现已经提交到 dev_groupnorm 分支

**Comment by Maosquerade** [comment]
x86 实现已提交到 dev_groupnorm 分支
