### ISSUE TITLE
tnn 是否支持动态输入

### ISSUE THREAD

**Issue by shengdewu** [Tencent/TNN#1710]
抱歉打扰了，请问目前tnn支持动态输入吗？

在文档中  https://github.com/Tencent/TNN/blob/master/doc/en/user/convert_en.md#how-to-create-a-tnn-model 的 -optimize 选项提到了动态输入，但是找不到具体例子。

**Comment by darrenyao87** [comment]
对于动态输入的模型，转模型时候不要用-optimize选项，运行时调用instance的Reshape接口调整大小。TNN自带的OCR的Demo里输入就是动态的，可以参考ocr_text_recognizer.cc中ProcessSDKInputMat的处理。
