### ISSUE TITLE
Unsupported data format for device acc: Transpose input or reshape output

### ISSUE THREAD

**Issue by HankYe** [Tencent/TNN#1737]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu 20.04
 - RunTime OS Version: Android
 - RunTime DEVICE: OPENCL

  **2. Github版本**
 - branch：master
 - commit(optional):

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)
ABI="arm64-v8a"
STL="c++_static"
PROFILING="OFF"
CLEAN=""
DEVICE_TYPE=""
INPUT_DATA_TYPE=0
MODEL_TYPE=TNN
USE_NCNN_MODEL=0
KERNEL_TUNE="-et"
THREAD_NUM=1
ADB=adb
BENCHMARK_TYPE="APP"
BENCHMARK_APP_DIR=benchmark_app/benchmark/

WORK_DIR=`pwd`
BENCHMARK_MODEL_DIR=$WORK_DIR/../benchmark-model
BUILD_DIR=build
BUILD_APP_DIR=build_app
ANDROID_DIR=/data/local/tmp/tnn-benchmark
ANDROID_DATA_DIR=$ANDROID_DIR/benchmark-model
OUTPUT_LOG_FILE=benchmark_models_result.txt
LOOP_COUNT=16
WARM_UP_COUNT=5
INTERVAL=5

benchmark_model_list=(
	mtinet.opt.tnnproto
)
  **4. 编译日志(build log)**
 E/tnn: tnn::Status tnn::OpenCLLayerAcc::CheckBlob(const std::vector<Blob *> &, const std::vector<Blob *> &) [File /home/mzz/TNN/source/tnn/device/opencl/acc/opencl_layer_acc.cc][Line 451] Resolve Layer(Transpose_962)-Input Blob(2475) Data Format(0) failed
E/tnn: virtual tnn::Status tnn::OpenCLPermuteLayerAcc::Reshape(const std::vector<Blob *> &, const std::vector<Blob *> &) [File /home/mzz/TNN/source/tnn/device/opencl/acc/opencl_permute_layer_acc.cc][Line 103] code: 0x9004 msg: unsupported data format for device acc
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/mzz/TNN/test/test.cc][Line 338] create instance failed: code: 0x9004 msg: unsupported data format for device acc 
/data/local/tmp/tnn-benchmark/benchmark_models_result.txt: 1 file pulled, 0 skipped. 21.7 MB/s (111508 bytes in 0.005s)
ZTE A2020N2 Pro

benchmark device: OPENCL 

I/tnn: tnn::Status tnn::OpenCLRuntime::Init() [File /home/mzz/TNN/source/tnn/device/opencl/opencl_runtime.cc][Line 120] OpenCL version: CL_TARGET_OPENCL_VERSION 200   CL_HPP_TARGET_OPENCL_VERSION 110   CL_HPP_MINIMUM_OPENCL_VERSION 110
I/tnn: tnn::Status tnn::OpenCLRuntime::Init() [File /home/mzz/TNN/source/tnn/device/opencl/opencl_runtime.cc][Line 155] Create common opencl context

Fri Jul 22 14:08:00 CST 2022

  **5. 详细描述bug 情况 (Describe the bug)**
Resolve Layer(Transpose_962)-Input Blob(2475) Data Format(0) failed
![image](https://user-images.githubusercontent.com/39550579/180379199-f2a1827b-6e51-48ce-bf3d-863f1b8b15f6.png)

  **6. bug所在模型代码**
![image](https://user-images.githubusercontent.com/39550579/180378843-5a0301b3-b705-4d03-82c4-da7562160eae.png)

**7. tnnproto**
![image](https://user-images.githubusercontent.com/39550579/180379894-868b48f8-049e-4e79-ba5c-a4ebefb19c50.png)

**Comment by HankYe** [comment]
试了很多种调整方式，依然绕不开data format的问题，不知道是什么原因

**Comment by 1627180283** [comment]
方便提供一下 tnn 模型吗，我们复现一下这个问题看看

**Comment by HankYe** [comment]
模型压缩在附件里了，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/TNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月23日(星期六) 下午3:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/TNN] Unsupported data format for device acc: Transpose input or reshape output (Issue #1737)





 
方便提供一下 tnn 模型吗，我们复现一下这个问题看看
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

mtinet.zip (60.74M, 2022年08月22日 15:31 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0e386661184600c511a965ef10660616530003530352030c1c085252034b0000545c4b00545701140109505007540609540b5705366c34544551080442484e5041385b&code=18fa6f49

**Comment by 1627180283** [comment]
我这边使用附件里的模型没有复现这个问题，看了一下模型结构，和 issue 里提到的有点不太一样，辛苦确认一下模型
附件里的模型，softmax 的 axis 大于了 3，目前 tnn 暂时不支持，需要把维度压缩一下

**Comment by 1627180283** [comment]
你好，这里还有问题吗

**Comment by 1627180283** [comment]
issue 长时间不活跃先关闭了，如果有需要可以重新打开
