### ISSUE TITLE
LSTMONNX 

### ISSUE THREAD

**Issue by jolt2017** [Tencent/TNN#1740]
1. 你好，我自己训练的 crnn 模型，pytorch 转 ncnn 可以正常识别，但是转tnn 模型时，LSTMONNX 算子却出现问题了，转换工具用的是官方 docker.奇怪的是，比较官方 tnn模型和自己转换的 tnn 模型，发现 demo中 LSTMONNX 算子6个输入，我自己转的只有一个输入，请问是转换工具的问题么？ 附上 onnx，tnn 相关文件.

**Comment by darrenyao87** [comment]
重复问题 [](https://github.com/Tencent/TNN/issues/1741)

**Comment by darrenyao87** [comment]
https://github.com/Tencent/TNN/issues/1741
