### ISSUE TITLE
LSTMONNX

### ISSUE THREAD

**Issue by jolt2017** [Tencent/TNN#1741]
**1. 使用环境（environment）**
 - OS: Ubuntu
 - OS Version:

  **2. Github版本**
 - branch：latest
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type:  模型转换失败（converter failed） 
                      模型不对齐（model misalignment）
 - original model： ONNX 
PS：
你好，我自己训练的 crnn 模型，pytorch 转 ncnn 可以正常识别，但是转tnn 模型时，LSTMONNX 算子却出现问题了，转换工具用的是官方 docker.奇怪的是，比较官方 tnn模型和自己转换的 tnn 模型，发现 demo中 LSTMONNX 算子6个输入，我自己转的只有一个输入，请问是转换工具的问题么？ 附上 onnx，tnn 相关文件.

**Comment by jolt2017** [comment]
上传不了文件..

**Comment by darrenyao87** [comment]
@jolt2017 zip后上传

**Comment by jolt2017** [comment]
你好，zip 后还是不行，我放网盘里了，麻烦你取下，谢谢.
链接：https://pan.baidu.com/s/1OpAMhDAd62ItXec1bisBCw 
提取码：53sn

**Comment by jolt2017** [comment]
你好，找到问题了，pth 转 onnx 后，不能进行 simplify,直接用docker 转换工具转换成 tnn model就行了。这里感觉后面 tnn要做下优化吧.
