### ISSUE TITLE
请问一下测速时为什么卡住了呢

### ISSUE THREAD

**Issue by wmkai** [Tencent/TNN#1766]
测速后就一直卡在这里了，<img width="605" alt="image" src="https://user-images.githubusercontent.com/39148461/184338631-8e56654b-cda7-4d5d-b685-37b25af46ba0.png">

**Comment by 1627180283** [comment]
可以在测速命令里加上 -bs 看一下

**Comment by wmkai** [comment]
可以停止了 不过啥都不显示
<img width="782" alt="image" src="https://user-images.githubusercontent.com/39148461/184617073-9f57f6c9-31aa-4cbd-b9a8-a7bab7c9bc23.png">
<img width="611" alt="image" src="https://user-images.githubusercontent.com/39148461/184617119-41317745-930c-4768-ae17-f78ae2e9ead1.png">

**Comment by 1627180283** [comment]
应该是程序段错误挂掉了，可以附上模型，我们后续排查一下

**Comment by wmkai** [comment]
感谢
[topformer-tiny448.zip](https://github.com/Tencent/TNN/files/9351630/topformer-tiny448.zip)

**Comment by wmkai** [comment]
你好，请问一下 我使用TNN代码库中提供的示例mobilenet_v2.tnnproto在小米10上测速，得到结果：
09-07 02:42:28.868 9097 9097 I tnn : void tnn::test::Timer::Print() [File test/timer.cc][Line 60] mobilenet_v2.tnnproto - ARM TNN Benchmark time cost: min = 32.450 ms | max = 34.163 ms | avg = 32.981 ms
09-07 02:42:38.035 9455 9455 I tnn : void tnn::test::Timer::Print() [File test/timer.cc][Line 60] mobilenet_v2.tnnproto - OPENCL TNN Benchmark time cost: min = 6.851 ms | max = 7.584 ms | avg = 7.202 ms
请问这个耗时是正常的吗
