### ISSUE TITLE
TNN 支持导出pytorch的opset16的算子

### ISSUE THREAD

**Issue by liuyingbin123** [Tencent/TNN#1770]
**Is your feature request related to a problem? Please describe.**
pytorch导出gridsample算子需要指定opset16，但是tnn在转换时报错不支持opset16.

**Describe the solution you'd like**
支持opset16的导出

**Describe alternatives you've considered**

**Additional context**

**Comment by 1627180283** [comment]
方便提供一下报错的详细信息吗

**Comment by liuyingbin123** [comment]
不好意思，我用最新的tnn可以了，之前不行是用的几个月前的版本。
