### ISSUE TITLE
error::op convert failed onnx:GRU

### ISSUE THREAD

**Issue by tianyashu2020** [Tencent/TNN#1777]
**1. 使用环境（environment）**
 - OS: Ubuntu
 - OS Version:18.04

Aborted when I tried to converrt a onnx model to tnn model,error occured，the flowlling is the report：

the cmd line is： python3 onnx2tnn.py ./ncnn_test0623.onnx  -version 1.0  -optimize 0 -o ./

could anybody help me？

root@ubuntu:/home/shuqinjun/TNN/tools/onnx2tnn/onnx-converter# python3 onnx2tnn.py ./ncnn_test0623.onnx  -version 1.0  -optimize 0  -o ./ 
0.----onnx version:1.6.0
algo_optimize 0
onnx_net_opt_path /home/shuqinjun/TNN/tools/onnx2tnn/onnx-converter/ncnn_test0623.onnx
2.----onnx2tnn: /home/shuqinjun/TNN/tools/onnx2tnn/onnx-converter/ncnn_test0623.onnx
E/tnn: onnx2tnn_convert [File tools/onnx2tnn/onnx-converter/onnx2tnn_convert.cc][Line 153] The input_info 
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = bn0.weight
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = bn0.bias
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = bn0.running_mean
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = bn0.running_var
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = conv2.depthwise_conv.weight
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = conv2.depthwise_conv.bias
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = conv3.depthwise_conv.weight
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = conv3.depthwise_conv.bias
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = conv4.depthwise_conv.weight
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = conv4.depthwise_conv.bias
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = FGRU.trans.weight
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = FGRU.trans.bias
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = FGRU.norm.weight
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = FGRU.norm.bias
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = FGRU.norm.running_mean
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = FGRU.norm.running_var
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = TGRU.trans.weight
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = TGRU.trans.bias
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = TGRU.norm.weight
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = TGRU.norm.bias
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = TGRU.norm.running_mean
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = TGRU.norm.running_var
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = deconv1.depthwise_conv.weight
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = deconv1.depthwise_conv.bias
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = deconv2.depthwise_conv.weight
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = deconv2.depthwise_conv.bias
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = deconv3.depthwise_conv.weight
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = deconv3.depthwise_conv.bias
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = deconv4.transposeconv.weight
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = deconv4.transposeconv.bias
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = mask_est.0.weight
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = mask_est.0.bias
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_283
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_284
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_286
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_287
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_289
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_290
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_292
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_293
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_295
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_296
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_298
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_299
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_301
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Conv_302
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::GRU_343
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::GRU_344
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::GRU_345
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Concat_346
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Concat_347
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Concat_348
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Concat_349
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Concat_350
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::GRU_368
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::GRU_369
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::GRU_370
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Concat_371
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Concat_372
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 388] weight = onnx::Concat_373
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 438] const node to initialize = Constant_17
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 438] const node to initialize = Constant_22
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 438] const node to initialize = Constant_33
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 438] const node to initialize = Constant_40
D/tnn: OnnxExtractBlobWeights [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 438] const node to initialize = Constant_57
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 173] name :onnx::Reshape_132
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 173] name :onnx::Reshape_182
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 173] name :onnx::Reshape_202
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 175] input 1 name:onnx::Reshape_202 is not weight
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 173] name :onnx::Reshape_213
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 175] input 1 name:onnx::Reshape_213 is not weight
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 173] name :onnx::Reshape_258
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 175] input 1 name:onnx::Reshape_258 is not weight
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 173] name :onnx::Reshape_132
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 173] name :onnx::Reshape_182
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 173] name :onnx::Reshape_202
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 175] input 1 name:onnx::Reshape_202 is not weight
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 173] name :onnx::Reshape_213
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 175] input 1 name:onnx::Reshape_213 is not weight
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 173] name :onnx::Reshape_258
D/tnn: get_node_attr_ai [File tools/onnx2tnn/src/core/onnx_utility.cc][Line 175] input 1 name:onnx::Reshape_258 is not weight
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 247] input_blob_shape dim_size: 3
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 247] input_blob_shape dim_size: 3
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 247] input_blob_shape dim_size: 3
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:onnx::Unsqueeze_111 onnx:Transpose -> tnn:Permute
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:onnx::Transpose_112 onnx:Unsqueeze -> tnn:Unsqueeze
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:input onnx:Transpose -> tnn:Permute
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:onnx::Transpose_114 onnx:BatchNormalization -> tnn:BatchNormCxx
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:input.3 onnx:Transpose -> tnn:Permute
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:input.11 onnx:Conv -> tnn:Convolution
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:input.15 onnx:Relu -> tnn:ReLU
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:input.19 onnx:Conv -> tnn:Convolution
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:input.27 onnx:Conv -> tnn:Convolution
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:input.31 onnx:Relu -> tnn:ReLU
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:input.35 onnx:Conv -> tnn:Convolution
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:input.43 onnx:Conv -> tnn:Convolution
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:input.47 onnx:Relu -> tnn:ReLU
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:input.51 onnx:Conv -> tnn:Convolution
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:input.59 onnx:Conv -> tnn:Convolution
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:onnx::Transpose_130 onnx:Relu -> tnn:ReLU
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:onnx::Reshape_131 onnx:Transpose -> tnn:Permute
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:input.63 onnx:Reshape -> tnn:Reshape
D/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 330] node:onnx::GRU_134 onnx:Transpose -> tnn:Permute
E/tnn: TNNWriteProto [File tools/onnx2tnn/src/core/onnx2tnn.cc][Line 326] error::op convert failed onnx:GRU
python3: /home/shuqinjun/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc:327: int Onnx2TNN::TNNWriteProto(): Assertion `0' failed.
Aborted (core dumped)

**Comment by 1627180283** [comment]
目前 TNN 还不支持 GRU 算子

**Comment by tianyashu2020** [comment]
> 目前 TNN 还不支持 GRU 算子

好的，多谢
