### ISSUE TITLE
ONNX模型转tnn失败

### ISSUE THREAD

**Issue by shiyutang** [Tencent/TNN#1797]
**1. 使用环境（environment）**
 - OS: Centos
 - OS Version: 7

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type:模型转换失败（converter failed）
 - original model：PaddlePaddle -》 onnx
 （如果可以的话，请上传原始的模型文件）
模型文件：https://github.com/shiyutang/files/raw/main/mobileseg_mobilenetv3_ade20k_512x512_160k_model.onnx

  **4. 日志（Log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 截图（Screenshots）**
<img width="1436" alt="90b097ad46334eb11be890fba6587f14" src="https://user-images.githubusercontent.com/34859558/193034411-ba5aab78-1eb3-4e70-bdde-a8d94832e1af.png">

**Comment by 1627180283** [comment]
可以在转换命令里加上 -debug 打印出详细日志看一下

**Comment by shiyutang** [comment]
增加选项之后日志如下：[mobilenetv3.log](https://github.com/Tencent/TNN/files/9738836/mobilenetv3.log)

**Comment by shiyutang** [comment]
我发现增加了pooling代码均会存在，转tnn时与上面相同的错误：D/tnn: get_node_attr_ai [File /opt/TNN/tpython3: /opt/TNN/tools/onnx2tnn/src/core/layer/onnx_converter_pool.cc:132: virtual std::__cxx11::string OnnxOpConverterPool::TNNLayerParam(onnx::NodeProto&, OnnxNetInfo&): Assertion `0' failed.  查看代码之后发现是pooling的pads.size落在不支持的范畴：
<img width="810" alt="5c3b118fe4432dd0417b600c77b3c70f" src="https://user-images.githubusercontent.com/34859558/194741628-4a5235e5-2103-4af7-8a4d-2ad8fb0c0f2c.png">

目前转模型会错误的代码示例如下，不知道能否如何修改pool参数，使其能成功被tnn支持？
<img width="478" alt="f8eab23692f8fc38980717736608264b" src="https://user-images.githubusercontent.com/34859558/194741660-acf403c6-a404-4dd6-a301-61bc7d0dcddb.png">

<img width="597" alt="84a9536473990a7f8ef1da6edb75e112" src="https://user-images.githubusercontent.com/34859558/194741666-f70549de-badc-4ba4-b8c5-b33781fad2de.png">

**Comment by 1627180283** [comment]
可以把 AdaptiveAvgPool 换成 AvgPool，同时显式的设置 kernel size 和 padding 看看

**Comment by 1627180283** [comment]
issue 长时间没有回复，先关闭了，如果有需要的话可以再打开
