### ISSUE TITLE
使用opencl后，模型推理速度变慢了/The model foward speed become slower when use DEVICE_OPENCL

### ISSUE THREAD

**Issue by wwdok** [Tencent/TNN#1808]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu
 - RunTime OS Version: Android
 - RunTime DEVICE: ARM

  **2. Github版本**
 - branch：最新版
 - commit(optional):

  **5. 详细描述bug 情况 (Describe the bug)**

我对比测试了float32的模型和量化的模型，发现速度反而下降了，前向推理耗时从18毫秒变成了23毫秒
有兴趣的可以用这些模型自己测试一下：[models.zip](https://github.com/Tencent/TNN/files/9837162/models.zip)

**Comment by henbucuoshanghai** [comment]
量化?how?

**Comment by henbucuoshanghai** [comment]
那换一个flops和parms更少的模型，一定比目前的快？
