### ISSUE TITLE
无法转成fp16格式/ fail to convert the model to fp16 format

### ISSUE THREAD

**Issue by wwdok** [Tencent/TNN#1809]
**1. 使用环境（environment）**
 - OS: Docker

  **2. Github版本**
 - branch：lastest
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 编译问题（Build failed）/ 模型转换失败（converter failed）/ 模型不对齐（model misalignment）
 - original model： Caffe/ONNX/TensorFlow/TensorFlowLite 
 （如果可以的话，请上传原始的模型文件）
我明明在转换命令里指定-half了，生成的模型还是float32格式：
![image](https://user-images.githubusercontent.com/43233772/197167542-7c201322-a00a-4150-9961-3221fb103389.png)

  **5. 截图（Screenshots）**
![image](https://user-images.githubusercontent.com/43233772/197167260-4b56db1d-cd5a-4bce-81c4-f6c465ff136b.png)

**Comment by 1627180283** [comment]
可以确认一下 tnn 模型大小是不是 onnx 模型的一半
