### ISSUE TITLE
Mac及iOS上结束推理并释放TNN后，内存未清干净，有残留

### ISSUE THREAD

**Issue by Smeegol** [Tencent/TNN#1817]
**1. 环境（environment）**
 - Build OS and Version: Mac
 - RunTime OS Version: Mac/IOS
 - RunTime DEVICE: METAL

  **2. Github版本**
 - branch：master
 - commit(optional): 最新

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
结束推理并释放TNN后，对比初始状态，内存清不干净，有残留。使用Instruments工具又没有检测到内存泄漏情况。这是Mac上的测试效果，iOS上也存在一样的问题，用的是Metal后端

  **6. 运行日志（runtime log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **7. 截图（Screenshots）**
![5F0D3B0E9E68F9FBA813A3209E71C116](https://user-images.githubusercontent.com/1212201/200277657-f5dc24dd-1842-4051-bb37-161620294bf7.jpg)

**Comment by darrenyao87** [comment]
![企业微信截图_0f564f2d-3bcd-4962-b2ce-49caf3e489fd](https://user-images.githubusercontent.com/62542779/223047457-002c8be0-8f53-44cf-be24-ab1dfbb0d275.png)
I test it with tnn example ultra fast face detector, the instrument shows no memory leak. If it has a leak, you can run it again and again, the memory will go up. try it
