### ISSUE TITLE
git cloine TNN, down laod model error  .why?

### ISSUE THREAD

**Issue by henbucuoshanghai** [Tencent/TNN#1827]
sh download_model.sh 
.
downloading version-slim-320_simplified.tnnproto ...
download_model.sh: 10: status: not found
download version-slim-320_simplified.tnnproto failed
download_model.sh: 14: return: Illegal number: -1

**Comment by andWhatShouldISay** [comment]
if (( status == 200 ))  

should be

if [$status -eq 200]

**Comment by darrenyao87** [comment]
you can download tnn models from the link below
https://www.aliyundrive.com/s/MSmarP3zqrb
