### ISSUE TITLE
使用opencl做infer结果与arm版本不一致

### ISSUE THREAD

**Issue by uestc-buddy** [Tencent/TNN#183]
这里使用ndk-build（20.1.5948944）分别编译arm和opencl版本的程序（使用的模型为deeplabv3，pytorch->onnx->tnnmodel无错），arm版本输出结果正常，opencl版本结果（fp16/fp32）就不对了，使用的代码来自：https://github.com/Tencent/TNN/tree/master/examples/android/demo/src/main/jni/cc/tnn_lib.cc

**Comment by shaundai-tencent** [comment]
是有精度误差，还是说结果完全不对？

**Comment by Zdahap** [comment]
> 这里使用ndk-build（20.1.5948944）分别编译arm和opencl版本的程序（使用的模型为deeplabv3，pytorch->onnx->tnnmodel无错），arm版本输出结果正常，opencl版本结果（fp16/fp32）就不对了，使用的代码来自：https://github.com/Tencent/TNN/tree/master/examples/android/demo/src/main/jni/cc/tnn_lib.cc

看tnn_lib.cc，应该是没有将数据传给gpu导致的问题。试一下CopyToDevice和CopyFromDevice？

**Comment by uestc-buddy** [comment]
> 是有精度误差，还是说结果完全不对？

是完全不对，输出的值是全0的，可能是拷贝的时候出问题了，我按照CopyToDevice和CopyFromDevice试试看看

**Comment by uestc-buddy** [comment]
> > 这里使用ndk-build（20.1.5948944）分别编译arm和opencl版本的程序（使用的模型为deeplabv3，pytorch->onnx->tnnmodel无错），arm版本输出结果正常，opencl版本结果（fp16/fp32）就不对了，使用的代码来自：https://github.com/Tencent/TNN/tree/master/examples/android/demo/src/main/jni/cc/tnn_lib.cc
> 
> 看tnn_lib.cc，应该是没有将数据传给gpu导致的问题。试一下CopyToDevice和CopyFromDevice？

好的，谢谢回复，我试一下您说的方法

**Comment by uestc-buddy** [comment]
问题确实是cpu数据没有传入导致，现在已经解决。有一个需要注意的是数据预处理的cl kernel中scale和bias是float4类型，尽管输入的图片channel为3也要将scale/bias大小设置为4

**Comment by weixiaolian21** [comment]
> 问题确实是cpu数据没有传入导致，现在已经解决。有一个需要注意的是数据预处理的cl kernel中scale和bias是float4类型，尽管输入的图片channel为3也要将scale/bias大小设置为4

请问怎么解决的 我也遇到了同样的问题 模型在pc端cpu和opencl都运行正常, 在arm的cpu上也正常, 在arm的opencl上结果就不对.

**Comment by banbishan** [comment]
我也遇到了同样的问题 模型在pc端cpu和opencl都运行正常, 在arm的cpu上也正常, 在arm的opencl上结果就不对
