### ISSUE TITLE
linux/x86/build_linux_native.sh 编译失败，已经修复了也编译成功，在这里提示下

### ISSUE THREAD

**Issue by private1215** [Tencent/TNN#1833]
**1. 使用环境（environment）**
 - OS: Ubuntu
 - OS Version: 22.04.1 LTS

  **2. Github版本**
 - branch：master
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 编译问题（Build failed）
 - original model： 官方模型（https://www.aliyundrive.com/s/MSmarP3zqrb）
 - desc： 直接clone master主分支，开始时参照[文档编译](https://github.com/Tencent/TNN/blob/master/doc/en/user/demo_en.md#iii-introduction-to-linuxmacwindowsarmlinuxcudalinux-demo)，配置好opencv3.4.13后，在example/linux/x86/build_linux_native.sh编译报错，后查看example/linux/x86/CMakeLists.txt中是find_package(OpenCV 4 ```REQUIRED)，于是配置了opencv4.6.0，再次编译依旧报错，然后仔细查看报错，搜了一下，[参考此处](https://blog.csdn.net/Quner6/article/details/117639223)，在base/tnn_sdk_sample.cc中添加`#include <iomanip>`后编译成功

  **4. 日志（Log）**
 ```txt
 /TNN/examples/base/tnn_sdk_sample.cc: In member function ‘std::string tnn::BenchResult::Description()’:
/TNN/examples/base/tnn_sdk_sample.cc:309:32: error: ‘setprecision’ is not a member of ‘std’
  309 |     ostr << std::fixed << std::setprecision(2) << "min = " << min << "  max = " << max << "  avg = " << avg;
      |                                ^~~~~~~~~~~~
[ 78%] Building CXX object CMakeFiles/demo_x86_imageclassify.dir/TNN/examples/base/utils/utils.cc.o
make[2]: *** [CMakeFiles/demo_x86_imageclassify.dir/build.make:398: CMakeFiles/demo_x86_imageclassify.dir/TNN/examples/base/tnn_sdk_sample.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/demo_x86_imageclassify.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
 Paste log here or pastebin
 ```

  **5. 截图（Screenshots）**
![image](https://user-images.githubusercontent.com/16433674/203210471-011c0122-ed18-4687-aca5-2be0c3f5d2bf.png)

**Comment by gttiankai** [comment]
fix pr: https://github.com/Tencent/TNN/pull/1853
