### ISSUE TITLE
hand_landmark_full.tflite 转换失败 

### ISSUE THREAD

**Issue by AlbertLarry** [Tencent/TNN#1836]
**1. 使用环境（environment）**
 - OS: Mac/Docker
 - OS Version:

  **2. Github版本**
 - branch：master
 - commit(optional):809d00096d7a5841512f3c11b3ea64870bd51449

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type:  模型转换失败（converter failed）
 - original model： TensorFlowLite 
 
[tfmodel.zip](https://github.com/Tencent/TNN/files/10111840/tfmodel.zip)

  **4. 日志（Log）**
 ```
Oh No, tflite2tnn failed :(
 ```

**Comment by 1627180283** [comment]
模型转换命令里可以加上 -debug 看一下

**Comment by AlbertLarry** [comment]
TNN/tools/convert2tnn/bin/TnnConverter -mt TFLITE  -mp 
TNN/tools/convert2tnn/hand_landmark_full.tflite -od /Users/larry/github/face/TNN/tools/convert2tnn//

E/tnn: Convert2Tnn [File tools/converter/source/tflite/tflite_converter.cc][Line 115] The TFLiteConverter do not support layer:model_1/model/batch_normalization/FusedBatchNormV3_dequantize

E/tnn: Convert2Tnn [File tools/converter/source/tflite/tflite_converter.cc][Line 117] The unsupported operator type is:DEQUANTIZE

E/tnn: Run [File tools/converter/source/tnn_converter.cc][Line 55] Converter: converter TNN/tools/convert2tnn/hand_landmark_full.tflite failed!


Oh No, tflite2tnn failed :(

**Comment by 1627180283** [comment]
DEQUANTIZE 这个算子目前还不支持

**Comment by 1627180283** [comment]
可以尝试一下非量化的 mobilenet v2，resnet50 之类的模型。
支持的算子列表可以参考一下 tools/converter/source/tflite 这个目录下的代码文件。
