### ISSUE TITLE
onnx转TNN的过程中model_check没过

### ISSUE THREAD

**Issue by JeaShining** [Tencent/TNN#1845]
这是转换命令，使用的docker:
python3 onnx2tnn.py /workspace/swin_v2_256W.onnx -version=v1.0.0.0 -optimize=0 -half=0 -o /workspace -input_shape input:1,3,224,224 -debug

结果截图如下：
![image](https://user-images.githubusercontent.com/21071320/206406299-0fc2cd65-d08d-4399-affa-effa80696e1f.png)

这是转换过程的详细日志：
[swin_v2_256W.log](https://github.com/Tencent/TNN/files/10183839/swin_v2_256W.log)

**Comment by 1627180283** [comment]
可以在转换命令里加上 -align all。这个会逐层分析，看哪一层有问题

**Comment by JeaShining** [comment]
> 可以在转换命令里加上 -align all。这个会逐层分析，看哪一层有问题

![image](https://user-images.githubusercontent.com/21071320/206422893-1eac3704-4b40-490f-9acd-3c47cc11458e.png)
跑到这里就崩了

**Comment by JeaShining** [comment]
> 可以在转换命令里加上 -align all。这个会逐层分析，看哪一层有问题

![image](https://user-images.githubusercontent.com/21071320/206423693-8bcf797f-e128-4a17-bbb7-45158920e0c1.png)
在这里就崩溃了。

**Comment by 1627180283** [comment]
看上去应该是在保存 shape 算子输出的时候挂掉了，可以用 onnxsim 优化一下 onnx 模型，这样可以把 shape 算子优化掉，再转换一下看看

**Comment by 1627180283** [comment]
这里挂掉应该是有 TNN 不支持的 data type，TNN 目前支持的 data type 有 FLOAT，INT32，INT64，DOUBLE
可以看看 onnx::MatMul_799 附近的算子是不是有不支持的 data type

**Comment by JeaShining** [comment]
> 

好的，感谢回复，我自己再去看看，issue就先关了
