### ISSUE TITLE
iOS demo跑不起来

### ISSUE THREAD

**Issue by daiyangyang945** [Tencent/TNN#1857]
Xcode 14.2
运行demo的时候报错
`Undefined symbols for architecture arm64:
  "tnn::kNetOptimizerFuseConvAdd", referenced from:
      tnn::optimizer::NetOptimizerFuseConvAdd::Strategy() in tnn(tnn-arm64-master.o)
  "tnn::kNetOptimizerFuseConvPost", referenced from:
      tnn::optimizer::NetOptimizerFuseConvAdd::IsSupported(tnn::NetworkConfig const&) in tnn(tnn-arm64-master.o)
      tnn::optimizer::NetOptimizerFuseConvPost::Strategy() in tnn(tnn-arm64-master.o)
  "tnn::kNetOptimizerRemoveLayers", referenced from:
      tnn::optimizer::NetOptimizerRemoveLayers::Strategy() in tnn(tnn-arm64-master.o)
  "tnn::kNetOptimizerCbamFusedReduce", referenced from:
      tnn::optimizer::NetOptimizerCbamFusedReduce::Strategy() in tnn(tnn-arm64-master.o)
  "tnn::kNetOptimizerCbamFusedPooling", referenced from:
      tnn::optimizer::NetOptimizerCbamFusedPooling::Strategy() in tnn(tnn-arm64-master.o)
  "tnn::kNetOptimizerInsertFp16Reformat", referenced from:
      tnn::optimizer::NetOptimizerInsertFp16Reformat::Strategy() in tnn(tnn-arm64-master.o)
  "tnn::kNetOptimizerInsertInt8Reformat", referenced from:
      tnn::optimizer::NetOptimizerInsertInt8Reformat::Strategy() in tnn(tnn-arm64-master.o)
  "tnn::kNetOptimizerDynamicRangeDequant", referenced from:
      tnn::optimizer::NetOptimizerDynamicRangeDequant::Strategy() in tnn(tnn-arm64-master.o)
  "tnn::kNetOptimizerInsertLayoutReformat", referenced from:
      tnn::optimizer::NetOptimizerInsertLayoutReformat::Strategy() in tnn(tnn-arm64-master.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

<img width="383" alt="截屏2023-01-01 15 56 02" src="https://user-images.githubusercontent.com/26043410/210164324-1b549d12-dfd4-4cd7-8164-4664ab83fb27.png">
模型文件应该是没问题的吧

**Comment by gttiankai** [comment]
Fix pr: https://github.com/Tencent/TNN/pull/1860
