### ISSUE TITLE
convert2tnn下 build.sh安装onnx2tnn环境报错

### ISSUE THREAD

**Issue by buwangchuxin1992** [Tencent/TNN#1865]
**1. 使用环境（environment）**
 - OS: Ubuntu
 - OS Version:

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
convert2tnn下 build.sh安装onnx2tnn环境报错，出现以下报错
![image](https://user-images.githubusercontent.com/23277799/211704294-79539393-8652-42f0-b2f4-4a11a59239d6.png)

ls: cannot access 'tools/onnx2tnn/onnx-converter/onnx2tnn*.so': No such file or directory
但是我在tnn-v0.3.0-ubuntu-16.04-x86.tar.gz解压包中也没找到这个库？请问在哪里呢？

**Comment by chenxijun1029** [comment]
我也遇到这个问题，sudo apt-get install libprotobuf-dev protobuf-compiler 安装protobuf可以解决

**Comment by gttiankai** [comment]
看下日志中标红的部分，日志显示你没有安装 protobuff。建议使用 docker 的方式进行模型转换。
