### ISSUE TITLE
Cannot convert float16 onnx model.

### ISSUE THREAD

**Issue by MankaranSingh** [Tencent/TNN#1878]
**1. 使用环境（environment）**
 - OS: Ubuntu
 - OS Version: 20.04

  **2. Github版本**
 - branch：master
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type:模型转换失败（converter failed）
 - original model： ONNX
 （如果可以的话，请上传原始的模型文件）

  **4. 日志（Log）**
 ```txt

D/tnn: TNNWriteProto [File /opt/TNN/tools/python3: /opt/TNN/tools/onnx2tnn/src/core/layer/onnx_op_converter.cc:321: static int OnnxOpConverter::WriteRawData(const void*, int, int, tnn::Serializer*, tnn::DataType, std::vector<int>): Assertion `0' failed.

Aborted (core dumped)

 ```

model link: https://github.com/commaai/openpilot/blob/master/selfdrive/modeld/models/supercombo.onnx

**Comment by darrenyao87** [comment]
issue resolved，test it after pr https://github.com/Tencent/TNN/pull/1892
