### ISSUE TITLE
转换模型时指定 half方式保存的模型，推理时出现不支持的层

### ISSUE THREAD

**Issue by HaoLiuHust** [Tencent/TNN#189]
E/tnn: virtual tnn::Status tnn::ArmDeconvLayerCommon::allocateBufferWeight(const std::vector<tnn::Blob*>&, const std::vector<tnn::Blob*>&) [File /home/liuhao/OpenSource/TNN_COPY/TNN/source/tnn/device/arm/acc/deconvolution/arm_deconv_layer_common.cc][Line 80] Error: DataType 1 not support
E/tnn: virtual tnn::Status tnn::DefaultNetwork::InitLayers(tnn::NetStructure*, tnn::NetResource*) [File /home/liuhao/OpenSource/TNN_COPY/TNN/source/tnn/core/default_network.cc][Line 220] Error Init layer 318 (err: 16384 or 0x4000)
Segmentation fault
/home/jieshen/3516_test # ./demo_linux 
E/tnn: virtual tnn::Status tnn::ArmDeconvLayerCommon::allocateBufferWeight(const std::vector<tnn::Blob*>&, const std::vector<tnn::Blob*>&) [File /home/liuhao/OpenSource/TNN_COPY/TNN/source/tnn/device/arm/acc/deconvolution/arm_deconv_layer_common.cc][Line 80] Error: DataType 1 not support
E/tnn: virtual tnn::Status tnn::DefaultNetwork::InitLayers(tnn::NetStructure*, tnn::NetResource*) [File /home/liuhao/OpenSource/TNN_COPY/TNN/source/tnn/core/default_network.cc][Line 220] Error Init layer 318 (err: 16384 or 0x4000)
Segmentation fault

**Comment by seanxcwang** [comment]
@HaoLiuHust 方便的话，模型发一下，看上去是deconv的问题，但是代码里看来是支持weight为half类型的

**Comment by HaoLiuHust** [comment]
[tnn_fp16.zip](https://github.com/Tencent/TNN/files/4963675/tnn_fp16.zip)
@seanxcwang 你们试试看

**Comment by seanxcwang** [comment]
@HaoLiuHust 修复后的代码已经merge到master了，我这边试了下你的模型可以运行
