### ISSUE TITLE
Concat 操作耗时大

### ISSUE THREAD

**Issue by cp0000** [Tencent/TNN#195]
Concat操作耗时比较大，不太正常

机型：vivox20
OpenCL

**Comment by darrenyao87** [comment]
![企业微信截图_edd563c2-b5e1-47fd-8e7b-299be17f0047](https://user-images.githubusercontent.com/62542779/87757441-3b334f00-c83d-11ea-80fe-3953cec37ed6.png)
concat 耗时交大，机型：vivox20，device：opencl

**Comment by neiltian-tencent** [comment]
已优化
