### ISSUE TITLE
in-place channel swapping for arm cpu

### ISSUE THREAD

**Issue by devandong** [Tencent/TNN#197]
For the `instance::SetInputMat` method, if the `reverse_channel` in` MatConvertParam` is true, TNN will perform in-place channel swapping on arm CPU and thus the original data of Mat will be changed. While for metal GPU, the  original data of Mat will not be changed and the transformation is performed on-the-fly.
This results in inconsistent behaviors across two platforms.
@darrenyao87  @seanxcwang @devandong

**Comment by quinnrong94** [comment]
The problem was solved. reverse_channel will no longer change the original mat on arm CPU. Please check it. @devandong
