### ISSUE TITLE
模型量化后无法在ios demo上运行

### ISSUE THREAD

**Issue by ljiqy** [Tencent/TNN#200]
我自己的模型成功在ios的单张图片人脸检测demo中运行，但是转成量化后的模型就在forward那句报错，请问是什么原因？

**Comment by darrenyao87** [comment]
@ljiqy 错误信息发一下，谢谢

**Comment by ljiqy** [comment]
<img width="1687" alt="error" src="https://user-images.githubusercontent.com/37796840/88263297-6534b780-ccfc-11ea-92fb-165cdcf51218.png">

这是我用xcode运行报错的截图

**Comment by seanxcwang** [comment]
量化模型可以提供下吗，只有proto也行 @ljiqy

**Comment by darrenyao87** [comment]
@ljiqy 从截图错误信息address=0x0看，应该是instance的实例没创建成功。有可能是你的量化模型路径不对。
