### ISSUE TITLE
onnx转tnn出错

### ISSUE THREAD

**Issue by li829** [Tencent/TNN#202]
python3 onnx2tnn.py peleeNet.onnx -version=0 -optimize=0 -half=0 -o="/home/liyuewen/PycharmProjects/pytorch/" -input_shape=[1,1,28,28]之后出现下面的错误：
0.----onnx version:1.6.0
algo_optimize 0
onnx_net_opt_path /home/liyuewen/app/TNN/tools/onnx2tnn/onnx-converter/peleeNet.onnx
2.----onnx2tnn: /home/liyuewen/app/TNN/tools/onnx2tnn/onnx-converter/peleeNet.onnx
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = conv1.0.bias
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = conv1.0.weight
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = conv2.0.bias
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = conv2.0.weight
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc1.0.bias
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc1.0.weight
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc1.1.bias
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc1.1.num_batches_tracked
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc1.1.running_mean
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc1.1.running_var
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc1.1.weight
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc2.0.bias
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc2.0.weight
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc2.1.bias
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc2.1.num_batches_tracked
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc2.1.running_mean
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc2.1.running_var
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc2.1.weight
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc2.3.bias
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 374] weight = fc2.3.weight
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 404] const node = 27
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 404] const node = 30
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 554] op Squeeze[38] input node id:16
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 561] Squeeze[38] out node id:18
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 554] op Squeeze[43] input node id:21
D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 561] Squeeze[43] out node id:23
D/converter: int Onnx2TNN::TNNWriteProto() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 222] input_blob 0(conv1) channel order:1() 1() 28() 28()
D/converter: int Onnx2TNN::TNNWriteProto() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 314] node:21 onnx:Conv -> tnn:Convolution
D/converter: int Onnx2TNN::TNNWriteProto() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 314] node:22 onnx:Relu -> tnn:ReLU
D/converter: int Onnx2TNN::TNNWriteProto() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 314] node:23 onnx:MaxPool -> tnn:Pooling
D/converter: int Onnx2TNN::TNNWriteProto() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 314] node:24 onnx:Conv -> tnn:Convolution
D/converter: int Onnx2TNN::TNNWriteProto() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 314] node:25 onnx:Relu -> tnn:ReLU
D/converter: int Onnx2TNN::TNNWriteProto() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 314] node:26 onnx:MaxPool -> tnn:Pooling
D/converter: int Onnx2TNN::TNNWriteProto() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 314] node:28 onnx:Shape -> tnn:Shape
D/converter: std::vector<long int> get_node_attr_ai(const onnx::NodeProto&, const char*, const OnnxNetInfo&, int) [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx_utility.cc][Line 116] name :27
D/converter: int Onnx2TNN::TNNWriteProto() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 314] node:29 onnx:Gather -> tnn:StridedSlice
D/converter: std::vector<long int> get_node_attr_ai(const onnx::NodeProto&, const char*, const OnnxNetInfo&, int) [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx_utility.cc][Line 116] name :27
D/converter: std::vector<long int> get_node_attr_ai(const onnx::NodeProto&, const char*, const OnnxNetInfo&, int) [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx_utility.cc][Line 116] name :27
D/converter: std::vector<long int> get_node_attr_ai(const onnx::NodeProto&, const char*, const OnnxNetInfo&, int) [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx_utility.cc][Line 116] name :27
D/converter: int Onnx2TNN::TNNWriteProto() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 314] node:33 onnx:Concat -> tnn:Concat
D/converter: int Onnx2TNN::TNNWriteProto() [File /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 314] node:34 onnx:Reshape -> tnn:Reshape
name: data_type :0
python3: /home/liyuewen/app/TNN/tools/onnx2tnn/src/core/onnx_utility.cc:556: const float* get_tensor_proto_data(const onnx::TensorProto&): Assertion `0' failed.
Aborted (core dumped)

**Comment by 1627180283** [comment]
方便把模型发给我看一下吗

**Comment by li829** [comment]
我应该是找到问题了，我的模型里有pytorch的Linear层做分类层，把这层去掉后就可以了。

**Comment by darrenyao87** [comment]
@li829 能否把公开模型给到 @1627180283 ,他这边看问题常见的话就合入到FAQ里面，谢谢

**Comment by henbucuoshanghai** [comment]
You should compile onnx2tnn first !!!
You can find more compilation details in <path-to-tnn>/doc/cn/user/convert.md

but 
-- Configuring incomplete, errors occurred!
See also "tnn/tools/onnx2tnn/onnx-converter/build/CMakeFiles/CMakeOutput.log".
See also "tnn/tools/onnx2tnn/onnx-converter/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
ls: cannot access 'tools/onnx2tnn/onnx-converter/onnx2tnn*.so': No such file or directory
/home/li/tnn/tools/onnx2tnn/onnx-converter/build
cp: missing destination file operand after '../../onnx-converter'
Try 'cp --help' for more information.

what wrong with the compile?

**Comment by shaundai-tencent** [comment]
> You should compile onnx2tnn first !!!
> You can find more compilation details in /doc/cn/user/convert.md
> 
> but
> -- Configuring incomplete, errors occurred!
> See also "tnn/tools/onnx2tnn/onnx-converter/build/CMakeFiles/CMakeOutput.log".
> See also "tnn/tools/onnx2tnn/onnx-converter/build/CMakeFiles/CMakeError.log".
> make: *** No targets specified and no makefile found. Stop.
> ls: cannot access 'tools/onnx2tnn/onnx-converter/onnx2tnn*.so': No such file or directory
> /home/li/tnn/tools/onnx2tnn/onnx-converter/build
> cp: missing destination file operand after '../../onnx-converter'
> Try 'cp --help' for more information.
> 
> what wrong with the compile?

You can open a new issue to track your problem and provide more detailed information.
