### ISSUE TITLE
ONNX转TNN模型明明提示错误，最后还提示成功，最后也没生成

### ISSUE THREAD

**Issue by yeyupiaoling** [Tencent/TNN#210]
```
const node = temp_shape_fc_0.tmp_0
const node = p2o.elementwise_add.shape.0
[libprotobuf FATAL /opt/TNN/tools/onnx2tnn/onnx-converter/3rdparty/protobuf-3.12.2/src/google/protobuf/repeated_field.h:1297] CHECK failed: (index) < (current_size_): 
Traceback (most recent call last):
  File "onnx2tnn.py", line 107, in main
    status = onnx2tnn.convert(onnx_net_opt_path, output_dir, algo_version, file_time, 0 if model_half == '0' else 1)
RuntimeError: CHECK failed: (index) < (current_size_): 

onnx2tnn succeed!
```

**Comment by 1627180283** [comment]
方便把模型发给我看一下吗？

**Comment by yeyupiaoling** [comment]
@1627180283  模型：[mobilenet_v2.zip](https://github.com/Tencent/TNN/files/4969726/mobilenet_v2.zip)

**Comment by 1627180283** [comment]
1. 提供模型中存在以下结构，需要手工修改
![image](https://user-images.githubusercontent.com/37806708/88368275-4a2b7b80-cdc0-11ea-9bb6-c129dea4da88.png)
可以替换为 conv 1x1 + reshape
![image](https://user-images.githubusercontent.com/37806708/88368412-9bd40600-cdc0-11ea-8d7b-70a25d28228f.png)
2. 提供模型的 ir_version 较高，如果需要使用 -optimize 参数，需要将 ir_version 降到 6 及其以下。
