### ISSUE TITLE
TNN compared to ncnn?

### ISSUE THREAD

**Issue by liorkad3** [Tencent/TNN#216]
Hi, I am quite new to ncnn and TNN, so could you please give me some introduction about the difference between these two frameworks? Is there any benchmark that show the differences? Is there a difference in the ONNX ops supported?
thanks

**Comment by bluaxe** [comment]
Good question, ncnn is a lightweight framework and provides first-class performance, TNN is upgraded from ncnn to support more devices. The performance varies along the development for both framework,  you can check the performance of TNNv0.3 [here](https://github.com/Tencent/TNN/blob/master/doc/benchmark_data.md), supported onnx ops [here](https://github.com/Tencent/TNN/blob/master/doc/en/user/support_en.md).
