### ISSUE TITLE
TNN Android Demo for 麦芒4？

### ISSUE THREAD

**Issue by AstonnMartin** [Tencent/TNN#220]
我在android studio （v4.0.1）里编译TNN android版本的demo，仿真时显示只支持arm64-v8a处理器。如何修改代码使仿真在低端平台运行呢？多谢。

**Comment by darrenyao87** [comment]
@neiltian-tencent 麦芒4应该是armv7的吧，demo添加下支持

**Comment by neiltian-tencent** [comment]
已添加支持
