### ISSUE TITLE
Converter ONNX to TNN model failed!

### ISSUE THREAD

**Issue by hxhh** [Tencent/TNN#221]
----------  convert model, please wait a moment ----------

Converter Tensorflow to TNN model

Convert TensorFlow to ONNX model succeed!

Converter ONNX to TNN Model

python3: /opt/TNN/tools/onnx2tnn/src/core/layer/onnx_converter_reshape.cc:33: virtual std::__cxx11::string OnnxOpConverterReshape::TNNLayerParam(onnx::NodeProto&, OnnxNetInfo&): Assertion `0' failed.
Aborted (core dumped)

Converter ONNX to TNN model failed!

**Comment by 1627180283** [comment]
Could you show me the model?

**Comment by hxhh** [comment]
[tflite.zip](https://github.com/Tencent/TNN/files/4985712/tflite.zip)
@1627180283 ,你好，模型发出来了，帮忙看下，谢谢！
