### ISSUE TITLE
ndk编译可执行程序成功，运行报不支持model type

### ISSUE THREAD

**Issue by banbishan** [Tencent/TNN#227]
model_type设置的是MODEL_TYPE_TNN，模型转为TNN模型：分别为*.opt.tnnmodel和*.opt.tnnproto，用nkd编译可执行文件链接TNN安卓静态链接库，在安卓上执行的时候报错：
```
tnn::Status tnn::TNN::Init(tnn::ModelConfig&) [File /home/jason/tnn_new/tnn/source/tnn/core/tnn.cc][Line 29] Error: not support mode type: 1
```
加了-Wl,--whole-archive TNN -Wl,--no-whole-archive也一样

**Comment by bjergshen** [comment]
建议使用动态库
我用海思3519，编译静态库，测试也是报这个错，换成动态库就好了

**Comment by banbishan** [comment]
> 建议使用动态库
> 我用海思3519，编译静态库，测试也是报这个错，换成动态库就好了

恩，感谢，我用之前用动态库试过是可以的，就是编静态库的时候不行

**Comment by ImEric** [comment]
编译静态库的时候同样遇到了这个问题

**Comment by seanxcwang** [comment]
https://github.com/Tencent/TNN/wiki/%E9%94%99%E8%AF%AF%E7%A0%81
