### ISSUE TITLE
能否增加支持tflite转tnn?

### ISSUE THREAD

**Issue by neiltian-tencent** [Tencent/TNN#23]
小白用户，tensorflow模型了解不多，但是之前用过tf_lite和MNN，都能很好的转换tensorflow模型到可执行状态，具体做法：
tf_lite直接使用代码转换tenorflow，非常便捷
MNN的路径是tensorflow -> tflite -> MNN，过程不需要输入-in -on参数。因为对于小白用户可能只是引用一下，为了用一下现有模型效果其实并不是很了解模型结构，就不太清楚参数输入

**Comment by gttiankai** [comment]
tflite2tnn的转换工具内部正在开发中，等开发完并测试稳定，会第一时间放出来。请给我们点时间

**Comment by neiltian-tencent** [comment]
tag v0.2版本已支持
