### ISSUE TITLE
关于推理时动态Reshape后的推理耗时相同的问题

### ISSUE THREAD

**Issue by moyuanye** [Tencent/TNN#237]
问题描述：
条件：1、tnnproto 的 第二行 输入blob的 dims 中 batch 已修改为 n (n>1).
           2、推理时在SetInputMat之前调用Reshape修改 输入blob的dims的batch值为 m (0<m<=n)
           3、统计 m取不同值时 SetInputMat->Forward->GetOutputMat 运行时长为 耗时 t。
结果：m取不同值时 t 值相同。

**Comment by darrenyao87** [comment]
@quinnrong94 这个问题清员看下吧，辛苦

**Comment by quinnrong94** [comment]
用官方的[version-slim-320_simplified模型](https://github.com/Tencent/TNN/blob/0be09deaf58aebe9b32ec733cd92afbdb369f8b3/model/download_model.sh#L50) 测试，n改为4，m分别取1,2,3,4，在cpu上测下来，耗时t分别为39.615，81.063，133.384，161.597 ms，t和m大致成正比。

测试方法：
1. 修改[TNN/test/test.cc](https://github.com/Tencent/TNN/blob/0be09deaf58aebe9b32ec733cd92afbdb369f8b3/test/test.cc#L150)，


            // 输入输出和batch参数
            int batch_siz_rt = 3;
            const std::string input_name = "input";
            const std::string output_name = "scores";

            // 修改输入mat shape
            DimsVector input_dim = input_mat_map[input_name]->GetDims();
            input_dim[0] = batch_siz_rt;
            std::shared_ptr<Mat> mat_input(new Mat(DEVICE_ARM, NCHW_FLOAT, input_dim, input_mat_map[input_name]->GetData()));

            // 修改输出mat shape
            DimsVector output_dim = output_mat_map[output_name]->GetDims();
            output_dim[0] = 1;
            std::shared_ptr<Mat> mat_output(new Mat(DEVICE_ARM, NCHW_FLOAT, output_dim));

            // reshape
            InputShapesMap input_shape_map;
            input_shape_map[input_name] = input_dim;
            ret = instance->Reshape(input_shape_map);

            timer.Reset();
            for (int i = 0; i < FLAGS_ic; ++i) {
                timer.Start();
                instance->SetInputMat(mat_input, input_params_map[input_name], input_name);
                ret = instance->ForwardAsync(nullptr);
                instance->GetOutputMat(mat_output, output_params_map[output_name], output_name);
                timer.Stop();
            }

            if (!FLAGS_op.empty()) {
                WriteOutput(output_mat_map);
            }
 
            timer.Print();

2. 运行编译脚本[build_linux.sh](https://github.com/Tencent/TNN/blob/master/scripts/build_linux.sh)
3. 解压以下测试文件至tnn仓库同级目录，运行其中的run.sh脚本
[batch-test.zip](https://github.com/Tencent/TNN/files/5006076/batch-test.zip)

@moyuanye 能否提供测试模型和测试代码，便于我们复现你的问题哈。
