### ISSUE TITLE
转换工具能否提供静默模式

### ISSUE THREAD

**Issue by neiltian-tencent** [Tencent/TNN#24]
只想知道模型最后转换成功or失败在哪里，不太喜欢被刷屏

**Comment by gttiankai** [comment]
已提供。目前的转换工具输出如下
![企业微信截图_0a66d950-1abb-4d68-bfec-129f26b1a597](https://user-images.githubusercontent.com/5379313/86119116-79720400-bb04-11ea-907e-d164fe907c57.png)
