### ISSUE TITLE
intel-opencl 内存泄漏问题

### ISSUE THREAD

**Issue by lakehui** [Tencent/TNN#244]
`        TNN_NS::Mat in_data(TNN_NS::DEVICE_NAIVE, TNN_NS::NGRAY, blob_desc.dims, im.data);

        //formular: y = scale*x + bias
        TNN_NS::MatConvertParam default_param;
        for (int i = 0; i < imageChannel; i++) {
            default_param.bias[i] = _pixel_mean[i];
            if (_algorithm_type == 0) {
                default_param.scale[i] = 1.0;
            }
            if (_algorithm_type == 1) {
                default_param.scale[i] = 1.0/255;
            }
        }
        while(1){
        TNN_NS::BlobConverter blob_converter(inputTensor);
        ret = blob_converter.ConvertFromMat(in_data, default_param, _command_queue);
        if (ret != TNN_NS::TNN_OK) {
            LOGE("input blob_converter failed (%s)\n", ret.description().c_str());
        }
        }`

以上这段代码，如果将net_config.device_type设置为DEVICE_OPENCL（安装的是intel-opencl sdk）。在while循环中内存会一直增长。如果将device_type设置为DEVICE_NAIVE或者是切换到另一台安装nvidia-opencl的机器上，均没有出现内存泄漏问题

**Comment by shaundai-tencent** [comment]
跑的是intel的GPU吗？你看的内存是CPU占用的内存吗？还是整体的大小？

**Comment by lakehui** [comment]
> 跑的是intel的GPU吗？你看的内存是CPU占用的内存吗？还是整体的大小？

是intel GPU， 看的整体内存大小。

**Comment by shaundai-tencent** [comment]
请问，这个问题后来有查到原因吗？
