### ISSUE TITLE
upsample层在reshape时输出尺寸计算不正确

### ISSUE THREAD

**Issue by johnzlli-tencent** [Tencent/TNN#249]
![image](https://user-images.githubusercontent.com/38726413/89382561-a5992a00-d72d-11ea-99b2-6083e8ab3461.png)

upsample层在推理output的shape时，是用输入宽高乘以scale来计算的，但是scale参数是在模型加载时就写死了的，所以在网络输入尺寸发生改变时，可能会导致upsample层推理出来的新output shape不正确。这里是不是应该考虑下修改upsample的输出shape指定方式，或者在推理输出shape时加判断条件来动态修改scale值。

**Comment by shaundai-tencent** [comment]
我们是支持固定shape输出的。如果upsample层后面带有固定输出大小的话。例如，
"Upsample 31 1 1 image_fullres 31 1 2 2 0 256 256 ,"
虽然这里设置了scale为2，但是后面跟了两个参数256，所以输出都固定是256.
