### ISSUE TITLE
使用GPU推理的时候，CPU占用反而变高

### ISSUE THREAD

**Issue by GUN-xing** [Tencent/TNN#261]
如题，在安卓设备上，将device_type设置为DEVICE_OPENCL，使用GPU来进行推理，发现cpu占用反而变高了。
使用CPU推理的时候，cpu占用未6.03%，
使用GPU推理的时候，cpu占用为8.26%。

**Comment by seanxcwang** [comment]
麻烦提供一下模型，或者还有什么更详细的信息可以提供

**Comment by GUN-xing** [comment]
> 麻烦提供一下模型，或者还有什么更详细的信息可以提供

https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB 用的ultraface里面的模型。

**Comment by lnmdlong** [comment]
@GUN-xing 
hi，针对反馈的问题，在安卓上对TNN CPU/GPU推理的CPU占用做了测试，没有复现上面GPU推理CPU占用变高的问题，实际测试下来跑CPU推理的时候cpu占用为12%~15%，GPU推理的时候cpu占用为7%~8%，测试环境是4核A73+4核A53，默认TNN推理使用的是单线程，CPU推理的时候用满单核，GPU推理的时候用到60%~70%单核，可以拿TNN的人脸检测Demo试一下

测试环境: Mate10(4x Cortex-A73 & 4x Cortex-A53, Mali-G72 MP12)
测试模型: face detector
测试分支: master

CPU推理profile结果:
<img width="1022" alt="截屏2021-04-09 下午2 41 35" src="https://user-images.githubusercontent.com/12627325/114141263-f4920180-9943-11eb-80ce-69fe0bbe46a0.png">
<img width="811" alt="截屏2021-04-09 下午2 56 15" src="https://user-images.githubusercontent.com/12627325/114141321-05427780-9944-11eb-9a2c-8a2b5a76b19f.png">

GPU推理profile结果:
<img width="1065" alt="截屏2021-04-09 下午2 42 50" src="https://user-images.githubusercontent.com/12627325/114141882-c95be200-9944-11eb-8843-f8766c7b5851.png">
<img width="813" alt="截屏2021-04-09 下午2 56 34" src="https://user-images.githubusercontent.com/12627325/114141919-d4167700-9944-11eb-9bea-4e58188c4ad8.png">

**Comment by GUN-xing** [comment]
> @GUN-xing
> hi，针对反馈的问题，在安卓上对TNN CPU/GPU推理的CPU占用做了测试，没有复现上面GPU推理CPU占用变高的问题，实际测试下来跑CPU推理的时候cpu占用为12%~15%，GPU推理的时候cpu占用为7%~8%，测试环境是4核A73+4核A53，默认TNN推理使用的是单线程，CPU推理的时候用满单核，GPU推理的时候用到60%~70%单核，可以拿TNN的人脸检测Demo试一下
> 
> 测试环境: Mate10(4x Cortex-A73 & 4x Cortex-A53, Mali-G72 MP12)
> 测试模型: face detector
> 测试分支: master
> 
> CPU推理profile结果:
> <img alt="截屏2021-04-09 下午2 41 35" width="1022" src="https://user-images.githubusercontent.com/12627325/114141263-f4920180-9943-11eb-80ce-69fe0bbe46a0.png">
> <img alt="截屏2021-04-09 下午2 56 15" width="811" src="https://user-images.githubusercontent.com/12627325/114141321-05427780-9944-11eb-9a2c-8a2b5a76b19f.png">
> 
> GPU推理profile结果:
> <img alt="截屏2021-04-09 下午2 42 50" width="1065" src="https://user-images.githubusercontent.com/12627325/114141882-c95be200-9944-11eb-8843-f8766c7b5851.png">
> <img alt="截屏2021-04-09 下午2 56 34" width="813" src="https://user-images.githubusercontent.com/12627325/114141919-d4167700-9944-11eb-9bea-4e58188c4ad8.png">

好的，谢谢。我当时用的时单核，固定频率调用检测模型。我回头再检查一下
