### ISSUE TITLE
how to set the input_convert_param and output_convert_param of Mobilenetssd 

### ISSUE THREAD

**Issue by weilanShi** [Tencent/TNN#275]
Thank you very much for the contribution of the author and the maintenance of the project. TNN is excellent. When I use TNN, I encounter a problem: I use TNN to forward the mobilenetssd model, and the result dimension is correct, but the numerical value is wrong. At present, it is suspected that it is the parameter "input_ convert_ Param" and "output_ convert_ Param" is set incorrectly. I expect to reply how to set these two parameters

**Comment by neiltian-tencent** [comment]
scale * (input mat) + bias -> network input
scale * (network output) + bias -> output mat

**Comment by weilanShi** [comment]
> scale * (input mat) + bias -> network input
> scale * (network output) + bias -> output mat

thank you, it's work
