### ISSUE TITLE
tf2onnx模型目前还不支持指定输入的 shape 信息

### ISSUE THREAD

**Issue by neiltian-tencent** [Tencent/TNN#28]
tf2onnx模型目前还不支持指定输入的 shape 信息，这对于大部分的 TF 模型没有问题，但是默写 tf 模型，在模型文件中并没有输入的 shape 信息，这就造成后面的转换失败。

**Comment by gttiankai** [comment]
目前在feature_align_model已经添加了相应的功能，如果 tf 转换TNN 模型失败，可以试试这个分支的代码，convert.md 文档中有如何使用。现在还有 docker image 没有更新，可以先使用 docker
build的方式来构建 docker image。

**Comment by gttiankai** [comment]
目前该功能已经merge到master分支。Docker image 也会自动化构建并上传docker hub.
