### ISSUE TITLE
yolov3在armlinux上feature_demofen分支推理框错误

### ISSUE THREAD

**Issue by doudoudiandiandou** [Tencent/TNN#294]
x = (x * 2 - 0.5 + ((i / num_anchor_) % dim[2])) * strides_[blob_index];
            y = (y * 2 - 0.5 + ((i / num_anchor_) / dim[2]) % dim[1]) * strides_[blob_index];
            width  = pow((width  * 2), 2) * anchor_grids_[blob_index * grid_per_input_ + (i%num_anchor_) * 2 + 0];
            height = pow((height * 2), 2) * anchor_grids_[blob_index * grid_per_input_ + (i%num_anchor_) * 2 + 1];
不知道是什么意思，感觉和公式不怎么符合呀
bx = σ(tx) + cx
by = σ(ty) + cy
bw = pwetw
bh = pheth

最后输出的图片检测框很乱，请问这部分代码针对Yolov3需要修改吗，图片输入网络之前要先resize608 608吗

**Comment by ZYJESJ** [comment]
> ```
>         x = (x * 2 - 0.5 + ((i / num_anchor_) % dim[2])) * strides_[blob_index];
>         y = (y * 2 - 0.5 + ((i / num_anchor_) / dim[2]) % dim[1]) * strides_[blob_index];
>         width  = pow((width  * 2), 2) * anchor_grids_[blob_index * grid_per_input_ + (i%num_anchor_) * 2 + 0];
>         height = pow((height * 2), 2) * anchor_grids_[blob_index * grid_per_input_ + (i%num_anchor_) * 2 + 1];
> ```
> 
> 不知道是什么意思，感觉和公式不怎么符合呀
> bx = σ(tx) + cx
> by = σ(ty) + cy
> bw = pwetw
> bh = pheth
> 
> 最后输出的图片检测框很乱，请问这部分代码针对Yolov3需要修改吗，图片输入网络之前要先resize608 608吗

您好，请问下您说的代码段是在哪个文件里?现在arm-linux demo里面应该是没有yolo的支持的（暂时只有图像分列和人脸检测）。图片输入网络前是要resize的，因为该分支上arm-linux还没有resize功能。

**Comment by doudoudiandiandou** [comment]
examples/armlinux/samples/ObjectDetectorYolo.cc  
请问一下，Android和iOS跑yolov5也是用的这个源文件吗，我后来发现这个源文件里面的边框回归和置信度计算需要修改一下，之后Yolov5s可以正确检测了，但是yolov3还是不可以了，谢谢，还发现这个yolov5s速度很慢，要3000ms,谢谢

**Comment by ZYJESJ** [comment]
> examples/armlinux/samples/ObjectDetectorYolo.cc
> 请问一下，Android和iOS跑yolov5也是用的这个源文件吗，我后来发现这个源文件里面的边框回归和置信度计算需要修改一下，之后Yolov5s可以正确检测了，但是yolov3还是不可以了，谢谢，还发现这个yolov5s速度很慢，要3000ms,谢谢

您好，是这样的。关于速度的问题能说下您跑测试的手机设备吗？安卓和ios用的也是这个源文件。但是在armlinux里我没有添加支持这个demo，您说的应该是examples/samples/ObjectDetectorYolo.cc，armlinux下只有两个demo。如果是您自已改写的，我先建议您自已把图片resize一下以后再尝试着看看是否推理正确。

**Comment by doudoudiandiandou** [comment]
嗯嗯，我增加了resize，设备没有用手机，就直接是linux的gpu，谢谢

**Comment by hufangjian** [comment]
<img width="216" alt="C2AE72F1-C7F7-4fdf-9920-895CED4914DC" src="https://user-images.githubusercontent.com/30458099/91286511-1d082980-e7c1-11ea-82fb-998856d5f14f.png">

**Comment by doudoudiandiandou** [comment]
赞
