### ISSUE TITLE
麒麟710F VGG16 性能差

### ISSUE THREAD

**Issue by neiltian-tencent** [Tencent/TNN#30]
model | cpu 1 thread(ms) | gpu time(ms)
-- | -- | --
VGG16 | 1323 | 2560
Mobilenet_v2 | 95 | 24
squeezenet_v1.1 | 64 | 25
Shufflenet_v2.0 | 15 | 7

**Comment by mylyu** [comment]
why someone may need vgg on phones?

**Comment by Hucley** [comment]
我们这边测试shufflenetv2_1.5x版本在rk3399平台TNN使用双大核，前向时间为140ms，MNN使用双大核实测48ms，感觉和mobilenet系列网络在上述平台测试结果差距较大，不知shufflenet网络在tnn上使用需要有哪些注意事项？

**Comment by darrenyao87** [comment]
shufflenetv2_1.5x在rk3399上的性能问题需要确认和定位下, @alohali

**Comment by neiltian-tencent** [comment]
vgg16  GPU性能差问题评测最新master(b2244a573ac766d592e324966144639e40dd7edc)已无此问题。 https://github.com/onnx/models/blob/master/vision/classification/vgg/model/vgg16-7.onnx 模型评测结果：评测手机 荣耀8x，ARM：950ms, OpenCL: 370ms。
