### ISSUE TITLE
关于C++和Android Demo

### ISSUE THREAD

**Issue by CheungBH** [Tencent/TNN#304]
您好.我想问下,tnn支持PC端C++的前向传播嘛?
然后我试了试安卓demo,图像分类那个按钮可以,但是点击人脸识别会返回主界面,人脸视频会闪退

**Comment by neiltian-tencent** [comment]
看demo文档，是否模型没有下载？

**Comment by CheungBH** [comment]
> 看demo文档，是否模型没有下载？

是的是的，我之前遗漏了，谢谢了。
还有就是，那个ARMLINUX的C++ demo可以在PC端跑嘛

**Comment by neiltian-tencent** [comment]
你是arm开发版就可以，x86 性能还在优化，预计9月份开源。
