### ISSUE TITLE
怎样支持五维？

### ISSUE THREAD

**Issue by doudoudiandiandou** [Tencent/TNN#305]
在推理Yolov5时，模型的输出是（1,3,19,19,85），但是不支持这种五维，请问怎样修改

**Comment by stephehuang** [comment]
不支持五纬度输入

**Comment by devandong** [comment]
demo中有yolov5模型，可以尝试使用。
由于在yolov5模型中，5维形状出现的位置在模型末尾处，demo中的处理方式是将3与85融合成为一个维度，并在后处理时进行对应处理，具体处理代码可见:https://github.com/Tencent/TNN/blob/fb695287d64a3e47da2f6ab7255ec9a17d4a9ee3/examples/base/object_detector_yolo.cc#L58

**Comment by cmdbug** [comment]
https://github.com/cmdbug/TNN_Demo/issues/1

**Comment by seanxcwang** [comment]
三月中旬会发布新版本，支持五维
