### ISSUE TITLE
请问是否支持一次Forward处理多张图片

### ISSUE THREAD

**Issue by laoxie001** [Tencent/TNN#309]
就是一次传入多张图像数据到Mat里，然后调用一次Forward处理:)

**Comment by gttiankai** [comment]
可以的，假设你的输入shape:(1,3,128,128)， 你可以输入 8 张图片一起进行 forward，输入的 shape 为(8, 3, 128, 128). 但是有个前提条件，你的原始模型当中的 n 这个维度上不能改变。

**Comment by laoxie001** [comment]
> 可以的，假设你的输入shape:(1,3,128,128)， 你可以输入 8 张图片一起进行 forward，输入的 shape 为(8, 3, 128, 128). 但是有个前提条件，你的原始模型当中的 n 这个维度上不能改变。

您好，我在caffemodel的prototxt中输入shape设置为(1, 3, 128, 128)，然后转完模型，将输入网络的Mat数据的shape设置为(8, 3, 128, 128)，这时输出的结果不对。但是在转模型前将prototxt里的shape设置为(8, 3, 128, 128)后，输出结果正常。也就是说一次forward处理的图片数量必须在转模型前设置好，然后就不能改变了，是这样的嘛~

**Comment by gttiankai** [comment]
"我在caffemodel的prototxt中输入shape设置为(1, 3, 128, 128)，然后转完模型，将输入网络的Mat数据的shape设置为(8, 3, 128, 128)，这时输出的结果不对" 这种使用方式，按照我的理解输出结果也是对的。你用 netron 你看下caffe 转换时生成的onnx 模型，里面有没有 reshape改变 batch的情况。

**Comment by laoxie001** [comment]
> "我在caffemodel的prototxt中输入shape设置为(1, 3, 128, 128)，然后转完模型，将输入网络的Mat数据的shape设置为(8, 3, 128, 128)，这时输出的结果不对" 这种使用方式，按照我的理解输出结果也是对的。你用 netron 你看下caffe 转换时生成的onnx 模型，里面有没有 reshape改变 batch的情况。

感谢，经过各种验证，最终发现是网络初始化输入层名字不对。
inputs.insert(std::pair<std::string, TNN_NS::DimsVector>("data", input_dims));
我上面设置网络初始化shape和输入层时名字写的“data”，但实际上tnnproto中输入层名字是"data_input"，修改后就可以正常的改变batch大小了。
注：转模型时prototxt输入层的两种写法转出来的tnnproto输入层名字也是不一样的，下图左边写法转出来的输入层名字是“data_input”，右边写法转出来的输入层名字是"input"。
![image](https://user-images.githubusercontent.com/57768395/91533141-f9202180-e941-11ea-961b-bf7bc2271910.png)

**Comment by gttiankai** [comment]
是的，由于 caffe 的 proto 有很多重名的情况，所有模型输入需要进行特殊处理。后面还是以 tnnproto 中的输入和输出为主。

另外caffe 的文档中有说明：

目前 caffe2onnx 的工具目前只支持最新版本的 caffe 的格式,所以在使用 caffe2onnx 工具之前需要将老版本的 caffe 网络和模型转换为新版. caffe 自带了工具可以把老版本的 caffe 网络和模型转换为新版本的格式. 具体的使用方式如下:
```
upgrade_net_proto_text [老prototxt] [新prototxt]
upgrade_net_proto_binary [老caffemodel] [新caffemodel]
```
修改后的输入的格式如下所示:
```
layer {
  name: "data"
  type: "input"
  top: "data"
  input_param { shape: { dim: 1 dim: 3 dim: 224 dim: 224 } }
}
```

**Comment by changewOw** [comment]
> 可以的，假设你的输入shape:(1,3,128,128)， 你可以输入 8 张图片一起进行 forward，输入的 shape 为(8, 3, 128, 128). 但是有个前提条件，你的原始模型当中的 n 这个维度上不能改变。

您好，这个性质，目前还可以使用吗

**Comment by gttiankai** [comment]
可以啊， 一直是可以使用的。
