### ISSUE TITLE
高通 845 model_check  opencl arm 结果不同。 

### ISSUE THREAD

**Issue by hufangjian** [Tencent/TNN#318]
模型转换：
sudo docker run --rm --volume=$(pwd):/TNN -it tnn-convert:latest python3 ./converter.py onnx2tnn \
    /TNN/person_sim.onnx \
    -optimize \
    -v v3.0 \
    -align  \
    -input_file /TNN/input.txt \
    -ref_file /TNN/output.txt	
input.txt output.txt  是我pytorch 模型的输入输出。(没有加校准也是同样的错误)。

编译：
./model_check_android.sh -c

-- >>>>>>>>>>>>>
-- TNN BUILD INFO:
--      System: Android
--      Processor: armv7-a
--      Cpu:    ON
--      X86:    OFF
--      Arm:    ON
--      Metal:  OFF
--      OpenCL: ON
--      CUDA:   OFF
--      DSP:    OFF
--      Atlas:  OFF
--      NPU:    OFF
--      OpenMP: OFF
--      TEST:   OFF
--      --Unit Test:    OFF
--      Qantization:    OFF
--      ModelCheck:     ON
--      DEBUG:
--      PROFILE:        OFF
--      BENCHMARK:      OFF
--      BENCHMARK Layer:        OFF
--      TNN2MEM:        OFF
--      enable armv7 neon
-- Build TNN OpenCL

运行(1)：
 ./model_check  -d ARM -p person_sim.tnnproto -m person_sim.tnnmodel
device: ARM
proto: person_sim.tnnproto
model: person_sim.tnnmodel
init model config success!
E/tnn: tnn::Status tnn::ModelChecker::FeedInputData() [File /home/hufangjian/android/TNN/tools/model_check/model_checker.cc][Line 154] Generate Random input...
E/tnn: bool tnn::ModelChecker::CompareData(void *, void *, tnn::DimsVector) [File /home/hufangjian/android/TNN/tools/model_check/model_checker.cc][Line 318] ERROR AT 408 result -0.438552 ref -0.742307  diff/sum 0.257233  diff 0.303755
.
.
.
failed layer count: 64    pass layer count: 77
the last layer check falied!
model check failed!

运行(2): 
./model_check  -d OPEN_CL -p person_sim.tnnproto -m person_sim.tnnmodel -o
device: OPEN_CL
proto: person_sim.tnnproto
model: person_sim.tnnmodel
dump output
init model config success!
E/tnn: tnn::Status tnn::ModelChecker::FeedInputData() [File /home/hufangjian/android/TNN/tools/model_check/model_checker.cc][Line 154] Generate Random input...
E/tnn: auto tnn::ModelChecker::CompareDeviceAndCpu()::(anonymous class)::operator()(std::vector<Blob *> &, tnn::LayerInfo *) const [File /home/hufangjian/android/TNN/tools/model_check/model_checker.cc][Line 295] dump blob (output0) data
E/tnn: auto tnn::ModelChecker::CompareDeviceAndCpu()::(anonymous class)::operator()(std::vector<Blob *> &, tnn::LayerInfo *) const [File /home/hufangjian/android/TNN/tools/model_check/model_checker.cc][Line 295] dump blob (output1) data
E/tnn: auto tnn::ModelChecker::CompareDeviceAndCpu()::(anonymous class)::operator()(std::vector<Blob *> &, tnn::LayerInfo *) const [File /home/hufangjian/android/TNN/tools/model_check/model_checker.cc][Line 295] dump blob (output2) data
model check pass!
输出对比pytorch 结果完全一致。

运行(3)：另外一个模型。
 ./model_check  -d ARM -p mobilefacenet.tnnproto  -m mobilefacenet.tnnmodel
device: ARM
proto: mobilefacenet.tnnproto
model: mobilefacenet.tnnmodel
init model config success!
E/tnn: tnn::Status tnn::ModelChecker::FeedInputData() [File /home/hufangjian/android/TNN/tools/model_check/model_checker.cc][Line 154] Generate Random input...
model check pass!

运行（4）：
dipper:/data/local/tmp/ocl_test $ ./model_check  -d OPEN_CL -p mobilefacenet.tnnproto  -m mobilefacenet.tnnmodel
device: OPEN_CL
proto: mobilefacenet.tnnproto
model: mobilefacenet.tnnmodel
init model config success!
E/tnn: tnn::Status tnn::ModelChecker::FeedInputData() [File /home/hufangjian/android/TNN/tools/model_check/model_checker.cc][Line 154] Generate Random input...
model check pass!

**Comment by hufangjian** [comment]
您好，这是我模型的地址。谢谢。
链接:https://pan.baidu.com/s/1DDn8ksfqQvTGslOPUQLceQ 提取码:kym6

**Comment by seanxcwang** [comment]
这个应该是winograd放大了精度误差导致的，导致超过了model_check的阈值，我看了下对最终的结果应该影响不大，如果你这边实在对精度要求高，可以把`arm_conv_layer_3x3.cc:273`的地方返回`2`，这样winograd的block会小一些

**Comment by hufangjian** [comment]
好的，我测试一下。非常感谢。
