### ISSUE TITLE
winograd精度损失的问题

### ISSUE THREAD

**Issue by laoxie001** [Tencent/TNN#319]
我用一个27层的resnet测试时发现，arm和opencl输出结果不一致，与本地caffe跑出来的结果对比后发现，arm结果是错的，opencl结果是对的，有略微精度损失，不过在可接受范围内。对比图如下：
![image](https://user-images.githubusercontent.com/57768395/91450312-bd884780-e8ae-11ea-949c-eee08bb91380.png)

后面经过排查，发现把 arm_conv_layer_3x3.cc 文件中的 SelectWinograd 函数返回值直接置零后，arm输出结果就正常了，但是速度慢了一倍。如下图所示：
![image](https://user-images.githubusercontent.com/57768395/91450838-5323d700-e8af-11ea-93f0-e46d160910fc.png)

另外我在一些小网络中也进行了对比测试，比如MTCNN等，小网络中arm和opencl输出结果是一致且正确的。
请问上述问题是winograd本身的精度损失逐层累计造成的吗

**Comment by seanxcwang** [comment]
需要分析一下，不排除实现的有问题，可以用model_check的工具跑一下，看是哪一层开始误差较大
[https://github.com/Tencent/TNN/blob/master/doc/cn/development/model_check.md](url)

**Comment by seanxcwang** [comment]
> 我用一个27层的resnet测试时发现，arm和opencl输出结果不一致，与本地caffe跑出来的结果对比后发现，arm结果是错的，opencl结果是对的，有略微精度损失，不过在可接受范围内。对比图如下：
> ![image](https://user-images.githubusercontent.com/57768395/91450312-bd884780-e8ae-11ea-949c-eee08bb91380.png)
> 
> 后面经过排查，发现把 arm_conv_layer_3x3.cc 文件中的 SelectWinograd 函数返回值直接置零后，arm输出结果就正常了，但是速度慢了一倍。如下图所示：
> ![image](https://user-images.githubusercontent.com/57768395/91450838-5323d700-e8af-11ea-93f0-e46d160910fc.png)
> 
> 另外我在一些小网络中也进行了对比测试，比如MTCNN等，小网络中arm和opencl输出结果是一致且正确的。
> 请问上述问题是winograd本身的精度损失逐层累计造成的吗

你好，另外一个winograd的issue也是你提的，我先把这个close掉

**Comment by seanxcwang** [comment]
#394
