### ISSUE TITLE
windows库编译??

### ISSUE THREAD

**Issue by liulai** [Tencent/TNN#32]

**Comment by neiltian-tencent** [comment]
windows库需要先把x86的加速做了，x86的加速已经在roadmap里面，不然windows只能编译出纯c++版本的实现，性能很慢。

**Comment by liulai** [comment]
> windows库需要先把x86的加速做了，x86的加速已经在roadmap里面，不然windows只能编译出纯c++版本的实现，性能很慢。

下一个大版本能出来吗？

**Comment by darrenyao87** [comment]
后续添加X86支持， @bluaxe

**Comment by neiltian-tencent** [comment]
已支持
