### ISSUE TITLE
全卷积网络变尺寸输入的问题

### ISSUE THREAD

**Issue by laoxie001** [Tencent/TNN#320]
我在MTCNN的PNET中测试发现，如果我转模型前prototxt里的输入shape设为(1, 3, 12, 12)，转成tnn模型后，将Mat输入数据的shape设为(1, 3, 96, 96)，不能得到正确输出。只有在转模型前将prototxt里的输入shape也设为(1, 3, 96, 96)，才能得到正确输出。
是因为TNN目前不支持全卷积网络的变尺寸输入吗

**Comment by gttiankai** [comment]
tnn 的 prototxt 的 input shape给出的是模型输入的 **上限**。假设你的 input shape 为（1， 3， 96， 96），那么你可以输入数据为（1，3， 12， 12），可以变小，但是不能变大。

**Comment by laoxie001** [comment]
> tnn 的 prototxt 的 input shape给出的是模型输入的 **上限**。假设你的 input shape 为（1， 3， 96， 96），那么你可以输入数据为（1，3， 12， 12），可以变小，但是不能变大。

之前出问题是因为网络初始化时input层名字写错了，我将input层名字修正后再次测试。PNET转模型时prototxt里输入shape为(1, 3, 12, 12)，网络初始化时shape设为(1, 3, 96, 96)，输入mat数据shape为(1, 3, 96, 96)，这时可以得到正确输出。但是输入mat数据shape为(1, 3, 48, 48)时，则不能得到正确输出，将网络初始化时的shape也设为(1,, 3, 48, 48)后才能得到正确输出。也就是说，如果有多个尺寸的图像要传入PNET，需要对每一个尺寸都创建一个网络实例，然后分别进行调用。

**Comment by banbishan** [comment]
> > tnn 的 prototxt 的 input shape给出的是模型输入的 **上限**。假设你的 input shape 为（1， 3， 96， 96），那么你可以输入数据为（1，3， 12， 12），可以变小，但是不能变大。
> 
> 之前出问题是因为网络初始化时input层名字写错了，我将input层名字修正后再次测试。PNET转模型时prototxt里输入shape为(1, 3, 12, 12)，网络初始化时shape设为(1, 3, 96, 96)，输入mat数据shape为(1, 3, 96, 96)，这时可以得到正确输出。但是输入mat数据shape为(1, 3, 48, 48)时，则不能得到正确输出，将网络初始化时的shape也设为(1,, 3, 48, 48)后才能得到正确输出。也就是说，如果有多个尺寸的图像要传入PNET，需要对每一个尺寸都创建一个网络实例，然后分别进行调用。

@gttiankai 碰到了同样的问题，使用ncnn没有这个问题，输入必须设置与转换模型时一样的shape才能正确输出，当与输入shape不一致时，我输出input的shape还是网络的固定的输入shape，网络的输出也是错误的shape。

**Comment by gttiankai** [comment]
@laoxie001 “也就是说，如果有多个尺寸的图像要传入PNET，需要对每一个尺寸都创建一个网络实例，然后分别进行调用。”是的，因为创建实例的时候会进行每一层的输出 shape 的计算，并进行对应的内存分配。针对不同的尺寸，每一层的输出 shape 不同，内存分配也不同
