### ISSUE TITLE
怎么能得到每一层weight 是NCHW格式的 

### ISSUE THREAD

**Issue by xinchenhawaii** [Tencent/TNN#324]
我现在在ARM下面开发，想在conv层直接得到NCHW，而不是NC4HW4 这样format的？请问怎么能最直接的方法得到？比如在Status ArmConvLayerCommon::allocateBufferWeight，里面直接直接用memcpy 把const float *src = conv_res->filter_handle.force_to<float *>(); 拷贝到float *dst = temp_buffer.force_to<float *>(); 里面可以吗？
另外，tnn的模型名字好像和pytorch 通过for name in net.state_dict(): print(name) 。打印出来的名字对不上。我如果想比较每一层pytorch weight和TNN 模型的weight，怎么能一一对应上呢？

**Comment by darrenyao87** [comment]
@xinchenhawaii 对的模型直接进来的就是nchw的格式。TNN里面weight的名称是按照层的名称保存的，没有单独的名称。如果要对应的话可以先通过层名称获取LayerResource，在获取每个weight或bias
