### ISSUE TITLE
mobilenetv2模型量化后精度损失

### ISSUE THREAD

**Issue by blueskywwc** [Tencent/TNN#326]
你好，对于mobilenetv2模型，经过int8量化后，精度损失大概有多少，谢谢！

**Comment by darrenyao87** [comment]
@blueskywwc post train方式的精度损失在3个点以内，与测试集相关。后续我们会打通训练量化，这样可以保障精度基本不掉。

**Comment by blueskywwc** [comment]
明白了，谢谢
