### ISSUE TITLE
convert工具不支持lstm转换

### ISSUE THREAD

**Issue by zwy4896** [Tencent/TNN#329]
期待TNN早日支持lstm

**Comment by darrenyao87** [comment]
@zwy4896 这个支持起来需要花点时间，包括转模型+各个平台的实现以及支持动态shape。我们已经开始考虑方案了。

**Comment by seanxcwang** [comment]
三月中旬会发布新版本，该版本支持lstm

**Comment by liziru** [comment]
> 三月中旬会发布新版本，该版本支持lstm

现在应该支持了吧
![image](https://user-images.githubusercontent.com/34911790/128655224-2f83560b-6aef-4ca0-84e4-f5e674c59e12.png)
是将torch lstm 或者tf lstm转换成onnx格式，再转到tnn格式的lstm吗
