### ISSUE TITLE
ncnn模型

### ISSUE THREAD

**Issue by Hank0223** [Tencent/TNN#33]
tnn支援ncnn的模型嗎？

**Comment by neiltian-tencent** [comment]
目前tnn可以解析ncnn大部分模型，但有一小部分op还没有覆盖到，这个还需要完善。

**Comment by Hank0223** [comment]
還需要做模型的轉換嗎？
轉成tnn的格式，還是能直接使用

**Comment by neiltian-tencent** [comment]
可以直接用，struct PUBLIC ModelConfig {
    // 配置为MODEL_TYPE_NCNN
    ModelType model_type
    // ncnn need two: params: order is param, weights。
    std::vector<std::string> params = {};
};
即可。
