### ISSUE TITLE
benchMark ARM 多核测试

### ISSUE THREAD

**Issue by hufangjian** [Tencent/TNN#333]
您好，请问一下benchmark 测试参数：
./TNNTest -th 2 -wc 5 -ic 5 -dt ARM -mt TNN -mp mobilefacenet.tnnproto  -dl 0,1
请问一下 -th 是多核还是 -dl是多核？
我设置-dl 速度没什么变化。
谢谢。

**Comment by seanxcwang** [comment]
> 您好，请问一下benchmark 测试参数：
> ./TNNTest -th 2 -wc 5 -ic 5 -dt ARM -mt TNN -mp mobilefacenet.tnnproto -dl 0,1
> 请问一下 -th 是多核还是 -dl是多核？
> 我设置-dl 速度没什么变化。
> 谢谢。

-th是指定线程数，-dl是绑定程序到对应的核上，所以要测多线程需要设置th，并且编译的时候需要打开openmp

**Comment by hufangjian** [comment]
> > 您好，请问一下benchmark 测试参数：
> > ./TNNTest -th 2 -wc 5 -ic 5 -dt ARM -mt TNN -mp mobilefacenet.tnnproto -dl 0,1
> > 请问一下 -th 是多核还是 -dl是多核？
> > 我设置-dl 速度没什么变化。
> > 谢谢。
> 
> -th是指定线程数，-dl是绑定程序到对应的核上，所以要测多线程需要设置th，并且编译的时候需要打开openmp

您好，请问一下如何进行核绑定？benchmark 测试代码是否是-dl参数不能用？不支持核绑定？

**Comment by seanxcwang** [comment]
> > > 您好，请问一下benchmark 测试参数：
> > > ./TNNTest -th 2 -wc 5 -ic 5 -dt ARM -mt TNN -mp mobilefacenet.tnnproto -dl 0,1
> > > 请问一下 -th 是多核还是 -dl是多核？
> > > 我设置-dl 速度没什么变化。
> > > 谢谢。
> > 
> > 
> > -th是指定线程数，-dl是绑定程序到对应的核上，所以要测多线程需要设置th，并且编译的时候需要打开openmp
> 
> 您好，请问一下如何进行核绑定？benchmark 测试代码是否是-dl参数不能用？不支持核绑定？

用不用dl取决于你要得到什么结果，我们一般测试大小核会用，比如`-dl 0,1,2,3`就是指定运行在0-3这四个核上
