### ISSUE TITLE
android app测试和benchmark测试速度相差很大？

### ISSUE THREAD

**Issue by hufangjian** [Tencent/TNN#336]
请教管问题。我测试了example 的人脸检测android app模型。发现在同样的模型在app中测试的速度比benchmark要慢好多，去除图片读取跟检测后处理，感觉也不会差这么多。请问一下是否是正常的？还是app中没有优化好？谢谢。
<img width="504" alt="1" src="https://user-images.githubusercontent.com/30458099/91927156-60a3eb80-ed0b-11ea-86d0-4b7ec7c5d1ba.png">
![3](https://user-images.githubusercontent.com/30458099/91927220-88934f00-ed0b-11ea-9177-309f63e54d24.jpg)

**Comment by neiltian-tencent** [comment]
fix by 57427954, build release.
