### ISSUE TITLE
3*3卷积unit_test结果存在差异 

### ISSUE THREAD

**Issue by Guanmoyu** [Tencent/TNN#340]
commit id：2c7b9742ad23e6dcc57ad5746dc9f6e6a289a4c3
安卓NDK：r16b
安卓版本：armv7、armv8
设备：骁龙835,845

卷积参数：
input_dim：1 * 384 * 80 * 144
kernel：96 * 384 * 3 * 3
stride=1，dialation=1，pad=1

执行命令：
`./unit_test -dt ARM -ic 1 -th 2 --gtest_filter=LayerTest/ConvLayer*`

输出结果：
Note: Google Test filter = LayerTest/ConvLayer*
[==========] Running 1 test from 1 test suite.`
[----------] Global test environment set-up.
[----------] 1 test from LayerTest/ConvLayerTest
[ RUN      ] LayerTest/ConvLayerTest.ConvLayer/0
E/tnn: tnn::Status tnn::LayerTest::Compare() [File ~/tnn/test/unit_test/layer_test/layer_test.cc][Line 468] cpu_mat.GetData(): 12.015625 0.000000 2.937500 0.000000
E/tnn: tnn::Status tnn::LayerTest::Compare() [File ~/tnn/test/unit_test/layer_test/layer_test.cc][Line 471] dev_cpu_mat.GetData(): 12.015609 0.000000 2.937487 0.000000
ERROR AT 236499 result 0.000122 ref 0.000000
~/tnn/test/unit_test/layer_test/layer_test.cc:478: Failure
Expected equality of these values:
  0
  cmp_result
    Which is: -1
[  FAILED  ] LayerTest/ConvLayerTest.ConvLayer/0, where GetParam() = (1, 384, 80, 1, 3, 1, 1, 1, 0) (12595 ms)
[----------] 1 test from LayerTest/ConvLayerTest (12595 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (12595 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] LayerTest/ConvLayerTest.ConvLayer/0, where GetParam() = (1, 384, 80, 1, 3, 1, 1, 1, 0)

 1 FAILED TEST

按照上面的卷积参数，修改test_conv_layer.cc，结果存在细微差异，且推理时间异常，且多线程无效，而tag v0.1.0是没问题的。求大佬看一下！

**Comment by teslawho** [comment]
关于多线程无效的问题，
执行命令应该是：
./unit_test -dt ARM -ic 1 -th 2 --gtest_filter=LayerTest/ConvLayer*   -ub 0   
你忘了加-ub 0，直接错把括号里的单元测试的时间当成，卷积层的计算时间了；
-ub {0|1}   用途是： 是否打印计算性能数据(GFLOPS)，用于性能测试，加上会输出卷积层的计算时间；
比如：
[ FAILED ] LayerTest/ConvLayerTest.ConvLayer/0, where GetParam() = (1, 384, 80, 1, 3, 1, 1, 1, 0) (12595 ms)
括号(12595 ms)里的 12595ms 这个是单元测试的时间，而不是卷积层的计算时间。

**Comment by Guanmoyu** [comment]
> 关于多线程无效的问题，
> 执行命令应该是：
> ./unit_test -dt ARM -ic 1 -th 2 --gtest_filter=LayerTest/ConvLayer* -ub 0
> 你忘了加-ub 0，直接错把括号里的单元测试的时间当成，卷积层的计算时间了；
> -ub {0|1} 用途是： 是否打印计算性能数据(GFLOPS)，用于性能测试，加上会输出卷积层的计算时间；
> 比如：
> [ FAILED ] LayerTest/ConvLayerTest.ConvLayer/0, where GetParam() = (1, 384, 80, 1, 3, 1, 1, 1, 0) (12595 ms)
> 括号(12595 ms)里的 12595ms 这个是单元测试的时间，而不是卷积层的计算时间。

更新一下，一开始确实没有设置-ub选项，设置之后2线程有一定提升，但是4线程几乎无提升；另外，如上参数的单元测试，TNN一直是过不了的，上面说tagv0.1.0能过是有个开关设置错了。
