### ISSUE TITLE
ArgMax 算子的支持

### ISSUE THREAD

**Issue by gttiankai** [Tencent/TNN#342]
支持 onnx 的 ArgMax 算子

**Comment by gttiankai** [comment]
ArgMax 和 ArgMin 算子已经支持，相关代码已经合并到 master 分支。

**Comment by qingyang-jiandao** [comment]
why onnx argmax convert to tnn,  the output value is 0, all

**Comment by shaundai-tencent** [comment]
You can open a new issue to track your problem and provide more detailed information.

**Comment by shaundai-tencent** [comment]
> why onnx argmax convert to tnn, the output value is 0, all

You can open a new issue to track your problem and provide more detailed information.
