### ISSUE TITLE
最新NDK 版本导致performace 问题

### ISSUE THREAD

**Issue by xinchenhawaii** [Tencent/TNN#348]
我们发现NDK 版本会导致performance在同一个手机差别2倍以上。我们试过NDK17 以及NDK21。发现NDK21 在编译的时候，会显示很多优化不支持。编译后的运行结果会比NDK17编译后的代码，performance 慢两倍以上。请能否给予解决一下

**Comment by neiltian-tencent** [comment]
@xinchenhawaii 是基于benchmark_android.sh脚本跑的吗？可以试试最新的提交。

**Comment by xinchenhawaii** [comment]
是基于benchmark_android.sh跑的

**Comment by neiltian-tencent** [comment]
@xinchenhawaii 能否提供详细的编译信息以及机型性能数据，我们验证了ndk16, ndk17以及ndk21，性能并没有差别。

**Comment by xinchenhawaii** [comment]
the NDK version is ndk-r21d. We found this problem was found in one and
half months ago. The TNN version should be that time.

Xin

**Comment by neiltian-tencent** [comment]
@xinchenhawaii 发现NDK21 在编译的时候，会显示很多优化不支持，这个具体是指什么？ 性能跟NDK版本没有关系

**Comment by xinchenhawaii** [comment]
同样的code，运行时间差了80%到一倍。比如ndk17，100 ms，ndk21r 180ms。我用了两部同样的手机做实验做了另外一个实验。一部手机ndk17，一部手机ndk21r。现在两个手机编译同样的code，ndk17运行 100ms，ndk21r 180ms。 然后我把手机的so互相交换，运行时间也互相交换了。在用ndk21
r 编译的时候，看到一个message，ndk版本过高，有些选项不支持。记不住了，是一个月以前发现的。所以我们现在都用ndk17。

**Comment by neiltian-tencent** [comment]
可能你一个跑在了大核上，一个跑在了小核上，应该跟ndk版本没有关系。这个issue先关了，有问题再反馈吧。

**Comment by xinchenhawaii** [comment]
都是在大核上。我绑定core的。我确定是cmake在版本好check的时候，条件设置的有问题。我看到提示了，当时项目在线验收，所以没有及时存screenshot。

**Comment by qiuhaining** [comment]
我这边测试ndkr17+cmake3.10 开-O2会有较大performance的提升
