### ISSUE TITLE
pytorch导出的densenet转换失败

### ISSUE THREAD

**Issue by CescMessi** [Tencent/TNN#357]
pytorch使用torchvision中的densenet121，导出的onnx模型在转换时只能生成.opt.onnx文件，提示转换成功但align时会报错。

pytorch版本1.5.1，torchvision版本0.6.1，平台为Windows。[onnx文件下载](https://share.weiyun.com/F0GGp02q)

![image.png](https://i.loli.net/2020/09/07/Tr48bNC1KDvYjEd.png)

**Comment by 1627180283** [comment]
这个问题已修复

**Comment by gttiankai** [comment]
已经合并到 master 分支，有时间请测试下。
