### ISSUE TITLE
TNN/tools/convert2tnn/bin/model_check does not exist! please make sure the file exist!

### ISSUE THREAD

**Issue by algpower** [Tencent/TNN#363]
TNN/tools/convert2tnn/bin/model_check does not exist! please make sure the file exist!

**Comment by hufangjian** [comment]
这个自己编译的 参考一下主cmakeList.txt

**Comment by 1627180283** [comment]
执行 TNN/tools/convert2tnn/build.sh 进行转换工具编译即可
