### ISSUE TITLE
缺少文件 metal_cpu_adapter_acc.mm

### ISSUE THREAD

**Issue by ChaosTong** [Tencent/TNN#37]
1 warning generated.
error: Build input file cannot be found: '/Users/chaostong/Downloads/TNN/source/tnn/device/metal/acc/metal_cpu_adapter_acc.mm' (in target 'tnn' from project 'tnn')
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'tnn' from project 'tnn')
note: Using new build system
note: Planning build
note: Constructing build description
** BUILD FAILED **

**Comment by neiltian-tencent** [comment]
fix by 89b38a6
