### ISSUE TITLE
模型输入大小问题

### ISSUE THREAD

**Issue by Kevin-1993-35** [Tencent/TNN#373]
请问下面代码中的target_dims是用来控制模型输入大小的吗？为什么我修改之后没有任何变化，我把height和width改为0还可以正常运行？

  TNN_NS::DimsVector target_dims = {1, 3, height, width};
    auto rgbTNN = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC4, target_dims, rgbaData);
    TNN_NS::Status status = asyncRefDetector->Detect(rgbTNN, width, height, faceInfoList);
    delete [] yuvData;
    delete [] rgbaData;
    if (status != TNN_NS::TNN_OK) {
        LOGE("failed to detect %d", (int)status);
        return 0;
    }

**Comment by hufangjian** [comment]
你生成tnnproto tnnmodel时修改输入看还有用。

**Comment by darrenyao87** [comment]
一般来说，模型的输入大小是不变的，如果要修改，下确保算法训练的时候就是可变输入大小的。改模型输入大小可以通过TNNSDKOption的input_shapes变量控制，可参考TNNFaceDetectorViewModel对应代码。

对于你这边代码Mat的大小target_dims，
auto rgbTNN = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC4, target_dims, rgbaData);
这个是给Mat告诉它输入维度是多少，由于data是你传入的，内部不会自动分配。
代码能正常运行是因为运行逻辑里面还没有用到你传入的target_dims，但后续扩展功能可能会用到，所以最好跟rgbaData的实际维度保持一致。
