### ISSUE TITLE
样例中arm版本编译不通过

### ISSUE THREAD

**Issue by zacks417** [Tencent/TNN#386]
linux/src/TNNImageClassify.cc中 包含头文件ImageClassifier.h文件不存在，应该是base下的 image_classifier.h
同样的linux/src/TNNFaceDetector.cc中包含的头文件UltraFaceDetector.h也不存在，改为ultra_face_detector.h
进行上述更改后继续编译build_armhf_linux.sh，出现如下错误：

[ 25%] Building CXX object CMakeFiles/demo_arm_linux_facedetector.dir/src/TNNFaceDetector/TNNFaceDetector.cc.o
[ 50%] Building CXX object CMakeFiles/demo_arm_linux_imageclassify.dir/src/TNNImageClassify/TNNImageClassify.cc.o
[ 75%] Linking CXX executable demo_arm_linux_facedetector
[100%] Linking CXX executable demo_arm_linux_imageclassify
CMakeFiles/demo_arm_linux_facedetector.dir/src/TNNFaceDetector/TNNFaceDetector.cc.o: In function `std::__shared_ptr<tnn::UltraFaceDetectorInput, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<tnn::UltraFaceDetectorInput>, std::shared_ptr<tnn::Mat>&>(std::_Sp_make_shared_tag, std::allocator<tnn::UltraFaceDetectorInput> const&, std::shared_ptr<tnn::Mat>&)':
TNNFaceDetector.cc:(.text._ZNSt12__shared_ptrIN3tnn22UltraFaceDetectorInputELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EJRSt10shared_ptrINS0_3MatEEEEESt19_Sp_make_shared_tagRKT_DpOT0_[_ZNSt12__shared_ptrIN3tnn22UltraFaceDetectorInputELN9__gnu_cxx12_Lock_policyE2EEC5ISaIS1_EJRSt10shared_ptrINS0_3MatEEEEESt19_Sp_make_shared_tagRKT_DpOT0_]+0x84): undefined reference to `tnn::TNNSDKInput::TNNSDKInput(std::shared_ptr<tnn::Mat>)'
TNNFaceDetector.cc:(.text._ZNSt12__shared_ptrIN3tnn22UltraFaceDetectorInputELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EJRSt10shared_ptrINS0_3MatEEEEESt19_Sp_make_shared_tagRKT_DpOT0_[_ZNSt12__shared_ptrIN3tnn22UltraFaceDetectorInputELN9__gnu_cxx12_Lock_policyE2EEC5ISaIS1_EJRSt10shared_ptrINS0_3MatEEEEESt19_Sp_make_shared_tagRKT_DpOT0_]+0x1e4): undefined reference to `vtable for tnn::UltraFaceDetectorInput'
CMakeFiles/demo_arm_linux_facedetector.dir/src/TNNFaceDetector/TNNFaceDetector.cc.o: In function `main':
TNNFaceDetector.cc:(.text.startup+0xb6): undefined reference to `tnn::UltraFaceDetectorOption::UltraFaceDetectorOption()'
TNNFaceDetector.cc:(.text.startup+0x146): undefined reference to `tnn::TNNSDKSample::TNNSDKSample()'
TNNFaceDetector.cc:(.text.startup+0x7d8): undefined reference to `tnn::Rectangle(void*, int, int, int, int, int, int, float, float)'
TNNFaceDetector.cc:(.text.startup+0xa08): undefined reference to `tnn::TNNSDKSample::~TNNSDKSample()'
TNNFaceDetector.cc:(.text.startup+0xb04): undefined reference to `vtable for tnn::UltraFaceDetector'
TNNFaceDetector.cc:(.text.startup+0xb2c): undefined reference to `typeinfo for tnn::UltraFaceDetectorOutput'
TNNFaceDetector.cc:(.text.startup+0xb30): undefined reference to `typeinfo for tnn::TNNSDKOutput'
collect2: error: ld returned 1 exit status
CMakeFiles/demo_arm_linux_facedetector.dir/build.make:83: recipe for target 'demo_arm_linux_facedetector' failed
make[2]: *** [demo_arm_linux_facedetector] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/demo_arm_linux_facedetector.dir/all' failed
make[1]: *** [CMakeFiles/demo_arm_linux_facedetector.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/demo_arm_linux_imageclassify.dir/src/TNNImageClassify/TNNImageClassify.cc.o: In function `std::__shared_ptr<tnn::TNNSDKInput, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<tnn::TNNSDKInput>, std::shared_ptr<tnn::Mat>&>(std::_Sp_make_shared_tag, std::allocator<tnn::TNNSDKInput> const&, std::shared_ptr<tnn::Mat>&)':
TNNImageClassify.cc:(.text._ZNSt12__shared_ptrIN3tnn11TNNSDKInputELN9__gnu_cxx12_Lock_policyE2EEC2ISaIS1_EJRSt10shared_ptrINS0_3MatEEEEESt19_Sp_make_shared_tagRKT_DpOT0_[_ZNSt12__shared_ptrIN3tnn11TNNSDKInputELN9__gnu_cxx12_Lock_policyE2EEC5ISaIS1_EJRSt10shared_ptrINS0_3MatEEEEESt19_Sp_make_shared_tagRKT_DpOT0_]+0x66): undefined reference to `tnn::TNNSDKInput::TNNSDKInput(std::shared_ptr<tnn::Mat>)'
CMakeFiles/demo_arm_linux_imageclassify.dir/src/TNNImageClassify/TNNImageClassify.cc.o: In function `main':
TNNImageClassify.cc:(.text.startup+0xac): undefined reference to `tnn::TNNSDKOption::TNNSDKOption()'
TNNImageClassify.cc:(.text.startup+0x124): undefined reference to `tnn::TNNSDKSample::TNNSDKSample()'
TNNImageClassify.cc:(.text.startup+0x584): undefined reference to `vtable for tnn::ImageClassifier'
TNNImageClassify.cc:(.text.startup+0x5a4): undefined reference to `typeinfo for tnn::ImageClassifierOutput'
TNNImageClassify.cc:(.text.startup+0x5a8): undefined reference to `typeinfo for tnn::TNNSDKOutput'
collect2: error: ld returned 1 exit status
CMakeFiles/demo_arm_linux_imageclassify.dir/build.make:83: recipe for target 'demo_arm_linux_imageclassify' failed
make[2]: *** [demo_arm_linux_imageclassify] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/demo_arm_linux_imageclassify.dir/all' failed
make[1]: *** [CMakeFiles/demo_arm_linux_imageclassify.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by neiltian-tencent** [comment]
fix by tag v0.2.2
