### ISSUE TITLE
winograd卷积输出有误

### ISSUE THREAD

**Issue by laoxie001** [Tencent/TNN#394]
测试环境：rk3288，Android
加速方式选ARM，输入的feature map宽高为偶数时，winograd卷积输出的feature map每个channel最后 a*b 大小的数据是错误的（a, b大小跟输入宽高有关）。输入feature map为奇数时没有问题。

![image](https://user-images.githubusercontent.com/57768395/93308692-2a02c080-f835-11ea-99e4-88688cbf730a.png)
如上图所示，左半边为arm加速的输出，右半边为opencl加速的输出，可以看到，最后4*4的数据不一致。

另外，arm加速下input data层3个channel第一个数据都是-1.00394，与实际数据不符。
![image](https://user-images.githubusercontent.com/57768395/93308247-9a5d1200-f834-11ea-8c0a-b7948caab2fb.png)

**Comment by seanxcwang** [comment]
> 测试环境：rk3288，Android
> 加速方式选ARM，输入的feature map宽高为偶数时，winograd卷积输出的feature map每个channel最后 a*b 大小的数据是错误的（a, b大小跟输入宽高有关）。输入feature map为奇数时没有问题。
> 
> ![image](https://user-images.githubusercontent.com/57768395/93308692-2a02c080-f835-11ea-99e4-88688cbf730a.png)
> 如上图所示，左半边为arm加速的输出，右半边为opencl加速的输出，可以看到，最后4*4的数据不一致。
> 
> 另外，arm加速下input data层3个channel第一个数据都是-1.00394，与实际数据不符。
> ![image](https://user-images.githubusercontent.com/57768395/93308247-9a5d1200-f834-11ea-8c0a-b7948caab2fb.png)

看上去确实有问题，能告知下winograd出错的那组参数是什么，我快速复现下

**Comment by laoxie001** [comment]
> > 测试环境：rk3288，Android
> > 加速方式选ARM，输入的feature map宽高为偶数时，winograd卷积输出的feature map每个channel最后 a*b 大小的数据是错误的（a, b大小跟输入宽高有关）。输入feature map为奇数时没有问题。
> > ![image](https://user-images.githubusercontent.com/57768395/93308692-2a02c080-f835-11ea-99e4-88688cbf730a.png)
> > 如上图所示，左半边为arm加速的输出，右半边为opencl加速的输出，可以看到，最后4*4的数据不一致。
> > 另外，arm加速下input data层3个channel第一个数据都是-1.00394，与实际数据不符。
> > ![image](https://user-images.githubusercontent.com/57768395/93308247-9a5d1200-f834-11ea-8c0a-b7948caab2fb.png)
> 
> 看上去确实有问题，能告知下winograd出错的那组参数是什么，我快速复现下

卷积参数：kernel_size: 3，stride: 1，pad: 0，输入32*110*94，输出64*108*92

**Comment by seanxcwang** [comment]
armv7在某些特定的参数下，比如`tile_count%8 > 4`的情况，目前看到最小能复现这个错误的input shape是8x22x6，pad=0，应该是汇编的kernel尾数处理有点问题

**Comment by quinnrong94** [comment]
> 另外，arm加速下input data层3个channel第一个数据都是-1.00394，与实际数据不符。
> ![image](https://user-images.githubusercontent.com/57768395/93308247-9a5d1200-f834-11ea-8c0a-b7948caab2fb.png)

input的shape是多少，是否有做什么预处理？ @laoxie001

**Comment by laoxie001** [comment]
> > 另外，arm加速下input data层3个channel第一个数据都是-1.00394，与实际数据不符。
> > ![image](https://user-images.githubusercontent.com/57768395/93308247-9a5d1200-f834-11ea-8c0a-b7948caab2fb.png)
> 
> input的shape是多少，是否有做什么预处理？ @laoxie001

input shape为3, 112, 96, 我是直接读取的BGR数据，然后手动转为nchw_float格式赋值给mat，然后就发现无论哪张图，input data的3个channel第一个数据都是-1.00394.

**Comment by quinnrong94** [comment]
> > > 另外，arm加速下input data层3个channel第一个数据都是-1.00394，与实际数据不符。
> > > ![image](https://user-images.githubusercontent.com/57768395/93308247-9a5d1200-f834-11ea-8c0a-b7948caab2fb.png)
> > 
> > 
> > input的shape是多少，是否有做什么预处理？ @laoxie001
> 
> input shape为3, 112, 96, 我是直接读取的BGR数据，然后手动转为nchw_float格式赋值给mat，然后就发现无论哪张图，input data的3个channel第一个数据都是-1.00394.

基于最新的master分支，用arm32和arm64分别做了测试：随机构造了类型为NCHW_FLOAT，dims为{1，3，112，96}的mat作为输入，经过ConvertFromMat和ConvertToMat之后，dump出来的data和原始数据是一致的。
@laoxie001 更新到最新的master看是否仍然有问题？

**Comment by laoxie001** [comment]
@quinnrong94 最新版的master跑出来的数据完全不对了，_(:з」∠)_ 
![image](https://user-images.githubusercontent.com/57768395/93474208-a1b21780-f929-11ea-9f36-9590415898f3.png)
上图左边为arm加速的input data层数据，右边为opencl加速的input data层数据。输入shape为（1,3,32,32）

我这边是把每一层的名字用AddOutput加入输出，forward后再取出每一层的数据，写法应该没什么问题吧
![image](https://user-images.githubusercontent.com/57768395/93474969-a7f4c380-f92a-11ea-9738-17e61be2ed6d.png)

![image](https://user-images.githubusercontent.com/57768395/93475076-c955af80-f92a-11ea-9a90-b6b1181d6d5b.png)

**Comment by quinnrong94** [comment]
> @quinnrong94 最新版的master跑出来的数据完全不对了，_(:з」∠)_
> ![image](https://user-images.githubusercontent.com/57768395/93474208-a1b21780-f929-11ea-9f36-9590415898f3.png)
> 上图左边为arm加速的input data层数据，右边为opencl加速的input data层数据。输入shape为（1,3,32,32）
> 
> 我这边是把每一层的名字用AddOutput加入输出，forward后再取出每一层的数据，写法应该没什么问题吧
> ![image](https://user-images.githubusercontent.com/57768395/93474969-a7f4c380-f92a-11ea-9738-17e61be2ed6d.png)
> 
> ![image](https://user-images.githubusercontent.com/57768395/93475076-c955af80-f92a-11ea-9a90-b6b1181d6d5b.png)

input_cvt_param中的参数是多少，scale和bias的值是设置过的吗？

**Comment by laoxie001** [comment]
@quinnrong94  scale和bias都设置了的，我把完整代码贴出来你看看，测试数据和模型也贴出来
[test_data_model.zip](https://github.com/Tencent/TNN/files/5243857/test_data_model.zip)



#include <tnn/core/tnn.h>
#include <string>
#include <stdio.h>
#include <string.h>
#include <iostream>
#include <fstream>
#include <sys/time.h>
#include <sstream>
#include <vector>
#include <math.h>
#include <algorithm>
#include <iomanip>

const int input_n = 1;
const int input_c = 3;
const int input_h = 32;
const int input_w = 32;

std::string fdLoadFile(std::string path) 
{
	std::ifstream file(path, std::ios::in);
	if (file.is_open()) {
		file.seekg(0, file.end);
		int size  = file.tellg();
		char* content = new char[size];

		file.seekg(0, file.beg);
		file.read(content, size);
		std::string fileContent;
		fileContent.assign(content, size);
		delete[] content;
		file.close();
		return fileContent;
	} else {
		return "";
	}
}

int f2(const char *param,const char *model,int use_opencl,const char *outfile)
{
	TNN_NS::Status status = TNN_NS::TNN_OK;
	TNN_NS::TNN net;
	TNN_NS::ModelConfig model_cfg;
	model_cfg.model_type = TNN_NS::MODEL_TYPE_TNN;
	
	model_cfg.params.push_back(fdLoadFile(param));
	model_cfg.params.push_back(fdLoadFile(model));
	
	status = net.Init(model_cfg);
	if (status != TNN_NS::TNN_OK) { printf("load model failed 0x%x.\n", (int)status); return -1; }
	printf("load model success.\n");
	
	std::vector<std::string> layername={"data_input", "conv1", "pool1", "conv2", "pool2", "conv3", "pool3", "conv4"};
	int layernum = layername.size();
	for(int i = 0; i < layernum; i++)
	{
		net.AddOutput(layername[i],i);
	}
	
	TNN_NS::InputShapesMap inputs;

	std::vector<int> input_dims;
	input_dims.push_back(input_n);
	input_dims.push_back(input_c);
	input_dims.push_back(input_h);
	input_dims.push_back(input_w);

	inputs.insert(std::pair<std::string, TNN_NS::DimsVector>("data_input", input_dims));
	
	TNN_NS::NetworkConfig net_cfg;
	if(use_opencl==1)
		net_cfg.device_type = TNN_NS::DEVICE_OPENCL;
	else if(use_opencl==0)
		net_cfg.device_type = TNN_NS::DEVICE_ARM;
	
	std::shared_ptr<TNN_NS::Instance> instance = net.CreateInst(net_cfg, status, inputs);
	if (status != TNN_NS::TNN_OK || !instance) { printf("create instance failed.\n"); return -1; }
	
	TNN_NS::MatConvertParam input_cvt_param;
	input_cvt_param.scale = { 0.0078125, 0.0078125, 0.0078125, 0 };
	input_cvt_param.bias = { -127.5*0.0078125, -127.5*0.0078125 , -127.5*0.0078125, 0 };
	
	std::ofstream out(outfile);
	float *tmpdata = new float[input_c*input_h*input_w];

	std::string imgpath = "../data";
	out<<imgpath<<"\n";
	
	FILE *fp = fopen(imgpath.c_str(),"rb");
	unsigned char filedata[input_c*input_h*input_w];
	int ret = fread(filedata, input_c*input_h*input_w, 1, fp);
	if(ret!=1)printf("read image failed!\n");
	fclose(fp);
	
	for(int i=0;i<input_h*input_w;i++)
	{
		tmpdata[i]=(filedata[3*i]-127.5f)/128.0f;
		tmpdata[i+input_h*input_w]=(filedata[3*i+1]-127.5f)/128.0f;
		tmpdata[i+2*input_h*input_w]=(filedata[3*i+2]-127.5f)/128.0f;
	}
	
	std::shared_ptr<TNN_NS::Mat> image_mat;
	image_mat= std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_ARM, TNN_NS::NCHW_FLOAT, input_dims, tmpdata);
	
	status = instance->SetInputMat(image_mat, input_cvt_param);
	if (status != TNN_NS::TNN_OK) { printf("convert input failed.\n"); return -1; }
	
	status = instance->Forward();
	if (status != TNN_NS::TNN_OK) { printf("forward failed.\n"); return -1; }
	
	for(int i = 0; i < layernum; i++)
	{
		std::shared_ptr<TNN_NS::Mat> output_mat_scores = nullptr;
		status = instance->GetOutputMat(output_mat_scores,input_cvt_param,layername[i]);
		if (status != TNN_NS::TNN_OK) { printf("output failed.\n"); return -1; }
		float * data = (float *)output_mat_scores->GetData();
		int c = output_mat_scores->GetChannel();
		int h = output_mat_scores->GetHeight();
		int w = output_mat_scores->GetWidth();
		
		out<<layername[i]<<"  "<<c<<"*"<<h<<"*"<<w<<"\n";
		
		for(int j = 0; j< c; j++)
		{
			out<<layername[i]<<"_c"<<j<<"\n";
			for(int k = 0; k < h; k++)
			{
				for(int p = 0; p < w; p++)
				{
					out<<std::setprecision(6)<<std::setw(12)<<data[j*h*w + k*w + p];
				}
				out<<"\n";
			}
			out<<"\n";
		}
		out<<"\n\n";
	}
	
	out.close();
	delete[]tmpdata;
	return 0;
}

int main(int argc, char *argv[])
{
	if(strcmp(argv[1],"cpu") == 0)
	{
		f2("../test.tnnproto", "../test.tnnmodel", 0, argv[2]);
	}
	else if(strcmp(argv[1], "gpu") == 0)
	{
		f2("../test.tnnproto", "../test.tnnmodel", 1, argv[2]);
	}
	
	return 0;
}

**Comment by quinnrong94** [comment]
@laoxie001 你这个用例，input_cvt_param的scale应该指定为1，bias应该指定为0，或者用默认构造的MatConvertParam即可。因为你的input mat已经做过乘以scale加上bias的操作，不需要tnn内部再处理了。

对于nchw_float类型的input mat，目前tnn这边opencl和arm的处理方式不一样，导致dump的结果不一致的。这个问题我们近期做统一。

**Comment by laoxie001** [comment]
@quinnrong94 感谢，经验证，input_cvt_param改为默认构造值后，arm和opencl的input data数据现在是一致的了。
另外上面的winograd卷积在tile_count%8 > 4时输出结果不对的问题有进展吗:)

**Comment by seanxcwang** [comment]
> @quinnrong94 感谢，经验证，input_cvt_param改为默认构造值后，arm和opencl的input data数据现在是一致的了。
> 另外上面的winograd卷积在tile_count%8 > 4时输出结果不对的问题有进展吗:)

这个问题修复了，麻烦拉下最新的master

**Comment by laoxie001** [comment]
@seanxcwang  感谢，问题已解决，我先close了
