### ISSUE TITLE
The onnx model not aligned with tnn model

### ISSUE THREAD

**Issue by algpower** [Tencent/TNN#396]
E/tnn: virtual tnn::Status tnn::PermuteLayer::InferOutputShape() [File /home/TNN/source/tnn/layer/permute_layer.cc][Line 45] Permute param got wrong size.
E/tnn: virtual tnn::Status tnn::DefaultNetwork::InitLayers(tnn::NetStructure*, tnn::NetResource*) [File /home/TNN/source/tnn/core/default_network.cc][Line 234] Error Init layer Transpose_574 (err: 4096 or 0x1000)
E/tnn: tnn::Status tnn::ModelChecker::Init(tnn::NetworkConfig&, tnn::ModelConfig&, tnn::InputShapesMap) [File /home/TNN/tools/model_check/model_checker.cc][Line 64] create cpu instance falied: code: 0x1000 msg: Permute param got wrong size

----------   Unfortunately   ----------
The onnx model not aligned with tnn model

**Comment by algpower** [comment]
https://github.com/ultralytics/yolov5/releases/download/v3.0/yolov5s.pt

**Comment by darrenyao87** [comment]
@gttiankai 文档添加下yolov5s的处理方式

**Comment by gttiankai** [comment]
已更新，相关内容详见下面的 wiki 的内容。
https://github.com/Tencent/TNN/wiki/%E6%A8%A1%E5%9E%8B%E8%BD%AC%E6%8D%A2Faq
