### ISSUE TITLE
onnx2tnn转换报错

### ISSUE THREAD

**Issue by AstonnMartin** [Tencent/TNN#409]
下载了最新的docker镜像。我运行了
docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py onnx2tnn /workspace/trial.onnx  -o /workspace

结果是：

python3: /opt/TNN/tools/onnx2tnn/src/core/onnx_utility.cc:560: const float* get_tensor_proto_data(const onnx::TensorProto&): Assertion `0' failed.
Aborted

Converter ONNX to TNN model failed!

我的模型只是简单的两个卷积层跟两个全连接层。请大佬多指教。
[trial.onnx.zip](https://github.com/Tencent/TNN/files/5242525/trial.onnx.zip)

**Comment by 1627180283** [comment]
你转换命令里加上 -optimize 试一下，加上之后我测试是可以成功转换的

**Comment by gttiankai** [comment]
@AstonnMartin 转换工具的文档中 **强烈** 建议大家转换的时候打开-optimize 优化选项，这个会对 onnx 模型进行优化和常量折叠等优化，可以保证大部分的模型转换成功。

**Comment by AstonnMartin** [comment]
搞定。感谢。
