### ISSUE TITLE
 error::op convert failed onnx:Expand

### ISSUE THREAD

**Issue by gofugoo** [Tencent/TNN#413]
onnx  op version11 
模型如下
[yolov_simp.onnx.zip](https://github.com/Tencent/TNN/files/5244384/yolov_simp.onnx.zip)

python3 converter.py onnx2tnn weights/yolov_simp.onnx -o . -v v1.0 -optimize -align

----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model

E/converter: int Onnx2TNN::TNNWriteProto() [File TNN-master/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 310] error::op convert failed onnx:Expand
Assertion failed: (0), function TNNWriteProto, file TNN-master/tools/onnx2tnn/src/core/onnx2tnn.cc, line 311.

Converter ONNX to TNN model failed!

**Comment by 1627180283** [comment]
<img width="193" alt="image" src="https://user-images.githubusercontent.com/37806708/93735763-a4a25600-fc10-11ea-9dba-e0a5c8f7158e.png">
模型里面含有 tnn 不支持的算子 Expand 和 ScatterND，可以将他们替换后再进行转换。
或者可以参考 tnn 提供的 yolo v5 ：https://github.com/darrenyao87/tnn-models/tree/master/model/yolov5
