### ISSUE TITLE
./src/main/jni/include/thirdparty/opencl/include\CL/cl2.hpp:1523: undefined reference to `clReleaseContext'

### ISSUE THREAD

**Issue by hufangjian** [Tencent/TNN#415]
我用最新的代码编译android libTNN.so 库。修改安卓example 直接链接到libTNN.so库报以下错误。

CMakeFiles/tnn_wrapper.dir/src/main/jni/cc/tnn_jni.cc.o: In function `cl::detail::ReferenceHandler<_cl_context*>::release(_cl_context*)':
C:\workspace\project\android\TNN_ANDROID\facerecog\android\demo\.cxx\cmake\debug\arm64-v8a/../../../../src/main/jni/include/thirdparty/opencl/include\CL/cl2.hpp:1523: undefined reference to `clReleaseContext'
CMakeFiles/tnn_wrapper.dir/src/main/jni/cc/tnn_jni.cc.o: In function clReleaseContext`cl::detail::ReferenceHandler<_cl_command_queue*>::release(_cl_command_queue*)':
C:\workspace\project\android\TNN_ANDROID\facerecog\android\demo\.cxx\cmake\debug\arm64-v8a/../../../../src/main/jni/include/thirdparty/opencl/include\CL/cl2.hpp:1532: undefined reference to `clReleaseCommandQueue'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

应该是找不到 clReleaseContext   clReleaseCommandQueue 两个函数的定义，在2个函数在opencl_wrapper.cc 里面定义了。

我在第一版的TNN自己编译了android动态连接库是可以正常运行的。最新发布的版本就不行。
应该是动态连接库的问题，我把原始的example  cmakelist   改成set(TNN_BUILD_SHARED ON CACHE BOOL "" FORCE)
也会报同样的错误，请问一下怎么生成动态连接库？

**Comment by neiltian-tencent** [comment]
因为TNN隐藏了opencl的符号，sdk使用opencl符号需要自己封装，TNN只封装了部分opencl 符号， 如果暴露会导致兼容性问题。

**Comment by neiltian-tencent** [comment]
具体可参照TNN的实现方式，在sdk层实现你需要的接口。

**Comment by hufangjian** [comment]
好的。谢谢。
