### ISSUE TITLE
onnx转tnn报input_blob_shape invalid

### ISSUE THREAD

**Issue by weiyaodu** [Tencent/TNN#422]
pytorch 转换 onnx 成功，结果验证一致。转 tnn 时出现如下错误，不知该如何分析？

> D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /Users/yaoduwei/PROJ/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 404] const node = 1538
> D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /Users/yaoduwei/PROJ/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 404] const node = 1552
> D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /Users/yaoduwei/PROJ/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 404] const node = 1555
> D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /Users/yaoduwei/PROJ/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 404] const node = 1557
> D/converter: int Onnx2TNN::OnnxExtractBlobWeights() [File /Users/yaoduwei/PROJ/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 404] const node = 1558
> E/converter: int Onnx2TNN::TNNWriteProto() [File /Users/yaoduwei/PROJ/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc][Line 249] input_blob_shape invalid
> Assertion failed: (0), function TNNWriteProto, file /Users/yaoduwei/PROJ/TNN/tools/onnx2tnn/src/core/onnx2tnn.cc, line 250.
> zsh: abort      python onnx2tnn.py model.onnx -version=v1.0 -optimize=0 -half=0 -o ~/Desktop

**Comment by 1627180283** [comment]
方便提供模型吗？我来定位一下问题

**Comment by gttiankai** [comment]
你模型的输入是多少？ 用 netron 的可视化结果截个图？

**Comment by weiyaodu** [comment]
> 方便提供模型吗？我来定位一下问题

我把 onnx 模型传到网盘了，麻烦看看
链接: https://pan.baidu.com/s/1WCDy8whoVoNhJ_qiwOgmWg 提取码: ypza

**Comment by weiyaodu** [comment]
> 你模型的输入是多少？ 用 netron 的可视化结果截个图？

![Uploading 926AE040-6956-449B-B907-E1FF162EADB8.png…]()

**Comment by 1627180283** [comment]
模型里面都是对三维的数据进行操作，TNN 不支持这样的 shape，可以替换为四维再次尝试转换

**Comment by weiyaodu** [comment]
> 模型里面都是对三维的数据进行操作，TNN 不支持这样的 shape，可以替换为四维再次尝试转换

好的，非常感谢，我转一下试试
