### ISSUE TITLE
 Android 静态包的问题

### ISSUE THREAD

**Issue by sxj731533730** [Tencent/TNN#426]
我发现我使用TNN编译出的Android版的动态包在Android中可以使用，但是静态包是无法在Android中使用的，是否有人遇到同样的问题？ 官方小哥哥测试过吗？

**Comment by matfeb** [comment]
@sxj731533730 Hi, I have the same problem. Functions from the compiled library (shared) are not found inside the application. I've changed the CMakeList.txt file 
```
include_directories(${CMAKE_SOURCE_DIR}/src/main/jni/include)
include_directories(${CMAKE_SOURCE_DIR}/src/main/jni/cc)

add_library(TNN
            SHARED
            IMPORTED)
set_target_properties(TNN
            PROPERTIES
            IMPORTED_LOCATION
            ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libTNN.so)
```

**Comment by sxj731533730** [comment]
哦，好的，谢谢你,在您的帮助下，我也解决了我的问题了；
ｏｋ,ｔｈａｎk you very much,I have also solved my problem with your helping;

**Comment by matfeb** [comment]
How did you solve your problem as I have still mine ? Does your functions are working when you call them ? What did you change exactly ?
My main issue is when I call a function (e.g. FaceDetector.init()) it is not found despite that I've linked libTNN.so in my CMakeList

```No implementation found for int com.tencent.tnn.demo.FaceDetector.init(java.lang.String, int, int, float, float, int, int) (tried Java_com_tencent_tnn_demo_FaceDetector_init and Java_com_tencent_tnn_demo_FaceDetector_init__Ljava_lang_String_2IIFFII)```
