### ISSUE TITLE
单通道图像设置scale和bias后预测结果为-nan

### ISSUE THREAD

**Issue by blueskywwc** [Tencent/TNN#427]
输入图像为单通道，设置input_cvt_param的scale为1.0和bias为0.0，scale和bias的设置方式试了多种(4个值，3个值，1个值)

加上: instance->SetInputMat(image_mat, input_cvt_param);后预测结果为-nan，不加此行代码可预测出数据

实际过程中需要对图像进行处理，所以要对input_cvt_param进行设置，该怎么解决nan的问题，谢谢!

**Comment by devandong** [comment]
请问使用的那种type的Mat，scale和bias给出的是单个值吗

**Comment by blueskywwc** [comment]
int predict(const char *param,const char *model)
{
    TNN_NS::Status status = TNN_NS::TNN_OK;
    TNN_NS::TNN net;
    TNN_NS::ModelConfig model_cfg;
    model_cfg.model_type = TNN_NS::MODEL_TYPE_TNN;

    model_cfg.params.push_back(fdLoadFile(param));
    model_cfg.params.push_back(fdLoadFile(model));

    status = net.Init(model_cfg);
    if (status != TNN_NS::TNN_OK)
    {
        printf("load model failed 0x%x.\n", (int)status); return -1;
    }
    else
    {
        printf("load model success.\n");
    }


    std::vector<int> input_dims = {1, 1, 128, 128};

    TNN_NS::NetworkConfig net_cfg;
    net_cfg.device_type = TNN_NS::DEVICE_ARM;
    
    std::shared_ptr<TNN_NS::Instance> instance = net.CreateInst(net_cfg,status);
    if (status != TNN_NS::TNN_OK || !instance) { printf("create instance failed.\n"); return -1; }

    TNN_NS::MatConvertParam input_cvt_param;
//    input_cvt_param.scale = {0.007843137};
//    input_cvt_param.bias = {-1.0};
    input_cvt_param.scale = {0.007843137, 0.007843137, 0.007843137, 0.0};
    input_cvt_param.bias  = {-1.0, -1.0, -1.0, 0.0};

//    char *input_img="../model/BaiYaoRong-L_000032.jpg";
    char *input_img="../model/CS07B-105-R2-NG-20190929-18_8_7.662_03.FoldMid_1027_508.jpg";
    int w, h, c;
    unsigned char *data = stbi_load(input_img, &w, &h, &c, 0);
    cout <<"input: "<< w << " " << h << " " << c << endl;
    int ow =128;
    int oh = 128;
    auto *odata = (unsigned char *) malloc(ow * oh * c);

    //改变图片尺寸
    stbir_resize(data, w, h, 0, odata, ow, oh, 0, STBIR_TYPE_UINT8, c, STBIR_ALPHA_CHANNEL_NONE, 0,
                 STBIR_EDGE_CLAMP, STBIR_EDGE_CLAMP,
                 STBIR_FILTER_BOX, STBIR_FILTER_BOX,
                 STBIR_COLORSPACE_SRGB, nullptr
    );
    cout <<"output: "<< ow << " " << oh << " " << c << endl;

    
    std::shared_ptr<TNN_NS::Mat> image_mat;
    image_mat= std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_ARM, TNN_NS::NCHW_FLOAT, input_dims, odata);

    std::vector<int> dim=image_mat->GetDims();
    cout<<"dim: "<<dim[0]<<" "<<dim[1]<<" "<<dim[2]<<" "<<dim[3]<<endl;

    status = instance->SetInputMat(image_mat, input_cvt_param);
    if (status != TNN_NS::TNN_OK) { printf("convert input failed.\n"); return -1; }

    status = instance->Forward();
    if (status != TNN_NS::TNN_OK) { printf("forward failed.\n"); return -1; }


    std::shared_ptr<TNN_NS::Mat> output_mat_scores = nullptr;
    status = instance->GetOutputMat(output_mat_scores,input_cvt_param);
    if (status != TNN_NS::TNN_OK) { printf("output failed.\n"); return -1; }
    float *score_data = (float *)output_mat_scores.get()->GetData();
    int fc = output_mat_scores->GetChannel();
    int fh = output_mat_scores->GetHeight();
    int fw = output_mat_scores->GetWidth();

    cout<<"type: "<<typeid(score_data).name()<<"\n";
    cout<<"result chw: "<<fc<<"*"<<fh<<"*"<<fw<<"\n";
    //打印得分
    cout<<"score_data: "<<score_data[0]<<"*"<<score_data[1]<<"*"<<score_data[2]<<"\n";

    stbi_image_free(data);
    stbi_image_free(odata);
    return 0;
}

你好，上面是我的代码，scale和bias我试过单值，2值，3值，4值，输出结果均为-nan，帮忙看下，谢谢

**Comment by blueskywwc** [comment]
我刚刚也试了3通道:对于三通道图像(模型输入也为三通道)，加上: instance->SetInputMat(image_mat, input_cvt_param)后预测结果为nan，不加此行代码可预测出数据(但结果不对)，是哪里出现了问题，谢谢!

**Comment by devandong** [comment]
你好，将input_mat的mat_type修改为NGRAY或N8UC4，再尝试下呢
`
image_mat= std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_ARM, TNN_NS::NGRAY, input_dims, odata);
`

**Comment by blueskywwc** [comment]
你好，改为TNN_NS::NGRAY后OK，谢谢
