### ISSUE TITLE
华为荣耀手机型号BLN-AL40 在使用GPU的方式去初始化模型时，出现 OpenCL Runtime Init() failed (ret = 36865)

### ISSUE THREAD

**Issue by chenhucxc** [Tencent/TNN#429]
![image](https://user-images.githubusercontent.com/24583220/94119712-dcfc9b00-fe81-11ea-8f46-d3ac8ab4eb32.png)
上面的是报错信息。
同样的apk文件，早OPPO R9上运行，是正常的，请问这是什么原因呢？
此外，在MTK 8163平台，在使用Linux平台下编译的可执行文件，在adb shell后，data目录下运行，可以使用GPU来初始化模型，但是在Android 平台下生成apk使用GPU方式初始化模型出现了错误。
设备信息如下：
![image](https://user-images.githubusercontent.com/24583220/94120308-8b084500-fe82-11ea-803b-13e064ad8eaa.png)

**Comment by chenhucxc** [comment]
我这边在网上搜索到的资料，此问题出现的原因是：部分Android 7.0 的设备，当采用OpenCL对部分NDK代码进行加速的时候，会出现在运行过程中无法调用厂商提供的libOpenCL库，究其原因是权限不够。[详情链接](https://www.cnblogs.com/thisisajoke/p/12759985.html)
我这边是改设备system下的文件，路径：vendor/etc/public.libraries.txt
step1: adb shell
step2: su
step3: mount -o rw,remount /system
step4: echo libOpenCL.so >> public.libraries.txt
strp5: 重启设备
这种方式确实解决了初始化的问题，但是前提是要将设备进行root。不知道是否有更好的方式来处理这个问题

**Comment by neiltian-tencent** [comment]
这个问题是从Android 7.0系统引入的，系统库可供第三方库使用，需要显示指定。华为开始推Android 7.0的系统，没有适配，就导致了系统库加载不起来，这个问题第三方库是没办法解决的，属于权限问题。后面厂商升级了系统基本都适配了。

**Comment by neiltian-tencent** [comment]
如果你是特定机器部署，可以root配置权限，或者升级系统。如果是非特定机器部署，没办法解决，只能切换的arm加速。

**Comment by chenhucxc** [comment]
好的，多谢解答

**Comment by Semper4u** [comment]
你好，我现在遇到了一样的问题，我的是Android11， Mali G52 的gpu，根据上述修改了libOpenCL.so libGLES_mali.so到public.libraries.txt中，但是依旧是OpenCL Runtime Init() failed (ret = 36865)!，请教一下该怎么弄呢

**Comment by Semper4u** [comment]
我在benchmark中使用opencl测试没有问题，请帮忙排查一下

**Comment by elxy** [comment]
原因是Android限制了私有库的链接权限，参见[原生库的命名空间 | Android 开源项目 | Android Open Source Project](https://source.android.com/docs/core/permissions/namespaces_libraries)。暂时规避的做法可以将项目的`targetSdkVersion`设置为`≤23`，参考[当应用关联到私有原生库时会发生什么情况](http://android-developers.blogspot.com/2016/06/improving-stability-with-private-cc.html)。
