### ISSUE TITLE
TNN有没有加载图片并预处理的API

### ISSUE THREAD

**Issue by blueskywwc** [Tencent/TNN#430]
TNN有没有类似NCNN的API:    ncnn::Mat::from_pixels_resize，方便加载图片并预处理，谢谢

**Comment by neiltian-tencent** [comment]
TNN提供了Mat接口，提供了resize, crop, warpaffine，cvtcolor等常用处理能力。并且传入网络输入前可以通过scale，bias，对mat输入进行归一化处理。

**Comment by darrenyao87** [comment]
简单预处理已经实现了，见mat_utils.h，包括Resize、Crop、WarpAffine、CvtColor，送入网络前可通过MatConvertParam进行scale和bias归一化。

TNN构建了TNNSDKSample基础类，方便用户通过继承的方式构建自己的SDK。建议直接看blazeface_detector.h

**Comment by blueskywwc** [comment]
好的，谢谢
