### ISSUE TITLE
 _Net->CreateInst   code :4096  message: "Permute param got wrong size"

### ISSUE THREAD

**Issue by gofugoo** [Tencent/TNN#433]
# Platform(Include target platform as well if cross-compiling):  
Android

# Github Version:
https://github.com/Tencent/TNN/releases/tag/v0.2.3

# 编译方式:
# Compiling Method
    cmake -GNinja \
      -DCMAKE_TOOLCHAIN_FILE=cmake/android.toolchain.cmake \
      -DDEBUG=OFF \
      -DANDROID_ABI="arm64-v8a" \
      -DANDROID_STL=c++_shared \
      -DANDROID_NATIVE_API_LEVEL=27  \
      -DANDROID_TOOLCHAIN=clang \
      -DBUILD_FOR_ANDROID_COMMAND=true \
      -DTNN_ARM_ENABLE=ON \
      -DTNN_HUAWEI_NPU_ENABLE=OFF \
      -DTNN_OPENCL_ENABLE=ON \
      -DSHARING_MEM_WITH_OPENGL=ON \
      -DTNN_BUILD_SHARED=ON ../..

错误描述:
   _instance = _Net->CreateInst(network_config, status);
Status 返回：
code :4096  message: "Permute param got wrong size"

附上我转化后的模型
[all.zip](https://github.com/alibaba/MNN/files/5286133/all.zip)

**Comment by gttiankai** [comment]
你好，非常感谢给我们提 issue。
如下图所示， permute 是 5 维的操作，目前 TNN 还不支持 5 维的操作。
![企业微信截图_2b36342b-c363-4c2e-b11a-2b1d58654e41](https://user-images.githubusercontent.com/5379313/94354178-24b23b00-00ab-11eb-885a-ee551477ff4e.png)

**Comment by gofugoo** [comment]
> 你好，非常感谢给我们提 issue。
> 如下图所示， permute 是 5 维的操作，目前 TNN 还不支持 5 维的操作。
> ![企业微信截图_2b36342b-c363-4c2e-b11a-2b1d58654e41](https://user-images.githubusercontent.com/5379313/94354178-24b23b00-00ab-11eb-885a-ee551477ff4e.png)

目前支持几维操作？

**Comment by southsea0725** [comment]
如果onnx模型包含Permute，转tnn可以成功，只是不能加载，如果从onnx模型删除Permute等节点，则又无法转换tnn成功。
[LP8.zip](https://github.com/Tencent/TNN/files/5839519/LP8.zip)
这里是删除了Permute节点的onnx模型，转tnn是不能成功的，报错信息：
Conversion to tnn failed :(

**Comment by southsea0725** [comment]
Onnx模型删除Permute节点之后，转ncnn是没有问题的，推理结果也是正确的。
