### ISSUE TITLE
ARM样例代码数据不会初始化

### ISSUE THREAD

**Issue by zacks417** [Tencent/TNN#449]
之前提过一个issue是编译不通过，切换到0.2.2之后能编译， 我改好代码跑自己模型与服务器端结果不一致。 找了很久的bug发现是输入数据不对。
刚才测试了样例的demo_arm_linux_imageclassify，输入不管是dog.png还是car.png 结果都是预测table，1000个节点输出是一样的。
进一步找bug发现auto image_mat = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_ARM, TNN_NS::N8UC3, nchw, data); 这里并没有进入Mat类的构造函数，数据没有传进去

**Comment by zacks417** [comment]
![image](https://user-images.githubusercontent.com/40654162/95535555-57e5ba00-0a1b-11eb-9429-827c16c98181.png)

**Comment by quinnrong94** [comment]
demo_arm_linux_imageclassify结果一致的问题是由于运行环境下的TNN动态库未更新导致。

**Comment by quinnrong94** [comment]
对于非图像输入，例如语音信息，可以创建NCHW_FLOAT格式的mat作为input。以snoring_detect模型为例，该模型输入维度：1x5x96x64，输入数据类型：float；输出维度：1x2x1x1，输出数据类型：float。步骤如下:

**Comment by quinnrong94** [comment]
1. 定制SnoringDetectorOutput和SnoringDetector类，放置在TNN/examples/base路径下
[snoring_detector.zip](https://github.com/Tencent/TNN/files/5389100/snoring_detector.zip)

2. 实现snoring_detect_demo，放置在TNN/examples/linux/src下
[snoring_detect.zip](https://github.com/Tencent/TNN/files/5389106/snoring_detect.zip)

3. 修改TNN/examples/linux/CMakeLists.txt，在末行加入：
`add_executable(demo_arm_linux_snoringdetector src/snoring_detect.cc ${SRC})`

4. 运行TNN/examples/linux/build_linux.sh脚本，编译可执行文件demo_arm_linux_snoringdetector

5. 运行demo_arm_linux_snoringdetector，需指定tnnproto和tnnmodel文件
