### ISSUE TITLE
安卓demo gradle失败

### ISSUE THREAD

**Issue by Rancherzhang** [Tencent/TNN#45]
按照https://github.com/Tencent/TNN/blob/master/doc/cn/user/demo.md中的安卓demo, 出现了如下的问题：
`
debug|armeabi-v7a :-- 	Arm:	ON
debug|armeabi-v7a :-- 	Metal:	OFF
debug|armeabi-v7a :-- 	OpenCL:	ON
debug|armeabi-v7a :-- 	CUDA:	OFF
debug|armeabi-v7a :-- 	DSP:	OFF
debug|armeabi-v7a :-- 	Atlas:	OFF
debug|armeabi-v7a :-- 	NPU:	OFF
debug|armeabi-v7a :-- 	OpenMP:	OFF
debug|armeabi-v7a :-- 	TEST:	OFF
debug|armeabi-v7a :-- 	--Unit Test:	OFF
debug|armeabi-v7a :-- 	Qantization:	OFF
debug|armeabi-v7a :-- 	ModelCheck:	OFF
debug|armeabi-v7a :-- 	DEBUG:	
debug|armeabi-v7a :-- 	PROFILE:	OFF
debug|armeabi-v7a :-- 	BENCHMARK:	OFF
debug|armeabi-v7a :-- 	BENCHMARK Layer:	OFF
debug|armeabi-v7a :--      enable armv7 neon
debug|armeabi-v7a :CMake Error at ../../../platforms/android/CMakeLists.txt:14 (if):
debug|armeabi-v7a :  if given arguments:
debug|armeabi-v7a :    "21" "GREATER_EQUAL" "21"
debug|armeabi-v7a :  Unknown arguments specified
debug|armeabi-v7a :Call Stack (most recent call first):
debug|armeabi-v7a :  ../../../CMakeLists.txt:272 (include)
debug|armeabi-v7a :-- Configuring incomplete, errors occurred!
debug|armeabi-v7a :See also "D:/Projects/mobile_frameworks/TNN/examples/android/demo/.cxx/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".
executing external native build for cmake D:\Projects\mobile_frameworks\TNN\examples\android\demo\CMakeLists.txt

FAILURE: Build failed with an exception.
`

**Comment by neiltian-tencent** [comment]
应该是GREATER_EQUAL cmake低版本不兼容问题，问题已修复

**Comment by neiltian-tencent** [comment]
@Rancherzhang 确认一下你的问题是否已修复，没问题就close了。

**Comment by Rancherzhang** [comment]
@neiltian-tencent 没问题了，可以close了，谢谢~
