### ISSUE TITLE
~BlobMemory()崩溃问题

### ISSUE THREAD

**Issue by eonwinner** [Tencent/TNN#450]
1 | FaceKeyCoreML | tnn::BlobMemory::~BlobMemory() (in FaceKeyCoreML) + 48
2 | FaceKeyCoreML | tnn::Blob1DMemory::~Blob1DMemory() (in FaceKeyCoreML) + 12
3 | FaceKeyCoreML | tnn::Blob1DMemory::~Blob1DMemory() (in FaceKeyCoreML) + 12
4 | FaceKeyCoreML | tnn::BlobMemoryPool::~BlobMemoryPool() (in FaceKeyCoreML) + 68
5 | FaceKeyCoreML | tnn::Blob1DMemoryPool::~Blob1DMemoryPool() (in FaceKeyCoreML) + 12
6 | FaceKeyCoreML | tnn::BlobManager::~BlobManager() (in FaceKeyCoreML) + 68
7 | FaceKeyCoreML | tnn::DefaultNetwork::DeInit() (in FaceKeyCoreML) + 108
8 | FaceKeyCoreML | tnn::DefaultNetwork::~DefaultNetwork() (in FaceKeyCoreML) + 40
9 | FaceKeyCoreML | tnn::Instance::DeInit() (in FaceKeyCoreML) + 72
10 | FaceKeyCoreML | tnn::Instance::~Instance() (in FaceKeyCoreML) + 40
11 | FaceKeyCoreML | std::__1::__shared_weak_count::__release_shared() (in FaceKeyCoreML) (memory:3587)
12 | FaceKeyCoreML | std::__1::shared_ptr<tnn::Instance>::~shared_ptr() (in FaceKeyCoreML) (memory:4523)
13 | FaceKeyCoreML | tnn::TNNSDKSample::~TNNSDKSample() (in FaceKeyCoreML) (TNNSDKSample.cc:63)
14 | FaceKeyCoreML | PTSTNN::~PTSTNN() (in FaceKeyCoreML) (pts_tnn.h:37)

您好，使用检测和关键点模型两个模型，分别对应两个类，两个类均继承demo中的TNNSDKSample类，在实际使用偶发崩溃，崩溃log如上，最终崩溃在了BlobMemory的析构函数里，这个问题是BlobMemory的问题吗，还是继承的shared_ptr被释放的问题呢？

**Comment by darrenyao87** [comment]
看着像是你自己构建了个PTSTNN类，PTSTNN在释放的时候挂掉了。请问这个是用的arm、metal还是oepncl？

**Comment by eonwinner** [comment]
问题已经解决了，我是在ios上跑的，构建了一个全局变量类的TNN前向的实例，这个实例在系统进行析构的时候出现了上面的崩溃，把全局变量改成局部变量就没有这个问题了，应该是析构的顺序的问题吧
