### ISSUE TITLE
Vulkan渲染管线中的Image能否直接利用TNN进行后处理？

### ISSUE THREAD

**Issue by Superlee506** [Tencent/TNN#453]
您好，
我用Vulkan写了一个渲染管线，如果要利用TNN对渲染的Image进行后处理，需要将image copy到CPU的内存空间，再利用TNN进行后处理，还是可以更高效的直接作为TNN的输入，省去GPU-CPU的I/O成本？

**Comment by neiltian-tencent** [comment]
看vulkan有没有API构建出clImage，然后clImage可以直接以N8UC4的格式送入TNN的Mat里面。 OpenGL是有API构建出clImage的。

**Comment by Superlee506** [comment]
climage是指opencl的image吗？

**Comment by nihui** [comment]
参考 https://github.com/KhronosGroup/Vulkan-Ecosystem/issues/42

不能直接 vulkan -> opencl
曲线救国 vulkan -> opengl -> opencl 理论上可以，不清楚能不能work

**Comment by Superlee506** [comment]
了解了，谢谢。
应该ncnn框架会好一点？这个框架是vulkan实现的
