### ISSUE TITLE
转换中间的.onnx档

### ISSUE THREAD

**Issue by SilentJCR** [Tencent/TNN#456]
请问在模型转换中间的.onnx档是否有其他用?例如用在onnx runtime?还是单纯只是个过度?转了一个caffe上的mobilenet-ssd的.onnx档，但在onnx runtime上使用似乎行不通

**Comment by gttiankai** [comment]
1. 针对 ssd 类的模型，onnx 文件只是作为一个中间的数据载体，这个 onnx 并不能运行，因为 onnx 不支持 ssd 的 priorbox 以及 DetectionOutput 等算子。

2. 对于非 ssd 类的模型，onnx 作为中间文件，是可以运行的。当在模型转换工具中加上“-align”参数时，内部的逻辑是先运行 onnx，在运行 tnn 模型，然后以 onnx 的运行结果作为参考，检验 tnn 的结果是否和 onnx 的一致。
