### ISSUE TITLE
安卓使用时怎样把TNN输出的Mat转成Bitmap

### ISSUE THREAD

**Issue by Zhenyu66** [Tencent/TNN#461]
安卓demo里面都是分类和检测，我现在是做的图像增强任务，网络输出的是原图大小，这种情况怎样把TNN输出的Mat转成Bitmap啊，NCNN有to_pixels和to_android_bitmap都可以满足需求，TNN没有找到类似的，求大佬给个办法

**Comment by leili666** [comment]
找到解决方法了吗，同卡住在这个地方。
