### ISSUE TITLE
如何实现mat的填充黑边效果

### ISSUE THREAD

**Issue by fire717** [Tencent/TNN#468]
在[issues430](https://github.com/Tencent/TNN/issues/430)中提到目前的TNN::mat已经支持Resize、Crop、WarpAffine、CvtColor，我想问问如何实现填充功能。
我的场景需求是，对一个小图片填充全0黑边使其成为正方形。
之前用opencv的方案是先新建一个全0的大图，然后用copyTo，可以指定复制的范围，类似如下：
`
cv::Mat pad_img(expand_size, expand_size, CV_8UC4, cv::Scalar(0));
img_crop.copyTo(pad_img(cv::Rect(pad_x0, pad_y0, img_crop_w, img_crop_h)));
`
TNN::mat也有copy的接口，
`
static Status Copy(Mat& src, Mat& dst, void* command_queue);
`
但是要求src和dst必须同样维度，所以没法用。
我也尝试了从a图中先crop得到b，然后把小图c，copy到b，但是原图a也没有变化，所以crop出来的应该是拷贝了一份新的。

**Comment by darrenyao87** [comment]
@lnmdlong @quinnrong94 @devandong 在mat上类似warpaffine实现个pad的功能吧

**Comment by quinnrong94** [comment]
在feature_mat_make_border分支，增加CopyMakeBorder接口，各平台在这个分支分别实现吧 @lnmdlong @devandong

**Comment by quinnrong94** [comment]
@fire717  新增的MatUtils::CopyMakeBorder接口，接收CopyMakeBorderParam参数，参数含义和opencv的cv::copyMakeBorder接口一致，top,bottom,left,right分别表示四个方向填充的像素个数，border_type目前只支持BORDER_TYPE_CONSTANT。将border_val设置为0，可实现填充黑边效果。 
在feature_mat_make_border分支中，NAIVE和ARM平台已实现。

**Comment by fire717** [comment]
> @fire717 新增的MatUtils::CopyMakeBorder接口，接收CopyMakeBorderParam参数，参数含义和opencv的cv::copyMakeBorder接口一致，top,bottom,left,right分别表示四个方向填充的像素个数，border_type目前只支持BORDER_TYPE_CONSTANT。将border_val设置为0，可实现填充黑边效果。
> 在feature_mat_make_border分支中，NAIVE和ARM平台已实现。

好的谢谢!
