### ISSUE TITLE
mobilenetv2-yolov3 caffe模型转tnn

### ISSUE THREAD

**Issue by biubiu0719** [Tencent/TNN#47]
Message type "caffe.LayerParameter" has no field named "yolov3_detection_output_param".

**Comment by gttiankai** [comment]
方便提供一下模型吗？ 我来支持下

**Comment by biubiu0719** [comment]
> 方便提供一下模型吗？ 我来支持下

[mobilenet_yolov3_bn_deploy.txt](https://github.com/Tencent/TNN/files/4774136/mobilenet_yolov3_bn_deploy.txt)

**Comment by biubiu0719** [comment]
还有一个shufflenetv2的caffe模型，该模型我直接转ncnn是能成功的，
但是这里转onnx的时候报错：
模型存在问题,未保存成功: Inferred shape and existing shape differ in dimension 1: (1) vs (6)
(op_type:Conv, name:stage1/conv): Inferred shape and existing shape differ in dimension 1: (1) vs (6)
模型如下：
[shufflentv2_lite.txt](https://github.com/Tencent/TNN/files/4774149/shufflentv2_lite.txt)

**Comment by masterwan96** [comment]
shufflentv2模型现已经支持~

**Comment by gttiankai** [comment]
Duplicate of: https://github.com/Tencent/TNN/issues/334 
这个 issue  先关闭掉，后续在 #issue334 里面跟踪。
