### ISSUE TITLE
有人编译armlinux 的opencl版本吗？提示cannot find -lOpenCL

### ISSUE THREAD

**Issue by GYxiaOH** [Tencent/TNN#48]
rt....暂时没找到armlinux的小伙伴，大部分都是安卓成功编译了，cmake显示找到libOpenCL.so了，按理说不会找不到opencl的库，之前MNN也正常的。。。。不知道是不是有哪里我搞错了。。

**Comment by neiltian-tencent** [comment]
问题已修复

**Comment by neiltian-tencent** [comment]
@GYxiaOH 这个问题我们验证已经修复了，没有问题我就close了。
