### ISSUE TITLE
转换工具构建了半天，卡主不动

### ISSUE THREAD

**Issue by xinyu391** [Tencent/TNN#49]
刚开始，pip install 卡主不动，换了镜像地址，过去了，   
我只需caffe/onnx 转 tnn的， 为啥还要下载 tensorflow阿。   

卡在这里，不动谈。估计也是网络问题，没vpn，过不去呀
`` 
+ [ -d build ]
+ /usr/bin/python3 script/detect_dependency.py

```

谁能提供个构建好的镜像呀。

**Comment by gttiankai** [comment]
https://github.com/Tencent/TNN/blob/master/doc/cn/user/convert.md#%E6%8B%89%E5%8F%96%E6%9E%84%E5%BB%BA%E5%A5%BD%E7%9A%84-docker-%E9%95%9C%E5%83%8F%E6%8E%A8%E8%8D%90

文档中不是有提供构建好的 docker image 吗？
