### ISSUE TITLE
静态编译的程序可以载入opencl么

### ISSUE THREAD

**Issue by ffffwyy** [Tencent/TNN#490]
我看dlopen的函数在静态编译的情况下好像不好使。载入库失败。这种情况要怎么解决呢？

**Comment by Qahl1413** [comment]
K

**Comment by Qahl1413** [comment]
> K

**Comment by shaundai-tencent** [comment]
静态编译应该是没有问题的。请排查一下：
1、是否存在opencl库？
2、如果存在，opencl库的读取权限是否有问？
3、opencl库加载失败，是dlopen失败，还是使用dlsym加载某个opencl函数失败;
