### ISSUE TITLE
rk3399上跑opencl，不但没加速速度还变慢了

### ISSUE THREAD

**Issue by DamalWang** [Tencent/TNN#494]
在RK3399 Linux系统上跑opencl，不但没加速，速度还变慢了，而且耗时很不稳定，偶尔耗时会增加到几秒到几十秒之间。

**Comment by tonylin52** [comment]
一样的问题，效果一半一半，一半加速了一半更慢了的

**Comment by shaundai-tencent** [comment]
是否可以贴一下profling的数据，ARM和OpenCL的对比

**Comment by mathpopo** [comment]
@tonylin52 你做好打印下1，input，2 deal，3，output三个时间就会明白了，然后换晓龙845之上的在同样打印就会明白了

**Comment by shibefore** [comment]
我在手机上也遇到这个问题，mobilenetv2-1.0.gpu上有的时候快有的时候慢，很不稳定。反而cpu时间很稳定。
