### ISSUE TITLE
编译onnx2tnn工具报链接错误

### ISSUE THREAD

**Issue by nicoljl** [Tencent/TNN#499]
参考网页指导编译onnx2tnn工具
cd <path-to-tnn>/tools/convert2tnn
./build.sh

上报如下链接错误
![image](https://user-images.githubusercontent.com/59855493/97177612-611fa680-17d1-11eb-8fae-dc44f60bda98.png)
protobuf库已安装完成，且添加到环境变量中，protoc --version命令返回libprotoc 3.13.0。
而且奇怪的是onnx2tnn目录的编译没有报链接错误，但converter目录的编译却报这个链接错误。
[请问有人处理过这个错误吗？

**Comment by 1627180283** [comment]
你好，我这边好像不能复现你的问题，不知道方不方便提供更多的信息？
或者你可以尝试用 docker 进行模型转换

**Comment by jackyfaster** [comment]
我也是参考网页指导编译onnx2tnn工具
cd /tools/convert2tnn
./build.sh

报如下错：
`++ '[' -d build ']'
++ /usr/bin/python3 script/detect_dependency.py
downloading 3rdparty/protobuf-3.13.0.tar.gz from
    https://github.com/protocolbuffers/protobuf/archive/v3.13.0.tar.gz
script/build_protoc.sh: 1: cd: can't cd to 3rdparty/protobuf-3.13.0/static_build
in /home/pjy/32s/TNN/TNN/tools/onnx2tnn/onnx-converter
CMake Error: The source directory "/home/pjy/32s/TNN/TNN/tools/onnx2tnn/onnx-con" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
script/build_protoc.sh: 5: script/build_protoc.sh: -DCMAKE_CXX_FLAGS= -fPIC -fvi: not founddden 
script/build_protoc.sh: 6: script/build_protoc.sh: -DBUILD_SHARED_LIBS=OFF: not found
script/build_protoc.sh: 7: script/build_protoc.sh: -Dprotobuf_BUILD_TESTS=OFF: not found
script/build_protoc.sh: 8: script/build_protoc.sh: -Dprotobuf_BUILD_EXAMPLES=OFF: not found
script/build_protoc.sh: 9: script/build_protoc.sh: -DCMAKE_INSTALL_PREFIX=../../protobuf: not found
script/build_protoc.sh: 10: script/build_protoc.sh: -DCMAKE_CXX_COMPILER=g++: not found
script/build_protoc.sh: 11: script/build_protoc.sh: -DCMAKE_C_COMPILER=gcc: not found
Traceback (most recent call last):
  File "script/detect_dependency.py", line 141, in <module>
    detect_dependency()
  File "script/detect_dependency.py", line 138, in detect_dependency
    detect_protobuf(pkgs)
  File "script/detect_dependency.py", line 116, in detect_protobuf
    raise RuntimeError('Fail to build protoc')
RuntimeError: Fail to build protoc`
请问这是什么原因？

**Comment by mathpopo** [comment]
(base) chenxin@Nitro-AN515:~/Downloads/protobuf$ protoc --version
libprotoc 3.13.0

onnx_converter.cc:(.text+0x3d7): undefined reference to `google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)'


cp: cannot stat 'tools/converter/TnnConverter': No such file or directory
+++ '[' -d build ']'
+++ /home/chenxin/anaconda/bin/python3 script/detect_dependency.py
Traceback (most recent call last):
  File "script/detect_dependency.py", line 141, in <module>
    detect_dependency()
  File "script/detect_dependency.py", line 138, in detect_dependency
    detect_protobuf(pkgs)
  File "script/detect_dependency.py", line 80, in detect_protobuf
    raise Exception("protobuf not found")
Exception: protobuf not found
Compiled successfully !

**Comment by mathpopo** [comment]
[100%] Linking CXX executable TnnConverter
CMakeFiles/TnnConverter.dir/source/onnx/onnx_converter.cc.o: In function `TNN_CONVERTER::Onnx2Tnn::ReadModel()':
onnx_converter.cc:(.text+0x3d7): undefined reference to `google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)'
CMakeFiles/TnnConverter.dir/source/onnx/onnx_converter.cc.o: In function `TNN_CONVERTER::Onnx2Tnn::Converter2Tnn(tnn::NetStructure&, tnn::NetResource&)':
onnx_converter.cc:(.text+0xa48): undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Get(int) const'
onnx_converter.cc:(.text+0xb37): undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::begin() const'
onnx_converter.cc:(.text+0xb42): undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::end() const'
onnx_converter.cc:(.text+0xc1c): undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::begin() const'
onnx_converter.cc:(.text+0xc27): undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::end() const'
onnx_converter.cc:(.text+0x1db7): undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Get(int) const'
CMakeFiles/TnnConverter.dir/source/onnx/onnx_gemm_converter.cc.o: In function `TNN_CONVERTER::OnnxGemmConverter::exec(tnn::NetStructure&, tnn::NetResource&, onnx::NodeProto const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, onnx::TensorProto const*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, onnx::TensorProto const*> > >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<TNN_CONVERTER::OnnxProxyNode>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<TNN_CONVERTER::OnnxProxyNode> > > >, bool&)':
onnx_gemm_converter.cc:(.text+0x70a): undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::size() const'

**Comment by gttiankai** [comment]
@mathpopo  你的运行环境和各个工具的版本信息方便提供下？

**Comment by mathpopo** [comment]
@gttiankai 
Ubuntu18.04  
(base) chenxin@Nitro-AN515:~/Downloads/TNN/tools/onnx2tnn/onnx-converter$ protoc --version
libprotoc 3.13.0

我参考了https://github.com/Tencent/TNN/issues/269，修改了两个文件
(base) chenxin@Nitro-AN515:~/Downloads/TNN/tools/onnx2tnn/onnx-converter$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   CMakeLists.txt
	modified:   build.sh

no changes added to commit (use "git add" and/or "git commit -a")


(base) chenxin@Nitro-AN515:~/Downloads/TNN/tools/onnx2tnn/onnx-converter$ git diff CMakeLists.txt
diff --git a/tools/onnx2tnn/onnx-converter/CMakeLists.txt b/tools/onnx2tnn/onnx-converter/CMakeLists.txt
index 1653fdc..2d52fa4 100755
--- a/tools/onnx2tnn/onnx-converter/CMakeLists.txt
+++ b/tools/onnx2tnn/onnx-converter/CMakeLists.txt
@@ -1,7 +1,16 @@
 cmake_minimum_required(VERSION 3.0)
 project(onnx2tnn)
 
-include(script/protobuf.cmake)
+#include(script/protobuf.cmake)
+find_package(Protobuf REQUIRED)
+if(PROTOBUF_FOUND)
+    include_directories(${PROTOBUF_INCLUDE_DIR})
+    include_directories(${CMAKE_CURRENT_BINARY_DIR})
+    protobuf_generate_cpp(ONNX_PROTO_SRC ONNX_PROTO_HEAD ./../src/onnx-proto/onnx.proto)
+    message(STATUS "Protobuf ${PROTOBUF_LIBRARIES}")
+else()
+    message(FATAL_ERROR "Protobuf not found, must install first")
+endif()
 
 add_subdirectory(pybind11)
 

(base) chenxin@Nitro-AN515:~/Downloads/TNN/tools/onnx2tnn/onnx-converter$ git diff build.sh
diff --git a/tools/onnx2tnn/onnx-converter/build.sh b/tools/onnx2tnn/onnx-converter/build.sh
index 9b64ac9..d811f0e 100755
--- a/tools/onnx2tnn/onnx-converter/build.sh
+++ b/tools/onnx2tnn/onnx-converter/build.sh
@@ -15,7 +15,7 @@ if [ -d "build" ]; then
        rm -rf build/
 fi
 
-$PYTHON script/detect_dependency.py 
+#$PYTHON script/detect_dependency.py 
 
 mkdir -p build
 cd build && $CMAKE .. \

执行/TNN/tools/onnx2tnn/onnx-converter/build.sh

[100%] Linking CXX shared module onnx2tnn.cpython-37m-x86_64-linux-gnu.so
[100%] Built target onnx2tnn
/usr/local/bin/cmake -E cmake_progress_start /home/chenxin/Downloads/TNN/tools/onnx2tnn/onnx-converter/build/CMakeFiles 0
++ cd ..
++ cp build/onnx2tnn.cpython-37m-x86_64-linux-gnu.so .
++ rm -rf build/


但是执行：/TNN/tools/convert2tnn/build.sh
[100%] Linking CXX executable TnnConverter
CMakeFiles/TnnConverter.dir/source/onnx/onnx_converter.cc.o: In function `TNN_CONVERTER::Onnx2Tnn::ReadModel()':
onnx_converter.cc:(.text+0x3d7): undefined reference to `google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)'
CMakeFiles/TnnConverter.dir/source/onnx/onnx_converter.cc.o: In function `TNN_CONVERTER::Onnx2Tnn::Converter2Tnn(tnn::NetStructure&, tnn::NetResource&)':
onnx_converter.cc:(.text+0xa48): undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Get(int) const'

**Comment by mathpopo** [comment]
但是尽管报错了，这个竟然也能用？？？

(TNN-Convert) chenxin@Nitro-AN515:~/Downloads/TNN1/tools/convert2tnn$ python ./converter.py -h
2020-11-12 17:16:19.690820: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
usage: convert [-h] {onnx2tnn,caffe2tnn,tf2tnn,tflite2tnn} ...

convert ONNX/Tensorflow/Tensorflowlite/Caffe model to TNN model

positional arguments:
  {onnx2tnn,caffe2tnn,tf2tnn,tflite2tnn}
    onnx2tnn            convert onnx model to tnn model
    caffe2tnn           convert caffe model to tnn model
    tf2tnn              convert tensorflow model to tnn model
    tflite2tnn          convert tensorflow-lite model to tnn model

optional arguments:
  -h, --help            show this help message and exit

**Comment by gttiankai** [comment]
@mathpopo “但是尽管报错了，这个竟然也能用？？？”  有 help 信息，并不是表示能够使用。converter.py 只是提供了对底层转换工具的封装。底层工具没有编译好，转换工具肯定不能使用。

**Comment by gttiankai** [comment]
我将代码修改的和你一致了，但是我这边编译没有复现你的问题。我的 protobuf 的版本也是和你一样的。你的 protobuf 是从 源码安装的吗？ 如果不是的话，我建议你从源码进行安装 protobuf

**Comment by mathpopo** [comment]
@gttiankai yes

but  more than this , i also need re-build cmake from source again
