### ISSUE TITLE
有关tnn使用opencl时内存占用的问题

### ISSUE THREAD

**Issue by banbishan** [Tencent/TNN#502]
使用ncnn cpu版本时，内存在运行完一次后，内存会释放，但网络不会释放：如下
![image](https://user-images.githubusercontent.com/13417277/97287769-ef526600-187f-11eb-8f35-04bf2acebff2.png)
使用tnn opencl版本时，在加载模型后会一致维持在ncnn峰值内存的内存量，run的时候内存只会增加图片的内存，tnn的内存没有增加，跑完模型要deinit后才会释放内存
![image](https://user-images.githubusercontent.com/13417277/97288211-86b7b900-1880-11eb-8010-bf8e09918fce.png)
但是需求是模型要一直维持在init的状态，不能deinit。
那么tnn一直维持较高内存是正常的吗？ncnn为什么是不用deinit也可以维持比较低的内存，是因为tnn使用opencl的缘故吗？

**Comment by shaundai-tencent** [comment]
分配的内存主要是存储中间计算结果。如果执行完就释放，那还需要再次分配，分配内存会有一定的耗时。没有必要。

**Comment by banbishan** [comment]
> 分配的内存主要是存储中间计算结果。如果执行完就释放，那还需要再次分配，分配内存会有一定的耗时。没有必要。

但是inference一般只想得到最终的output，中间layer的结果感觉没有特别必要留在内存里

**Comment by shaundai-tencent** [comment]
两个进程跑两个模型，肯定要使用独立的内存，不然中间结果会相互影响的。如果是同一个线程，跑不同的模型，目前OpenCL还没有实现共享。
此外，中间结果拿到output后是不需要，但是内存是需要保留的，因为后面还需要做推理。如果后面不需要做推理了，可以将instance 销毁掉就可以释放内存。

**Comment by Smeegol** [comment]
> 分配的内存主要是存储中间计算结果。如果执行完就释放，那还需要再次分配，分配内存会有一定的耗时。没有必要。

@shaundai-tencent Metal后端推理也是这样的逻辑吗，分配的Metal内存在执行完也是不会释放的？我遇到了类似的问题，在执行完推理，然后设置TNN、Instance实例为nullptr以试图完全释放，结果并不会被释放，请帮忙看下：https://github.com/Tencent/TNN/issues/1817
