### ISSUE TITLE
啥时候提供分割的demo呢

### ISSUE THREAD

**Issue by GeneralJing** [Tencent/TNN#505]
最近看TNN多了几个示例，啥时候可以提供分割的demo呢

**Comment by devandong** [comment]
在[feature_demo_handtracking](https://github.com/Tencent/TNN/tree/feature_demo_handtracking)分支上有头发分割的demo，可以参考：https://github.com/Tencent/TNN/blob/feature_demo_handtracking/examples/base/hair_segmentation.cc

**Comment by devandong** [comment]
头发分割demo已合并入master分支

**Comment by devandong** [comment]
close via #530
