### ISSUE TITLE
mac 编译过程中报错

### ISSUE THREAD

**Issue by GeneralJing** [Tencent/TNN#506]
error: Build input file cannot be found: '/Users/jing/Documents/TNN/source/tnn/optimizer/net_optimizer_insert_reformat.cc' (in target 'tnn' from project 'tnn')
warning: Skipping duplicate build file in Compile Sources build phase: /Users/jing/Documents/TNN/source/tnn/core/mat.cc (in target 'tnn' from project 'tnn')
warning: Skipping duplicate build file in Compile Sources build phase: /Users/jing/Documents/TNN/source/tnn/core/mat.cc (in target 'tnn' from project 'tnn')
** BUILD FAILED **
error: Build input file cannot be found: '/Users/jing/Documents/TNN/source/tnn/optimizer/net_optimizer_insert_reformat.cc' (in target 'tnn' from project 'tnn')
note: Using new build system
note: Using codesigning identity override: 
note: Planning build
note: Constructing build description
warning: Skipping duplicate build file in Compile Sources build phase: /Users/jing/Documents/TNN/source/tnn/core/mat.cc (in target 'tnn' from project 'tnn')
warning: Skipping duplicate build file in Compile Sources build phase: /Users/jing/Documents/TNN/source/tnn/core/mat.cc (in target 'tnn' from project 'tnn')
warning: Skipping duplicate build file in Compile Sources build phase: /Users/jing/Documents/TNN/source/tnn/core/mat.cc (in target 'tnn' from project 'tnn')
** BUILD FAILED **
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: build/Release-iphonesimulator/tnn.framework/tnn (No such file or directory)
******************** step 3: add version attr ********************
文件不存在: /Users/xxxx/Documents/TNN/scripts/../platforms/ios/tnn.framework/tnn

**Comment by devandong** [comment]
这是由于tnn项目文件变化导致的，可以在xcode中更新tnn.xcodeproj中包含的文件，删除已删除文件，并增加未包含到项目中的文件。分支[fix_tnn_project](https://github.com/Tencent/TNN/pull/508)修复了这个问题。

**Comment by GeneralJing** [comment]
note: Constructing build description
warning: Skipping duplicate build file in Compile Sources build phase: /Users/jing/Documents/TNN/source/tnn/core/mat.cc (in target 'tnn' from project 'tnn')
warning: Skipping duplicate build file in Compile Sources build phase: /Users/jing/Documents/TNN/source/tnn/core/mat.cc (in target 'tnn' from project 'tnn')
warning: Skipping duplicate build file in Compile Sources build phase: /Users/jing/Documents/TNN/source/tnn/core/mat.cc (in target 'tnn' from project 'tnn')
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: build/Release-iphonesimulator/tnn.framework/tnn and build/Release-iphoneos/tnn.framework/tnn have the same architectures (arm64) and can't be in the same fat output file
这个分支编译还是会报错，我本地另外一个路径下，有很早之前的下载编译的TNN工程，跟这个有关系吗？

**Comment by devandong** [comment]
是使用scripts/build_ios.sh，且DEVICE_PLATFORM="iPhone+Simulator"(build_ios.sh 15行)，且xcode版本>=12(xcodebuild -version)吗？

**Comment by GeneralJing** [comment]
第15行是DEVICE_PLATFORM="iPhone+Simulator"，且xcode版本Version 12.0.1 (12A7300)

**Comment by GeneralJing** [comment]
是使用的build_ios.sh这个脚本，15行也对，xcode版本Version 12.0.1 (12A7300)

**Comment by devandong** [comment]
这可能是由于xcode12改变了simulator的arch造成的，导致iPhone和simulator的arch相同。
可以修改build_ios.sh第15行为：DEVICE_PLATFORM="iPhone"，仅对真机编译；
或者修改build_ios.sh第68行为:
xcodebuild -quiet -target "$TARGET_NAME" -configuration ${CONFIGURATION}  -sdk iphonesimulator -arch x86_64 build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
在build前增加"-arch x86_64"

**Comment by GeneralJing** [comment]
error: the following command failed with exit code 0 but produced no further output
CompileC /Users/jing/Documents/TNN/platforms/ios/build/tnn.build/Release-iphonesimulator/tnn.build/Objects-normal/x86_64/arm_pool_layer_acc.o /Users/jing/Documents/TNN/source/tnn/device/arm/acc/arm_pool_layer_acc.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
编译中间出现了这么一个提示，有问题吗？
另外，最后输出内容是这个：
1 warning generated.
1 warning generated.
note: Using new build system
note: Using codesigning identity override: 
note: Planning build
note: Constructing build description
warning: Skipping duplicate build file in Compile Sources build phase: /Users/jing/Documents/TNN/source/tnn/core/mat.cc (in target 'tnn' from project 'tnn')
 
******************** step 3: add version attr ********************
就没有了，这算是编译成功了吗？

**Comment by devandong** [comment]
可查看TNN项目下的platforms/ios目录，是否有刚编译生成的tnn.bundle和tnn.framework

**Comment by GeneralJing** [comment]
是有了，但是时间戳不是同时的，bundle产生的比较早个二十几分钟，framework是刚产生的，应该没问题吧

**Comment by devandong** [comment]
可以主要对比tnn.framework/tnn与tnn.bundle/tnn.metallib两个文件的时间戳，正常情况下应该是一致的。

**Comment by GeneralJing** [comment]
没有看到tnn.metalib文件呢 是在别的文件夹下面吗

**Comment by devandong** [comment]
TNN项目下的 platforms/ios/tnn.bundle 目录中没有tnn.metallib吗？

**Comment by GeneralJing** [comment]
没有，没看到这个文件

**Comment by GeneralJing** [comment]
现在编译可以通过，但是程序不能启动The file “TNNExamples” couldn’t be opened because you don’t have permission to view it.You don’t have permission.
To view or change permissions, select the item in the Finder and choose File > Get Info.
没找到解决方法

**Comment by GeneralJing** [comment]
这个是啥问题啊？我查了下说是有依赖的文件没有添加到compile sources，是遗漏文件了吗？

**Comment by devandong** [comment]
编译错误修正已合并入master分支 #523
