### ISSUE TITLE
Android平台关于TNN成功加载模型后，内存增加的问题

### ISSUE THREAD

**Issue by chenhucxc** [Tencent/TNN#507]
TNN_NS::InputShapesMap shapeMap;
TNN_NS::NetworkConfig network_config;
network_config.library_path = {""};
network_config.device_type = TNN_NS::DEVICE_OPENCL;
auto instance = net_->CreateInst(network_config, status, shapeMap);

TNN 使用GPU模式加载模型文件，成功初始化后会锁定较大的Memory（270 M的内存），被锁定的内存在instance不置空的情况下，一直都不会释放。如果一次只使用一种模型不会有什么问题，但是遇到一个功能，需要同时加载多个模型的时候，会出现内存占用非常大的情况，导致设备内存吃紧。而TNN 以GPU的方式加载模型耗时比较长（在OPPO R9km的设备上，加载一个模型需要耗时3s左右），这样就导致无法做到跑完一个模型就释放所有内存资源，要用了再重新去加载的情况。
所以想咨询一下，有没有提供某些API，在GPU模式下成功加载一种模型文件后，只占用较少的资源，运算时再额外申请内存资源去运算，运算完后释放此次申请的内存，但不释放初始化申请的内存。

**Comment by shaundai-tencent** [comment]
目前没有提供那样的API，内存是同时申请的。加载多个模型是同一线程还是不同的线程？

**Comment by chenhucxc** [comment]
目前是直接创建一个子线程来加载一个模型，多个模型加载在不同的线程中。

**Comment by chenhucxc** [comment]
> 目前没有提供那样的API，内存是同时申请的。加载多个模型是同一线程还是不同的线程？

同一个线程加载和在不同的线程中加载，会有什么样的区别了？

**Comment by shaundai-tencent** [comment]
如果是不同的线程，那内存是无法复用的，如果是同一个线程，理论上，中间计算结果是可以复用的。不过OpenCL，这一块内存的复用还没有实现。
另外，初始化时间较长，可能是buildKernel的时间较长。并不是分配内存的时间较长。要减少buildKernel时间。可以通过预加载模型的方式，加载的这个instance不要销毁。等到进程退出时再销毁。

**Comment by jonbakerfish** [comment]
@shaundai-tencent  我尝试修改android demo 里面检测模型的输入大小，  从320x320 -> 256x256  , 但是内存占用只从270MB降到240MB。请问demo里面是有其他代码控制内存大小的吗？

**Comment by shaundai-tencent** [comment]
请问你说的是哪个检测模型？是什么时候的代码？我复现一下。

**Comment by jonbakerfish** [comment]
@shaundai-tencent  YoloV5s, 最新版的master

**Comment by shaundai-tencent** [comment]
我们demo中的yolov5s模型的输入是448x640，你这边是怎么改到320x320或者256x256的？我需要了解一下细节，可以在tnn交流群中直接找我，我的昵称是Shaun。

**Comment by jonbakerfish** [comment]
我用的是https://github.com/ultralytics/yolov5 的模型，转化流程为：PT -> ONNX -> TNN

转换ONNX前需要修改`models/yolo.py`的以下代码：
```python
            # normal
            bs, _, ny, nx = x[i].shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
            x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()

            # # for TNN
            # x[i] = x[i].sigmoid()
            # x[i] = x[i].permute(0,2,3,1).contiguous()
```

改为：
```python
            # # normal
            # bs, _, ny, nx = x[i].shape  # x(bs,255,20,20) to x(bs,3,20,20,85)
            # x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()

            # for TNN
            x[i] = x[i].sigmoid()
            x[i] = x[i].permute(0,2,3,1).contiguous()
```

PT转ONNX：

```bash
python models/export.py --weights yolov5s.pt --img 320 --batch 1
```

ONNX转TNN：

```bash
python3 onnx2tnn.py yolov5s.onnx -version=v1.0 -optimize=1 -half=0 -o out_dir/ -input_shape images:1,3,320,320
```

**Comment by shaundai-tencent** [comment]
你那边导出的yolov5s.pt或者tnnproto方便发给我吗？我好快速复现一下。

**Comment by jonbakerfish** [comment]
@shaundai-tencent 谢谢。文件上传在了 https://tmpfiles.org/download/167773/coco_yolov5s.zip

**Comment by shaundai-tencent** [comment]
针对内存消耗分析了一下：
TNN内部的内存的消耗主要是以下部分：
1、model_config的内部拷贝，这部分在TNN内部有一份拷贝，如果模型较大，则这部分拷贝会消耗比较大，比如yolov5s的模型，有将近30MB。
2、model_interpreter的resource内存消耗，这部分也是和模型大小相关，是存储模型的权重。和model_config中的param[1]大小相近。
3、不同平台会将权重信息重新排布，所以权重信息会再次复制一份。并且根据排布的格式不同，消耗的大小也有差异。
4、blob_manager中的内存池消耗，主要存储模型的中间计算结果。这部分已经优化过，有内存复用机制。
5、平台相关的其他内存消耗，比如OpenCL平台，BuildProgram之后也会有一部分内存消耗。
6、其他消耗，相对来说占比比较小。

目前第1点近期会优化掉，第2点后面可能会提供接口，让用户自己释放。而你尝试的将输入大小变小，主要影响的是第3点的内存消耗。对于yolov5这个模型，主要的内存消耗是第1点和第2点。所以收益不是很大。

此外，对于应用apk来讲，外部传入的model_config里面的params，调用完TNN::Init()之后就可以释放。否则还会占用额外的内存。

**Comment by jonbakerfish** [comment]
@shaundai-tencent 非常感谢解答。还有几个问题想请教一下：
1、关于内存消耗的分析，你是用什么工具、方法、思路去得到详细的分析结果的？我想学习一下这种技术，以便后面能够自己排查问题。
2、我测试的手机是高通820芯片，TNN设定用的是GPU，不知道你上面的消耗分析是基于CPU的、还是GPU的？这两者会有不同的内存分配策略吗？

**Comment by doctorimage** [comment]
超分模型参数量3k，模型size 仅8KB，加载到tnn后，
1）iPhone X，640x480，2x，内存增量92MB（相对于没开启超分），GPU占有率由2.82%增加到77.96%
2）小米11，604x480，2x，内存增量127MB（相对于没开启超分），GPU由7.81%增加到47.28%

**Comment by HaoLiuHust** [comment]
> 针对内存消耗分析了一下： TNN内部的内存的消耗主要是以下部分： 1、model_config的内部拷贝，这部分在TNN内部有一份拷贝，如果模型较大，则这部分拷贝会消耗比较大，比如yolov5s的模型，有将近30MB。 2、model_interpreter的resource内存消耗，这部分也是和模型大小相关，是存储模型的权重。和model_config中的param[1]大小相近。 3、不同平台会将权重信息重新排布，所以权重信息会再次复制一份。并且根据排布的格式不同，消耗的大小也有差异。 4、blob_manager中的内存池消耗，主要存储模型的中间计算结果。这部分已经优化过，有内存复用机制。 5、平台相关的其他内存消耗，比如OpenCL平台，BuildProgram之后也会有一部分内存消耗。 6、其他消耗，相对来说占比比较小。
> 
> 目前第1点近期会优化掉，第2点后面可能会提供接口，让用户自己释放。而你尝试的将输入大小变小，主要影响的是第3点的内存消耗。对于yolov5这个模型，主要的内存消耗是第1点和第2点。所以收益不是很大。
> 
> 此外，对于应用apk来讲，外部传入的model_config里面的params，调用完TNN::Init()之后就可以释放。否则还会占用额外的内存。

请问这个2有优化吗

**Comment by gjd2017** [comment]
> 

除了预加载模型，还有其他的方法可以减少模型加载耗时么？
