### ISSUE TITLE
unsupport data type: 0

### ISSUE THREAD

**Issue by jackyfaster** [Tencent/TNN#510]
Hi:
    I used ubuntu os, when I ran "python onnx2tnn.py /home/pjy/32s/onnx/vgg16.onnx -version=v1.0 -optimize=0 -half=0 -o /home/pjy/32s/onnx/ -input_shape input:1,3,32,32", I got the following error:
-----------------------------------------------------------------------------------------------------------
D/converter: int get_tensor_proto_data_size(const onnx::TensorProto&) [File/home/pjy/32s/TNN/tools/onnx2tnn/src/core/onnx_utility.cc][Line 522] unsupport data type: 0
--------------
python: /home/pjy/32s/TNN/tools/onnx2tnn/src/core/onnx_utility.cc:523: int get_tensor_proto_data_size(const onnx::TensorProto&): Assertion `0' failed. Aborted (core dumped)
--------------------------------------------------------------------------------------------------------------------------

Could you help me ? please. 
Thanks!

**Comment by 1627180283** [comment]
Could you provide your onnx model?

**Comment by jackyfaster** [comment]
Hi,  my original model is vgg16, and I have found the reason. 
I used pytorch to create my original model, when the model from conv2d to linear with .view(), i got the above error.
when I replaced .view() with .reshape(), I avoided the error.

**Comment by NeoLc** [comment]
I have the same problem， changed “”-optimize=0 “” to “”-optimize=1“”, then the problem was solved.
