### ISSUE TITLE
benchmark  huiwei-npu  麒麟980  error

### ISSUE THREAD

**Issue by mathpopo** [Tencent/TNN#511]
(base) chenxin@Nitro-AN515:~/Downloads/TNN/benchmark/benchmark_android$ bash ./benchmark_models.sh
NPU Enable
-- android-14 is unsupported. Using minimum supported version 16.
/home/chenxin/Downloads/TNN
/home/chenxin/Downloads/TNN
-- Found OpenMP_C: -fopenmp=libomp  
-- Found OpenMP_CXX: -fopenmp=libomp  
-- Found OpenMP: TRUE   
-- >>>>>>>>>>>>>
-- TNN BUILD INFO:
-- 	System: Android
-- 	Processor: aarch64
-- 	Cpu:	OFF
-- 	X86:	OFF
-- 	Arm:	ON
-- 	Metal:	OFF
-- 	OpenCL:	ON
-- 	CUDA:	OFF
-- 	HuaweiNPU:	ON
-- 	RKNPU:	OFF
-- 	OpenMP:	ON
-- 	TEST:	ON
-- 	--Unit Test:	OFF
-- 	Qantization:	OFF
-- 	ModelCheck:	OFF
-- 	DEBUG:	
-- 	PROFILE:	OFF
-- 	BENCHMARK:	ON
-- 	BENCHMARK Layer:	OFF
-- 	Model Converter:	OFF
-- 	TNN2MEM:	OFF
-- Build TNN OpenCL
-- Build TNN NPU
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chenxin/Downloads/TNN/benchmark/benchmark_android/build
/usr/local/bin/cmake -S/home/chenxin/Downloads/TNN -B/home/chenxin/Downloads/TNN/benchmark/benchmark_android/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /home/chenxin/Downloads/TNN/benchmark/benchmark_android/build/CMakeFiles /home/chenxin/Downloads/TNN/benchmark/benchmark_android/build//CMakeFiles/progress.marks
make -s -f CMakeFiles/Makefile2 all
Scanning dependencies of target gflags_nothreads_static
Scanning dependencies of target TNNNPU
[  0%] Building CXX object third_party/gflags/CMakeFiles/gflags_nothreads_static.dir/src/gflags.cc.o
[ 21%] Built target TNNArm
[ 21%] Building CXX object source/tnn/device/huawei_npu/CMakeFiles/TNNNPU.dir/convert/math/npu_acos_layer_convert.cc.o
[ 22%] Building CXX object source/tnn/device/huawei_npu/CMakeFiles/TNNNPU.dir/convert/math/npu_add_layer_convert.cc.o
[ 41%] Built target TNNOpenCL
/home/chenxin/Downloads/TNN/source/tnn/device/huawei_npu/convert/math/npu_acos_layer_convert.cc:15:10: /home/chenxin/Downloads/TNN/source/tnn/device/huawei_npu/convert/math/npu_add_layer_convert.cc:fatal error15: :10:
       'graph/op/all_ops.h' fatal errorfile:  not 
found      'graph/op/all_ops.h'
 file not found
#include <graph/op/all_ops.h>
         ^~~~~~~~~~~~~~~~~~~~
#include <graph/op/all_ops.h>
         ^~~~~~~~~~~~~~~~~~~~

**Comment by neiltian-tencent** [comment]
https://github.com/Tencent/TNN/blob/master/doc/cn/faq.md
