### ISSUE TITLE
关于人脸配准模型

### ISSUE THREAD

**Issue by fire717** [Tencent/TNN#513]
你好，我研究了下你们提供的优图的人脸配准模型，发现好像只支持视频流，不支持单张图片：

第一张图片输入时，会调用WarpByRect()对大图进行处理，
后续的图片都是调用AlignN()进行处理。

而AlignN需要输入前一帧的关键点，肯定无法单独使用，而我测试单独使用WarpByRect()，即对每一张都执行WarpByRect()，发现正脸还算准，侧脸非常不准。

所以想问问是否是我理解不对（demo也没有检测单张图片关键点的功能），
如果的确只支持视频流，那么请问能提供单张图片关键点检测的模型吗（比如MNN用的是PLFD）？

**Comment by devandong** [comment]
对现在算法的理解是正确的。现在的人脸检测模型实际上使用了开源的blazeface，因此当需要完全依赖于检测模型结果进行配准时，效果相对会差一些。
暂时没有针对单张图片进行关键点检测demo的计划，不过可以将blazeface替换为其他人脸监测模型，尝试改进效果。

**Comment by fire717** [comment]
好的，谢谢。
