### ISSUE TITLE
初始化TNN模型时报错net_structure blobs is empty

### ISSUE THREAD

**Issue by jackyfaster** [Tencent/TNN#520]
您好，
我在rk3399(android6.0)上用c++调用TNN初始化模型报了如下错误：
![image](https://user-images.githubusercontent.com/45895756/97958574-6dff5400-1de8-11eb-8535-5489f8a28c4c.png)
我写的代码如下，请问这是什么问题啊，谢谢了。
`
#include "tnn/core/tnn.h"
#include "tnn/core/blob.h"
#include <opencv2/opencv.hpp>
#include "tnn/core/common.h"
#include <cmath>
#include <string>
#include <fstream>
#include <iostream>

std::string fdLoadFile(std::string path){
        std::ifstream file(path, std::ios::in);
        if (file.is_open()) {
        file.seekg(0, file.end);
        int size = file.tellg();
        char *content = new char[size];
        file.seekg(0, file.beg);
        file.read(content, size);
        std::string fileContent;
        fileContent.assign(content, size);
        delete[] content;
        file.close();
        return fileContent;
    } else {
        return "";
    }
}

std::shared_ptr<TNN_NS::TNN> net_ = nullptr;
std::shared_ptr<TNN_NS::Instance> instance_ = nullptr;
TNN_NS::DeviceType device_type_ = TNN_NS::DEVICE_ARM;

int TNN_CLASSIFY(std::string protoPath, std::string modelPath, int computeUnitType){
    std::string protoContent, modelContent;
    protoContent = fdLoadFile(protoPath);
    modelContent = fdLoadFile(modelPath);

    TNN_NS::Status status;
    TNN_NS::ModelConfig config;
    config.model_type = TNN_NS::MODEL_TYPE_TNN;
    config.params = {protoContent, modelContent};
    auto net = std::make_shared<TNN_NS::TNN>();
    status = net->Init(config);
    net_ = net;

    device_type_ = TNN_NS::DEVICE_ARM;
    if (computeUnitType >= 1) {
        device_type_ = TNN_NS::DEVICE_OPENCL;
    }

    TNN_NS::InputShapesMap shapeMap;
    TNN_NS::NetworkConfig network_config;
    network_config.library_path = {""};
    network_config.device_type = device_type_;
    auto instance = net_->CreateInst(network_config, status, shapeMap);
    if (status != TNN_NS::TNN_OK || !instance) {
        network_config.device_type = TNN_NS::DEVICE_ARM;
        instance = net_->CreateInst(network_config, status, shapeMap);
    }
    instance_ = instance;

    if (status != TNN_NS::TNN_OK) {
        //LOGE("TNN init failed %d", (int) status);
        return -1;
    }else{
        std::cout<<"TNN init successed"<<std::endl;
    }
    return 0;

};

int main(int argc, char* argv[]){
        std::string protoPath = argv[0];
	std::string modelPath = argv[1];
	TNN_CLASSIFY(protoPath, modelPath, 0);
	return 0;
};

`

**Comment by ShaunRain** [comment]
@jackyfaster 请教下怎么解决的😅

**Comment by lhwcv** [comment]
@jackyfaster  你好， 请问最后是怎么解决的， 多谢！

**Comment by jackyfaster** [comment]
不好意思现在才回复，我当时出错是因为我自己大意把代码写错了，我用了string（protoContent, modelContent）去接fdLoadFile函数的输出，然后把protoContent, modelContent用来配置ModelConfig的实例config，这就导致了config.param没有得到正确配置，把protoContent, modelContent的类型由string改为auto应该就行了。
