### ISSUE TITLE
caffe2tnn 转换FaceBoxes模型，第一层卷积就报错

### ISSUE THREAD

**Issue by zacks417** [Tencent/TNN#525]
![image](https://user-images.githubusercontent.com/40654162/98096813-27ccf200-1ec7-11eb-9ec1-2efaa2a1efe0.png)
采用如图转换faceboxes，第一层卷积报错
faceboxes的prototxt和caffemodel均采用作者开源模型

[faceboxes_models.zip](https://github.com/Tencent/TNN/files/5487001/faceboxes_models.zip)

**Comment by 1627180283** [comment]
可以按 QQ 上讨论的方案进行尝试

**Comment by 1627180283** [comment]
> 可以按 QQ 上讨论的方案进行尝试

https://github.com/zisianw/FaceBoxes.PyTorch
使用 pytorch 版的代码即可

**Comment by zacks417** [comment]
已完成测试，正在封装faceboxes的类接口

**Comment by jayshonzs** [comment]
Same error, how is this issue fixed?
