### ISSUE TITLE
对于模型量化的小小建议

### ISSUE THREAD

**Issue by MrJ0hnson** [Tencent/TNN#533]
当进行模型量化输出参数时, 不能指定量化输出的模型文件名或者模型文件路径, 
并且转化后的模型文件名都统一为"model_quantized.tnnproto"和"model_quantized.tnnmodel"

> ./quantization_cmd [-h] [-p] [-m] [-i] [-b] [-w] [-n] [-s] [-c] <param>

当进行大量模型同时进行量化, 或者测试不同量化参数对模型进行量化时, 
当前较难通过脚本自动化处理大量模型的量化工作, 并且容易造成错误.

建议在模型量化的命令中, 可以加上一个参数指定输出模型的文件夹路径, 
类似于ONNX转TNN模型时, 可以通过"-o"参数指定输出模型的文件夹路径.

> usage: onnx2tnn.py [-h] [-version VERSION] [-optimize OPTIMIZE] [-half HALF]
> [-o OUTPUT_DIR] [-input_shape INPUT_SHAPE]

**Comment by shaundai-tencent** [comment]
非常好的建议，近期会安排上
