### ISSUE TITLE
调整object_detector_yolo.cc去运行yolov3

### ISSUE THREAD

**Issue by jackyfaster** [Tencent/TNN#534]
我想通过改动object_detector_yolo.cc去运行yolov3，但是遇到了一些问题，
Status ObjectDetectorYolo::ProcessSDKOutput(std::shared_ptr<TNNSDKOutput> output_)里面报错，返回(int)status的值为4096，关键我不知道怎么改，请帮帮我，谢谢。
![image](https://user-images.githubusercontent.com/45895756/98659200-db7a2a00-237e-11eb-9fdf-48ab6b658dff.png)

**Comment by devandong** [comment]
你好，可以排查一下更换后的yolov3模型的输出blob的name。
这里代码中GetMat参数中的字符串(即"428", “427”, "426")与demo中使用的yolo模型输出blob name一致，而不一定与你那边的yolov3一致，所以可能导致无法找到对应的输出。可以使用Netron打开yolov3 tnn模型，确认模型输出blob的name，并在代码中进行相应的修改。

**Comment by jackyfaster** [comment]
嗯嗯，感谢，我现在能找到对应的数据了，但是我发现，yolov5的输出的通道应该是在后的，而yolov3的输出是通道在前，我按照通道在前改了一点
void GenerateDetectResult(std::vector<std::shared_ptr<TNN_NS::Mat> >outputs, std::vector<ObjectInfo>& detects, int image_width, int image_height)中的代码如下，但是最终的检测结果不对，我怀疑这里的float* data = static_cast<float*>(output->GetData());是不是不适用通道在前的输出，还是说有其他原因，谢谢！
![image](https://user-images.githubusercontent.com/45895756/98776146-6283dc80-2429-11eb-86a0-a283cf2f4b7c.png)

**Comment by devandong** [comment]
这个方法是获取Mat内封装的数据，与具体数据的shape无关，可以通过Mat的GetDims()方法获得Mat的具体形状。
在通道顺序变化时，对应的后处理代码也需要调整；
也可以尝试在yolo模型最后增加Permute层，将通道调整到最后。Permute层的用法可以参照原始的yolov5模型yolov5s-permute.tnnproto

**Comment by jackyfaster** [comment]
感谢！！我用了Permute层成功了。
