### ISSUE TITLE
convert onnx error

### ISSUE THREAD

**Issue by mathpopo** [Tencent/TNN#539]
可以从onnx转到tnnproto，但是使用TNNTest报错，是模型问题吗？

**Comment by mathpopo** [comment]
[mnist-8.zip](https://github.com/Tencent/TNN/files/5523711/mnist-8.zip)

**Comment by mathpopo** [comment]
[webwxgetmsgimg(2).zip](https://github.com/Tencent/TNN/files/5527641/webwxgetmsgimg.2.zip)

**Comment by mathpopo** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/21274466/98882853-2d7a9700-24c8-11eb-8278-908293f03abc.png)
![Uploading webwxgetmsgimg1.png…]()

**Comment by mathpopo** [comment]
![webwxgetmsgimg1](https://user-images.githubusercontent.com/21274466/98884588-551f2e80-24cb-11eb-85e8-72ebcd22290d.png)

**Comment by gttiankai** [comment]
首先你截图的信息不全。
根据已有的截图看起来有可能是 concat 的参数校验没有通过。两个输出做 concat 操作是有要求的。除了要做 concat 的维度之外，其他维度的 size 必须一样。
