### ISSUE TITLE
想请教下，TNNTest中测试模型的时间统计疑问？

### ISSUE THREAD

**Issue by mathpopo** [Tencent/TNN#541]
想请问下：如果使用opencl测试，测试的时间包括：1.cpu拷贝数据到gpu，2.gpu执行model，3.执行完gpu将结果返回拷贝到cpu？在代码没能看出来
/TNN/test /test.cc
    Timer timer(model_name);

            for (int i = 0; i < FLAGS_ic; ++i) {
                timer.Start();
                for(auto element : input_converters_map) {
                    auto name = element.first;
                    auto blob_converter = element.second;
                    ret = blob_converter->ConvertFromMatAsync(*input_mat_map[name], input_params_map[name], command_queue);
                    if (!CheckResult("ConvertFromMat", ret)) {
                        return 0;
                    }
                }
                ret = instance->ForwardAsync(nullptr);
                if (!CheckResult("Forward", ret)) {
                    return 0;
                }
                for(auto element : output_converters_map) {
                    auto name = element.first;
                    auto blob_converter = element.second;
                    ret = blob_converter->ConvertToMat(*output_mat_map[name], output_params_map[name], command_queue);
                    if (!CheckResult("ConvertToMat", ret)) {
                        return 0;
                    }
                }
                timer.Stop();
            }
#if TNN_PROFILE
            instance->FinishProfile(true);
#endif
            CheckResult("Forward", ret);

            if (!FLAGS_op.empty()) {
                WriteOutput(output_mat_map);
            }
 
            timer.Print();
 
            FreeMatMapMemory(input_mat_map);
            FreeMatMapMemory(output_mat_map);
        }
        return 0;
    }

**Comment by mathpopo** [comment]
![rk3399_TNN](https://user-images.githubusercontent.com/21274466/98888406-ec3bb480-24d2-11eb-8cd3-353aecd61b7a.png)

**Comment by mathpopo** [comment]
![rk3399_MNN](https://user-images.githubusercontent.com/21274466/98888438-fd84c100-24d2-11eb-83bc-3514fc314164.png)
![rk3399_TNN](https://user-images.githubusercontent.com/21274466/98888568-2efd8c80-24d3-11eb-802d-001984a6e96a.png)

**Comment by shaundai-tencent** [comment]
在OpenCL场景下，ConvertFromMatAsync是从CPU拷贝到GPU，ConvertToMat是从GPU拷贝到CPU，只是拷贝到GPU是异步的，最后拷贝到CPU同步。

**Comment by mathpopo** [comment]
@shaundai-tencent 请问下能有一些demo提供给开发者做实验吗？

**Comment by shaundai-tencent** [comment]
在TNN/examples下面有些demo
