### ISSUE TITLE
BlazeFace相关

### ISSUE THREAD

**Issue by yyqgood** [Tencent/TNN#552]
你好：
有BlazeFace的网络模型代码和训练测试代码吗？

**Comment by darrenyao87** [comment]
balzeface使用的google公开的模型，可从论文网站获取相关训练代码https://arxiv.org/abs/1907.05047

**Comment by yyqgood** [comment]
@darrenyao87 这篇paper我读过；我是问：你们有实现好的模型代码和训练代码吗？
