### ISSUE TITLE
how to compile tnn android opencl?

### ISSUE THREAD

**Issue by mathpopo** [Tencent/TNN#558]
![image](https://user-images.githubusercontent.com/21274466/99217429-fd5a2d80-2812-11eb-8688-8d6de9a43263.png)
******************** step 2: start build rpn arm32 ********************
armeabi-v7a
-- 	OpenCL:	ON

******************** step 3: start build rpn arm64 ********************
arm64-v8a
-- 	OpenCL:	ON

[ 98%] Linking CXX shared library libTNN.so
/home/chenxin/Downloads/TNN/source/tnn/device/opencl/opencl_context.cc:46: error: undefined reference to 'tnn::OpenCLContext::GetCommandQueue()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/TNN.dir/build.make:4041: recipe for target 'libTNN.so' failed

[ 98%] Linking CXX shared library libTNN.so
source/tnn/device/opencl/CMakeFiles/TNNOpenCL.dir/opencl_context.cc.o: In function `tnn::OpenCLContext::ShareCommandQueue(tnn::Context*)':
/home/chenxin/Downloads/TNN/source/tnn/device/opencl/opencl_context.cc:46: undefined reference to `tnn::OpenCLContext::GetCommandQueue()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/TNN.dir/build.make:4041: recipe for target 'libTNN.so' failed

**Comment by shaundai-tencent** [comment]
we have fixed this problem. please pull the latest master.

**Comment by shaundai-tencent** [comment]
请问，问题解决了吗？

**Comment by mathpopo** [comment]
@shaundai-tencent 是，谢谢！
