### ISSUE TITLE
why  build tnn for linux is X86:	OFF?Arm:	ON?

### ISSUE THREAD

**Issue by mathpopo** [Tencent/TNN#559]
(TNN-Convert) chenxin@Nitro-AN515:~/Downloads/TNN/scripts$ ./build_linux.sh
-- >>>>>>>>>>>>>
-- TNN BUILD INFO:
-- 	System: Linux
-- 	Processor: 
-- 	Cpu:	ON
-- 	X86:	OFF
-- 	Arm:	ON

**Comment by seanxcwang** [comment]
正式发布的版本里还没有针对x86的专门实现，暂时用ARM实现代码的x86 debug版本代替，只是在作为调试用的，当然这里容易造成困惑

**Comment by seanxcwang** [comment]
master里面已经有专门的X86实现，build_linux.sh已经修改过来
