### ISSUE TITLE
/TNN/platforms/linux/test_x86_cpu.sh  error

### ISSUE THREAD

**Issue by mathpopo** [Tencent/TNN#561]
./test/TNNTest -mt TNN -mp=$MODEL_DIR/mobilenet_v2.tnnproto -ip=$MODEL_DIR/$INPUT_FILE_NAME -op=dump_data.txt -wc=0 -ic=1

mobilenet_v2.tnnproto  come from TNN/benchmark/benchmark-model

[ 28%] Built target TNNCpu
[ 99%] Built target TNN
[100%] Built target TNNTest
E/tnn: bool tnn::test::CheckResult(std::__cxx11::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 322] init tnn failed: code: 0x6005 msg: model content is invalid 

i cannot understand this issue

**Comment by seanxcwang** [comment]
目录下有没有tnnmodel文件？如果只想用tnnproto去测试性能，cmake参数里需要开启BENCHMARK_MODE

**Comment by mathpopo** [comment]
cmake ../../.. \
          -DCMAKE_BUILD_TYPE=Debug \
          -DDEBUG=$DEBUG \
          -DTNN_TEST_ENABLE:BOOL="ON"  \
          -DTNN_CPU_ENABLE:BOOL="ON"   \
          -DTNN_BENCHMARK_MODE="ON"

E/tnn: bool tnn::test::CheckResult(std::__cxx11::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 322] init tnn failed: code: 0x1002 msg: proto content is empty

**Comment by mathpopo** [comment]
我把test_android.sh执行完的test.tnnproto拿来也用不了

E/tnn: bool tnn::test::CheckResult(std::__cxx11::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 322] create instance failed: code: 0x9000 msg: device is nil or unsupported

**Comment by mathpopo** [comment]
@seanxcwang 算了，我就在arm上测吧
