### ISSUE TITLE
请问如何支持多输入输出的ONNX网络转换及推理？

### ISSUE THREAD

**Issue by vilon888** [Tencent/TNN#562]
如何转换多输入多输出的onnx网络到tnn，　有相应的示例代码吗？

**Comment by seanxcwang** [comment]
模型转换可以支持多输入多输出，和单输入的转换方式没有区别；推理的时候也一样，多次调用SetInputMat

**Comment by vilon888** [comment]
@seanxcwang 了解, 谢谢啦
