### ISSUE TITLE
请告诉我下，怎么升级这个呢？

### ISSUE THREAD

**Issue by mathpopo** [Tencent/TNN#573]
@neiltian-tencent
FOLLOW https://github.com/Tencent/TNN/issues/511 CAN  compile it , but new error.

[100%] Built target TNNTest
./libTNN.so: 1 file pushed. 31.1 MB/s (3435464 bytes in 0.105s)
test/TNNTest: 1 file pushed. 21.5 MB/s (166216 bytes in 0.007s)
/home/chenxin/Downloads/TNN/benchmark/benchmark_android/../benchmark-model/: 13 files pushed. 3.7 MB/s (159904 bytes in 0.041s)
Run Huawei Npu
/home/chenxin/Downloads/TNN/benchmark/benchmark_android/../../third_party/huawei_npu/cpp_lib/arm64-v8a/libc++_shared.so: 1 file pushed. 15.9 MB/s (5973872 bytes in 0.359s)
/home/chenxin/Downloads/TNN/benchmark/benchmark_android/../../third_party/huawei_npu/hiai_ddk_latest/arm64-v8a/libcpucl.so: 1 file pushed. 17.7 MB/s (1075096 bytes in 0.058s)
/home/chenxin/Downloads/TNN/benchmark/benchmark_android/../../third_party/huawei_npu/hiai_ddk_latest/arm64-v8a/libhcl.so: 1 file pushed. 4.6 MB/s (594336 bytes in 0.124s)
/home/chenxin/Downloads/TNN/benchmark/benchmark_android/../../third_party/huawei_npu/hiai_ddk_latest/arm64-v8a/libhiai_ir_build.so: 1 file pushed. 8.7 MB/s (38896 bytes in 0.004s)
/home/chenxin/Downloads/TNN/benchmark/benchmark_android/../../third_party/huawei_npu/hiai_ddk_latest/arm64-v8a/libhiai_ir.so: 1 file pushed. 25.2 MB/s (1071144 bytes in 0.041s)
/home/chenxin/Downloads/TNN/benchmark/benchmark_android/../../third_party/huawei_npu/hiai_ddk_latest/arm64-v8a/libhiai.so: 1 file pushed. 23.0 MB/s (198688 bytes in 0.008s)
5 files pushed. 11.9 MB/s (2978160 bytes in 0.239s)
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 340] create instance failed: code: 0xE000 msg: ERROR: GetRomVersion(ROM): huawei_npu is not installed or rom version is too low 
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 340] create instance failed: code: 0xE000 msg: ERROR: GetRomVersion(ROM): huawei_npu is not installed or rom version is too low 
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 340] create instance failed: code: 0xE000 msg: ERROR: GetRomVersion(ROM): huawei_npu is not installed or rom version is too low 
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 340] create instance failed: code: 0xE000 msg: ERROR: GetRomVersion(ROM): huawei_npu is not installed or rom version is too low 
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 340] create instance failed: code: 0xE000 msg: ERROR: GetRomVersion(ROM): huawei_npu is not installed or rom version is too low 
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 340] create instance failed: code: 0xE000 msg: ERROR: GetRomVersion(ROM): huawei_npu is not installed or rom version is too low 
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 340] create instance failed: code: 0xE000 msg: ERROR: GetRomVersion(ROM): huawei_npu is not installed or rom version is too low 
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 340] create instance failed: code: 0xE000 msg: ERROR: GetRomVersion(ROM): huawei_npu is not installed or rom version is too low 
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 340] create instance failed: code: 0xE000 msg: ERROR: GetRomVersion(ROM): huawei_npu is not installed or rom version is too low 
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 340] create instance failed: code: 0xE000 msg: ERROR: GetRomVersion(ROM): huawei_npu is not installed or rom version is too low 
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 340] create instance failed: code: 0xE000 msg: ERROR: GetRomVersion(ROM): huawei_npu is not installed or rom version is too low 
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 340] create instance failed: code: 0xE000 msg: ERROR: GetRomVersion(ROM): huawei_npu is not installed or rom version is too low 
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File /home/chenxin/Downloads/TNN/test/test.cc][Line 340] create instance failed: code: 0xE000 msg: ERROR: GetRomVersion(ROM): huawei_npu is not installed or rom version is too low 
/data/local/tmp/tnn-benchmark/benchmark_models_result.txt: 1 file pulled. 0.0 MB/s (71 bytes in 0.003s)

**Comment by mathpopo** [comment]
如果没有npu或是非华为手机 ： 报错 ERROR: GetRomVersion(ROM): npu is not installed or rom version is too low

但是 ：
  (base) chenxin@Nitro-AN515:~$ adb shell getprop ro.product.model
PCT-AL10
(base) chenxin@Nitro-AN515:~$ adb shell cat /proc/cpuinfo
Processor	: AArch64 Processor rev 0 (aarch64)
processor	: 0
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd05
CPU revision	: 0

processor	: 1
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd05
CPU revision	: 0

processor	: 2
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd05
CPU revision	: 0

processor	: 3
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd05
CPU revision	: 0

processor	: 4
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x48
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd40
CPU revision	: 0

processor	: 5
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x48
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd40
CPU revision	: 0

processor	: 6
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x48
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd40
CPU revision	: 0

processor	: 7
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x48
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd40
CPU revision	: 0

Hardware	: Hisilicon Kirin980

**Comment by mathpopo** [comment]
Hardware : Hisilicon Kirin980

**Comment by shaundai-tencent** [comment]
NPU不支持麒麟980的机器，我们只支持华为第三代NPU，麒麟980是第二代NPU。

**Comment by neiltian-tencent** [comment]
这个部署的时候，要根据是否支持NPU来决定是否用NPU，不支持会有error code返回。SDK要代码判断，然后切换为GPU或者CPU。

**Comment by mathpopo** [comment]
@neiltian-tencent @shaundai-tencent 请教下华为第三代NPU是哪些？

**Comment by mathpopo** [comment]
目前有：麒麟810，麒麟820，麒麟985，麒麟990，麒麟990 5G，麒麟990E，麒麟9000，麒麟9000E等。
