### ISSUE TITLE
支持异构和调用其他厂商的库吗？

### ISSUE THREAD

**Issue by i4oolish** [Tencent/TNN#59]
如题，
1. 支持异构吗，比如npu+gpu?自动分割网络，将模型拆分成可以在npu和gpu上执行的子网络
2. 支持调用第三方厂商提供的库吗，比如在高通上直接调用高通的snpe，在三星上直接调用eden。

**Comment by darrenyao87** [comment]
1. 目前支持自动在cpu和gpu上切换网络，但在npu上还不支持，后续会考虑加入
2. npu代码目前没放出来，内部使用觉得很多模型提升不大。预计下个版本发出来。

**Comment by darrenyao87** [comment]
@shaundai-tencent 后续加上麒麟NPU支持

**Comment by shaundai-tencent** [comment]
NPU会在V0.2版本加入。
