### ISSUE TITLE
请问.tnnproto文件能可视化吗？像ncnn的.param文件可以用Netron查看结构

### ISSUE THREAD

**Issue by xchen13** [Tencent/TNN#598]
您好，我最近遇到问题：onnx转tnn后，设置正确的input和output name，但是得不到正确的结果。已经排除是输入格式的问题，现在怀疑可能是转换后网络结构不对。因此有可视化tnn模型的需求，但是找不到方法。
因此提了这个issue。
或者，请问tnn支持逐层输出结果吗？

**Comment by 1627180283** [comment]
可以把 tnnproto 拖拽到 netron 里打开，类似于这样
![image](https://user-images.githubusercontent.com/37806708/100621542-c3cd0a80-335a-11eb-99ab-4dae86d078e1.png)
或者用网页版 netron 打开 https://netron.app

**Comment by 1627180283** [comment]
转换的时候加 -align 会提示模型能成功对齐吗

**Comment by xchen13** [comment]
> 转换的时候加 -align 会提示模型能成功对齐吗
提示了，如图所示。这个网络是单输入，三输出的，修改了图片预处理的均值，未修改bitmap的RGB为BGR，但传入2张其他相同，仅rgb bgr不一样的图片，得到的结果一样，都是“极小的固定值”，后实验发现传入任何图片输出都是这一个固定值。之前怀疑是输入不对，但是instance_->SetInputMat( )内的每一步都执行成功了，TNNSDKSample::Predict( )的第二步instance_->ForwardAsync( )，第三步instance_->GetOutputMat( )均成功执行未报错。输出结果的矩阵也是预期维度，只是值不对，一直是个“极小的固定值”.
![image](https://user-images.githubusercontent.com/30519789/100686116-a3cc3400-33b8-11eb-83f1-a180e457b54d.png)

**Comment by 1627180283** [comment]
-algin 提示成功转换的话说明得到的 tnn 模型是和 onnx 模型一致的。
可以看一下模型第一层的输入和输出是否和 onnx 模型一致。
