### ISSUE TITLE
reduce_layer 的 NAIVE 实现存在 bug

### ISSUE THREAD

**Issue by 1627180283** [Tencent/TNN#599]
**1. 环境（environment）**
 - Build OS and Version: Mac
 - RunTime OS Version: MacOS
 - RunTime DEVICE: NAIVE

  **2. Github版本**
 - branch：master
 - commit(optional): 5f1ec6c0eeadbcf00859956c25ca254349847761

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)
-DDEBUG=ON -DTNN_CPU_ENABLE=ON -DTNN_TEST_ENABLE=ON

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
reduce_layer 的 NAIVE 实现存在 bug
![image](https://user-images.githubusercontent.com/37806708/100622680-1a871400-335c-11eb-8151-5257ac39461d.png)
PreCalculateReduce 之后结果会保存到 input_data 中，会导致之后无法获取 input_data 的原始值。例如这样的结构就会出现结果不对齐
![image](https://user-images.githubusercontent.com/37806708/100622936-6d60cb80-335c-11eb-9012-1d968e203ceb.png)

**Comment by gttiankai** [comment]
相关修复代码已经合并到 master 分支。
