### ISSUE TITLE
onnx的Conv+BatchNormalization在tnn里自动合并成Convolution的问题

### ISSUE THREAD

**Issue by xchen13** [Tencent/TNN#601]
您好，我最近遇到一个问题：onnx转tnn，-optimize -align转换成功，但是我在Netron里发现tnn自动把conv和BN合并了，且权值不太正常，请问对卷积核进行操作等价于BN层吗？
目前我的网络输入输出设置正确，输出得到的矩阵维度正确，但是值不对，且**任何不同的输入都是同一个输出**，有没有可能是这里的问题？
![image](https://user-images.githubusercontent.com/30519789/100706100-5e712c00-33e3-11eb-8d51-80a91951a13c.png)

**Comment by 1627180283** [comment]
tnn 在转换的时候会对 conv 和 bn 进行融合，融合之后 conv 的输出应该是等价于原始模型 conv + bn 的输出。
转换的时候使用 -align 能转换成功的话，说明转换得到的 tnn 模型和原始的 onnx 模型使用随机输入进行推理得到的结果是一致的，也就是转换得到的 tnnproto 和 tnnmodel 是正确的。
对于不同的输入都能得到相同的输出，可以看一下输入是否正确的传入网络进行推理。

**Comment by yuezhuang1387** [comment]
你好，我有跟你一样的问题，network_config.device_type设置为DEVICE_ARM时，一切正常；
将其设置为DEVICE_OPENCL时，网络正常输出，且输出矩阵维度也正确，但是值不对，任何不同的输入都是同一个输出。

**Comment by xchen13** [comment]
> tnn 在转换的时候会对 conv 和 bn 进行融合，融合之后 conv 的输出应该是等价于原始模型 conv + bn 的输出。
> 转换的时候使用 -align 能转换成功的话，说明转换得到的 tnn 模型和原始的 onnx 模型使用随机输入进行推理得到的结果是一致的，也就是转换得到的 tnnproto 和 tnnmodel 是正确的。
> 对于不同的输入都能得到相同的输出，可以看一下输入是否正确的传入网络进行推理。

非常感谢您的回答，请允许我详细说明下自己的TNN使用过程，我套用TNN工程Android Demo中的ImageFaceDetector，
1. 修改face_detector_jni.cc中的NET_W_INPUT=640和NET_H_INPUT=640，并且传入的照片分辨率也为640*640，
2. 修改ultra_face_detector.cc中的input_convert_param.scale和.bias为自己的
3. 修改ultra_face_detector.cc中的#define num_featuremap 3（原始是4），修改相应的min_boxes和strides，
4. 修改ultra_face_detector.cc中的ProcessSDKOutput()函数里的auto output_mat_scores = output->GetMat("586");其中“586”为自己模型的三个输出之一的name，如是修改三次。

我通过debug追踪TNNSDKSample::Predict过程，input_mat大小正确， auto input_convert_param = GetConvertParamForInput();参数正确， auto status = instance_->SetInputMat(input_mat, input_convert_param);均未报错。其中输入类型为：
        blob_->GetBlobDesc().data_type=DATA_TYPE_FLOAT
        image.GetMatType()=N8UC4
追踪default_network.cc中的ForwardAsync（）函数， for (auto layer : layers_) result = layer->Forward();每一层返回都正确（卷积层参数诸如kernel、stride等能在debug模式下看到，但是filter的weight却看不到，weight是在每一层的Exec函数里才加载吗？）
最后，在ultra_face_detector.cc的UltraFaceDetector::ProcessSDKOutput里，截获输出，发现输出的scores值岿然不动。（此处我发现无法展开查看scores的值，因此我在for循环里将每一个值push_back到一个vector里进行查看，不知道是否有更方便的查看方法？）
————————————————————————————————————————————————————
我对比了TNN Face_detector Demo使用的Ultra-Light-Fast-Generic-Face-Detector网络的onnx和自己网络的onnx输入过程，发现仅有RGB和BGR的区别（即使忘记转，也仅仅是影响精度，不至于任何输入，输出都一样）
以上，请问您能看出有啥问题吗？
另外，如何查看tnn第一层的输出呢？我在debug模式下想查看input或者ouput，都显示“error = parent failed to evaluate: variable not available”,该问题谷歌百度都没有找到解决方法。

**Comment by 1627180283** [comment]
要不你在 QQ 群里私聊我，我和你具体看一下吧。我 QQ 群里的昵称是 ealin。

**Comment by xchen13** [comment]
> 要不你在 QQ 群里私聊我，我和你具体看一下吧。我 QQ 群里的昵称是 ealin。

好的，非常感谢您~
