### ISSUE TITLE
while循环做多次人脸检测inference问题

### ISSUE THREAD

**Issue by StrugglingForBetter** [Tencent/TNN#602]
**1. 环境（environment）**
 - Build OS and Version: Mac
 - RunTime OS Version: IOS
 - RunTime DEVICE: METAL

  **2. Github版本**
 - branch：master
 - commit(optional):243ecf7aa809fad11b84ea0c9066489ab9b8f6ce

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
用demo里面的人脸检测模型在IOS跑demo，对demo程序进行了修改，区别在于demo里面只对一张图进行了inference，然后我这边是写了一个while循环对一张图片做多次inference，但是最后跑出来耗时远远大于demo里面的人脸检测所需的时间，我这里大概是4FPS的速度，就是每做一次inference需要250ms，demo里面需要9~12ms，耗时差别太大，即使我把循环次数改为1，还是一样耗时250ms以上。

另外就是循环似乎只能做40次左右，到了一定次数，会报错：The app TNNExamples on iPhone8 plus quit unexpectedly. Message from debugger: Terminated due to memory

我的程序用的接口和demo例子是一样的，区别在于demo没有用循环，我用了循环，然后就是我删除了inference完成之后和camera相关的代码，因为我不需要显示出来，只需要把inference的结果保存在手机里面

报错信息见截图

  **6. 运行日志（runtime log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **7. 截图（Screenshots）**
 ```txt
 将截图粘贴在这里
 Paste screenshorts here or pastebin
![{3A8C689B-D30F-E6BC-AA57-38D2C6C5470D}](https://user-images.githubusercontent.com/20771340/100716865-3c33da00-33f4-11eb-8909-2a7082500ca5.jpg)
![{6E395FA7-9EC4-AB19-44D2-327EC037F729}](https://user-images.githubusercontent.com/20771340/100716872-3fc76100-33f4-11eb-8a6e-e8cd8cbfab2b.jpg)

![{B52FE5C7-B6C3-1E38-B0CF-EA9A14254753}](https://user-images.githubusercontent.com/20771340/100716980-6b4a4b80-33f4-11eb-8484-abfc1bd4363d.jpg)

**Comment by devandong** [comment]
（1）循环使用demo sdk时，需要设置BenchOption.forward_count=1，否则会重复执行模型多次；
（2）在ObjC循环中需要使用autoreleasepool避免临时对象累计，footprint过大导致内存问题
