### ISSUE TITLE
模型转换LOG打印

### ISSUE THREAD

**Issue by yyqgood** [Tencent/TNN#610]
你好,我使用: python converter.py onnx2tnn version-slim-320_simplified.onnx 命令转换模型; 终端直接打印:
----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model

Converter ONNX to TNN model failed!

从打印LOG来看, 我转换模型失败了; 但我没有任何能跟踪的地方?请问: 模型转换失败能否定位具体位置?
期待你的回复, 谢谢!

**Comment by 1627180283** [comment]
TNN/tools/convert2tnn/converter.py 里的 24 行改成 
logging.basicConfig(level=logging.DEBUG, format="")
可以打印出来详细的日志信息

**Comment by yyqgood** [comment]
@1627180283 谢谢,你的回复!
我再实践中遇到和解决的几个问题:
1. 使用代码下载protobuf, 我的Ubuntu18.04, 会下载3.10.0版本, 但此版本编译通不过
2. 下载3.13.0编译通过, 且支持的模型转换成功
3. 代码下载protobuf在终端还是太慢, 建议优化其方法
谢谢!

**Comment by ColdCodeCool** [comment]
@1627180283  请问使用docker转换工具如何打出详细log，谢谢

**Comment by zeakey** [comment]
这也太离谱了。转换失败不给log还要上github上找改源代码来打印log。
