### ISSUE TITLE
Android apk 不支持 荣耀v20

### ISSUE THREAD

**Issue by peyer** [Tencent/TNN#62]
编译好的apk在荣耀v20上无法运行人脸检测，直接闪退，提示apk不兼容jiao高版本安卓

**Comment by neiltian-tencent** [comment]
可能你没有下载模型，参照https://github.com/Tencent/TNN/blob/master/doc/cn/user/demo.md

**Comment by neiltian-tencent** [comment]
或者发一下错误信息

**Comment by peyer** [comment]
确实是没有下载模型
