### ISSUE TITLE
TNN中的 resize 和 opencv 的 resize 结果存在差异

### ISSUE THREAD

**Issue by yanceyou** [Tencent/TNN#626]
**1. 环境（environment）**
 - Build OS and Version: Mac/Ubuntu/Centos/Windows
 - RunTime OS Version: Linux/Android/IOS
 - RunTime DEVICE: ARM/OPENCL/METAL

 **2. 详细描述bug 情况 (Describe the bug)**

如果传值的 param 为 size 的话，总共 16800 多个像素，大概存在 30来个像素存在 1px 的偏差，如下图
![image](https://user-images.githubusercontent.com/16320418/101306196-33715700-387f-11eb-9f89-4da79752cfc4.png)

但是，如果 param 为 scale 的话，会放大至 20%以上的像素存在误差，并且误差存在累计。

预计可能的原因应该是入参的问题，opencv 采用的 scale 计算为 double， tnn 的为 float

**Comment by quinnrong94** [comment]
如果参数中的scale不是由源图像和目标图像的尺寸计算获得，而是任意的数值，tnn和opencv的处理方式存在微小差异，该差异对resize效果不会产生影响。
如果需要达到像素级对齐，建议参数中直接设置源图像和目标图像的尺寸，或者根据图像尺寸计算出实际使用的scale数值。
