### ISSUE TITLE
在Jetson TX2上编译不通过

### ISSUE THREAD

**Issue by ShanQiong** [Tencent/TNN#634]
求助...
在TX2上直接编译,不通过,
采用的编译指令如下:(仿照build_aarch64_linux.sh和build_linux.sh)
#!/bin/bash

SHARED_LIB="ON"
ARM="ON"
OPENMP="ON"
OPENCL="OFF"
QUANTIZATION="OFF"
CC=gcc
CXX=g++

if [ -z $TNN_ROOT_PATH ]
then
    TNN_ROOT_PATH=$(cd `dirname $0`; pwd)/..
fi

mkdir build_linux
cd build_linux

cmake ${TNN_ROOT_PATH} \
    -DCMAKE_SYSTEM_NAME=Linux  \
    -DTNN_TEST_ENABLE=OFF \
    -DTNN_CPU_ENABLE=OFF \
    -DCMAKE_C_COMPILER=$CC \
    -DCMAKE_CXX_COMPILER=$CXX \
    -DCMAKE_BUILD_TYPE=Release \
    -DTNN_ARM_ENABLE:BOOL=$ARM \
    -DTNN_OPENMP_ENABLE:BOOL=$OPENMP \
    -DTNN_OPENCL_ENABLE:BOOL=$OPENCL \
    -DTNN_BUILD_SHARED:BOOL=$SHARED_LIB \

make -j4

编译得到的错误信息:

../../libTNN.so.0.1.0.0: undefined reference to `GemmInt8Unit8x8'
../../libTNN.so.0.1.0.0: undefined reference to `GemmBfp16SlidewC3'
../../libTNN.so.0.1.0.0: undefined reference to `GEMM_FLOAT_N8'
../../libTNN.so.0.1.0.0: undefined reference to `ConvBfp16O4'
../../libTNN.so.0.1.0.0: undefined reference to `ConvDw3x3FloatSlideW'
../../libTNN.so.0.1.0.0: undefined reference to `DeconvFloatO4'
../../libTNN.so.0.1.0.0: undefined reference to `ConvDw5x5Bfp16SlideW'
../../libTNN.so.0.1.0.0: undefined reference to `ConvDw3x3Bfp16SlideW'
../../libTNN.so.0.1.0.0: undefined reference to `ConvDw5x5FloatSlideW'
../../libTNN.so.0.1.0.0: undefined reference to `GEMM_BFP16_N8'
../../libTNN.so.0.1.0.0: undefined reference to `GemmInt8Unit4x4'
../../libTNN.so.0.1.0.0: undefined reference to `ConvFloatO4'
../../libTNN.so.0.1.0.0: undefined reference to `GemmFloatSlidewC3'
collect2: error: ld returned 1 exit status
tools/converter/CMakeFiles/TnnConverter.dir/build.make:1354: recipe for target 'tools/converter/TnnConverter' failed
make[2]: *** [tools/converter/TnnConverter] Error 1
CMakeFiles/Makefile2:560: recipe for target 'tools/converter/CMakeFiles/TnnConverter.dir/all' failed
make[1]: *** [tools/converter/CMakeFiles/TnnConverter.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by seanxcwang** [comment]
加上`-DCMAKE_SYSTEM_PROCESSOR=aarch64`

**Comment by ShanQiong** [comment]
确实可以了, 我没加过去,找了半天,谢谢啦
我后来用了nvidia提供的交叉编译工具链也编译过去了
