### ISSUE TITLE
Pose demo

### ISSUE THREAD

**Issue by KyoukaMinaduki** [Tencent/TNN#637]
Hello. I wonder whether there are or will be any demo for pose estimation? Either for mobile devices(andorid or ios) or x86.

**Comment by devandong** [comment]
Hi, two pose demos are under development and will be released in a few days. If you want to try it now, you could switch to the feature_demo_skeleton branch and it can run on iOS devices.

**Comment by KyoukaMinaduki** [comment]
Oh thank you. I am waiting.
BTW, the pose demos on android and ios, and x86 demos with C++，will be released recently together, right？

**Comment by devandong** [comment]
We will provide C++ code and an iOS app for these two demos. All core operations are handled in the C++ code and the ObjC layer just focues on the user interface and camera. The android and x86 demos may not catch up with the iOS app, so if you want a full-platform support, you may need to implement them for now with the reference to current demos.

**Comment by jizhu1023** [comment]
Hi @devandong, the pose-related model files in the two pose demo branches (feature_demo_sleleton, feature_demo_blazepose) are missing and cannot be downloaded through the "download_model.sh" (404: Not Found). We want to test the two demos. Could you update the model link? Many thanks in advance!

**Comment by devandong** [comment]
> Hi @devandong, the pose-related model files in the two pose demo branches (feature_demo_sleleton, feature_demo_blazepose) are missing and cannot be downloaded through the "download_model.sh" (404: Not Found). We want to test the two demos. Could you update the model link? Many thanks in advance!

Reply in TNN QQ group.

**Comment by devandong** [comment]
blazepose and skeleton demos have benn merged into master.
