### ISSUE TITLE
量化mobilenetV2显示成功，推断时输出为NA

### ISSUE THREAD

**Issue by tucker666** [Tencent/TNN#642]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu
 - RunTime OS Version: Android
 - RunTime DEVICE: ARM

  **2. Github版本**
 - branch：master

  **3. 编译方式(compile method)**
成功编译

  **4. 编译日志(build log)**
成功编译
/root/TNN/platforms/linux/build/quantization_cmd \
-p /root/TNN/int8/model/model928_linux_sim.opt.tnnproto \
-m /root/TNN/int8/model/model928_linux_sim.opt.tnnmodel \
-i /root/TNN/int8/input/ \
-n 0.61892796,0.49968997,0.384884 \
-s 0.28675202,0.30338955,0.32455528

  **5. 详细描述bug 情况 (Describe the bug)**
使用量化工具，成功量化mobilenet V2模型，但是在安卓demo推断时输出为NA

  **6. 运行日志（runtime log）**
	Quantize Convolution parameters...
	====> done!
	Quantize Convolution parameters...
	====> done!
	Quantize InnerProduct parameters...
	====> done!
Start to Merge Blob Scale ...
quantize model success!

  **7. 截图（Screenshots）**
![image](https://user-images.githubusercontent.com/53161743/102035776-41cdee80-3dfc-11eb-9925-3698c059d9e6.png)

**Comment by shaundai-tencent** [comment]
量化中设置的预处理公式是：
y = (x - bias) * scale
看你设置的-n，貌似不太正确，请检查一下。

**Comment by tucker666** [comment]
> 量化中设置的预处理公式是：
> y = (x - bias) * scale
> 看你设置的-n，貌似不太正确，请检查一下。
感谢回复，按照公式修改了一下，输出是无穷大
-n 157.8266298,127.42094234999999,98.14542 \
-s 0.01367581,0.0129258,0.01208289
![image](https://user-images.githubusercontent.com/53161743/102047572-7485e000-3e18-11eb-943f-b438212ab63e.png)

**Comment by tucker666** [comment]
> 量化中设置的预处理公式是：
> y = (x - bias) * scale
> 看你设置的-n，貌似不太正确，请检查一下。
感谢回复，已经修改，现在完整命令为
/root/TNN/platforms/linux/build/quantization_cmd \
-p /root/TNN/int8/model/model928_linux_sim.opt.tnnproto \
-m /root/TNN/int8/model/model928_linux_sim.opt.tnnmodel \
-i /root/TNN/int8/input/ \
-n 157.8266298,127.42094234999999,98.14542 \
-s 0.01367581,0.0129258,0.01208289
但是输出为无穷大，还是有问题
![image](https://user-images.githubusercontent.com/53161743/102047849-f83fcc80-3e18-11eb-8911-e41b01782bdf.png)

**Comment by shaundai-tencent** [comment]
量化的效果和模型的参数分布有一定的关系的。可以排查一下从哪一层开始，结果不正常的。
方法：
1. 更改一下源码，TNN/source/tnn/utils/blob_dump_utils.h中，DUMP_OUTPUT_BLOB设为1。
2. 重新编译跑一下，会dump出所有层的output。
住：forwad的时候使用Forward()接口，不要使用ForwardAsync()，否则也dump不出来。
