### ISSUE TITLE
Benchmark evaluation failed - CreateLayer failed - no more information

### ISSUE THREAD

**Issue by Ajay-Reva** [Tencent/TNN#647]
**1. 环境（environment）**
 - Build OS and Version: Mac/Ubuntu/Centos/Windows - Linux 18.04
 - RunTime OS Version: Linux/Android/IOS - Android
 - RunTime DEVICE: ARM/OPENCL/METAL: Both ARM and OpenCL

  **2. Github版本**
 - branch：Master

5. I am trying run a converted tnnproto model but I am not able to debug the problem "CreateLayer failed"

6. E/tnn: virtual tnn::Status tnn::DefaultNetwork::InitLayers(tnn::NetStructure *, tnn::NetResource *) [File /TNN/source/tnn/core/default_network.cc][Line 154] Error: CreateLayer failed, type:103
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File TNNN/test/test.cc][Line 322] create instance failed: code: 0x1000 msg: CreateLayer failed 
E/tnn: virtual tnn::Status tnn::BinaryLayerResourceGenerator::GenLayerResource(tnn::LayerParam *, tnn::LayerResource **, std::vector<Blob *> &) [File TNN/source/tnn/interpreter/layer_resource_generator.cc][Line 220] [WARNNING] can't infer resource shape from binary param in benchmark mode, random generator may not be exactly same with the real resource!
E/tnn: virtual tnn::Status tnn::BinaryLayerResourceGenerator::GenLayerResource(tnn::LayerParam *, tnn::LayerResource **, std::vector<Blob *> &) [File TNN/source/tnn/interpreter/layer_resource_generator.cc][Line 220] [WARNNING] can't infer resource shape from binary param in benchmark mode, random generator may not be exactly same with the real resource!
E/tnn: virtual tnn::Status tnn::BinaryLayerResourceGenerator::GenLayerResource(tnn::LayerParam *, tnn::LayerResource **, std::vector<Blob *> &) [File TNN/source/tnn/interpreter/layer_resource_generator.cc][Line 220] [WARNNING] can't infer resource shape from binary param in benchmark mode, random generator may not be exactly same with the real resource!
E/tnn: virtual tnn::Status tnn::BinaryLayerResourceGenerator::GenLayerResource(tnn::LayerParam *, tnn::LayerResource **, std::vector<Blob *> &) [File TNN/source/tnn/interpreter/layer_resource_generator.cc][Line 220] [WARNNING] can't infer resource shape from binary param in benchmark mode, random generator may not be exactly same with the real resource!
E/tnn: virtual tnn::Status tnn::BinaryLayerResourceGenerator::GenLayerResource(tnn::LayerParam *, tnn::LayerResource **, std::vector<Blob *> &) [File TNN/source/tnn/interpreter/layer_resource_generator.cc][Line 220] [WARNNING] can't infer resource shape from binary param in benchmark mode, random generator may not be exactly same with the real resource!
E/tnn: virtual tnn::Status tnn::BinaryLayerResourceGenerator::GenLayerResource(tnn::LayerParam *, tnn::LayerResource **, std::vector<Blob *> &) [File TNN/source/tnn/interpreter/layer_resource_generator.cc][Line 220] [WARNNING] can't infer resource shape from binary param in benchmark mode, random generator may not be exactly same with the real resource!
E/tnn: virtual tnn::Status tnn::BinaryLayerResourceGenerator::GenLayerResource(tnn::LayerParam *, tnn::LayerResource **, std::vector<Blob *> &) [File TNN/source/tnn/interpreter/layer_resource_generator.cc][Line 220] [WARNNING] can't infer resource shape from binary param in benchmark mode, random generator may not be exactly same with the real resource!
E/tnn: virtual tnn::Status tnn::DefaultNetwork::InitLayers(tnn::NetStructure *, tnn::NetResource *) [File TNN/source/tnn/core/default_network.cc][Line 154] Error: CreateLayer failed, type:103
E/tnn: bool tnn::test::CheckResult(std::string, tnn::Status) [File TNN/test/test.cc][Line 322] create instance failed: code: 0x1000 msg: CreateLayer failed 
/data/local/tmp/tnn-benchmark/benchmark_models_result.txt: 1 file pulled, 0 skipped. 0.1 MB/s (100 bytes in 0.001s)

**Comment by shaundai-tencent** [comment]
这是Cast算子不支持导致的错误，可以用最新的代码重新试试，最新代码各个平台已经支持这个算子。
