### ISSUE TITLE
auto image_mat构建失败

### ISSUE THREAD

**Issue by xiongzhu666** [Tencent/TNN#662]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu18.04
 - RunTime OS Version: Linux

  **2. Github版本**
 - branch：直接拉的主分支master

  **3. 编译方式(compile method)**
直接执行build_linux.sh文件
SHARED_LIB="ON"
ARM="ON"
OPENMP="ON"
OPENCL="OFF"
QUANTIZATION="OFF"
CC=gcc
CXX=g++

if [ -z $TNN_ROOT_PATH ]
then
    TNN_ROOT_PATH=$(cd `dirname $0`; pwd)/..
fi
mkdir build_linux
cd build_linux
cmake ${TNN_ROOT_PATH} \
    -DCMAKE_SYSTEM_NAME=Linux  \
    -DTNN_TEST_ENABLE=ON \
    -DTNN_CPU_ENABLE=ON \
    -DCMAKE_C_COMPILER=$CC \
    -DCMAKE_CXX_COMPILER=$CXX \
    -DTNN_ARM_ENABLE:BOOL=$ARM \
    -DTNN_OPENMP_ENABLE:BOOL=$OPENMP \
    -DTNN_OPENCL_ENABLE:BOOL=$OPENCL \
    -DTNN_QUANTIZATION_ENABLE:BOOL=$QUANTIZATION \
    -DTNN_UNIT_TEST_ENABLE=ON \
    -DTNN_COVERAGE=ON \
    -DTNN_BENCHMARK_MODE=ON \
    -DTNN_BUILD_SHARED:BOOL=$SHARED_LIB \
    -DTNN_CONVERTER_ENABLE=ON
make -j4
# check compile error, or ci will not stop
if [ 0 -ne $? ]
then
    exit -1
fi
ctest --output-on-failure -j 2

  **4. 编译日志(build log)**
运行build_linux.sh编译成功，运行./demo_arm_linux_facedetector ../../../model/face_detector/version-slim-320_simplified.tnnproto ../../../model/face_detector/version-slim-320_simplified.tnnmodel没问题

  **5. 详细描述bug 情况 (Describe the bug)**
image_mat 构建失败，我是仿照人脸检测demo的例子写的hair_segmentation：
unsigned char *data = stbi_load(input_imgfn, &image_width, &image_height, &image_channel, 3);
auto image_mat = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_NAIVE, TNN_NS::N8UC3, nchw, data);
我把data的数据打印出来是有的，但是image_mat是空

  **6. 运行日志（runtime log）**
tnn::Status tnn::Instance::SetInputMat(std::shared_ptr<tnn::Mat>, tnn::MatConvertParam, std::__cxx11::string) [File /DATA/share/xiongzhu/thirdpart/TNN/source/tnn/core/instance.cc][Line 118] input mat is empty ,please check!
E/tnn: tnn::Status tnn::Instance::SetInputMat(std::shared_ptr<tnn::Mat>, tnn::MatConvertParam, std::__cxx11::string) [File /DATA/share/xiongzhu/thirdpart/TNN/source/tnn/core/instance.cc][Line 118] input mat is empty ,please check!
TNN API ERROR:0x1000E/tnn: tnn::Status tnn::Instance::SetInputMat(std::shared_ptr<tnn::Mat>, tnn::MatConvertParam, std::__cxx11::string) [File /DATA/share/xiongzhu/thirdpart/TNN/source/tnn/core/instance.cc][Line 118] input mat is empty ,please check!

**Comment by shaundai-tencent** [comment]
首先检查一下 data这个数据指针是否是空。因为这种Mat的使用方法，只是把data的数据指针传入。

**Comment by liziru** [comment]
> 首先检查一下 data这个数据指针是否是空。因为这种Mat的使用方法，只是把data的数据指针传入。
你好，我初始化了data指针，来代替读入图片，并且data不为空。但还是遇到了这个问题。
[https://github.com/Tencent/TNN/issues/1227#issuecomment-900338386](url)

**Comment by shaundai-tencent** [comment]
是"input mat isempty"这个错误吗？这个TNN内部就是做了一个简单的检查，因为传入的Mat是一个智能指针，如果传入的智能指针为空，则会报这个错，那请你在调用接口之前确认一下，这个Mat是否已经自动销毁了或者没有初始化成功。

**Comment by liziru** [comment]
> 是"input mat isempty"这个错误吗？这个TNN内部就是做了一个简单的检查，因为传入的Mat是一个智能指针，如果传入的智能指针为空，则会报这个错，那请你在调用接口之前确认一下，这个Mat是否已经自动销毁了或者没有初始化成功。

是的，错误如下。
![image](https://user-images.githubusercontent.com/34911790/129829285-4b126ed7-70df-4d26-970d-c2b998dfc3ae.png)
我在mat初始化后做了是否初始化为空的判断，如下，但还是出现上面图片的错误。 有点迷惑。 
![image](https://user-images.githubusercontent.com/34911790/129829214-f0b326a3-a59b-4ff4-84cc-efb3ff46f9ad.png)

**Comment by liziru** [comment]
最新的消息，问题出现在图中标注的预测的那一行，我不知道这一行为什么会出这个问题。。。
![image](https://user-images.githubusercontent.com/34911790/129830333-8c24df56-8044-47ee-a15d-02614b82a7e6.png)

![image](https://user-images.githubusercontent.com/34911790/129830409-4ed4ada8-9b9b-40b9-8e60-caf003fa5a6a.png)

**Comment by shaundai-tencent** [comment]
TNN内部判断是否为空和你判断的data指针是否为空没有关系，因为TNN判断的主体是你这边的resize_mat，而不是image_mat中的data指针。你需要再你的逻辑上面检查，传入的resize_mat这个智能指针为什么是空的。

**Comment by liziru** [comment]
> image_mat

我仔细检查了，并没有发现resize_mat为空，毕竟就这几行代码，我也已做了一些测试。 
可以帮忙看一下吗，代码在上面。

**Comment by liziru** [comment]
问题已经解决，谢谢。 @shaundai-tencent

**Comment by shaundai-tencent** [comment]
好的，是使用上面的问题吗？能否同步一下原因，也可以让其他开发者参考一下。

**Comment by liziru** [comment]
> 好的，是使用上面的问题吗？能否同步一下原因，也可以让其他开发者参考一下。

是输入的问题。 要求两个输入，但只给了一个，就产生了这个错误。
