### ISSUE TITLE
NetworkConfig结构体中Precision参数怎么配置？

### ISSUE THREAD

**Issue by enduringstack** [Tencent/TNN#67]
你好！关于NetworkConfig结构体中的Precision枚举参数，请教如下的问题：

1、该参数用户在构造NetworkConfig的时候，怎么配置？ 

2、该参数是表示模型参数如权值参数数据类型还是运行的结果的数据类型？

3、该参数应该可以看做决定了模型的精度，关于精度和性能，用户如何平衡？还是框架平衡？ 

期待回答。

**Comment by alohali** [comment]
目前， 正常运行fp32， int8模型设置为PRECISION_NORMAL和HIGH都可以，LOW是单独给bfp16用的
