### ISSUE TITLE
能否支持x86平台下的int8推理加速

### ISSUE THREAD

**Issue by hset911** [Tencent/TNN#677]
目前在前端嵌入式采用int8推理加速后，要和x86服务端联动，x86的int8推理只支持native的方式，速度不可接受的慢。

希望可以优化x86平台下int8推理加速，实现算子simd加速，以及汇编实现核心算子加速等。

**Comment by bluaxe** [comment]
您好，x86 int8 也是我们关注的重要特性， 已正在后续版本规划中，还请等待后续版本
