### ISSUE TITLE
arm Linux rk3399 open model error

### ISSUE THREAD

**Issue by idreamerhx** [Tencent/TNN#678]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu
 - RunTime OS Version: Linux
 - RunTime DEVICE: ARM/

  **2. Github版本**
 - branch：master
 - commit(optional):

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)
root@ea9b915671cf:/opt/TNN/scripts# cat build_aarch64_linux.sh.bak
#!/bin/bash

SHARED_LIB="ON"
ARM="ON"
OPENMP="ON"
OPENCL="OFF"
CC=aarch64-linux-gnu-gcc
CXX=aarch64-linux-gnu-g++
TARGET_ARCH=aarch64

if [ -z $TNN_ROOT_PATH ]
then
    TNN_ROOT_PATH=$(cd `dirname $0`; pwd)/..
fi

mkdir build_aarch64_linux
cd build_aarch64_linux

cmake ${TNN_ROOT_PATH} \
    -DCMAKE_SYSTEM_NAME=Linux  \
    -DTNN_TEST_ENABLE=ON \
    -DTNN_CPU_ENABLE=OFF \
    -DCMAKE_C_COMPILER=$CC \
    -DCMAKE_CXX_COMPILER=$CXX \
    -DCMAKE_BUILD_TYPE=Release \
    -DTNN_ARM_ENABLE:BOOL=$ARM \
    -DTNN_OPENMP_ENABLE:BOOL=$OPENMP \
    -DTNN_OPENCL_ENABLE:BOOL=$OPENCL \
    -DCMAKE_SYSTEM_PROCESSOR=$TARGET_ARCH \
    -DTNN_BUILD_SHARED:BOOL=$SHARED_LIB

make -j4

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**

  **6. 运行日志（runtime log）**
 ```txt
 将日志粘贴在这里
root@ea9b915671cf:/opt/TNN# cat run_test.sh
export LD_LIBRARY_PATH=/opt/TNN/build_aarch64_linux:/opt/opencv-4.5.0/inst/lib

./build_aarch64_linux/test/TNNTest -mt TNN -mp model/yolov5/yolov5s-permute.tnnproto \
-dt ARM -ic 1 -wc 0 \
-ip /opt/media/images/Cat-640x448.bgr -op /tmp/aa.jpg \
-dl 0 -th 1 -it 1 -pr NORMAL -is input[1,3,448,640]
root@ea9b915671cf:/opt/TNN# sh run_test.sh
E/tnn: bool tnn::test::CheckResult(std::__cxx11::string, tnn::Status) [File /opt/TNN/test/test.cc][Line 322] init tnn failed: code: 0x6005 msg: model content is invalid
r
 ```

  **7. 截图（Screenshots）**
 ```txt
 将截图粘贴在这里
 Paste screenshorts here or pastebin
 ```

**Comment by seanxcwang** [comment]
tnnmodel和proto在同一个目录吗，看你的编译参数没有开启BENCHMARK_MODE，所以如果没有找到tnnmodel是会报错的，如果开启该参数，则找不到model会自动生成随机权值
