### ISSUE TITLE
mobilenetV2模型推断过程中误差逐渐积累

### ISSUE THREAD

**Issue by tucker666** [Tencent/TNN#679]
**1. 环境（environment）**
 - Build OS and Version: Windows
 - RunTime OS Version: Android
 - RunTime DEVICE: ARM
使用mobilenetV2模型，在转换模型时提示align成功
日志如下
----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model

Converter ONNX to TNN model succeed!

----------  align model (tflite or ONNX vs TNN),please wait a moment ----------

Check onnx input shape and tnn input shape align!

----------  Congratulations!   ----------
The onnx model aligned with tnn model
在推断过程中，误差似乎有逐渐积累的状况
初始输入tnn前四个值为
![image](https://user-images.githubusercontent.com/53161743/103269361-a38f7a80-49f0-11eb-9725-27938e1d249e.png)
onnx runningtime输入为
![image](https://user-images.githubusercontent.com/53161743/103269461-e3eef880-49f0-11eb-82ef-cc2a7c9d58cc.png)
最后几位小数点已经有一些不同
  在中间某个relu层tnn前四个数值为
![image](https://user-images.githubusercontent.com/53161743/103269123-13513580-49f0-11eb-8778-e35479ee251c.png)

onnx runningtime输出为
![image](https://user-images.githubusercontent.com/53161743/103269140-1fd58e00-49f0-11eb-869e-177814ef575b.png)
已经有了一些偏差
到最后全连接层时，tnn输出为
![image](https://user-images.githubusercontent.com/53161743/103269194-41cf1080-49f0-11eb-8113-a4236eacf032.png)
而onnx模型输出为
![image](https://user-images.githubusercontent.com/53161743/103269258-6b883780-49f0-11eb-8c91-ec8b6d632a41.png)
差异已经非常大
请问在模型转换align提示成功的情况下是否会出现逐渐积累误差的情况，以及应该如何解决该问题，谢谢

**Comment by seanxcwang** [comment]
可以将device type设置为NAIVE和OPENCL看下，转换模型时，align参数是使用onnx与NAIVE的计算结果去比对的

**Comment by tucker666** [comment]
> 可以将device type设置为NAIVE和OPENCL看下，转换模型时，align参数是使用onnx与NAIVE的计算结果去比对的
您说的是在demo里打开和关闭GPU么，这两者结果有一点差异，但是和onnx模型差异更大，请问NAIVE的含义是什么，是在CPU下对齐么
![image](https://user-images.githubusercontent.com/53161743/103323858-b8ffb580-4a7f-11eb-9c70-dc4606d6cf06.png)
![image](https://user-images.githubusercontent.com/53161743/103323861-bd2bd300-4a7f-11eb-9501-36407f5157b4.png)

**Comment by tucker666** [comment]
我又试了一张全黑的图片
这是onnx的结果
![image](https://user-images.githubusercontent.com/53161743/103324208-717a2900-4a81-11eb-9e23-a3e8e4870a66.png)
这是tnn的结果
![微信图片_20201230092958](https://user-images.githubusercontent.com/53161743/103324241-a1c1c780-4a81-11eb-9276-b80d367f113d.jpg)
试了一张全白的图片
![微信图片_20201230092958](https://user-images.githubusercontent.com/53161743/103324507-bb174380-4a82-11eb-9832-41226550a2c5.jpg)
![image](https://user-images.githubusercontent.com/53161743/103324515-c2d6e800-4a82-11eb-9b4d-27ee76bd70b8.png)

**Comment by tucker666** [comment]
又测试了一下，如果输入图片是模型输入尺寸，也就是224*224的话，tnn和onnxrunnningtime是差不多的，如果是大尺寸需要resize,那么结果差别就会比较大，应该是onnxrunning time 使用 transform(PIL)的resize和Bitmap的resclae方法不同导致的结果差异造成的
