### ISSUE TITLE
ARM and GPU duration is the same - error code: 40963

### ISSUE THREAD

**Issue by Ajay-Reva** [Tencent/TNN#685]
**1. 环境（environment）**
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

  **2. Github版本**
 - branch：master
 - commit(optional): commit 45f058623f43c940b0d6d04485e1c03b016fccf4 (HEAD -> master, origin/master, origin/HEAD)
Merge: 2483c382 3cb9fb6b
Author: neiltian <65950677+neiltian-tencent@users.noreply.github.com>
Date:   Wed Dec 30 20:25:02 2020 +0800

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments) - Default

    cmake ../../.. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DANDROID_ABI="${ABI}" \
          -DANDROID_STL=${STL}\
          -DANDROID_NATIVE_API_LEVEL=android-14  \
          -DANDROID_TOOLCHAIN=clang \
          -DTNN_ARM_ENABLE:BOOL=ON \
          -DTNN_OPENCL_ENABLE:BOOL=ON \
          -DTNN_HUAWEI_NPU_ENABLE:BOOL=${HUAWEI_NPU_ENABLE} \
          -DTNN_OPENMP_ENABLE:BOOL=ON \
          -DTNN_TEST_ENABLE:BOOL=ON \
          -DTNN_BUILD_BENCHMARK_TEST_LIB_ENABLE:BOOL=ON \
          -DTNN_BENCHMARK_MODE:BOOL=ON \
          -DTNN_PROFILER_ENABLE:BOOL=${PROFILING} \
          -DTNN_BUILD_SHARED:BOOL=ON \
          -DBUILD_FOR_ANDROID_COMMAND=true
    make -j4

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```
ajay@n005:TNN/benchmark/benchmark_android$ ./benchmark_models.sh -c
-- android-14 is unsupported. Using minimum supported version 16.
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: android/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /android/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is Clang
-- Found assembler: android/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
/TNN
/TNN
-- Found OpenMP_C: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  
-- >>>>>>>>>>>>>
-- TNN BUILD INFO:
-- 	System: Android
-- 	Processor: aarch64
-- 	Cpu:	OFF
-- 	X86:	OFF
-- 	Arm:	ON
-- 	Arm82:	OFF
-- 	Metal:	OFF
-- 	OpenCL:	ON
-- 	CUDA:	OFF
-- 	DSP:	OFF
-- 	Atlas:	OFF
-- 	TensorRT:	OFF
-- 	HuaweiNPU:	
-- 	RKNPU:	OFF
-- 	OpenVINO:	OFF
-- 	OpenMP:	ON
-- 	TEST:	ON
-- 	--Unit Test:	OFF
-- 	Qantization:	OFF
-- 	ModelCheck:	OFF
-- 	DEBUG:	
-- 	PROFILE:	OFF
-- 	BENCHMARK:	ON
-- 	BENCHMARK Layer:	OFF
-- 	Model Converter:	OFF
-- 	TNN2MEM:	OFF
-- 	BENCHMARK Test Lib:	ON
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
Generate OpenCL Source done !!! 

-- Build TNN OpenCL
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - found
-- Looking for C++ include fnmatch.h
-- Looking for C++ include fnmatch.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Looking for strtoll
-- Looking for strtoll - found
-- Configuring done
-- Generating done
-- Build files have been written to: /xxx/xxxx/xxx/xx

  **5. 详细描述bug 情况 (Describe the bug)**
CPU and GPU performance time is the same
12-30 16:26:59.120 4909 4909 I tnn : Net.tnnproto TNN Benchmark time cost failed error code: 40963

  **6. 运行日志（runtime log）**

[100%] Built target tnn_wrapper
Performing Streamed Install
Success
TNN/benchmark/benchmark_android/../benchmark-model/: 42 files pushed, 0 skipped. 15.4 MB/s (1608583 bytes in 0.099s)
./build_app/libtnn_wrapper.so: 1 file pushed, 0 skipped. 788.4 MB/s (464968 bytes in 0.001s)
./test/libTNNBenchmarkTest.so: 1 file pushed, 0 skipped. 668.5 MB/s (223368 bytes in 0.000s)
./libTNN.so: 1 file pushed, 0 skipped. 243.5 MB/s (3951728 bytes in 0.015s)

benchmark device: ARM

Stopping: com.tencent.tnn.benchmark
Starting: Intent { cmp=com.tencent.tnn.benchmark/.MainActivity (has extras) }
Status: ok
LaunchState: COLD
Activity: com.tencent.tnn.benchmark/.MainActivity
TotalTime: 1365
WaitTime: 1367
Complete
12-30 16:26:50.747 4625 4625 I tnn : void tnn::test::Timer::Print() [File TNN/test/timer.cc][Line 60] Net.tnnproto - ARM TNN Benchmark time cost: min = 38.208 ms | max = 45.418 ms | avg = 41.151 ms

benchmark device: OPENCL

Stopping: com.tencent.tnn.benchmark
Starting: Intent { cmp=com.tencent.tnn.benchmark/.MainActivity (has extras) }
Status: ok
LaunchState: COLD
Activity: com.tencent.tnn.benchmark/.MainActivity
TotalTime: 2151
WaitTime: 1380
Complete
12-30 16:26:59.120 4909 4909 I tnn : Net.tnnproto TNN Benchmark time cost failed error code: 40963
Success
Redmi Note 8 Pro
12-30 16:26:50.747 4625 4625 I tnn : void tnn::test::Timer::Print() [File TNN/test/timer.cc][Line 60] Net.tnnproto - ARM TNN Benchmark time cost: min = 38.208 ms | max = 45.418 ms | avg = 41.151 ms

Wed Dec 30 16:27:05 CET 2020

**Comment by shaundai-tencent** [comment]
这个错误是OpenCL平台某个算子初始化失败了，可能是算子不支持，所以OpenCL没有跑起来，可以具体打印一下error info。可以使用最新的代码重新试一下，近期已经添加了很多算子支持。
