### ISSUE TITLE
加入了新算子的tnn包在IOS端出现interpreter is nil的报错

### ISSUE THREAD

**Issue by Huahua2021** [Tencent/TNN#686]
今后可能会开发新增算子，因此先走个全流程。
pytorh里的linear层可能会被转成onnx里的matmul，然后tnn将matmul识别为gemm，转换成innerproduct。
我想仿照innerproduct开发一个残血版的matmul。

由于错误不断，我索性只改innerproduct的名字以及类相关的为matmul。而且连convert也改了，可以保证将onnx里的matmul改成tnn里的matmul。并且在andorid端运行成功，且结果完全一致（那是自然）。

但是在ios上运行的时候报错
> 2020-12-31 09:27:29.059462+0800 TNNExamples[11445:2562834] [TNNExamples] getVal16:139: *** IIOScanner::getVal16 reached EOF
> E/tnn: virtual tnn::Status tnn::ModelInterpreter::InterpretModel(std::string) [File /Users/zhonghanyu/Desktop/TNN-0.2.3-matmul2-ios/source/tnn/interpreter/tnn/model_interpreter.cc][Line 296] Error: layer_interpreter nil name:MatMul_149 type_from_str:MatMul type:105
> E/tnn: virtual tnn::Status tnn::TNNSDKSample::Init(std::shared_ptr<TNNSDKOption>) [File /Users/zhonghanyu/Desktop/TNN-0.2.3-matmul2-ios/examples/base/tnn_sdk_sample.cc][Line 458] instance.net init failed 245812020-12-31 09:27:30.008104+0800 TNNExamples[11445:2562834] Error: code: 0x6005 msg: Error: layer_interpreter is nil

项目链接如下，模型已经更改，运行ios的demo中的imageclassify即可
链接: https://pan.baidu.com/s/17R1WhK05L-Iadg2dgG_btw 提取码: dqqk 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by devandong** [comment]
如果增加了新的interpretor代码文件，则需要更新xcode项目，才可以将interpreter编译进去。
具体需要打开platforms/ios/tnn.xcodeproj，并将新增的代码文件添加到项目中。
