### ISSUE TITLE
模型转换工具疑问

### ISSUE THREAD

**Issue by tucker666** [Tencent/TNN#698]
![image](https://user-images.githubusercontent.com/53161743/103519206-15b00580-4eb0-11eb-9c4e-1c2d2a30f1e7.png)
其中ref文件是随便删了输入的几行，最后提示align成功，不太理解，另外请问模型输出是在哪里

**Comment by shaundai-tencent** [comment]
我们这边没有复现你的问题，能否提供一下你的模型与输入输出文件？
