### ISSUE TITLE
TNN在Android跑CPU multi-thread SetCpuNumThreads會閃退

### ISSUE THREAD

**Issue by joytsay** [Tencent/TNN#705]
**Is your feature request related to a problem? Please describe.**
我在tnn的android demo找不到可以增加cpu multi-thread的開關功能

**Describe the solution you'd like**
有這功能 還是tnn不支援cpu multi-thread？

**Describe alternatives you've considered**
因為其他Framework跑在Android有提供增加cpu multi-thread的接口(e.g. TFlite)

**Additional context**
目前跑在RK-3399上面

**Comment by joytsay** [comment]
我好像找到了 [在coreinstanceh](https://github.com/Tencent/TNN/blob/master/doc/en/user/api_en.md#5-coreinstanceh)
`    // set threads run on cpu 
    virtual Status SetCpuNumThreads(int num_threads);`
我先把issue close掉了 先觀察效果

**Comment by joytsay** [comment]
不好意思 我嘗試在 examples/base/tnn_sdk_sample.cc 中
加入auto ret = instance_->SetCpuNumThreads(4); 
結果跑到status = instance_->ForwardAsync(nullptr);就會掛掉
請問如果要正確使用SetCpuNumThreads應該如何實現？

**Comment by seanxcwang** [comment]
确定是加了SetCpuNumThreads导致的？现在的Android Demo好像有问题，你可以在demo的文件夹下的CMakeLists.txt加下set(TNN_CPU_ENABLE ON CACHE BOOL "" FORCE)

**Comment by joytsay** [comment]
我同時加了
CMakeLists.txt 的 set(TNN_CPU_ENABLE ON CACHE BOOL "" FORCE)
以及
[examples/base/tnn_sdk_sample.cc](https://github.com/Tencent/TNN/blob/master/examples/base/tnn_sdk_sample.cc) 的 auto ret = instance_->SetCpuNumThreads(4);
跑圖像分類-圖片輸入(貓的分類範例)
發現運作時間 並沒有明顯變化 (硬體RK3399 _单线程_ 及 _4個线程_ 都是 **72ms**)
請問還有哪裡可以調的嗎？

**Comment by seanxcwang** [comment]
可能是OPENMP没有开，可以打开试下

**Comment by joytsay** [comment]
成功了！感謝～
依照[compile_en.md](https://github.com/Tencent/TNN/blob/master/doc/en/user/compile_en.md#description-for-build-options)
增加set(TNN_OPENMP_ENABLE ON CACHE BOOL "" FORCE)
從原本 单线程 72ms -> 44ms (硬體:RK3399)

我這裡也順便測試了Resnet_50的效能

rockchip RK3399:
model | cpu time(1 thread，ms) | cpu time(2 threads，ms) | gpu time(ms)
-- | -- | -- | --
squeezenet_v1.0 | 72  | 44 | 55
Resnet_50| 705 | 430  | 313 
Resnet_50_int8 | 475 | 244  |  N/A
