### ISSUE TITLE
Android example 每次运行都会重新编译，十分耗时

### ISSUE THREAD

**Issue by jonbakerfish** [Tencent/TNN#711]
Android example 每次运行都会重新编译libtnn_wrapper.so，有什么办法改善吗？

**Comment by Lamply** [comment]
似乎是因为在 CMakeLists.txt 中每次都重新编译了整个 TNN 库，如果不需要修改 TNN 源码的话，可以预先根据这个 https://github.com/Tencent/TNN/blob/master/doc/cn/user/compile.md#二android库编译 编译一次 TNN 安卓库，然后再把编译好的库导进来就好了

把这个
https://github.com/Tencent/TNN/blob/c80ba72eb7fb51b6aa0e92df159e0282bb0ea9a9/examples/android/demo/CMakeLists.txt#L35  
改成  
```CMake
add_library( TNN SHARED IMPORTED )
set_target_properties(
        TNN
        PROPERTIES IMPORTED_LOCATION
        <path_to_tnn>/scripts/release/${ANDROID_ABI}/libTNN.so
)
```

**Comment by jonbakerfish** [comment]
改了后会有下面的错误：
```
CMakeFiles/tnn_wrapper.dir/src/main/jni/cc/tnn_jni.cc.o: In function `cl::detail::ReferenceHandler<_cl_context*>::release(_cl_context*)':
/TNN/examples/android/demo/.cxx/cmake/debug/arm64-v8a/../../../../../../../third_party/opencl/include/CL/cl2.hpp:1523: undefined reference to `clReleaseContext'
CMakeFiles/tnn_wrapper.dir/src/main/jni/cc/tnn_jni.cc.o: In function `cl::detail::ReferenceHandler<_cl_command_queue*>::release(_cl_command_queue*)':
/TNN/examples/android/demo/.cxx/cmake/debug/arm64-v8a/../../../../../../../third_party/opencl/include/CL/cl2.hpp:1532: undefined reference to `clReleaseCommandQueue'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by Lamply** [comment]
参照这个 https://github.com/Tencent/TNN/issues/415#issue-705057961 ，我不懂 opencl，直接用源码里的 opencl 实现也没遇到问题

> 改了后会有下面的错误：
> 
> ```
> CMakeFiles/tnn_wrapper.dir/src/main/jni/cc/tnn_jni.cc.o: In function `cl::detail::ReferenceHandler<_cl_context*>::release(_cl_context*)':
> /TNN/examples/android/demo/.cxx/cmake/debug/arm64-v8a/../../../../../../../third_party/opencl/include/CL/cl2.hpp:1523: undefined reference to `clReleaseContext'
> CMakeFiles/tnn_wrapper.dir/src/main/jni/cc/tnn_jni.cc.o: In function `cl::detail::ReferenceHandler<_cl_command_queue*>::release(_cl_command_queue*)':
> /TNN/examples/android/demo/.cxx/cmake/debug/arm64-v8a/../../../../../../../third_party/opencl/include/CL/cl2.hpp:1532: undefined reference to `clReleaseCommandQueue'
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> ninja: build stopped: subcommand failed.
> ```

**Comment by seanxcwang** [comment]
把tnn_lib.h里面include的opencl头文件注释掉试下
