### ISSUE TITLE
calibration init falied!

### ISSUE THREAD

**Issue by Wulingtian** [Tencent/TNN#715]
E/tnn: virtual tnn::Status tnn::PermuteLayer::InferOutputShape() [File /home/willer/TNN/source/tnn/layer/permute_layer.cc][Line 45] Permute param got wrong size.
E/tnn: virtual tnn::Status tnn::DefaultNetwork::InitLayers(tnn::NetStructure*, tnn::NetResource*) [File /home/willer/TNN/source/tnn/core/default_network.cc][Line 236] Error Init layer Transpose_533 (err: 4096 or 0x1000)
E/tnn: tnn::Status tnn::Calibration::Init(tnn::NetworkConfig&, tnn::ModelConfig&, tnn::InputShapesMap) [File /home/willer/TNN/tools/quantization/calibration.cc][Line 116] create instance falied!
calibration init falied!

**Comment by shaundai-tencent** [comment]
这是模型结构不支持导致的。
