### ISSUE TITLE
device type OpenCL only supports N8UC4?

### ISSUE THREAD

**Issue by heathcliffYang** [Tencent/TNN#718]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu
 - RunTime OS Version: Android
 - RunTime DEVICE: OPENCL

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

use `build_android.sh`

  **4. 编译日志(build log)**
 ```txt
---
 ```

  **5. 详细描述bug 情况 (Describe the bug)**

I create a Mat whose MatType is N8UC3 and the error message said convert type not support yet. And from https://github.com/Tencent/TNN/blob/c80ba72eb7fb51b6aa0e92df159e0282bb0ea9a9/source/tnn/device/opencl/opencl_blob_converter.cc#L294 , I discover that opencl device type only support N8UC4 only? If my thought is correct, could you support N8UC3? Because we don't need alpha channel information in many scenarios.

  **6. 运行日志（runtime log）**
 ```txt
E/tnn: tnn::Status tnn::Instance::SetInputMat(std::shared_ptr<Mat>, tnn::MatConvertParam, std::string) [File /home/ginny/Projects/TNN/source/tnn/core/instance.cc][Line 162] input_blob_convert.ConvertFromMatAsync Error: code: 0x1000 msg: convert type not support yet
 ```

Thank you!

**Comment by devandong** [comment]
You could try to use the N8UC4 mat type while set the channel to 3.

**Comment by heathcliffYang** [comment]
OK! Thank you!!
