### ISSUE TITLE
模型导出成 .C 文件, 提高跨平台性能.

### ISSUE THREAD

**Issue by shengmingkai** [Tencent/TNN#72]
现有的模型导出的 P/M  文件,只能通过文件路径进行加载, 模型文件和推理部分是分裂的.很不方便.
例如NCNN, 模型的导出可以是.h 文件,可以通过直接路径进行加载, 也可以直接把.h 作为C++ 代码的一部分.在编译的时候,可以直接和推理部分代码编译在一起, 对后期的整个模型的跨平台很友好和方便.
       希望也能尽快支持.

**Comment by darrenyao87** [comment]
@shengmingkai , good suggestion

**Comment by neiltian-tencent** [comment]
已支持, 文档 doc/cn/user/tnn2mem.md。
