### ISSUE TITLE
OpenCV mat as TNN mat : Segmentation fault

### ISSUE THREAD

**Issue by heathcliffYang** [Tencent/TNN#720]
**1. 环境（environment）**
 - Build OS and Version: = Ubuntu
 - RunTime OS Version: Android
 - RunTime DEVICE: OPENCL

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**

I use OpenCV mat's data as TNN mat's data. 

```
unsigned char *input_data_ = (unsigned char *)imgRGBA.data;

void *input_data = (void *)input_data_;

auto input_mat =
      std::make_shared<tnn::Mat>(device_type_, input_type, nchw, input_data);

auto status = instance_->SetInputMat(input_mat, input_convert_param);
```

Error is Segmentation fault right after https://github.com/Tencent/TNN/blob/c80ba72eb7fb51b6aa0e92df159e0282bb0ea9a9/source/tnn/device/opencl/opencl_mat_converter.cc#L205

What is the correct way to pass OpenCV mat into TNN mat and set it as model's input mat?

Or this error comes from OpenCL ?

**Comment by devandong** [comment]
Hi, what's the device_type? Is it DEVICE_OPENCL?

**Comment by heathcliffYang** [comment]
Hi, I forgot they are on different devices' memory. With your instruction, it works. Thank you!

**Comment by lhxy1991** [comment]
> Hi, I forgot they are on different devices' memory. With your instruction, it works. Thank you!

你好，我看官方的demo上面，是直接java的byte[] 转换到jni层，然后转换为unsigned cha* ,然后变为input_mat,并未经过copy函数。cv::Mat本质上应该和unsigned char* 是一样的吧

**Comment by devandong** [comment]
> > Hi, I forgot they are on different devices' memory. With your instruction, it works. Thank you!
> 
> 你好，我看官方的demo上面，是直接java的byte[] 转换到jni层，然后转换为unsigned cha* ,然后变为input_mat,并未经过copy函数。cv::Mat本质上应该和unsigned char* 是一样的吧

如果Mat的device_type为DEVICE_ARM或DEVICE_NAIVE，那么下层都是cpu 内存指针，所以不需要copy可以直接使用。可以看下demo中应该设置了mat的device_type

**Comment by lhxy1991** [comment]
> > > Hi, I forgot they are on different devices' memory. With your instruction, it works. Thank you!
> > 
> > 
> > 你好，我看官方的demo上面，是直接java的byte[] 转换到jni层，然后转换为unsigned cha* ,然后变为input_mat,并未经过copy函数。cv::Mat本质上应该和unsigned char* 是一样的吧
> 
> 如果Mat的device_type为DEVICE_ARM或DEVICE_NAIVE，那么下层都是cpu 内存指针，所以不需要copy可以直接使用。可以看下demo中应该设置了mat的device_type

也就是说 input_mat 是DEVICE_ARM, Resize_mat是DEVICE_OPENCL ,则中间需要一个过渡，使用Copy转换到device再使用resize吗？

**Comment by devandong** [comment]
> > > > Hi, I forgot they are on different devices' memory. With your instruction, it works. Thank you!
> > > 
> > > 
> > > 你好，我看官方的demo上面，是直接java的byte[] 转换到jni层，然后转换为unsigned cha* ,然后变为input_mat,并未经过copy函数。cv::Mat本质上应该和unsigned char* 是一样的吧
> > 
> > 
> > 如果Mat的device_type为DEVICE_ARM或DEVICE_NAIVE，那么下层都是cpu 内存指针，所以不需要copy可以直接使用。可以看下demo中应该设置了mat的device_type
> 
> 也就是说 input_mat 是DEVICE_ARM, Resize_mat是DEVICE_OPENCL ,则中间需要一个过渡，使用Copy转换到device再使用resize吗？

是的，需要保证src与dst的device_type一致。具体可以参考这里的代码：https://github.com/Tencent/TNN/blob/master/source/tnn/device/opencl/opencl_mat_converter.cc#L278

**Comment by joe807191330** [comment]
status = instance->SetInputMat(input_mat, input_cvt_param,"input.1");
SetInputMat has three parammeter, this may be useful.

**Comment by ymyliucongcong** [comment]
How to convert cv::Mat to TNN::Mat
cv::Mat cv_mat;
MatType mat_type = N8UC4; // if cv_mat.channels() == 3, then mat_type = N8UC3.
DimsVector dims = {1, cv_mat.channels(), cv_mat.rows, cv_mat.cols};
auto tnn_mat = new TNN::Mat(DeviceType, mat_type, dims, (void *)cv_mat.ptr);
