### ISSUE TITLE
调用 MatUtils::Resize 输入转换大小有可能出错

### ISSUE THREAD

**Issue by cmdbug** [Tencent/TNN#721]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu20.04
 - RunTime OS Version: Android 8.1.0 meizu16x
 - RunTime DEVICE: ARM正常，OPENCL出错

  **2. Github版本**
```
static char *branch_name_tnn = "master";
static char *commit_date_tnn = "2020-12-30";
static char *commit_hash_tnn = "45f0586";
```
  **3. 编译方式(compile method)**
  ubuntu下配置好环境，直接使用scripts下的build_android.sh文件没有修改。

  **4. 编译日志(build log)**
日志是没有了，但编译是成功的。

  **5. 详细描述bug 情况 (Describe the bug)**
模型调用CPU可以正常运行，但配置OPENCL后在转换大小这步出错。
```C++
// 原始图片
    TNN_NS::DeviceType dt = NanoDet::device_type;
    TNN_NS::DimsVector image_dims = {1, 4, image_h, image_w};
    auto input_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC4, image_dims, imageSource);
    // 模型输入
    TNN_NS::DimsVector target_dims = {1, 4, in_h, in_w};
    auto resize_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC4, target_dims);
    // 转换大小
    TNN_NS::ResizeParam param;
    auto status = TNN_NS::MatUtils::Resize(*input_mat, *resize_mat, param, nullptr);
    if (status != TNN_NS::TNN_OK) {
        TLOGE("MatUtils::Resize Error: %s", status.description().c_str());
    }

    // 输入数据
    TNN_NS::MatConvertParam input_cvt_param;
    input_cvt_param.scale = {103.53f / 255, 116.28f / 255, 123.675f / 255, 0.0};
    input_cvt_param.bias = {0.017429f, 0.017507f, 0.017125f, 0.0};
    status = NanoDet::instance->SetInputMat(resize_mat, input_cvt_param);
    if (status != TNN_NS::TNN_OK) {
        TLOGE("instance.SetInputMat Error: %s", status.description().c_str());
    }
```
完整代码：
https://github.com/cmdbug/TNN_Demo/blob/main/android_TNN_Demo/app/src/main/cpp/Yolov5.cpp
其它人也碰到这个问题，不知道是哪里引起的。
https://github.com/cmdbug/TNN_Demo/issues/2

  **6. 运行日志（runtime log）**
 ```txt
 E/tnn: virtual tnn::Status tnn::OpenCLMatConverterAcc::Resize(tnn::Mat &, tnn::Mat &, tnn::ResizeParam, void *) [File /home/teng/codes/TNN/source/tnn/device/opencl/opencl_mat_converter.cc][Line 285] Get OpenCL command queue failed!
E/WZT_TNN: MatUtils::Resize Error: code: 0x1004 msg: Get OpenCL command queue failed!
 ```
错误信息中有ubuntu下tnn代码的路径，但我是在win下运行android studio，在手机上运行的。

  **7. 截图（Screenshots）**
![image](https://user-images.githubusercontent.com/19603468/103961258-12a66500-518f-11eb-886d-02dd3ae06209.png)

**Comment by devandong** [comment]
MatUtils::Resize的最后一个参数是CommandQueue的指针，对于OpenCL device来说不能设为nullptr。可以参考TNN官方demo中的实例代码：Status TNNSDKSample::Resize(std::shared_ptr<TNN_NS::Mat> src, std::shared_ptr<TNN_NS::Mat> dst, TNNInterpType interp_type) {

**Comment by cmdbug** [comment]
好的，我再看看。3Q

**Comment by cmdbug** [comment]
```C++
    // 原始图片
    TNN_NS::DeviceType dt = YoloV5::device_type;
    TNN_NS::DimsVector image_dims = {1, 4, image_h, image_w};
    auto input_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC4, image_dims, imageSource);
    // 模型输入
    TNN_NS::DimsVector target_dims = {1, 4, net_height, net_width};
    auto resize_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC4, target_dims);
    // opencl需要设置queue
    void *command_queue = nullptr;
    auto status = YoloV5::instance->GetCommandQueue(&command_queue);
    if (status != TNN_NS::TNN_OK) {
        TLOGE("MatUtils::GetCommandQueue Error: %s", status.description().c_str());
    }
    // 转换大小
    TNN_NS::ResizeParam param;
    param.type = TNN_NS::InterpType::INTERP_TYPE_NEAREST;
    status = TNN_NS::MatUtils::Resize(*input_mat, *resize_mat, param, command_queue);
    if (status != TNN_NS::TNN_OK) {
        TLOGE("MatUtils::Resize Error: %s", status.description().c_str());
    }

    // 输入数据
    TNN_NS::MatConvertParam input_cvt_param;
    input_cvt_param.scale = {1.0 / 255, 1.0 / 255, 1.0 / 255, 0.0};
    input_cvt_param.bias = {0.0, 0.0, 0.0, 0.0};
    status = YoloV5::instance->SetInputMat(resize_mat, input_cvt_param);
    if (status != TNN_NS::TNN_OK) {
        TLOGE("instance.SetInputMat Error: %s", status.description().c_str());
    }
```
加完command_queue在opencl下是不会出现前面的错误了，但运行Resize时直接崩溃了。ARM下正常，还需要配置什么嘛？
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x24221aff232119 in tid 6709 (pool-1-thread-1), pid 6648 (com.wzt.tnn)

后面测试时发现，先运行一下ARM，再返回打开opencl再运行就不会崩溃。

**Comment by devandong** [comment]
input_mat, resize_mat与instance的device一样吗？例如，在opencl下执行时，需要input_mat, resize_mat与instance均为opencl

**Comment by cmdbug** [comment]
切换运行方式是这样判断的
```C++
YoloV5::device_type = useGPU ? TNN_NS::DEVICE_OPENCL : TNN_NS::DEVICE_ARM;
// 防止意外改成这样再试了一下，也是会崩溃
YoloV5::device_type = TNN_NS::DEVICE_OPENCL;
```
创建实例，日志中GPU没有创建失败
```C++
        TNN_NS::InputShapesMap shapeMap;
        TNN_NS::NetworkConfig network_config;
        network_config.library_path = {""};
        network_config.device_type = YoloV5::device_type;
        auto ins = YoloV5::net->CreateInst(network_config, status, shapeMap);
        if (status != TNN_NS::TNN_OK || !ins) {
            TLOGW("GPU initialization failed, switch to CPU");
            // 如果出现GPU加载失败，切换到CPU
            YoloV5::device_type = TNN_NS::DEVICE_ARM;
            network_config.device_type = TNN_NS::DEVICE_ARM;
            ins = YoloV5::net->CreateInst(network_config, status, shapeMap);
        }
        YoloV5::instance = ins;
```

**Comment by cmdbug** [comment]
input_mat, resize_mat, instance 都是opencl

**Comment by devandong** [comment]
> ```c++
>     // 原始图片
>     TNN_NS::DeviceType dt = YoloV5::device_type;
>     TNN_NS::DimsVector image_dims = {1, 4, image_h, image_w};
>     auto input_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC4, image_dims, imageSource);
>     // 模型输入
>     TNN_NS::DimsVector target_dims = {1, 4, net_height, net_width};
>     auto resize_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC4, target_dims);
>     // opencl需要设置queue
>     void *command_queue = nullptr;
>     auto status = YoloV5::instance->GetCommandQueue(&command_queue);
>     if (status != TNN_NS::TNN_OK) {
>         TLOGE("MatUtils::GetCommandQueue Error: %s", status.description().c_str());
>     }
>     // 转换大小
>     TNN_NS::ResizeParam param;
>     param.type = TNN_NS::InterpType::INTERP_TYPE_NEAREST;
>     status = TNN_NS::MatUtils::Resize(*input_mat, *resize_mat, param, command_queue);
>     if (status != TNN_NS::TNN_OK) {
>         TLOGE("MatUtils::Resize Error: %s", status.description().c_str());
>     }
> 
>     // 输入数据
>     TNN_NS::MatConvertParam input_cvt_param;
>     input_cvt_param.scale = {1.0 / 255, 1.0 / 255, 1.0 / 255, 0.0};
>     input_cvt_param.bias = {0.0, 0.0, 0.0, 0.0};
>     status = YoloV5::instance->SetInputMat(resize_mat, input_cvt_param);
>     if (status != TNN_NS::TNN_OK) {
>         TLOGE("instance.SetInputMat Error: %s", status.description().c_str());
>     }
> ```
> 
> 加完command_queue在opencl下是不会出现前面的错误了，但运行Resize时直接崩溃了。ARM下正常，还需要配置什么嘛？
> A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x24221aff232119 in tid 6709 (pool-1-thread-1), pid 6648 (com.wzt.tnn)

这里看代码，底层数据来源是imageSource指针，这里的指针指向的内也会随instance的device变化而变化吗？即instance为opencl是，imageSource指向GPU内存；instance为arm时，指向cpu内存

**Comment by cmdbug** [comment]
这是完整的代码，还没加 command_queue。整个过程是参考 objectdetector_jni.cc 中 172行 的detecFromImage写的。
https://github.com/cmdbug/TNN_Demo/blob/main/android_TNN_Demo/app/src/main/cpp/Yolov5.cpp
imageSource指向GPU还是CPU是怎么个写法？

**Comment by devandong** [comment]
> 这是完整的代码，还没加 command_queue。整个过程是参考 objectdetector_jni.cc 中 172行 的detecFromImage写的。
> https://github.com/cmdbug/TNN_Demo/blob/main/android_TNN_Demo/app/src/main/cpp/Yolov5.cpp
> imageSource指向GPU还是CPU是怎么个写法？

如果图像数据在cpu上，那么mat_type为device_arm，使用cpu推理时，instance为device_arm；使用gpu推理时，instance为device_opencl，在setinputmat时，TNN自动进行了copy，将数据从cpu拷贝到gpu(opencl)；
如果图像数据本身就位于gpu，那么mat_tyoe要设置为device_opencl，instance也要为device_opencl。
在你的代码中，如果图像数据始终位于CPU，那么保证mat_type为arm，resize不需要command_queue，instance设置为opencl应该可以执行

**Comment by cmdbug** [comment]
```C++
// 原始图片
    TNN_NS::DeviceType dt = TNN_NS::DEVICE_ARM;  // 数据始终位于CPU，不需要设置成OPENCL，tnn自动复制cpu->gpu
    TNN_NS::DimsVector image_dims = {1, 4, image_h, image_w};
    auto input_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC4, image_dims, imageSource);
```
谢谢大佬，解决了。输入数据 dt 始终为ARM就行了，comman_queue也是有加的，可以正常运行。在手机上速度快了3倍。
