### ISSUE TITLE
caffe2onnx模型转换中Eltwise存在bug

### ISSUE THREAD

**Issue by iyouju** [Tencent/TNN#726]
caffe中使用Eltwise实现元素乘，模型转换时 output_shape 格式不对。问题定位在 tools/caffe2onnx/src/OPs/Eltwise.py 中
`def __createMul(layer, nodename, inname, outname, input_shape):
    output_shape = input_shape[0]`
应修改为：
`def __createMul(layer, nodename, inname, outname, input_shape):
    output_shape = [input_shape[0]]`

**Comment by asiryan** [comment]
> caffe中使用Eltwise实现元素乘，模型转换时 output_shape 格式不对。问题定位在 tools/caffe2onnx/src/OPs/Eltwise.py 中
> `def __createMul(layer, nodename, inname, outname, input_shape): output_shape = input_shape[0]`
> 应修改为：
> `def __createMul(layer, nodename, inname, outname, input_shape): output_shape = [input_shape[0]]`

Could you share the caffemodel and prototxt to reproduce this bug?
