### ISSUE TITLE
华为p40 使用opencl ，cpu占用太高

### ISSUE THREAD

**Issue by lhxy1991** [Tencent/TNN#736]
**1. 环境（environment）**
 - Build OS and Version: ubuntu16.04
 - RunTime OS Version: Android
 - RunTime DEVICE: ARM/OPENCL

 **2. 使用官方推荐的mobilenetv2_ssd模型，初始化的时候设置为DEVICE_OPENCL运行，此时top命令查看cpu占用达到600多；
而使用DEVICE_ARM，查看cpu占用仅100多。
输出结果均是正确的

**Comment by shaundai-tencent** [comment]
我使用P40跑了一下TNN的官方demo，使用mobilenetv2_ssd，使用ARM跑时cpu占用大概在110%左右，使用OpenCL跑时，cpu占用率在48%左右，使用OpenCL会降低cpu占用率。请检查一下，你使用的程序在OpenCL下面是不是触发了其他逻辑。

**Comment by lhxy1991** [comment]
> 我使用P40跑了一下TNN的官方demo，使用mobilenetv2_ssd，使用ARM跑时cpu占用大概在110%左右，使用OpenCL跑时，cpu占用率在48%左右，使用OpenCL会降低cpu占用率。请检查一下，你使用的程序在OpenCL下面是不是触发了其他逻辑。

我也验证了官方的demo，cpu占用情况跟你的一样，但是按照官方的编译成android so之后，按照同样的配置，仅有DEVICE_ARM和DEVICE_OPENCL的改变，使用opencl速度变慢，cpu占用很高，对照官方demo,配置一样的。
