### ISSUE TITLE
TNN_NS::MatUtils::Resize()太占用cpu, 请问错在哪里?

### ISSUE THREAD

**Issue by lhxy1991** [Tencent/TNN#737]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu
 - RunTime OS Version: Android
 - RunTime DEVICE: OPENCL

  **2. Github版本**
static char *branch_name_tnn = "master";
static char *commit_date_tnn = "2020-11-25";
static char *commit_hash_tnn = "a18e014";
  **3. 编译方式(compile method)**
ABIA32="armeabi-v7a with NEON"
#ABIA32="armeabi-v7a"
ABIA64="arm64-v8a"
STL="c++_shared"
#STL="gnustl_static"
SHARED_LIB="ON"
ARM="ON"
OPENMP="ON"
OPENCL="ON"
HUAWEI_NPU="OFF"
  **4. 编译日志(build log)**
   **5. 详细描述bug 情况 (Describe the bug)**
在android jni层开启多线程运行,发现一旦运行TNN_NS::MatUtils::Resize(*input_mat, *resize_mat, param, NULL);cpu占用就会很高,而用opencv执行resize函数替换掉,cpu占用就会降得很低了.
具体配置如下:
Init()
   mTNNDevice_type_ = TNN_NS::DEVICE_OPENCL;
    TNN_NS::InputShapesMap shapeMap;
    TNN_NS::NetworkConfig network_config;
    network_config.library_path = {""};
    network_config.device_type = mTNNDevice_type_;
    network_config.precision = TNN_NS::PRECISION_AUTO;
    auto instance = mTnnNet_->CreateInst(network_config, status, shapeMap);
Detect():
   TNN_NS::DeviceType dt = TNN_NS::DEVICE_ARM;
    TNN_NS::DimsVector input_dims = {1, 4, width, height};
    TNN_NS::DimsVector resize_dims = {1, 4, 300, 300};
    float scale_h = input_dims[2] / 300.0f;
    float scale_w = input_dims[3] / 300.0f;
    LOGE("lihuan start");
    auto input_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC4, input_dims, rgbaData.data);
    auto resize_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC4, resize_dims);
    TNN_NS::ResizeParam param;
    TNN_NS::MatUtils::Resize(*input_mat, *resize_mat, param, NULL);

 ```

**Comment by quinnrong94** [comment]
OPENMP编译选项打开的情况下，Resize默认会使用多线程运行。可以通过Instance的SetCpuNumThreads接口将线程数设置成1，或者编译时将OPENMP选项改成OFF，使用单线程运行。
