### ISSUE TITLE
结果不对

### ISSUE THREAD

**Issue by chenloveheimei** [Tencent/TNN#744]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu18.04
 - RunTime OS Version: Android
 - RunTime DEVICE: ARM

  **2. Github版本**
 - branch：HEAD -> master, origin/master, origin/HEAD
 - commit(optional):

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
Mat OPic = imread("/storage/emulated/0/hdr/val/needY/IMG_20201109_160934.jpg");
//Mat    OPic = imread("/storage/emulated/0/hdr/val/needY/IMG_20201109_172017.jpg");

    imwrite("/storage/emulated/0/hdr/save/OPic.jpg",OPic);

    OPic.convertTo(OPic, CV_32FC3);

    float* pDst = OPic.ptr<float>();

    int wholeLen = OPic.cols * OPic.rows * 3;

    for (int i = 0; i < wholeLen; i+=3)
    {
        pDst[i] =   (pDst[i] - fmean[0][0]) / fstd[0][0];
        pDst[i + 1] =   (pDst[i + 1] - fmean[0][1]) / fstd[0][1];
        pDst[i + 2] =       (pDst[i + 2] - fmean[0][2]) / fstd[0][2];
    }

    TNN_NS::DeviceType dt = TNN_NS::DEVICE_ARM;
    TNN_NS::DimsVector target_dims = {1, 3, OPic.rows, OPic.cols};
    auto input_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC4, target_dims, pDst);
    // step 1. set input mat
    TNN_NS::MatConvertParam input_cvt_param;

    input_cvt_param.scale = {1.0,1.0,1.0,1.0};//std
    input_cvt_param.bias  = {0.0,0.0,0.0, 0.0};//mean/std

    auto status = instance_->SetInputMat(input_mat, input_cvt_param);

    // step 2. Forward
    status = instance_->ForwardAsync(nullptr);
    if (status != TNN_NS::TNN_OK) {
        LOGE("instance.Forward Error: %s\n", status.description().c_str());
        return ;
    }

    // step 3. get output mat
    std::shared_ptr<TNN_NS::Mat> output_mat_scores = nullptr;
    status = instance_->GetOutputMat(output_mat_scores);

    if (status != TNN_NS::TNN_OK) {
        return;
    }

    // 返回预测结果
    auto *scores_data = (float *)output_mat_scores->GetData();

    LOG("channels:%d", output_mat_scores->GetChannel());
    for (int i = 0; i < output_mat_scores->GetChannel(); ++i) {
        LOG("data:%f", scores_data[i]);
    }

模型加载成功，但是跑结果，跑两个不同分类的结果都是一样的．

  **6. 运行日志（runtime log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **7. 截图（Screenshots）**
 ```txt
 将截图粘贴在这里
![image](https://user-images.githubusercontent.com/30176962/104904799-90067c80-59bc-11eb-8362-1ffa195141f2.png)

 Paste screenshorts here or pastebin
 ```

**Comment by devandong** [comment]
N8UC3类型的mat底层数据为unsigned char型，因此基于float*指针建立N8UC4类型的mat不正确。
可参考官方demo中使用Mat保存输入数据的方法，可以利用MatConvertParam实现归一化。
基于已有图像数据建立Mat：https://github.com/Tencent/TNN/blob/master/examples/linux/src/face_detector.cc#L70
MatConvertParam 的设置：https://github.com/Tencent/TNN/blob/master/examples/base/ultra_face_detector.cc#L91

**Comment by chenloveheimei** [comment]
> N8UC4类型的mat底层数据为unsigned char型，因此基于float*指针建立N8UC4类型的mat不正确。
> 可参考官方demo中使用Mat保存输入数据的方法，可以利用MatConvertParam实现归一化。
> 基于已有图像数据建立Mat：https://github.com/Tencent/TNN/blob/master/examples/linux/src/face_detector.cc#L70
> MatConvertParam 的设置：https://github.com/Tencent/TNN/blob/master/examples/base/ultra_face_detector.cc#L91

你好,感谢回复.
1.能否不用MatConvertParam归一化,我自己先外部归一化好后,再直接用归一化后的结果输入呢?
2.TNN_NS::DimsVector target_dims = {1, 3, OPic.rows, OPic.cols};这个如果写的是NCWH的顺序,那我是不是要把NWHC的顺序倒成跟这里定义的一样?
3.那我可否可以定义成TNN_NS::DimsVector target_dims = {1, OPic.rows, OPic.cols,3};这种NWHC的顺序呢?

**Comment by devandong** [comment]
> > N8UC4类型的mat底层数据为unsigned char型，因此基于float*指针建立N8UC4类型的mat不正确。
> > 可参考官方demo中使用Mat保存输入数据的方法，可以利用MatConvertParam实现归一化。
> > 基于已有图像数据建立Mat：https://github.com/Tencent/TNN/blob/master/examples/linux/src/face_detector.cc#L70
> > MatConvertParam 的设置：https://github.com/Tencent/TNN/blob/master/examples/base/ultra_face_detector.cc#L91
> 
> 你好,感谢回复.
> 1.能否不用MatConvertParam归一化,我自己先外部归一化好后,再直接用归一化后的结果输入呢?
> 2.TNN_NS::DimsVector target_dims = {1, 3, OPic.rows, OPic.cols};这个如果写的是NCWH的顺序,那我是不是要把NWHC的顺序倒成跟这里定义的一样?
> 3.那我可否可以定义成TNN_NS::DimsVector target_dims = {1, OPic.rows, OPic.cols,3};这种NWHC的顺序呢?

1、可以，将MatConvertParam中scale1，bias设为0即可，可参考开源demo代码；
2、dims的形状是n-c-h-w，但底层数据布局不取决于shape的顺序，主要由MatType决定。对于N8UC4的mat，底层数据顺序与opencv一致，即channel维度连读；
3、不可以，dims中每一维度的含义确定

**Comment by chenloveheimei** [comment]
> > > N8UC4类型的mat底层数据为unsigned char型，因此基于float*指针建立N8UC4类型的mat不正确。
> > > 可参考官方demo中使用Mat保存输入数据的方法，可以利用MatConvertParam实现归一化。
> > > 基于已有图像数据建立Mat：https://github.com/Tencent/TNN/blob/master/examples/linux/src/face_detector.cc#L70
> > > MatConvertParam 的设置：https://github.com/Tencent/TNN/blob/master/examples/base/ultra_face_detector.cc#L91
> > 
> > 
> > 你好,感谢回复.
> > 1.能否不用MatConvertParam归一化,我自己先外部归一化好后,再直接用归一化后的结果输入呢?
> > 2.TNN_NS::DimsVector target_dims = {1, 3, OPic.rows, OPic.cols};这个如果写的是NCWH的顺序,那我是不是要把NWHC的顺序倒成跟这里定义的一样?
> > 3.那我可否可以定义成TNN_NS::DimsVector target_dims = {1, OPic.rows, OPic.cols,3};这种NWHC的顺序呢?
> 
> 1、可以，将MatConvertParam中scale1，bias设为0即可，可参考开源demo代码；
> 2、dims的形状是n-c-h-w，但底层数据布局不取决于shape的顺序，主要由MatType决定。对于N8UC4的mat，底层数据顺序与opencv一致，即channel维度连读；
> 3、不可以，dims中每一维度的含义确定

1.但我归一化后的数据是0.几的小数,那那个N8UC4能改成什么去支持浮点?还是说你们只能支持整形输入,然后用你们的MatConvertParam归一化呢?

**Comment by devandong** [comment]
> > > > N8UC4类型的mat底层数据为unsigned char型，因此基于float*指针建立N8UC4类型的mat不正确。
> > > > 可参考官方demo中使用Mat保存输入数据的方法，可以利用MatConvertParam实现归一化。
> > > > 基于已有图像数据建立Mat：https://github.com/Tencent/TNN/blob/master/examples/linux/src/face_detector.cc#L70
> > > > MatConvertParam 的设置：https://github.com/Tencent/TNN/blob/master/examples/base/ultra_face_detector.cc#L91
> > > 
> > > 
> > > 你好,感谢回复.
> > > 1.能否不用MatConvertParam归一化,我自己先外部归一化好后,再直接用归一化后的结果输入呢?
> > > 2.TNN_NS::DimsVector target_dims = {1, 3, OPic.rows, OPic.cols};这个如果写的是NCWH的顺序,那我是不是要把NWHC的顺序倒成跟这里定义的一样?
> > > 3.那我可否可以定义成TNN_NS::DimsVector target_dims = {1, OPic.rows, OPic.cols,3};这种NWHC的顺序呢?
> > 
> > 
> > 1、可以，将MatConvertParam中scale1，bias设为0即可，可参考开源demo代码；
> > 2、dims的形状是n-c-h-w，但底层数据布局不取决于shape的顺序，主要由MatType决定。对于N8UC4的mat，底层数据顺序与opencv一致，即channel维度连读；
> > 3、不可以，dims中每一维度的含义确定
> 
> 1.但我归一化后的数据是0.几的小数,那那个N8UC4能改成什么去支持浮点?还是说你们只能支持整形输入,然后用你们的MatConvertParam归一化呢?
> 2.MatConvertParam UltraFaceDetector::GetConvertParamForInput(std::string tag) {
> MatConvertParam input_convert_param;
> input_convert_param.scale = {1.0 / 128, 1.0 / 128, 1.0 / 128, 0.0};
> input_convert_param.bias = {-127.0 / 128, -127.0 / 128, -127.0 / 128, 0.0};
> return input_convert_param;
> }
> 我看了你们这个写的bias都加负号,是都要加负号吗?

1、一定需要在外部归一化的话，结果为小数，就需要使用NCHW_FLOAT的mat，且数据布局形式为n-c-h-w，需要手工调整；
2、MatConverParam的计算方式是 scale*value+bias，bias为负数表示减

**Comment by chenloveheimei** [comment]
> > > > > N8UC4类型的mat底层数据为unsigned char型，因此基于float*指针建立N8UC4类型的mat不正确。
> > > > > 可参考官方demo中使用Mat保存输入数据的方法，可以利用MatConvertParam实现归一化。
> > > > > 基于已有图像数据建立Mat：https://github.com/Tencent/TNN/blob/master/examples/linux/src/face_detector.cc#L70
> > > > > MatConvertParam 的设置：https://github.com/Tencent/TNN/blob/master/examples/base/ultra_face_detector.cc#L91
> > > > 
> > > > 
> > > > 你好,感谢回复.
> > > > 1.能否不用MatConvertParam归一化,我自己先外部归一化好后,再直接用归一化后的结果输入呢?
> > > > 2.TNN_NS::DimsVector target_dims = {1, 3, OPic.rows, OPic.cols};这个如果写的是NCWH的顺序,那我是不是要把NWHC的顺序倒成跟这里定义的一样?
> > > > 3.那我可否可以定义成TNN_NS::DimsVector target_dims = {1, OPic.rows, OPic.cols,3};这种NWHC的顺序呢?
> > > 
> > > 
> > > 1、可以，将MatConvertParam中scale1，bias设为0即可，可参考开源demo代码；
> > > 2、dims的形状是n-c-h-w，但底层数据布局不取决于shape的顺序，主要由MatType决定。对于N8UC4的mat，底层数据顺序与opencv一致，即channel维度连读；
> > > 3、不可以，dims中每一维度的含义确定
> > 
> > 
> > 1.但我归一化后的数据是0.几的小数,那那个N8UC4能改成什么去支持浮点?还是说你们只能支持整形输入,然后用你们的MatConvertParam归一化呢?
> > 2.MatConvertParam UltraFaceDetector::GetConvertParamForInput(std::string tag) {
> > MatConvertParam input_convert_param;
> > input_convert_param.scale = {1.0 / 128, 1.0 / 128, 1.0 / 128, 0.0};
> > input_convert_param.bias = {-127.0 / 128, -127.0 / 128, -127.0 / 128, 0.0};
> > return input_convert_param;
> > }
> > 我看了你们这个写的bias都加负号,是都要加负号吗?
> 
> 1、一定需要在外部归一化的话，结果为小数，就需要使用NCHW_FLOAT的mat，且数据布局形式为n-c-h-w，需要手工调整；
> 2、MatConverParam的计算方式是 scale*value+bias，bias为负数表示减
> iOS和android平台有丰富的示例demo，可参考demo中的写法

/***************************代码*******************************************/
OPic = imread("/storage/emulated/0/hdr/val/needY/IMG_20201109_160934.jpg");
//    OPic = imread("/storage/emulated/0/hdr/val/needY/IMG_20201109_172017.jpg");

    imwrite("/storage/emulated/0/hdr/save/OPic.jpg",OPic);

    OPic.convertTo(OPic, CV_32FC3);

    float* pDst = OPic.ptr<float>();

    int wholeLen = OPic.cols * OPic.rows * 3;

//NWHC
//    for (int i = 0; i < wholeLen; i+=3)
//    {
//        pDst[i] =   (pDst[i] - fmean[0][0]) / fstd[0][0];
//        pDst[i + 1] =   (pDst[i + 1] - fmean[0][1]) / fstd[0][1];
//        pDst[i + 2] =       (pDst[i + 2] - fmean[0][2]) / fstd[0][2];
//    }
//NCWH
    for (int i = 0; i < wholeLen; i+=3)
    {
        pDst[i] =   (pDst[i] - fmean[0][0]) / fstd[0][0];
        pDst[wholeLen + i] =   (pDst[i + 1] - fmean[0][1]) / fstd[0][1];
        pDst[wholeLen + wholeLen + i] =       (pDst[i + 2] - fmean[0][2]) / fstd[0][2];
    }

    TNN_NS::DeviceType dt = TNN_NS::DEVICE_ARM;
    TNN_NS::DimsVector target_dims = {1, 3, OPic.rows, OPic.cols};
    auto input_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::NCHW_FLOAT, target_dims, pDst);

    // step 1. set input mat
    TNN_NS::MatConvertParam input_cvt_param;

    input_cvt_param.scale = {0.0,0.0,0.0,0.0};//std
    input_cvt_param.bias  = {0.0,0.0,0.0,0.0};//mean/std

    auto status = instance_->SetInputMat(input_mat, input_cvt_param);

    // step 2. Forward
    status = instance_->ForwardAsync(nullptr);
    if (status != TNN_NS::TNN_OK) {
        LOGE("instance.Forward Error: %s\n", status.description().c_str());
        return ;
    }

    // step 3. get output mat
    std::shared_ptr<TNN_NS::Mat> output_mat_scores = nullptr;
    status = instance_->GetOutputMat(output_mat_scores);
/***************************代码*******************************************/

改好了,但结果还是不对,要怎么逐层验证呢?

**Comment by devandong** [comment]
1) scale应该为而不是0；
2) 这段循环是否存在问题，循环界限是否计算正确？是否可以原地做hwc-chw的转换？
`
for (int i = 0; i < wholeLen; i+=3)
{
    pDst[i] =   (pDst[i] - fmean[0][0]) / fstd[0][0];
    pDst[wholeLen + i] =   (pDst[i + 1] - fmean[0][1]) / fstd[0][1];
    pDst[wholeLen + wholeLen + i] =       (pDst[i + 2] - fmean[0][2]) / fstd[0][2];
}
`

**Comment by chenloveheimei** [comment]
> 1. scale应该为1而不是0；
>    `input_cvt_param.scale = {1.0, 1.0, 1.0};//std input_cvt_param.bias  = {0.0, 0.0, 0.0};//mean/std`
> 2. 这段循环是否存在问题，循环界限是否计算正确？是否可以原地做hwc-chw的转换？
>    `for (int i = 0; i < wholeLen; i+=3) { }`

我的代码改了一下:

    /***************************代码*******************************************/
    float* pSrc = OPic.ptr<float>();

    Mat dstMat = Mat::zeros(Size(OPic.cols, OPic.rows * 3),CV_32FC1);

    float* pDst = dstMat.ptr<float>();

    int wholeLen = OPic.cols * OPic.rows;

    for (int i = 0; i < wholeLen; i++)
    {
        pDst[i] = (pSrc[3 * i] - fmean[0][0]) / fstd[0][0];
        pDst[wholeLen + i] =  (pSrc[3 * i + 1] - fmean[0][1]) / fstd[0][1];
        pDst[wholeLen + wholeLen + i] = (pSrc[3 * i + 2] - fmean[0][2]) / fstd[0][2];
    }

    TNN_NS::DeviceType dt = TNN_NS::DEVICE_ARM;
    TNN_NS::DimsVector target_dims = {1, 3, OPic.rows, OPic.cols};
    auto input_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::NCHW_FLOAT, target_dims, pDst);

    // step 1. set input mat
    TNN_NS::MatConvertParam input_cvt_param;

    input_cvt_param.scale = {1.0,1.0,1.0,0.0};//std
    input_cvt_param.bias  = {0.0,0.0,0.0,0.0};//mean/std

    auto status = instance_->SetInputMat(input_mat, input_cvt_param);
    /***************************代码*******************************************/
比如分辨率为200*200的图片,
hwc是RGBRGBRGB..40000*3..RGBRGB,对吧.
chw是不是先存RR..40000..RR,再存GG..40000..GG,再存BB..40000..BB这样的顺序进去.
我的原图hwc是:
![OPic](https://user-images.githubusercontent.com/30176962/105017916-52b6f300-5a7f-11eb-9bdb-5aa3ba0919a3.jpg)
然后转换成chw是:
![dstMat](https://user-images.githubusercontent.com/30176962/105017971-63ffff80-5a7f-11eb-8118-b166f572b5d2.jpg)

**Comment by devandong** [comment]
> *

对的；另外target_dims中channel=3，所以scale和bias中给出前3个值就可以了

**Comment by chenloveheimei** [comment]
> > 
> 
> 对的；另外target_dims中channel=3，所以scale和bias中给出前3个值就可以了

已经改了
    input_cvt_param.scale = {1.0,1.0,1.0};//std
    input_cvt_param.bias  = {0.0,0.0,0.0};//mean/std

但结果还是不对,还能怎么做捏?

**Comment by devandong** [comment]
> > > 
> > 
> > 
> > 对的；另外target_dims中channel=3，所以scale和bias中给出前3个值就可以了
> 
> 已经改了
> input_cvt_param.scale = {1.0,1.0,1.0};//std
> input_cvt_param.bias = {0.0,0.0,0.0};//mean/std
> 
> 但结果还是不对,还能怎么做捏?

方便加下这个群吗？方便沟通细节。解决问题以后再把结论同步到这里。
技术交流 QQ 群： 913940506 答案：TNN

**Comment by chenloveheimei** [comment]
> > > > 
> > > 
> > > 
> > > 对的；另外target_dims中channel=3，所以scale和bias中给出前3个值就可以了
> > 
> > 
> > 已经改了
> > input_cvt_param.scale = {1.0,1.0,1.0};//std
> > input_cvt_param.bias = {0.0,0.0,0.0};//mean/std
> > 但结果还是不对,还能怎么做捏?
> 
> 方便加下这个群吗？方便沟通细节。解决问题以后再把结论同步到这里。
> 技术交流 QQ 群： 913940506 答案：TNN

已发到群里了,有空再群里回复下,谢谢

**Comment by chenloveheimei** [comment]
> > > > 
> > > 
> > > 
> > > 对的；另外target_dims中channel=3，所以scale和bias中给出前3个值就可以了
> > 
> > 
> > 已经改了
> > input_cvt_param.scale = {1.0,1.0,1.0};//std
> > input_cvt_param.bias = {0.0,0.0,0.0};//mean/std
> > 但结果还是不对,还能怎么做捏?
> 
> 方便加下这个群吗？方便沟通细节。解决问题以后再把结论同步到这里。
> 技术交流 QQ 群： 913940506 答案：TNN

哥,木有人解答捏

**Comment by devandong** [comment]
模型转换不对齐导致的问题，增加-optimize后可对齐模型，问题解决。

**Comment by HongChow** [comment]
> 913940506

还有别的群吗？ 这个满员了
