### ISSUE TITLE
tflite模型在同事的电脑上转TNN可以，在自己的电脑上转TNN总是失败

### ISSUE THREAD

**Issue by aaron3658** [Tencent/TNN#745]
**1. 使用环境（environment）**
 - OS: Ubuntu
 - OS Version:18.04

  **2. Github版本**
 - branch：
 - commit(optional):docker run --volume=$(pwd):/workspace -it tnn-convert:latest python3 ./converter.py tflite2tnn \
    /workspace/lite_pose_landmark_39kp_256x256_float32.tflite \
    -v v1.0 \
    -debug

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 编译问题（Build failed）/ 模型转换失败（converter failed）/ 模型不对齐（model misalignment）
 - original model： Caffe/ONNX/TensorFlow/TensorFlowLite 
 （如果可以的话，请上传原始的模型文件）

[lite_pose_landmark_39kp_256x256_float32.zip](https://github.com/Tencent/TNN/files/5829704/lite_pose_landmark_39kp_256x256_float32.zip)

  **4. 日志（Log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```
----------  convert model, please wait a moment ----------

/opt/TNN/tools/convert2tnn

/opt/TNN/tools/convert2tnn/bin/TnnConverter -mt TFLITE  -mp /workspace/lite_pose_landmark_39kp_256x256_float32.tflite -od /workspace/
E/tnn: virtual tnn::Status TNN_CONVERTER::TFLiteConv2DConverter::exec(tnn::NetStructure&, tnn::NetResource&, const std::unique_ptr<tflite::OperatorT>&, const std::vector<std::unique_ptr<tflite::TensorT> >&, const std::vector<std::unique_ptr<tflite::BufferT> >&, const std::vector<std::unique_ptr<tflite::OperatorCodeT> >&, bool) [File /opt/TNN/tools/converter/source/tflite/tflite_conv2d_converter.cc][Line 191] TFLite Converter: If any value of dilation_rate is > 1, then all values of strides must be 1.

E/tnn: tnn::Status TNN_CONVERTER::TFLite2Tnn::Convert2Tnn(tnn::NetStructure&, tnn::NetResource&) [File /opt/TNN/tools/converter/source/tflite/tflite_converter.cc][Line 134] TFLite converter Convolution failed!

E/tnn: int TNN_CONVERTER::Run(int, char**) [File /opt/TNN/tools/converter/source/tnn_converter.cc][Line 41] Converter: converter /workspace/lite_pose_landmark_39kp_256x256_float32.tflite failed!

Oh No, tflite2tnn failed :(

  **5. 截图（Screenshots）**
![2021-01-18 18-40-22屏幕截图](https://user-images.githubusercontent.com/31470238/104906467-b3322b80-59be-11eb-89ce-e02ce8837c2a.png)

**Comment by gttiankai** [comment]
针对 TFLite conv2d的转换，前段时间修复过一次 bug，你可以使用最新的代码，重新测试下。如果还有问题，如果方面的话，请附上你的模型。

**Comment by gttiankai** [comment]
暂时关闭如果还有问题，再重新打开。
