### ISSUE TITLE
量化模型(int8)輸出異常

### ISSUE THREAD

**Issue by joytsay** [Tencent/TNN#751]
您好 我嘗試跑 量化 (int8) 的 Resnet_50 在 Android上
應用是在 RK-3399 實現 提取特徵(output: 512 float)的 人臉辨識模型

查詢之前的issue 根據[＃187](https://github.com/Tencent/TNN/issues/187#issuecomment-666043673)
可知 **Android jni** 與 **TNN 量化工具** 兩者對 輸入圖的 **泛化公式** 有所差異:
> 然后我看blob_converter.h里的注释公式是这个：//formular: y = scale*x + bias
> 文档里量化工具用的公式是这个input_pre = (input - bias) * scale

我的模型也需要進行 輸入圖 的 泛化
區間為 (-1 ~ +1) -> (2/255)
進行量化轉換的過程中我給這些值(給予30張224x224典型的输入圖):
```
./quantization_cmd -p /workspace/09-02_02-45.opt.tnnproto \ 
 -m /workspace/09-02_02-45.opt.tnnmodel  \ 
 -i /workspace/face224/  \ 
 --scale 0.007843137255,0.007843137255,0.007843137255  \ 
 --bias 127.5,127.5,127.5 
```

而在Android上我給這些值:
```
    input_param.scale = { 0.007843137255, 0.007843137255, 0.007843137255, 0 };   // 2/255
    input_param.bias = { -1.0, -1.0 , -1.0, 0 };     // -(255/2)*(2/255)
```

相同的input_param在Android上跑起來
fp32 兩張人臉圖(face01 & face02)的相識分數(歐基里得距離) 結果是正確無誤的 
(e.g. 跟Tensorflow-Lite的相識分數FR score比較 TFlite: 86.92, TNN: 87.57)
<img src="https://user-images.githubusercontent.com/49137653/105134741-d7f6e200-5b29-11eb-8a38-a394c21457cc.png" width="250" height="400">

但量化轉為 int8 後模型 的相識分數FR score 算出來為零
(e.g. TFlite: 86.92, TNN: 0.0)
觀察 output: 512 float 的值 也比 fp32 原本小很多
(e.g.只看左臉圖face 01取出512個特徵的第一個浮點數
TFlite face 01 feature01[0]: 0.04408752, 
TNN face 01 feature03[0]: -0.0090331435)
<img src="https://user-images.githubusercontent.com/49137653/105134791-ea711b80-5b29-11eb-81a3-eccd8ca8a318.png" width="250" height="400">

請問我哪裡有做錯嗎?
還是量化的時候還有哪裡要注意?

**Comment by seanxcwang** [comment]
使用上看不出问题，如果可能的话，把模型发给我们看下；另外你也可以试下device type换成naive，这样耗时会很大，但是结果应该是ok的，先排除下是不是arm实现的问题

**Comment by joytsay** [comment]
剛嘗試 device type换成 naive
`TNN_NS::DeviceType dt = TNN_NS::DEVICE_NAIVE; ` 
在android上會閃退 (原本DEVICE_ARM是OK的)
轉換模型我下這個指令:
```
./quantization_cmd -p /workspace/09-02_02-45.opt.tnnproto \
 -m /workspace/09-02_02-45.opt.tnnmodel \
 -i /workspace/face224/ \
 -s 0.007843137255,0.007843137255,0.007843137255 \
 -n 127.5,127.5,127.5 \
 -b 2 \
 -w 1
```
這裡是轉完後的 int8模型檔案:
[int8.zip](https://github.com/Tencent/TNN/files/5841808/int8.zip)
感謝您！

**Comment by quinnrong94** [comment]
1. android上DEVICE_NAIVE闪退可能是编译时[TNN_CPU_ENABLE选项](https://github.com/Tencent/TNN/blob/master/doc/en/user/compile_en.md#description-for-build-options)未打开

2. 用提供的量化模型和两张输入图片，运行结果如下：[data.zip](https://github.com/Tencent/TNN/files/5847233/data.zip)
比较512维输出向量，余弦相似度为0.954。

3. 能否提供能否提供浮点模型，以及两张图片正确的输出结果，以便比较

**Comment by quinnrong94** [comment]
@joytsay  定位出量化模型部分层的量化参数异常，导致输出结果偏小。具体原因还在分析。

可以尝试在量化工具中，把[LAYER_INNER_PRODUCT](https://github.com/Tencent/TNN/blob/a7dcd85f89c64d683a36eda72da46dcaf8813d24/tools/quantization/calibration.cc#L28)和[LAYER_POOLING](https://github.com/Tencent/TNN/blob/a7dcd85f89c64d683a36eda72da46dcaf8813d24/tools/quantization/calibration.cc#L30)两层从量化名单中删除，再验证输出是否正常。

**Comment by joytsay** [comment]
剛試了把LAYER_INNER_PRODUCT和LAYER_POOLING两层从量化名单中删除
的確值得範圍比較正確了
但是每次執行 輸出值差距滿大 忽大忽小 造成相似分數會浮動:
<img src="https://user-images.githubusercontent.com/49137653/105484606-8cd5fe00-5ce6-11eb-8ef0-47772f17041f.png" width="250" height="400">
<img src="https://user-images.githubusercontent.com/49137653/105484618-90698500-5ce6-11eb-87dd-9a35a1acf9ef.png" width="250" height="400">

這裡提供量化模型:
[int8_0122.zip](https://github.com/Tencent/TNN/files/5855397/int8_0122.zip)

**Comment by quinnrong94** [comment]
@joytsay 在arm64环境下测试，int8_0122.zip中的量化模型和fp32模型计算结果如下：
![image](https://user-images.githubusercontent.com/67782915/105676958-39ea8980-5f26-11eb-8cd2-f9a9983f29b3.png)
量化模型和fp32模型相似度在99%以上，两张图片的相似度为0.78，执行多次结果未改变

复现方法：
1. 切换至hotfix_issue_751分支，编译时确保-DTNN_TEST_ENABLE=ON选项打开，编译TNN
2. 下载[int8vsfp32.zip](https://github.com/Tencent/TNN/files/5865091/int8vsfp32.zip)，修改run.sh脚本中的PathToTNNTest，指向第一步编译出的TNNTest可执行文件
3. 修改run.sh脚本的Loop变量，表示运行次数
4. 执行run.sh脚本

建议参考https://github.com/Tencent/TNN/blob/master/test/test.cc检查TNN接口是否正确调用。
如果问题还是存在，可以提供能复现问题的代码做进一步分析。

**Comment by joytsay** [comment]
的確 我在macOS 運行build_aarch64_macos/test/TNNTest的結果:
```
root@7cff4aeb7833:/workspace/int8vsfp32# ./run.sh 
(512,)  vs  (512,)
[cosine distance]  [0.887472283] = 0.887160/(1.000000*0.999648) [max_diff: 0.053092] output/face01_int8.out vs output/face01_fp32.out
(512,)  vs  (512,)
[cosine distance]  [0.859363704] = 0.859081/(1.000000*0.999671) [max_diff: 0.071613] output/face02_int8.out vs output/face02_fp32.out
(512,)  vs  (512,)
[cosine distance]  [0.782358636] = 0.781826/(0.999648*0.999671) [max_diff: 0.099731] output/face01_fp32.out vs output/face02_fp32.out
(512,)  vs  (512,)
[cosine distance]  [0.784457150] = 0.784457/(1.000000*1.000000) [max_diff: 0.090491] output/face01_int8.out vs output/face02_int8.out
```
相似度好像沒你那麼高 不過已經比我之前正確許多
看起來我在Android implement 的地方 使用量化模型的時候 輸入值可能有問題 我會參照建議的https://github.com/Tencent/TNN/blob/master/test/test.cc 交叉比對 Android jni TNN接口 code
這裡我看到TNNTest參數下 `-it 1` 意思是要用1:bgr u8的輸入範圍值才會對？
有結果我會持續更新上來 感謝您！

**Comment by quinnrong94** [comment]
-it参数指定输入的数据格式，(0: NCHW FLOAT), (1: 8UC3), (2: 8UC1)，和-ip指定的输入文件要匹配。
-it指定为1时，会从输入文件中读取uint8整数，赋值给input mat，参考：
https://github.com/Tencent/TNN/blob/f4e74b4e1a7074d8098f24206f4686137a1c2a93/test/test.cc#L373

**Comment by quinnrong94** [comment]
@joytsay  “相似度好像沒你那麼高 不過已經比我之前正確許多”
你的macOS应该是x86架构，使用build_aarch64_macos.sh编译出来的TNNTest，只能跑arm的仿真代码（默认情况会跑fp16仿真代码），arm的fp16仿真代码在模型侧还未做对齐测试，可能导致相似度不高。
可以在run.sh脚本中，运行浮点模型时，增加-pr HIGH选项，使用arm fp32仿真代码，是可以和量化结果对齐的。

**Comment by joytsay** [comment]
增加了-pr HIGH选项就對了
```
(512,)  vs  (512,)
[cosine distance]  [0.993278071] = 0.993278/(1.000000*1.000000) [max_diff: 0.017357] output/face01_int8.out vs output/face01_fp32.out
[euclidean simlarity]  [1.142026176] 
(512,)  vs  (512,)
[cosine distance]  [0.994565085] = 0.994565/(1.000000*1.000000) [max_diff: 0.014727] output/face02_int8.out vs output/face02_fp32.out
[euclidean simlarity]  [1.147870760] 
(512,)  vs  (512,)
[cosine distance]  [0.783148111] = 0.783148/(1.000000*1.000000) [max_diff: 0.084851] output/face01_fp32.out vs output/face02_fp32.out
[euclidean simlarity]  [0.870719000] 
(512,)  vs  (512,)
[cosine distance]  [0.784457150] = 0.784457/(1.000000*1.000000) [max_diff: 0.090491] output/face01_int8.out vs output/face02_int8.out
[euclidean simlarity]  [0.871714457] 

```
Android的部份我還在找bug  感謝

**Comment by joytsay** [comment]
不好意思 android 的部份
我還是無法得到build_aarch64_macos.sh的TNNTest結果
同樣代碼 如果換成fp32的model就正常結果
但換成int8的model還是會亂跳輸出結果
java輸入圖格式為Bitmap.Config.ARGB_8888
```

std::vector<float> TNNFR::run(JNIEnv *env, jobject bitmap) {
    std::vector<float> results;
    AndroidBitmapInfo bitmapInfo;
    void *imageSource;
    if (AndroidBitmap_getInfo(env, bitmap, &bitmapInfo) < 0) {
        return results;
    }
    if (bitmapInfo.format != ANDROID_BITMAP_FORMAT_RGBA_8888) {
        return results;
    }
    if (AndroidBitmap_lockPixels(env, bitmap, &imageSource) < 0) {
        return results;
    }
    int image_h = bitmapInfo.height;
    int image_w = bitmapInfo.width;
    // 原始图片get
    TNN_NS::DeviceType dt = TNN_NS::DEVICE_ARM;
    TNN_NS::DimsVector image_dims = {1, 4, image_h, image_w};
    auto input_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::N8UC4, image_dims, imageSource);
    // 输入数据 //formular: y = scale*x + bias
    TNN_NS::MatConvertParam input_cvt_param;
    input_cvt_param.scale = { 0.007843137255, 0.007843137255, 0.007843137255, 0.0}; // 2/255
    input_cvt_param.bias = { -1.0, -1.0 , -1.0, 0.0}; // -(255/2)*(2/255)
    auto status = TNNFR::instance->SetInputMat(input_mat, input_cvt_param);
    if (status != TNN_NS::TNN_OK) {
        LOGE("instance.SetInputMat Error: %s", status.description().c_str());
    }
    // 前向
    status = TNNFR::instance->ForwardAsync(nullptr);
    if (status != TNN_NS::TNN_OK) {
        LOGE("instance.Forward Error: %s", status.description().c_str());
    }
    // 获取数据
    std::shared_ptr<TNN_NS::Mat> output_mat;
    TNN_NS::MatConvertParam output_param;
    status = TNNFR::instance->GetOutputMat(output_mat, output_param, "embedding:0");
    if (status != TNN_NS::TNN_OK) {
        LOGE("instance.GetOutputMat Error: %s", status.description().c_str());
    }
    // 后处理
    float * data = (float *)output_mat->GetData();
    LOGD("TNNFR::run data[0,1,128,510,511]:[%f,%f,%f,%f,%f]",data[0],data[1],data[128],data[510],data[511]);
    for (int i = 0; i < 512; ++i) {
        results.push_back(data[i]);
    }
    AndroidBitmap_unlockPixels(env, bitmap);
    if (status != TNN_NS::TNN_OK) {
        LOGE("get outputmat fail");
        return results;
    }
    return results;
}
```

**Comment by quinnrong94** [comment]
@joytsay 请问是在CPU还是GPU上运行的？

**Comment by joytsay** [comment]
https://github.com/joytsay/Android-TensorFlow-Lite-Example/blob/5df787a7f9dd647ac8d1a59a7e46ed080b46ea53/geoengine/src/main/cpp/tnnFR.cpp#L62
`        TNNFR::device_type = useGPU ? TNN_NS::DEVICE_OPENCL : TNN_NS::DEVICE_ARM;`
這裡我外部`useGPU＝false`所以是在CPU上運行

**Comment by quinnrong94** [comment]
使用上述代码，修改imageSource，从文件中读取数据，在android手机上（ndk版本r18b，华为mate30）运行，输出结果可以对齐，未复现输出不稳定的问题：

![image](https://user-images.githubusercontent.com/67782915/106132676-3281e500-619f-11eb-9ae1-f714d63e6abd.png)

复现方法：
1. 切换至hotfix_issue_751分支，运行srcipts/build_android.sh脚本编译TNN
2. 下载[android.zip](https://github.com/Tencent/TNN/files/5886745/android.zip)，修改run_android.sh脚本中的TNN_ROOT指向TNN仓库路径
3. 执行run_android.sh脚本

建议每次循环将imageSource打印或保存下来，确保输入是正常的。注意到input_mat是4通道的，而模型的输入是3通道的，TNN只会使用input_mat的前三个通道，第四个通道会被忽略。

**Comment by joytsay** [comment]
透過 android.zip 看起來是OK的
與之前aarch64跑出來face01_int8.out:
```
Loop 1
input data[0,1,2,3]:[183,183,167,0]
output data[0,1,128,510,511]:[0.030281,0.009188,-0.046817,0.074146,0.046054]

Loop 2
input data[0,1,2,3]:[183,183,167,0]
output data[0,1,128,510,511]:[0.030281,0.009188,-0.046817,0.074146,0.046054]

(512,)  vs  (512,)
[cosine distance]  [0.999549323] = 0.999549/(1.000000*1.000000) [max_diff: 0.004520] face01_int8_android.out vs face01_int8.out

```
我會依據您的建議去觀察原始代碼運行 input_mat 的結果
感謝！

**Comment by joytsay** [comment]
@quinnrong94 
我找到我在android int8模型輸出異常原因
如果有加入多執行序:
`auto ret = instance->SetCpuNumThreads(2);`
每次輸出結果就會不同
拿掉就正常了 輸出結果穩定
但我還是希望能使用[Instance::SetCpuNumThreads](https://github.com/Tencent/TNN/blob/d90ba8d242465dfc39d79f307438cb51f74afca0/source/tnn/core/instance.cc#L117)多執行序來加速
請問如何正確使用`SetCpuNumThreads`呢?
是需要做Thread 的 Lock Unlock動作嗎?

**Comment by quinnrong94** [comment]
@joytsay TNN支持多线程加速，内部不需要额外操作。

尝试在android.zip的run函数中，CreateInst之后增加:
`ret = instance->SetCpuNumThreads(2);`
未复现结果不稳定问题。
另外，TNNTest使用-th参数指定线程数，结果也是正常的。

SetCpuNumThreads会在全局范围影响openmp使用的线程数，如果外部有地方使用了openmp，需要保证它是线程安全的。

**Comment by joytsay** [comment]
更新一下狀況
目前我重新開了一個新的Android jni NDK 專案
只運行讀取face01.txt (RGBA)兩次 loop在 int8模型上
沒開 SetCpuNumThreads(2):
<img src="https://user-images.githubusercontent.com/49137653/106698697-46ed3400-661c-11eb-8bf9-7cdce737b938.png" width="400" height="640">
有開 SetCpuNumThreads(2):
<img src="https://user-images.githubusercontent.com/49137653/106698713-50769c00-661c-11eb-8a08-14bb85134e8b.png" width="400" height="640">
結果都是正常的 不會再有輸出不穩定的狀況
看來是之前專案用了其他套件(OpenCV, Tensorflow, TensorflowLite)
如您所說的 影響到OpenMP thread的運行 感謝您！

**Comment by quinnrong94** [comment]
@joytsay 也感谢你的反馈！

**Comment by joytsay** [comment]
@quinnrong94 請問我在android 如果包成.aar給別人用 SetCpuThreads(2)會發生之前說的feature結果亂跳問題 是否是因為產生aar的時候 需要自己下 -fopenmp 參數才能包libopenmp.so?
