### ISSUE TITLE
请问TNN运行build_android.sh在安卓真机上测试模型速度的时候能改变cpu线程数吗?

### ISSUE THREAD

**Issue by ShihuaiXu** [Tencent/TNN#76]
感谢腾讯团队提供TNN模型
请问TNN运行build_android.sh在安卓真机上测试模型速度的时候能改变cpu线程数吗?

**Comment by zhangwei147258** [comment]
in fact, there is the API:virtual Status SetCpuNumThreads(int num_threads);   but I set the cpu thread and find it runs slower in mutilthreads.
        if(device_type_==TNN_NS::DEVICE_ARM){
            int numThreads = 4;
            instance_->SetCpuNumThreads(numThreads);
        }

**Comment by ShihuaiXu** [comment]
是的，2线程最快，4线程比1线程还慢





------------------ 原始邮件 ------------------
发件人: John <notifications@github.com&gt;
发送时间: 2020年6月19日 14:28
收件人: Tencent/TNN <TNN@noreply.github.com&gt;
抄送: Demo Xu <531232693@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Tencent/TNN] 请问TNN运行build_android.sh在安卓真机上测试模型速度的时候能改变cpu线程数吗? (#76)





 
in fact, there is the API:virtual Status SetCpuNumThreads(int num_threads);   but I set the cpu thread and find it runs slower in mutilthreads.
 if(device_type_==TNN_NS::DEVICE_ARM){
 int numThreads = 4;
 instance_-&gt;SetCpuNumThreads(numThreads);
 }

**Comment by alohali** [comment]
@ShihuaiXu 增加了改变线程数支持，使用方法为benchmark_models.sh   -th 线程数
