### ISSUE TITLE
Android Studio编译失败

### ISSUE THREAD

**Issue by sunmengnan** [Tencent/TNN#765]
In file included from F:\framework\TNN-master\TNN-master\source\tnn\device\arm\acc\compute_arm82\arm_conv_fp16_layer_depthwise.cc:23:
F:\framework\TNN-master\TNN-master\source\tnn\device\arm\acc\Half8.h:59:27: error: use of undeclared identifier 'vzip_f16'
![1](https://user-images.githubusercontent.com/30337134/105668783-fdfcf780-5f18-11eb-9fca-e4ab95485ab9.JPG)

**Comment by seanxcwang** [comment]
编译ARMv8.2的代码，NDK的版本需要大于r18b
