### ISSUE TITLE
模型不对齐（model misalignment）多个输入

### ISSUE THREAD

**Issue by KevinZ1992** [Tencent/TNN#768]
模型不对齐（model misalignment）

看源码里模型对齐部分run_onnx函数没对多个输入做处理，导致模型输入是多个的时候跑align对不齐，想问下，目前在手机端做推理是否支持多个输入呢

**Comment by 1627180283** [comment]
master 分支的代码暂时只支持单输入模型进行对齐，feature_dynamic_dims 分支可以支持多输入模型的对齐，最近会让 master 分支支持多输入模型的对齐。

**Comment by KevinZ1992** [comment]
那手机端运行是支持多个输入的是吗

**Comment by 1627180283** [comment]
是的

**Comment by gttiankai** [comment]
目前模型转换工具已经支持对多输入模型的对齐。
