### ISSUE TITLE
Download TNN zip file时 跑build_android.sh脚本出错

### ISSUE THREAD

**Issue by wuyuhan1218** [Tencent/TNN#77]
提示需要git repository
试了git init 之后step1和2还是跑不出来，显示current branch 'master' does not have any commits yet
![微信图片_20200617155502](https://user-images.githubusercontent.com/55457458/84871343-fc31a280-b0b2-11ea-9de3-864c2e4b9d05.jpg)

**Comment by LuffySSR** [comment]
可以试试加一下环境变量  TNN_ROOT_PATH

**Comment by wuyuhan1218** [comment]
> 环境变量

是指在/etc/profile 里加GIT_HOME=我的TNN的文件夹 吗

**Comment by LuffySSR** [comment]
> > 环境变量
> 
> 是指在/etc/profile 里加GIT_HOME=我的TNN的文件夹 吗

可以直接指定TNN_ROOT_PATH，不要让它去找git路径
export TNN_ROOT_PATH=<path>/TNN

**Comment by wuyuhan1218** [comment]
> > > 环境变量
> > 
> > 
> > 是指在/etc/profile 里加GIT_HOME=我的TNN的文件夹 吗
> 
> 可以直接指定TNN_ROOT_PATH，不要让它去找git路径
> export TNN_ROOT_PATH=/TNN

改完之后还是显示your current branch ‘master’ does not have any commits yet...

**Comment by alohali** [comment]
> > > > 环境变量
> > > 
> > > 
> > > 是指在/etc/profile 里加GIT_HOME=我的TNN的文件夹 吗
> > 
> > 
> > 可以直接指定TNN_ROOT_PATH，不要让它去找git路径
> > export TNN_ROOT_PATH=/TNN
> 
> 改完之后还是显示your current branch ‘master’ does not have any commits yet...

已修复，可以更新一下代码试试。之前路径制定的有问题，通过git来查找根目录，忽视了使用zip download
