### ISSUE TITLE
Linux compile error

### ISSUE THREAD

**Issue by evan0621** [Tencent/TNN#776]
System: Ubuntu18.04 x86
when I use:
`./build_linux.sh`

with my CMakeError.log:

`Determining if the pthread_create exist failed with the following output:
Change Dir: /home/lab70636/Projects/TNN/scripts/build_linux/openvino/build/CMakeFiles/CMakeTmp
Run Build Command:"/usr/bin/make" "cmTC_5377c/fast"
/usr/bin/make -f CMakeFiles/cmTC_5377c.dir/build.make CMakeFiles/cmTC_5377c.dir/build
make[1]: Entering directory '/home/lab70636/Projects/TNN/scripts/build_linux/openvino/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_5377c.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_5377c.dir/CheckSymbolExists.c.o   -c /home/lab70636/Projects/TNN/scripts/build_linux/openvino/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_5377c
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5377c.dir/link.txt --verbose=1
/usr/bin/cc      CMakeFiles/cmTC_5377c.dir/CheckSymbolExists.c.o  -o cmTC_5377c 
CMakeFiles/cmTC_5377c.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_5377c.dir/build.make:86: recipe for target 'cmTC_5377c' failed
make[1]: *** [cmTC_5377c] Error 1
make[1]: Leaving directory '/home/lab70636/Projects/TNN/scripts/build_linux/openvino/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_5377c/fast' failed
make: *** [cmTC_5377c/fast] Error 2
File /home/lab70636/Projects/TNN/scripts/build_linux/openvino/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>
int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}
Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/lab70636/Projects/TNN/scripts/build_linux/openvino/build/CMakeFiles/CMakeTmp
Run Build Command:"/usr/bin/make" "cmTC_8754a/fast"
/usr/bin/make -f CMakeFiles/cmTC_8754a.dir/build.make CMakeFiles/cmTC_8754a.dir/build
make[1]: Entering directory '/home/lab70636/Projects/TNN/scripts/build_linux/openvino/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_8754a.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_8754a.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.11/Modules/CheckFunctionExists.c
Linking C executable cmTC_8754a
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8754a.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_8754a.dir/CheckFunctionExists.c.o  -o cmTC_8754a -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_8754a.dir/build.make:86: recipe for target 'cmTC_8754a' failed
make[1]: *** [cmTC_8754a] Error 1
make[1]: Leaving directory '/home/lab70636/Projects/TNN/scripts/build_linux/openvino/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_8754a/fast' failed
make: *** [cmTC_8754a/fast] Error `

**Comment by shaundai-tencent** [comment]
可以尝试最新的代码，没有复现你的问题。
