### ISSUE TITLE
onnx2tnn 转换失败

### ISSUE THREAD

**Issue by pekinghk** [Tencent/TNN#780]
**1. 使用环境（environment）**
 - OS: Docker
 - OS Version:latest

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 编译问题（Build failed）/ 模型转换失败（converter failed）/ 模型不对齐（model misalignment）
 - original model： Caffe/ONNX/TensorFlow/TensorFlowLite 
 （如果可以的话，请上传原始的模型文件）

  **4. 日志（Log）**
 ```txt
 将日志粘贴在这里
D/converter: std::vector<long int> get_node_attr_ai(const onnx::NodeProto&, const char*, const TensorProtoMap&, int) [File /opt/TNN/tools/onnx2tnn/src/core/onnx_utility.cc][Line 165] name :657
D/converter: int get_tensor_proto_data_size(const onnx::TensorProto&) [File /opt/TNN/tools/onnx2tnn/src/core/onnx_utility.cc][Line 522] unsupport data type: 0
python3: /opt/TNN/tools/onnx2tnn/src/core/onnx_utility.cc:523: int get_tensor_proto_data_size(const onnx::TensorProto&): Assertion `0' failed.
Aborted (core dumped)
 ```

  **5. 截图（Screenshots）**

转换一个由yolov5训练的模型，转换失败。报错如上

**Comment by pekinghk** [comment]
yolov5s.pt -> yolov5s.onnx 官方模型yolov5s转成onnx之后都没办法转成TNN，不知道到底是什么问题，请求开发者帮忙解答一下。

**Comment by 1627180283** [comment]
方便上传一下你的 onnx 模型吗

**Comment by pekinghk** [comment]
> 方便上传一下你的 onnx 模型吗
方便留一个您的邮箱么，我发给您

**Comment by 1627180283** [comment]
> > 方便上传一下你的 onnx 模型吗
> > 方便留一个您的邮箱么，我发给您

我的邮箱是 1627180283@qq.com

**Comment by pekinghk** [comment]
> > > 方便上传一下你的 onnx 模型吗
> > > 方便留一个您的邮箱么，我发给您
> 
> 我的邮箱是 [1627180283@qq.com](mailto:1627180283@qq.com)
已经通过邮箱发给您了，麻烦您有空帮忙看一下

**Comment by 1627180283** [comment]
你好，你可以参考这个文档( https://github.com/Tencent/TNN/wiki/%E6%A8%A1%E5%9E%8B%E8%BD%AC%E6%8D%A2Faq )把模型里涉及到五维的地方都修改一下。修改完之后，在转换的命令里加上 -optimize 。

**Comment by pekinghk** [comment]
> 你好，你可以参考这个文档( https://github.com/Tencent/TNN/wiki/%E6%A8%A1%E5%9E%8B%E8%BD%AC%E6%8D%A2Faq )把模型里涉及到五维的地方都修改一下。修改完之后，在转换的命令里加上 -optimize 。

好的，谢谢，我尝试一下

**Comment by pekinghk** [comment]
> > 你好，你可以参考这个文档( https://github.com/Tencent/TNN/wiki/%E6%A8%A1%E5%9E%8B%E8%BD%AC%E6%8D%A2Faq )把模型里涉及到五维的地方都修改一下。修改完之后，在转换的命令里加上 -optimize 。
> 
> 好的，谢谢，我尝试一下

果然删掉reshape那一段就可以转换了，谢谢大佬

**Comment by jonbakerfish** [comment]
@pekinghk 请问你是怎么修改呢？

**Comment by pekinghk** [comment]
> @pekinghk 请问你是怎么修改呢？

导出的时候在yolo的detect层中，删掉reshape、以及根据anchor还原坐标等一系列操作。使得输出是三个四维张量即可。
