### ISSUE TITLE
DEVICE_METAL makes memory keep increasing

### ISSUE THREAD

**Issue by heathcliffYang** [Tencent/TNN#782]
**1. 环境（environment）**
 - Build OS and Version: Mac
 - RunTime OS Version: IOS
 - RunTime DEVICE: METAL

  **2. Github版本**
 - branch：
 - commit(optional): fe446c6
 - 
  **5. 详细描述bug 情况 (Describe the bug)**
I set device type of instance and mat passed into instance_->SetInputMat() as DEVICE_METAL. When the model runs, the memory keeps increasing and this causes app to stop. (The model's output is correct)

However, yolov5 detector you provides doesn't. 

Thank you!

**Comment by devandong** [comment]
Hi, did you put the network forward inside a loop? If this is the situation, you could try your code inside the loop with autoreleasepool:
```
for() {
  @autoreleasepool{
    ...  // your code
  }
}
```

**Comment by heathcliffYang** [comment]
Thank you for your reply!

Yes, I put the network forward inside a loop of a series of images, which creates many temporary objects. To the best of my knowledge, autorelease pool block can reduce the maximum memory footprint of the application (from this [link](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmAutoreleasePools.html)) and this works for me.

I know that demo ios app you provide doesn't have this problem (autorelease pool block is put at https://github.com/Tencent/TNN/blob/c8f98518260ebb0c6e0b758221dca7a6154e8ffe/examples/ios/TNNExamples/main.m#L6) With this, I have a question: autorelease pool block must be add into my code or I misuse your framework? That's, if I use your framework in a right way, is there no need to use autorelease pool block?

Thank you!

**Comment by devandong** [comment]
There are some temporary objects created in metal and they should be released by the autoreleasepool. In the official demo, when control flow goes to the main thread(e.g., when completing an event handler), the autoreleasepool you pointed out will be used and these objects willnot cause memory problems.
But when the forward is put inside a loop, the autoreleasepool in main.m willnot be used for a long time, so these temporary objects have no chance to be released and extra autoreleasepool may be necessary.

**Comment by heathcliffYang** [comment]
OK, thank you for the prompt reply!
