### ISSUE TITLE
win10 编译出错

### ISSUE THREAD

**Issue by zhongwenkun886** [Tencent/TNN#797]
在win10下按照说明编译出错，提示“Configure Openvino Failed”。
文件 “\scripts\build_msvc\openvino\build\CMakeFiles\CMakeError.log” 中有：
CheckIncludeFile.c(1): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory
ninja: build stopped: subcommand failed.”

**Comment by shaoeric** [comment]
> 在win10下按照说明编译出错，提示“Configure Openvino Failed”。
> 文件 “\scripts\build_msvc\openvino\build\CMakeFiles\CMakeError.log” 中有：
> CheckIncludeFile.c(1): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory
> ninja: build stopped: subcommand failed.”

我也遇到这个问题了，请问您解决了吗。另外，我编译的过程还有这些
```
-- Could NOT find Wget (missing: WGET_EXECUTABLE)
-- MODELS_PATH=
CMake Error at inference-engine/thirdparty/CMakeLists.txt:51 (add_subdirectory):
  The source directory

    E:/python_project/TNN/TNN/scripts/build_msvc/openvino/inference-engine/thirdparty/ade

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  inference-engine/thirdparty/CMakeLists.txt:73 (build_with_lto)


CMake Error at inference-engine/samples/CMakeLists.txt:122 (add_subdirectory):
  The source directory

    E:/python_project/TNN/TNN/scripts/build_msvc/openvino/inference-engine/samples/thirdparty/gflags

  does not contain a CMakeLists.txt file.

CMake Error at inference-engine/samples/CMakeLists.txt:123 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  gflags_nothreads_static

CMake Warning at inference-engine/samples/common/format_reader/CMakeLists.txt:26 (message):
  OPENCV is disabled or not found, format_reader will be built without OPENCV
  support

**Comment by ping-xiong** [comment]
> > 在win10下按照说明编译出错，提示“Configure Openvino Failed”。
> > 文件 “\scripts\build_msvc\openvino\build\CMakeFiles\CMakeError.log” 中有：
> > CheckIncludeFile.c(1): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory
> > ninja: build stopped: subcommand failed.”
> 
> 我也遇到这个问题了，请问您解决了吗。另外，我编译的过程还有这些
> 
> ```
> -- Could NOT find Wget (missing: WGET_EXECUTABLE)
> -- MODELS_PATH=
> CMake Error at inference-engine/thirdparty/CMakeLists.txt:51 (add_subdirectory):
>   The source directory
> 
>     E:/python_project/TNN/TNN/scripts/build_msvc/openvino/inference-engine/thirdparty/ade
> 
>   does not contain a CMakeLists.txt file.
> Call Stack (most recent call first):
>   inference-engine/thirdparty/CMakeLists.txt:73 (build_with_lto)
> 
> 
> CMake Error at inference-engine/samples/CMakeLists.txt:122 (add_subdirectory):
>   The source directory
> 
>     E:/python_project/TNN/TNN/scripts/build_msvc/openvino/inference-engine/samples/thirdparty/gflags
> 
>   does not contain a CMakeLists.txt file.
> 
> CMake Error at inference-engine/samples/CMakeLists.txt:123 (set_target_properties):
>   set_target_properties Can not find target to add properties to:
>   gflags_nothreads_static
> 
> CMake Warning at inference-engine/samples/common/format_reader/CMakeLists.txt:26 (message):
>   OPENCV is disabled or not found, format_reader will be built without OPENCV
>   support
> ```


缺少ade子模块
在TNN\scripts\build_msvc\openvino目录下执行：
`git submodule update --init --recursive`

**Comment by ping-xiong** [comment]
更方便的方法是切换到origin/dev_windows分支，这个分支可以正常在编译脚本自动执行：
`git submodule update --init --recursive`


其他遇到的问题和解决方法：

1.  TNN\examples\utils\landmark_smoothing_filter.cc(116): error C2039: "back_inserter": 不是 "std" 的成员
找到这个文件，增加： `#include <iterator>`

2. fatal error C1083: 无法打开包括文 件: “sys/time.h”: No such file or directory
根据报错的文件路径，找到对应文件，编辑：
把 `#include <sys/time.h>`  改为 `#include <time.h>`

3. 在系统环境变量填写了OpenCV_DIR路径，编译examples仍然报错
不要用官方下载的预编译好的，要自己把opencv重新编译一遍，再设置build路径到系统环境变量

4. 建议用x64 Native Tools Command Prompt for VS 工具来运行build_msvc.bat编译


解决了上面问题后，编译examples，我遇到了：
`/MANIFEST /MANIFESTFILE:demo_x86_webcam.exe.manifest" failed (exit code 1120) with the following output:
blazepose_landmark.cc.obj : error LNK2019: 无法解析的外部符号 "class std::chrono::time_point<struct std::chrono::steady_clock,class std::chrono::duration<__int64,struct std::ratio<1,1000000000> > > __cdecl tnn::Now(void)" (?Now@tnn@@YA?AV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@XZ)，函数 "public: virtual class tnn::Status __cdecl tnn::BlazePoseLandmark::ProcessSDKOutput(class std::shared_ptr<class tnn::TNNSDKOutput>)" (?ProcessSDKOutput@BlazePoseLandmark@tnn@@UEAA?AVStatus@2@V?$shared_ptr@VTNNSDKOutput@tnn@@@std@@@Z) 中引用了该符号
skeleton_detector.cc.obj : error LNK2001: 无法解析的外部符号 "class std::chrono::time_point<struct std::chrono::steady_clock,class std::chrono::duration<__int64,struct std::ratio<1,1000000000> > > __cdecl tnn::Now(void)" (?Now@tnn@@YA?AV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@XZ)
blazepose_landmark.cc.obj : error LNK2019: 无法解析的外部符号 "public: class tnn::Status __cdecl tnn::VelocityFilter::Apply(class std::vector<class std::tuple<float,float,float>,class std::allocator<class std::tuple<float,float,float> > > const &,struct std::pair<int,int> const &,class std::chrono::time_point<struct std::chrono::steady_clock,class std::chrono::duration<__int64,struct std::ratio<1,1000000000> > > const &,class std::vector<class std::tuple<float,float,float>,class std::allocator<class std::tuple<float,float,float> > > *)" (?Apply@VelocityFilter@tnn@@QEAA?AVStatus@2@AEBV?$vector@V?$tuple@MMM@std@@V?$allocator@V?$tuple@MMM@std@@@2@@std@@AEBU?$pair@HH@5@AEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@5@PEAV45@@Z)，函数 "public: virtual class tnn::Status __cdecl tnn::BlazePoseLandmark::ProcessSDKOutput(class std::shared_ptr<class tnn::TNNSDKOutput>)" (?ProcessSDKOutput@BlazePoseLandmark@tnn@@UEAA?AVStatus@2@V?$shared_ptr@VTNNSDKOutput@tnn@@@std@@@Z) 中引用了该符号
skeleton_detector.cc.obj : error LNK2019: 无法解析的外部符号 "public: class tnn::Status __cdecl tnn::VelocityFilter::Apply2D(class std::vector<struct std::pair<float,float>,class std::allocator<struct std::pair<float,float> > > const &,struct std::pair<int,int> const &,class std::chrono::time_point<struct std::chrono::steady_clock,class std::chrono::duration<__int64,struct std::ratio<1,1000000000> > > const &,class std::vector<struct std::pair<float,float>,class std::allocator<struct std::pair<float,float> > > *)" (?Apply2D@VelocityFilter@tnn@@QEAA?AVStatus@2@AEBV?$vector@U?$pair@MM@std@@V?$allocator@U?$pair@MM@std@@@2@@std@@AEBU?$pair@HH@5@AEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@5@PEAV45@@Z)，函数 "public: virtual class tnn::Status __cdecl tnn::SkeletonDetector::ProcessSDKOutput(class std::shared_ptr<class tnn::TNNSDKOutput>)" (?ProcessSDKOutput@SkeletonDetector@tnn@@UEAA?AVStatus@2@V?$shared_ptr@VTNNSDKOutput@tnn@@@std@@@Z) 中引用了该符号
demo_x86_webcam.exe : fatal error LNK1120: 3 个无法解析的外部命令`

这个问题暂不清楚原因，到这一步，库已经编译好了，但是examples的webcam例子仍然编译失败。

**Comment by seanxcwang** [comment]
> 在win10下按照说明编译出错，提示“Configure Openvino Failed”。
> 文件 “\scripts\build_msvc\openvino\build\CMakeFiles\CMakeError.log” 中有：
> CheckIncludeFile.c(1): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory
> ninja: build stopped: subcommand failed.”

pthread.h本来就是linux下面的，windows不会用到；现在x86的优化已经合到master了，可以试下build_msvc_native.bat，这个是不含openvino的版本，openvino因为依赖的比较多，可能会模块拉取失败

**Comment by LeeeLiu** [comment]
> 更方便的方法是切换到origin/dev_windows分支，这个分支可以正常在编译脚本自动执行：
> `git submodule update --init --recursive`
> 
> 其他遇到的问题和解决方法：
> 
> 1. TNN\examples\utils\landmark_smoothing_filter.cc(116): error C2039: "back_inserter": 不是 "std" 的成员
>    找到这个文件，增加： `#include <iterator>`
> 2. fatal error C1083: 无法打开包括文 件: “sys/time.h”: No such file or directory
>    根据报错的文件路径，找到对应文件，编辑：
>    把 `#include <sys/time.h>`  改为 `#include <time.h>`
> 3. 在系统环境变量填写了OpenCV_DIR路径，编译examples仍然报错
>    不要用官方下载的预编译好的，要自己把opencv重新编译一遍，再设置build路径到系统环境变量
> 4. 建议用x64 Native Tools Command Prompt for VS 工具来运行build_msvc.bat编译
> 
> 解决了上面问题后，编译examples，我遇到了：
> `/MANIFEST /MANIFESTFILE:demo_x86_webcam.exe.manifest" failed (exit code 1120) with the following output: blazepose_landmark.cc.obj : error LNK2019: 无法解析的外部符号 "class std::chrono::time_point<struct std::chrono::steady_clock,class std::chrono::duration<__int64,struct std::ratio<1,1000000000> > > __cdecl tnn::Now(void)" (?Now@tnn@@YA?AV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@XZ)，函数 "public: virtual class tnn::Status __cdecl tnn::BlazePoseLandmark::ProcessSDKOutput(class std::shared_ptr<class tnn::TNNSDKOutput>)" (?ProcessSDKOutput@BlazePoseLandmark@tnn@@UEAA?AVStatus@2@V?$shared_ptr@VTNNSDKOutput@tnn@@@std@@@Z) 中引用了该符号 skeleton_detector.cc.obj : error LNK2001: 无法解析的外部符号 "class std::chrono::time_point<struct std::chrono::steady_clock,class std::chrono::duration<__int64,struct std::ratio<1,1000000000> > > __cdecl tnn::Now(void)" (?Now@tnn@@YA?AV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@XZ) blazepose_landmark.cc.obj : error LNK2019: 无法解析的外部符号 "public: class tnn::Status __cdecl tnn::VelocityFilter::Apply(class std::vector<class std::tuple<float,float,float>,class std::allocator<class std::tuple<float,float,float> > > const &,struct std::pair<int,int> const &,class std::chrono::time_point<struct std::chrono::steady_clock,class std::chrono::duration<__int64,struct std::ratio<1,1000000000> > > const &,class std::vector<class std::tuple<float,float,float>,class std::allocator<class std::tuple<float,float,float> > > *)" (?Apply@VelocityFilter@tnn@@QEAA?AVStatus@2@AEBV?$vector@V?$tuple@MMM@std@@V?$allocator@V?$tuple@MMM@std@@@2@@std@@AEBU?$pair@HH@5@AEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@5@PEAV45@@Z)，函数 "public: virtual class tnn::Status __cdecl tnn::BlazePoseLandmark::ProcessSDKOutput(class std::shared_ptr<class tnn::TNNSDKOutput>)" (?ProcessSDKOutput@BlazePoseLandmark@tnn@@UEAA?AVStatus@2@V?$shared_ptr@VTNNSDKOutput@tnn@@@std@@@Z) 中引用了该符号 skeleton_detector.cc.obj : error LNK2019: 无法解析的外部符号 "public: class tnn::Status __cdecl tnn::VelocityFilter::Apply2D(class std::vector<struct std::pair<float,float>,class std::allocator<struct std::pair<float,float> > > const &,struct std::pair<int,int> const &,class std::chrono::time_point<struct std::chrono::steady_clock,class std::chrono::duration<__int64,struct std::ratio<1,1000000000> > > const &,class std::vector<struct std::pair<float,float>,class std::allocator<struct std::pair<float,float> > > *)" (?Apply2D@VelocityFilter@tnn@@QEAA?AVStatus@2@AEBV?$vector@U?$pair@MM@std@@V?$allocator@U?$pair@MM@std@@@2@@std@@AEBU?$pair@HH@5@AEBV?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@5@PEAV45@@Z)，函数 "public: virtual class tnn::Status __cdecl tnn::SkeletonDetector::ProcessSDKOutput(class std::shared_ptr<class tnn::TNNSDKOutput>)" (?ProcessSDKOutput@SkeletonDetector@tnn@@UEAA?AVStatus@2@V?$shared_ptr@VTNNSDKOutput@tnn@@@std@@@Z) 中引用了该符号 demo_x86_webcam.exe : fatal error LNK1120: 3 个无法解析的外部命令`
> 
> 这个问题暂不清楚原因，到这一步，库已经编译好了，但是examples的webcam例子仍然编译失败。
> 
> 至此，已经可以在release文件夹中看到demo_x86_facedetector.exe和demo_x86_imageclassify.exe

我也遇到了。请问解决了吗？

**Comment by LeeeLiu** [comment]
> 这个问题暂不清楚原因，到这一步，库已经编译好了，但是examples的webcam例子仍然编译失败。

破案了，因为TNN是以release模式编译的，所以，openCV也要以release模式编译
我环境Win10，用的是 master分支，基于摄像头的人脸配准demo终于通了，泪目.........

**Comment by ZufeCy** [comment]
> 

什么意思啊？

**Comment by shaoeric** [comment]
已收到你的邮件，我会尽快回复
