### ISSUE TITLE
请问linux-x86下如何输入图片来推理

### ISSUE THREAD

**Issue by biubiu0719** [Tencent/TNN#80]
如标题

**Comment by biubiu0719** [comment]
是否有支持armlinux下图片的路径访问输入

**Comment by alohali** [comment]
@biubiu0719 在feature demo分支开发了arm linux下的图像检测和分类的demo:https://github.com/Tencent/TNN/tree/feature_demo/examples/armlinux

**Comment by alohali** [comment]
@biubiu0719 但是x86平台性能还在优化中，目前还有待提升
