### ISSUE TITLE
Yolov5 转 TNN 错误

### ISSUE THREAD

**Issue by jonbakerfish** [Tencent/TNN#800]
**1. 使用环境（environment）**
 - OS: Ubuntu
 - OS Version: 20.04

  **2. Github版本**
 - branch：master
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型转换失败（converter failed）
 - original model： ONNX
 （如果可以的话，请上传原始的模型文件）
使用onnx2tnn转换 https://github.com/ultralytics/yolov5/  export 出来的onnx模型会出错。

  **4. 日志（Log）**
 ```txt
python3 onnx2tnn.py yolov5s.onnx -version=v1.0 -optimize=0 -half=0 -o out_dir/ -input_shape input:1,3,320,320                                                                            

0.----onnx version:1.8.0                                                                                                                                                              
algo_optimize 0                                                                                                                                                                       
onnx_net_opt_path yolov5s.onnx                                                                  
2.----onnx2tnn: yolov5s.onnx 

D/converter: std::vector<long int> get_node_attr_ai(const onnx::NodeProto&, const char*, const TensorProtoMap&, int) [File /home/code/ncnn/TNN/tools/onnx2tnn/src/core/onnx_utility.cc][Line 165] name :395
D/converter: int get_tensor_proto_data_size(const onnx::TensorProto&) [File /home/code/ncnn/TNN/tools/onnx2tnn/src/core/onnx_utility.cc][Line 522] unsupport data type: 0
python3: /home/code/ncnn/TNN/tools/onnx2tnn/src/core/onnx_utility.cc:523: int get_tensor_proto_data_size(const onnx::TensorProto&): Assertion `0' failed.
 ```

能否提供一下官方的转换yolov5模型的相关操作或代码？

**Comment by 1627180283** [comment]
https://github.com/Tencent/TNN/wiki/%E6%A8%A1%E5%9E%8B%E8%BD%AC%E6%8D%A2Faq
可以参考这个对 YOLO V5 进行修改。转换修改之后的模型需要把 -optimize 打开。

**Comment by jonbakerfish** [comment]
@1627180283 谢谢指导，我去掉reshape后转换成功了。但是用netron比较后，TNN上面的yolov5 与 ultralytics转出来的yolov5有些层并一样：TNN的有BatchNormCxx，PReLU层，三个output都加了Permute

如果我想用TNN example里面提供的yolov5代码跑ultralytics转出来的模型，是否只需要在三个output都加上相同的Permute层就可以了？

**Comment by 1627180283** [comment]
TNN 的 YOLO V5 是使用 https://github.com/ultralytics/yolov5， commit 号是 41bb70b32598c016cc55debae7bafd26ec94e984，你可以先对比一下看这个 commit 和你使用的有没有区别

**Comment by jonbakerfish** [comment]
@1627180283 好的，谢谢。经过验证后，最新版的ultralytics模型在三个output都加上相同的sigmoid和Permute层后，也可以直接跑TNN的代码

**Comment by FishWoWater** [comment]
请问你部署后的运行效率如何？我yolov5s 要 3s / img 输入是 320 x 320,  x86_64的 i7 2.8Ghz CPU

**Comment by jonbakerfish** [comment]
@FishWoWater CPU的没有测试，不过在高通820上是~70ms/img

**Comment by FishWoWater** [comment]
> @FishWoWater CPU的没有测试，不过在高通820上是~70ms/img

可以请问下你是怎么实现TNN推理的吗，我在高通865上 arm 是 400ms,  opencl 是 500ms.... 但是我benchmark工具测出来opencl 只要 50ms(arm是相当的),  调了一下发现主要就是ForwardAsync 耗时长，看了挺久源码也没有解决
