### ISSUE TITLE
onnx2tnn  模型转换工具中 conv + BN 融合针对 conv 中 weight 共用的模型存在 bug

### ISSUE THREAD

**Issue by gttiankai** [Tencent/TNN#808]
**1. 使用环境（environment）**
 - OS: Linux
 - OS Version: Centos 7.2 gcc 4.8

  **2. Github版本**
 - branch：master
 - commit(optional): latest

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型转换失败（converter failed）
 - original model： ONNX 模型
 （如果可以的话，请上传原始的模型文件）

  **4. 日志（Log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 截图（Screenshots）**
<img width="593" alt="企业微信截图_ea61d8f9-b5f1-4cb3-9ba5-ffd12a039f04" src="https://user-images.githubusercontent.com/5379313/108980052-3e8d9380-76c6-11eb-9ca4-e13dd95dcc53.png">

**Comment by njmcusd** [comment]
如果BN参数不一样，前面conv又使用共享参数的话，这样合并起来肯定会有问题啊，除非转换的时候这两个conv使用单独的参数内存去存放，不过这样的话模型也没必要设计成共享权重了

**Comment by gttiankai** [comment]
@njmcusd 目前转换的是每个 conv 确实使用单独的参数去存放。

**Comment by gttiankai** [comment]
这个 bug 已经修复，并合并到 master
