### ISSUE TITLE
转化retinaFace模型失败

### ISSUE THREAD

**Issue by damon-93** [Tencent/TNN#824]
**1. 使用环境（environment）**
 - OS: Ubuntu

  **2. docker images版本**
REPOSITORY                TAG                      IMAGE ID            CREATED             SIZE
turandotkay/tnn-convert   latest                   eb1db67ab01c        5 days ago          3.53GB

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 模型转换失败（converter failed）
 - original model： Caffe
 - 使用retinaFace的caffe模型转换TNN失败,我使用的转换命令:
 - docker run --volume=$(pwd):/workspace -it turandotkay/tnn-convert:latest python3 ./converter.py caffe2tnn /workspace/mnet.25.prototxt /workspace/mnet.25.caffemodel -optimize
 - 我的转化过程:由于retinaFace原始模式是mxnet的,我先转换成caffe再进行转化TNN的操作,
 - 原始模型mxnet的下载地址:https://pan.baidu.com/s/1P1ypO7VYUbNAezdvLm2m9w 提取码:nzof   ,  我用的是[mnet.25-0000.params, mnet.25-symbol.json]
 - 我转换的caffe模型 https://pan.baidu.com/s/1ZKa0g9T1zg3C47Tc7vaouQ 提取码: apn8 
 - 
  **4. 日志（Log）**
----------  convert model, please wait a moment ----------

Converter Caffe to ONNX Model

Congratulations! caffe2onnx succeed!

Converter ONNX to TNN Model

Converter ONNX to TNN model failed!

**Comment by damon-93** [comment]
@neiltian-tencent @gttiankai 您好,这个问题我解决了,应该是-optimize参数以及Reshape算子参数有问题,我写了一片博客

**Comment by damon-93** [comment]
@neiltian-tencent @gttiankai 您好,这个问题我解决了,应该是-optimize参数以及Reshape算子参数有问题,我写了一篇博客:https://blog.csdn.net/damon93/article/details/114920557
入行不久,写的比较浅显,您看看是否有问题

**Comment by gttiankai** [comment]
简单看了一下博客，写得不错.
关于你博客中的的疑惑：“看来是tnn解析onnx时需要从完整的输入nchw四个维度的信息,否则解析会出错.当然这个推论需要详细了解caffe、onnx、tnn解析模型的代码才能确定.”
你的推论是正确的，截止目前 master 分支的代码确实要求模型的输入以及中间每一层都要保持 nchw 四维。当然了，模型转换工具中对某些常见模型中的某一层算子不足四维的情况作了特殊处理。但是由于目前模型的情况比较复杂，所以特殊处理可能没有办法覆盖所有的情况。

**Comment by damon-93** [comment]
> 简单看了一下博客，写得不错.
> 关于你博客中的的疑惑：“看来是tnn解析onnx时需要从完整的输入nchw四个维度的信息,否则解析会出错.当然这个推论需要详细了解caffe、onnx、tnn解析模型的代码才能确定.”
> 你的推论是正确的，截止目前 master 分支的代码确实要求模型的输入以及中间每一层都要保持 nchw 四维。当然了，模型转换工具中对某些常见模型中的某一层算子不足四维的情况作了特殊处理。但是由于目前模型的情况比较复杂，所以特殊处理可能没有办法覆盖所有的情况。

感谢答惑,thx
