### ISSUE TITLE
模型inference初始化的时候，出现layer acc of type(131) is nil报错，好像是LAYER_REORG层初始化失败

### ISSUE THREAD

**Issue by xiaoxiongli** [Tencent/TNN#838]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu
 - RunTime OS Version: Linux
 - RunTime DEVICE: Intel CPU

  **2. Github版本**
 - branch：
 - commit(optional):

  **3. 编译方式(compile method)**
  CMake完整编译参数(full cmake arguments)

  **4. 编译日志(build log)**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **5. 详细描述bug 情况 (Describe the bug)**
超分RFDN，其TNN模型在模型初始化的时候，出现如下报错：
E/tnn: virtual tnn::Status tnn::BaseLayer::Init(tnn::Context*, tnn::LayerParam*, tnn::LayerResource*, std::vector<tnn::Blob*>&, std::vector<tnn::Blob*>&, tnn::AbstractDevice*) [File /home/ubuntu/lishaoxiong/sr/TNN/source/tnn/layer/base_layer.cc][Line 70] layer acc of type(131) is nil
E/tnn: virtual tnn::Status tnn::DefaultNetwork::InitLayers(tnn::NetStructure*, tnn::NetResource*) [File /home/ubuntu/lishaoxiong/sr/TNN/source/tnn/core/default_network.cc][Line 236] Error Init layer DepthToSpace_211 (err: 12288 or 0x3000)

  **6. 运行日志（runtime log）**
 ```txt
 将日志粘贴在这里
 Paste log here or pastebin
 ```

  **7. 截图（Screenshots）**
 ```txt
 将截图粘贴在这里
 Paste screenshorts here or pastebin
 ```
![image](https://user-images.githubusercontent.com/13975044/110449024-b9aa6d00-80fc-11eb-9756-467574ef20ee.png)

[TNN_RFCN_model.zip](https://github.com/Tencent/TNN/files/6107438/TNN_RFCN_model.zip)

**Comment by gttiankai** [comment]
我在最新的master 代码中测试了，这个模型已经可以支持了，你试一下。如果有问题，再重新打开。
