### ISSUE TITLE
是否支持crnn不定长shape输入

### ISSUE THREAD

**Issue by gofugoo** [Tencent/TNN#860]
请问, tnn是否支持crnn不定长shape输入？

**Comment by neiltian-tencent** [comment]
可以先用feature_dynamic_dims分支

**Comment by gofugoo** [comment]
> 可以先用feature_dynamic_dims分支

那像其它模型，例如yolov5能支持不定长shape输入吗？

**Comment by darrenyao87** [comment]
当前master版本已经支持可变长度，可参看中文文字OCR的demo。proto里面的纬度值不能为0，可选一个合适的常用的值，如果要改变维度，可以调用Instance的Reshape接口。
