### ISSUE TITLE
在大屏上（安卓环境，cpu、gpu均有）视频流推理时报错，但是采用图片推理却能正常进行

### ISSUE THREAD

**Issue by hongtao-ai** [Tencent/TNN#866]
E/tnn: tnn::Status tnn::Instance::Init(std::shared_ptr<AbstractModelInterpreter>, tnn::InputShapesMap) [File C:\Users\hongtao\Desktop\rmkj\TNN\source\tnn\core\instance.cc][Line 51]    ERROR: network_ is nil, network_type may not support

StreamObjectDetectFragment: detect from stream ret null

**Comment by shaundai-tencent** [comment]
上述的问题报错应该和描述的问题没有关系，请检查一下TNN的库链接是否有问题。
