### ISSUE TITLE
ShuffleNetV2运行TNNTest报错：Permute param got wrong size.

### ISSUE THREAD

**Issue by chienkan** [Tencent/TNN#87]
Hi，
首先感谢鹅厂大佬的杰作！
转换模型时我是直接使用docker中的转换工具tf2tnn，生成了tnn模型，转换过程无报错，但在RK3399平台运行TNNTest时出现报错，具体打印如下：
```bash
$ ./TNNTest -mt TNN -mp ./model/ShuffleNetV2.opt.tnnproto -ic 1000 -wc 1 -th 2
E/tnn: virtual tnn::Status tnn::PermuteLayer::InferOutputShape() [File /home/data/TNN/source/tnn/layer/permute_layer.cc][Line 45] Permute param got wrong size.
E/tnn: virtual tnn::Status tnn::DefaultNetwork::InitLayers(tnn::NetStructure*, tnn::NetResource*) [File /home/data/TNN/source/tnn/core/default_network.cc][Line 220] Error Init layer ShuffleNet_v2/shufflenet/stage2/shufflebk_0/channelchuffle/transpose (err: 4096 or 0x1000)
E/tnn: bool tnn::test::CheckResult(std::__cxx11::string, tnn::Status) [File /home/data/TNN/test/test.cc][Line 271] create instance failed: code: 0x1000 msg: Permute param got wrong size 
```
同样的方法运行MobileNet_V2/V3_L/V3_S没有问题。
有没有大佬知道什么原因XD

**Comment by gttiankai** [comment]
模型能否提供下？

**Comment by chienkan** [comment]
你好，
模型稍后会提供，我先描述下昨天定位到的情况：
直接利用GDB工具对TNNTest进行单步调试，发现Permute算子得到的输入Blob维度是5；在TF模型中，5维转4维由Transpose算子完成，当前TNN Permute算子不支持这种情况。

**Comment by chienkan** [comment]
另外，我跑了一下你们提供的模型（https://raw.githubusercontent.com/darrenyao87/tnn-models/master/shufflenet_v2/shufflenet_v2.tnnproto），也发生了报错：
```bash
$ ./TNNTest -mt TNN -mp ./model/shufflenet_v2_official.tnnproto        
E/tnn: bool tnn::test::CheckResult(std::__cxx11::string, tnn::Status) [File /home/data/TNN/test/test.cc][Line 271] init tnn failed: code: 0x6005 msg: model content is invalid 
```

**Comment by chienkan** [comment]
@gttiankai 模型链接如下：
https://drive.google.com/file/d/1fh3FNtt_8XWgQaC2WITLt1hf_lX__rSG/view?usp=sharing

**Comment by gttiankai** [comment]
模型是从Tensorflow转换过来，由于Tensorflow nhwc 到 nchw的原因，模型中间加了很多transpose。造成shuffle的融合失败，这个我来实现下。

![企业微信截图_7889bcee-a195-4caf-b280-bfa71cfe1b22](https://user-images.githubusercontent.com/5379313/85508782-4bce1c00-b627-11ea-859b-928da7fbc774.png)

**Comment by liulai** [comment]
> 模型是从Tensorflow转换过来，由于Tensorflow nhwc 到 nchw的原因，模型中间加了很多transpose。造成shuffle的融合失败。 这个需要特殊处理。

你好，请问下，如果shape维度为6，应该如何处理啊？

**Comment by gttiankai** [comment]
建议将 Tensorflow 模型导出为 TFLite 模型，然后使用 TFLite 模型进行转换。
