### ISSUE TITLE
feature_dynamic_dims opencl版本推断失败

### ISSUE THREAD

**Issue by gofugoo** [Tencent/TNN#876]
**1. 环境（environment）**
 - Build OS and Version: Mac
 - RunTime OS Version: Android
 - RunTime DEVICE: OPENCL

  **2. Github版本**
 - branch：feature_dynamic_dims
 - commit(optional):a04c783b

  **3. 编译方式(compile method)**
 cmake -GNinja \
      -DCMAKE_TOOLCHAIN_FILE=android-sdk/ndk/22.0.7026061/build/cmake/android.toolchain.cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DDEBUG:BOOL=OFF \
      -DANDROID_ABI="arm64-v8a" \
      -DANDROID_STL=c++_shared \
      -DANDROID_NATIVE_API_LEVEL=android-21  \
      -DANDROID_TOOLCHAIN=clang \
      -DBUILD_FOR_ANDROID_COMMAND=ON \
      -DTNN_ARM_ENABLE:BOOL=ON \
      -DTNN_ARM82_ENABLE:BOOL=ON \
      -DTNN_HUAWEI_NPU_ENABLE:BOOL=OFF \
      -DTNN_OPENCL_ENABLE:BOOL=ON \
      -DTNN_TEST_ENABLE:BOOL=OFF \
      -DTNN_BENCHMARK_MODE:BOOL=OFF \
      -DTNN_OPENMP_ENABLE:BOOL=OFF \
      -DSHARING_MEM_WITH_OPENGL=ON \
      -DTNN_BUILD_SHARED:BOOL=ON

  **5. 详细描述bug 情况 (Describe the bug)**
使用feature_dynamic_dims分支，arm进行推断能够完成预期结果。opencl版本无法得到预期结果
调用代码：

关键代码如下：
```
         {
                TNN_NS::NetworkConfig network_config;
                network_config.library_path = {""};
                network_config.device_type = mDeviceType;//这儿修改为opencl or arm.
                TNN_NS::InputShapesMap ism;
                TNN_NS::InputShapesMap minShape{}, maxShape{};
                minShape.insert({"image", TNN_NS::DimsVector({1, 3, 320, 640})});
                maxShape.insert({"image", TNN_NS::DimsVector({1, 3, 384, 640})});
                mTnnTnstancePtr = mTnnNetPtr->CreateInst(network_config, status, minShape, maxShape);
       }

std::shared_ptr<TNN_NS::Mat> inputMatPtr = std::make_shared<TNN_NS::Mat>(DEVICE_NAIVE, TNN_NS::NCHW_FLOAT, inputShape, mInputArrPtr->data());
//自己完成normalize和nhwc 到nchw
 hwc2chwAndNormalize(*mCopiedMatPtr, inputMatPtr->data());
auto status = mTnnTnstancePtr->SetInputMat(inputMatPtr,
                                                   TNN_NS::MatConvertParam());
        if(status == TNN_NS::TNN_OK)
            status = mTnnTnstancePtr->Forward();
```

**Comment by lnmdlong** [comment]
feature_dynamic_dims分支最近提交了opencl fp16不对齐问题的修复，commit-a04c783b没有包含这部分改动，可以用最新的分支试一下 @gofugoo
