### ISSUE TITLE
在x86下编译

### ISSUE THREAD

**Issue by weixiaolian21** [Tencent/TNN#88]
请问如何能在X86LINUX 下编译?  需要在电脑上进行模型和代码的验证.

**Comment by ZhenpengChenCode** [comment]
Same question

**Comment by gttiankai** [comment]
```shell
cd <tnn_root_path>
mkdir build
cd build
cmake ..  -DTNN_CPU_ENABLE=ON -DTNN_TEST_ENABLE=ON
make -j
./test/TNNTest -h
```

```text
    -h                      print a usage message.
    -mt "<model type>"    specify model type: TNN, OPENVINO, COREML, SNPE.
    -mp "<model path>"    specify model path: tnn proto path, openvino xml path, coreml mlmodel path, snpe dlc path.
    -dt "<device type>"   specify tnn device type: NAIVE, X86, ARM, CUDA, METAL, OPENCL, default is ARM.
    -lp "<library path>"  specify tnn NetworkConfig library_path. For metal, it is the tnn.metallib full path
    -ic "<number>"        iterations count (default 1).
    -wc "<number>"        warm up count (default 0).
    -ip "<path>"          input file path
    -op "<path>"          output file path
    -dl "<device list>"   device list(eg: 0,1,2,3)
    -th "<thread umber>"  cpu thread num(eg: 0,1,2,3, default 1)
    -it "<input type>"    input format(0: nchw float, 1:bgr u8, 2, gray u8)
    -fc "<format for compare>"output format for comparison
    -pr "<precision >"    compute precision(HIGH, NORMAL, LOW)
```

例子:
```shell
 ./test/TNNTest -dt NAIVE -mp ~/Downloads/test.tnnproto -ip ~/Downloads/input.txt -op ~/Downloads/output-tnn.txt
```
NAIVE 表示纯CPU的代码,没有任何加速的代码,一般只是用来验证模型是否运行正确.

**Comment by weixiaolian21** [comment]
> ```shell
> cd <tnn_root_path>
> mkdir build
> cd build
> cmake ..  -DTNN_CPU_ENABLE=ON -DTNN_TEST_ENABLE=ON
> make -j
> ./test/TNNTest -h
> ```
> 
> ```
>     -h                      print a usage message.
>     -mt "<model type>"    specify model type: TNN, OPENVINO, COREML, SNPE.
>     -mp "<model path>"    specify model path: tnn proto path, openvino xml path, coreml mlmodel path, snpe dlc path.
>     -dt "<device type>"   specify tnn device type: NAIVE, X86, ARM, CUDA, METAL, OPENCL, default is ARM.
>     -lp "<library path>"  specify tnn NetworkConfig library_path. For metal, it is the tnn.metallib full path
>     -ic "<number>"        iterations count (default 1).
>     -wc "<number>"        warm up count (default 0).
>     -ip "<path>"          input file path
>     -op "<path>"          output file path
>     -dl "<device list>"   device list(eg: 0,1,2,3)
>     -th "<thread umber>"  cpu thread num(eg: 0,1,2,3, default 1)
>     -it "<input type>"    input format(0: nchw float, 1:bgr u8, 2, gray u8)
>     -fc "<format for compare>"output format for comparison
>     -pr "<precision >"    compute precision(HIGH, NORMAL, LOW)
> ```
> 
> 例子:
> 
> ```shell
>  ./test/TNNTest -dt NAIVE -mp ~/Downloads/test.tnnproto -ip ~/Downloads/input.txt -op ~/Downloads/output-tnn.txt
> ```
> 
> NAIVE 表示纯CPU的代码,没有任何加速的代码,一般只是用来验证模型是否运行正确.
谢谢解答 我把这个编译好了 然后想把sample文件夹里那个armlinux的例子在电脑上编译一下,能够编译成功,但是运行会报错, TNN API ERROR:0x9000

我编译用的cmakelists:

cmake_minimum_required(VERSION 3.1)
project(TNN-demo)
message(${CMAKE_SOURCE_DIR})
# message(${TNN_LIB_PATH})

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O3 -std=c++11 -fPIC")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -std=c++11 -pthread -fPIC")
set(TNN_LIB_PATH "../../build/")
# set(CMAKE_SOURCE_DIR "")
set(TNNRoot ${CMAKE_SOURCE_DIR}/../../)
set(TNNInclude ${TNNRoot}/include)

include_directories(${TNNInclude})
include_directories(${CMAKE_SOURCE_DIR}/include)
include_directories(${CMAKE_SOURCE_DIR}/../samples)
link_directories(${TNN_LIB_PATH})


file(GLOB_RECURSE SRC "src/*.cc" "${CMAKE_SOURCE_DIR}/../samples/*.cc")

add_executable(demo_linux ${SRC})
target_link_libraries(demo_linux TNN)

找了半天没找到问题出在哪里.

**Comment by gttiankai** [comment]
从报错信息上来看，是编译选项不对，没有生成你运行平台的相应的代码。
你就是按照我的命令编译的吗？能再详细的描述下你的需求？你是具体怎么操作的吗？

**Comment by weixiaolian21** [comment]
> 从报错信息上来看，是编译选项不对，没有生成你运行平台的相应的代码。
> 你就是按照我的命令编译的吗？能再详细的描述下你的需求？你是具体怎么操作的吗？

是这样的，我想在ubuntu（x86）上编译TNN，然后编译一个例子试试。按照你的方式我把TNN编译好了编译在TNN根目录的build文件夹里，并且在里边运行 ./test/TNNTest -dt NAIVE 。。。也能够运行，显示的是一个平均的运行时间。  现在我想进行第二步，编译一个sample程序，我选择的是samples里armlinux里的那个代码，然后我按照自己的想法写了cmakelists，能够完成编译，但是在运行的时候就会报TNN API ERROR:0x9000。
现在就是没找到为什么这个程序运行不了。。。。

**Comment by gttiankai** [comment]
我大约明白你的意思了，这样吧，你去TNN的 QQ交流群里找我吧，我帮你编译起来。等你编译起来了，我把步骤再贴到这个issue 下面。

**Comment by weixiaolian21** [comment]
> 我大约明白你的意思了，这样吧，你去TNN的 QQ交流群里找我吧，我帮你编译起来。等你编译起来了，我把步骤再贴到这个issue 下面。

我加qq群了 但是没找到大佬你这个ID

**Comment by gttiankai** [comment]
我群里的名称是Lucas

**Comment by gttiankai** [comment]
经过进一步的分析，目前在x86上编译Armlinux的代码，是可以编译的。但是运行起来会报错，主要是CPU端还不支持bgr等一些图片格式。

**Comment by weixiaolian21** [comment]
最终解决, 注意两点一个是数据类型 最好都设置成NCHW_FLOAT类型,     所有的device type 设置成TNN_NS::DEVICE_NAIVE类型

**Comment by Lihit** [comment]
遇到了同样的问题，在instance_->SetInputMat(image, input_cvt_param)这一步就直接Segmentation fault

**Comment by xinchenhawaii** [comment]
> > 我大约明白你的意思了，这样吧，你去TNN的 QQ交流群里找我吧，我帮你编译起来。等你编译起来了，我把步骤再贴到这个issue 下面。
> 
> 我加qq群了 但是没找到大佬你这个ID

能把步骤贴在这吗？

**Comment by blueskywwc** [comment]
同样的问题，能贴下步骤吗，谢谢

**Comment by mkwml** [comment]
> 遇到了同样的问题，在instance_->SetInputMat(image, input_cvt_param)这一步就直接Segmentation fault

face_detector.cc文件中 auto image_mat = std::make_shared<TNN_NS::Mat>(TNN_NS::DEVICE_NAIVE, TNN_NS::N8UC3, nchw, data); 这一行数据类型不要改成float；
tnn_sdk_sample.cc文件中，把device type改成 TNN_NS::DEVICE_NAIVE，关键的一个步骤是：// step 3. get output mat

 status = instance_->GetOutputMat(output_mat, output_convert_param, name, DEVICE_NAIVE); 这一行，把默认的device type改成naive就可以了运行了。
