### ISSUE TITLE
When is a new version build planned to be released?

### ISSUE THREAD

**Issue by ofirkris** [Tencent/TNN#881]
Hello, since Oct 10, 2020 there hasn't been a new release - are you planning to release a stable version anytime soon?

**Comment by darrenyao87** [comment]
Around April 15th
New features :
1.support x86 and nvidia  
2.runtime dynamic shape 
3.support NLP models like LSTM and bert

**Comment by ofirkris** [comment]
Awesome!

**Comment by ofirkris** [comment]
@darrenyao87 do you have a new timeline for the new version?

**Comment by shaundai-tencent** [comment]
The new version was released on April 27th。 you can have a try.
