### ISSUE TITLE
TNNImageColourController gray transfer models

### ISSUE THREAD

**Issue by ozgurshn** [Tencent/TNN#883]
**Is your feature request related to a problem? Please describe.**
download_model.sh in TNNExamples does not have urls for gray transfer models (G_8_GRAY2RGB_256.tnnmodel,G_8_GRAY2RGB_256.tnnproto) used in TNNImageColourController.
This leads to  Error: proto or model path is invalid error.
Where can I find these models?

**Comment by devandong** [comment]
You can download this model in the 'Group Sharing' of the TNN QQ group: QQ Group: 913940506 Answer: TNN.

**Comment by ozgurshn** [comment]
Is it possible to download it with a direct link? It seems impossible to join qq international, it doesn't have a web version as I check. Its mobile app doesn't offer English version.

**Comment by devandong** [comment]
Coule you try this google drive link? [demo-gray_transfer.zip](https://drive.google.com/file/d/1RQWFyu0pTdME1TxWcwoY_rrSF4goX5va/view?usp=sharing)

**Comment by ozgurshn** [comment]
Thank you very much. I downloaded from this link.
