### ISSUE TITLE
 fatal error: rknpu/rknpu_pub.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by PanJinquan** [Tencent/TNN#886]
在RK3399 Pro上build 出现“../TNN/source/tnn/device/rknpu/convert/rknpu_base_layer.h:25:10: fatal error: rknpu/rknpu_pub.h: 没有那个文件或目录”

**Comment by seanxcwang** [comment]
https://github.com/Tencent/TNN/blob/master/doc/en/faq_en.md#rknpu-compilation-prerequisite
另外rk3399 pro并不支持
