### ISSUE TITLE
单通道输入模型输出nan

### ISSUE THREAD

**Issue by fire717** [Tencent/TNN#908]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu
 - RunTime OS Version:Android
 - RunTime DEVICE: ARM

  **2. Github版本**
 - branch： docker镜像转换的模型， tnn-convert:21.02.03
 - commit(optional):

  **3. 转换方式(compile method)**

sudo docker run --rm --volume=$(pwd):/workspace -it tnn-convert:21.02.03 python3 ./converter.py onnx2tnn \
    /workspace/mymodel.onnx \
    -optimize \
    -v v1.0 \
    -align  \

  **5. 详细描述bug 情况 (Describe the bug)**
1.onnx模型测试输出正常

2.转为tnn时，打印日志正常，同时显示align

3.上板运行，检查模型输入图片正常，输出h、w、c分别为1，1，143
output_mat_scores->GetHeight(), output_mat_scores->GetWidth(),output_mat_scores->GetChannel()

4.打印结果为
float *scores_data = (float *) output_mat_scores->GetData();
    for(int i=0;i<143;i++){
        lmtLog.LogLevel(YxLog::DEBUG, "GetOutputMat tmp3: %d %f", i, scores_data[i]);
    }
全部为nan

我也看到了这个类似的[issue](https://github.com/Tencent/TNN/issues/427)，我的输入也是单通道图片，于是我也修改了输入如下：

TNN_NS::DimsVector target_dims = {1, 1, MODEL_INPUT_HEIGHT, MODEL_INPUT_WIDTH};
auto tnn_mat = std::make_shared<TNN_NS::Mat>(dt, TNN_NS::NGRAY, target_dims, final_input_mat.data);

也尝试了
//    input_convert_param.scale = {1.0, 1.0, 1.0, 1.0};
//    input_convert_param.bias  = {0.0, 0.0, 0.0, 0.0};
    input_convert_param.scale = {1.0};
    input_convert_param.bias  = {0.0};

但是结果都依旧是nan，请问还有什么设置需要修改呢？

**Comment by fire717** [comment]
有理由怀疑是一个bug。理由是我只是换了模型backbone，输出就正常了。

详细来说，我的网络的backbone是shufflenetv2_1.0,出现了nan的问题，我尝试换成shufflenetv2_0.5，测试输出就正常了，其他地方未作任何修改。

附两个模型供测试
[model.zip](https://github.com/Tencent/TNN/files/6349646/model.zip)

**Comment by shaundai-tencent** [comment]
你的附件里面trained.opt.tnnproto是可以复现问题的吗？我两个模型都尝试了，没有复现问题。
请问，你跑的时候使用的是ARM还是OPENCL？是在哪个commit上面跑的？
可以试试最新的代码，我没有测出问题。

**Comment by shaundai-tencent** [comment]
请问，问题还存在吗？

**Comment by minushuang** [comment]
> 

请问这个问题最后是怎么解决的呢？或者出现该问题的原因是什么？
