### ISSUE TITLE
android demo ocr模型路径不匹配

### ISSUE THREAD

**Issue by benjaminwan** [Tencent/TNN#911]
1. 下载脚本里的路径是chinese-ocr
https://github.com/Tencent/TNN/blob/96f4813adc639e6d5304b467fc4a2bd35997e4fa/model/download_model.sh#L172

2. 代码里的路径是ocr
https://github.com/Tencent/TNN/blob/96f4813adc639e6d5304b467fc4a2bd35997e4fa/examples/android/demo/src/main/java/com/tencent/tnn/demo/StreamOCRDetector/StreamOCRDetectFragment.java#L95

会造成找不到模型的错误

**Comment by devandong** [comment]
pr#912 修复，已合并回mater
