### ISSUE TITLE
TNN android demo 一个工程里不要搞太多，编译不动

### ISSUE THREAD

**Issue by onexuan** [Tencent/TNN#915]
TNN android demo 一个工程里不要搞太多，编译不动，一直在building，希望分开子demo

**Comment by lnmdlong** [comment]
@onexuan android demo的编译瓶颈主要在TNN lib的编译，集成多demo不会导致编译时间明显增加，jni和demo java的编译耗时占总耗时的比例很小。你遇到的问题是不是每次修改demo代码，需要重新编译整个工程，如果是上述问题，TNN master上做了支持demo增量编译的优化，可以试用

**Comment by onexuan** [comment]
不是，是第一次android studio 打开demo后编译，一直building，很久，后面没运行起来

**Comment by onexuan** [comment]
刚重新试了再编译，用了build apk，睡了一觉起来，编译完成了，用时50分钟

**Comment by lnmdlong** [comment]
@onexuan 第一次编译时间过长的问题如上面回复的，瓶颈是在TNN lib的编译，这个是不同demo共用的，独立出子demo不会有明显提升，性能受限于编译环境的cpu，我的编译环境上实测用时是5分钟左右，如果要缩短第一次编译时间，可以找个cpu能力更强的编译环境生成apk，本地直接install apk即可
关于Run demo要重新编译的问题，master分支默认是增量编译的，第一次编译结束再次Run demo，只会编译有修改的文件，如果改动不大的话，编译用时不会很长

**Comment by onexuan** [comment]
OK，谢谢回复，=试试

**Comment by joe807191330** [comment]
可以手动把编译好的动态库链接过去  就不用一直编译tnn库了
