### ISSUE TITLE
convert2tnn成功align-netron可视化报错-模型init失败

### ISSUE THREAD

**Issue by FeiMiBa** [Tencent/TNN#918]
**1. 使用环境（environment）**
 - OS: Ubuntu
 - OS Version: 16.04

  **2. Github版本**
 - branch：master
 - commit(optional): ffc8c777d996d6812bf054b05a49fe3e517dc5d4

  **3. 详细描述bug 情况 (Describe the bug)**
pytorhc导出onnx，转化成tnn模型并align成功，tnn模型拖入netron报错（如下截屏），工程中加载tnn模型失败（代码、报错如下）
```txt
    std::string protoContent, modelContent;
    protoContent = fdLoadFile(model_file);
    modelContent = fdLoadFile(weights_file);

    auto net_ = std::make_shared<TNN_NS::TNN>();
    model_config.model_type = TNN_NS::MODEL_TYPE_TNN;
    //model_config.params = { protoContent, modelContent };
    model_config.params.push_back(protoContent);
    model_config.params.push_back(modelContent);
    


    status = net_->Init(model_config);
 ```

  **4. 日志（Log）**
convert2tnn并成功align 
```txt
----------  convert model, please wait a moment ----------

Converter ONNX to TNN Model...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN model succeed!

----------  align model (tflite or ONNX vs TNN),please wait a moment ----------

input.1: input shape of onnx and tnn is aligned!

Run tnn model_check...
----------  Congratulations!   ----------
The onnx model is aligned with tnn model
 ```

模型加载报错
 ```txt
E/tnn: tnn::ModelInterpreter::InterpretModel [File ..\..\source\tnn\interpreter\tnn\model_interpreter.cc][Line 383] Error: layer_interpreter nil name: type_from_str: type:0
 ```

  **5. 截图（Screenshots）**
![image](https://user-images.githubusercontent.com/60102595/115712028-da760b80-a3a6-11eb-916b-2fcdcfcc240c.png)

**Comment by FeiMiBa** [comment]
[Uploading models.zip…]()

**Comment by FeiMiBa** [comment]
[models.zip](https://github.com/Tencent/TNN/files/6358220/models.zip)

**Comment by gttiankai** [comment]
1.  更新下你的 netron 工具。
2. 我切换到你提到的 commit id 进行测试，模型是可以正常解析的。你最好保证以下你的 TNN 的版本是最新的版本。
下面的截图是我的测试结果。
![image](https://user-images.githubusercontent.com/5379313/115993593-1bb82680-a606-11eb-9b1a-92bc2845f5b1.png)
