### ISSUE TITLE
converter BlazeFace 失败

### ISSUE THREAD

**Issue by lilinxiong** [Tencent/TNN#932]
**1. 使用环境（environment）**
 - OS: Docker
 - OS Version: latest

  **2. Github版本**
 - branch：master
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type:  模型转换失败（converter failed）
 - original model： TensorFlowLite 
 https://github.com/google/mediapipe/blob/0.8.3.2/mediapipe/models/face_detection_front.tflite

  **4. 日志（Log）**
 ```txt
----------  convert model, please wait a moment ----------

Oh No, tflite2tnn failed :(
 ```

  **5. 截图（Screenshots）**
![image](https://user-images.githubusercontent.com/24367027/116544307-8b3d5700-a921-11eb-8771-14648f29a716.png)

**Comment by gttiankai** [comment]
你 Issue 中提供的 TFLite 模型是量化模型，当前 TFLite 量化模型的转换的相关功能还没有 merge 到 master 分支，你可以切换到：feature_quantized_tflite，尝试转化下这个模型。

另外 TNN 中的 BlazeFace 使用的原始模型不是 TFLite 模型，而是 Pytorch 的模型。具体链接： https://github.com/hollance/BlazeFace-PyTorch

**Comment by hengshan123** [comment]
你好，feature_quantized_tflite这个分支找不到了，是已经合并到master了吗？
