### ISSUE TITLE
CUDA version TNN running on Jetson nano

### ISSUE THREAD

**Issue by heathcliffYang** [Tencent/TNN#940]
It's not clear if scripts/build_cuda_linux.sh can build TNN library on Jetson nano (cpu is ARM) or not?

May I just turn on `TNN_ARM_ENABLE` to achieve what I want? Or this function needs some code to support it?
My goal is to run model on device cuda set and get output mat on device arm.

Thank you!

**Comment by johnzlli-tencent** [comment]
Please try to use scripts/build_cuda_linux.sh. BTW, CUDA version TNN need TensorRT libs and only TensorRT version >= 7.2 can run on arm device.
