### ISSUE TITLE
Inference speed - MobileNetV3, with V0.3.0

### ISSUE THREAD

**Issue by mayaboker** [Tencent/TNN#946]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu
 - RunTime OS Version: Android
 - RunTime DEVICE: OPENCL

  **2. Github版本**
 - branch：Release v 0.3.0

  **5. 详细描述bug 情况 (Describe the bug)**
I've been testing the new release version 0.3.0 it seem that there is significant improve in inference speed compared to older version 0.2.0. When testing Mobilenetv3 architecture I've noticed that the performance is lower (see below performance logs). I tried to drill down to layers and blocks, and found that Squeeze and Excite block with Linear op is to be blame. replacing the Linear op with Conv2d improve the inference speed back to normal and better than the older version. 

** Model Converted with latest docker tnn-convert **
Torch version: 1.6.0

Squeeze&Excite Linear (.tnnproto):
![image](https://user-images.githubusercontent.com/47945073/117788338-fc4d0a80-b24f-11eb-9a7a-79ae57e73f21.png)
Squeeze&Excite Conv2d (.tnnproto):
![image](https://user-images.githubusercontent.com/47945073/117788432-11c23480-b250-11eb-98ab-c63823a69008.png)

** Inference speed: **
Input-size: (1, 3, 112, 112)
device: Samsung Galaxy S20, with OpenCl backend.

Model | TNN version | latency (ms)
--- | --- | --- 
mv3_se_linear | 0.2.0 | 8.304 
mv3_se_linear | 0.3.0 | 28.5811 
mv3_se_conv | 0.3.0 | 6.1013

**Comment by mayaboker** [comment]
Attached pastebin of our Torch implementation of the different SE blocks: [pastebin](https://pastebin.com/k7CA4c6n)

**Comment by shaundai-tencent** [comment]
there is some difference in kernel local size calculation in v0.3.0, comparing to v0.2.0.
In v0.3.0, we can tune local size when set enable_tune_kernel true in NetworkConfig. You can have a try.
By the way, we have done a lot of optimization in Convolution. So we suggest you use the Conv2d structure.

**Comment by mayaboker** [comment]
There is a slight improvement in inference speed when setting enable_tune_kernel=true. Probably the solution will be to use the Conv2d operator instead. The MAC operations are the same for both Conv2d and Linear on input tensor with sizes {b, c, 1, 1}.

Model | TNN version | enable_tune_kernel | latency (ms)
-- | -- | -- | --
mv3_se_linear | 0.2.0 | -- | 8.304
mv3_se_linear | 0.3.0 | false | 28.5811
mv3_se_linear | 0.3.0 | true | 25.5360 
mv3_se_conv | 0.3.0 | false | 6.1013
mv3_se_conv | 0.3.0 | true | 5.2979

About the enable_tool_kernel field it seems that it improve inference speed for many architecture that we are using. I have noticed the comment in the common.h file:
```cpp
// network init or reshape may cost more time to select opt kernel implement if enable tune kernel
// cache_path can set to store tune kernel info.
bool enable_tune_kernel = false;
```
Is there an example on how to use the cache_path to store tune kernel info?

**Comment by shaundai-tencent** [comment]
You can just set enable_tune_kernel true and cache_path, and the kernel info will be store in the folder which is set by cache_path. 
Ref：https://github.com/Tencent/TNN/blob/master/doc/en/user/api_en.md#1-corecommonh

**Comment by mayaboker** [comment]
Thanks, it works really well, enable_tune_kernel is a gem, improve model inference speed by 10-20%.
Shouldn't it be true as default value?

**Comment by shaundai-tencent** [comment]
As the init time cost will be increased when enabling kernel tuning, which can not be accepted in some cases, we set it false by default so that TNN will fit all cases.
