### ISSUE TITLE
linux编译错误

### ISSUE THREAD

**Issue by zhuoran-guo** [Tencent/TNN#951]
**1. 环境（environment）**
 - Build OS and Version: Centos
 - RunTime OS Version: Linux
 - RunTime DEVICE: ARM

在centos上对tnn进行编译
cd TNN/scripts/
./build_linux.sh
报错：
[ 99%] Building CXX object test/CMakeFiles/TNNTest.dir/test.cc.o
[100%] Building CXX object test/CMakeFiles/TNNTest.dir/test_utils.cc.o
[100%] Building CXX object test/CMakeFiles/TNNTest.dir/timer.cc.o
[100%] Linking CXX executable TNNTest
../libTNN.so.0.1.0.0: undefined reference to `InferenceEngine::Core::SetConfig(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `InferenceEngine::Core::AddExtension(std::shared_ptr<InferenceEngine::IExtension>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `ngraph::Node::description[abi:cxx11]() const'
../libTNN.so.0.1.0.0: undefined reference to `InferenceEngine::Data::getName[abi:cxx11]() const'
../libTNN.so.0.1.0.0: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `ngraph::node_validation_failure_loc_string[abi:cxx11](ngraph::Node const*)'
../libTNN.so.0.1.0.0: undefined reference to `InferenceEngine::Core::LoadNetwork(InferenceEngine::CNNNetwork const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
../libTNN.so.0.1.0.0: undefined reference to `ngraph::Node::set_friendly_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `InferenceEngine::Core::Core(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `ngraph::op::v0::ROIPooling::ROIPooling(ngraph::Output<ngraph::Node> const&, ngraph::Output<ngraph::Node> const&, ngraph::Shape const&, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `ngraph::CheckFailure::make_what(ngraph::CheckLocInfo const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `ngraph::Function::Function(std::vector<std::shared_ptr<ngraph::Node>, std::allocator<std::shared_ptr<ngraph::Node> > > const&, std::vector<std::shared_ptr<ngraph::op::v0::Parameter>, std::allocator<std::shared_ptr<ngraph::op::v0::Parameter> > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [test/TNNTest] Error 1
make[1]: *** [test/CMakeFiles/TNNTest.dir/all] Error 2
make: *** [all] Error 2
 ```
执行
./build_x86_linux.sh
报错：
[ 99%] Built target TNN
Consolidate compiler generated dependencies of target TNNTest
[ 99%] Linking CXX executable TNNTest
../libTNN.so.0.1.0.0: undefined reference to `InferenceEngine::CNNNetwork::getInputShapes[abi:cxx11]() const'
../libTNN.so.0.1.0.0: undefined reference to `InferenceEngine::Core::SetConfig(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `InferenceEngine::Core::AddExtension(std::shared_ptr<InferenceEngine::IExtension>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `InferenceEngine::CNNNetwork::reshape(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<unsigned long, std::allocator<unsigned long> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<unsigned long, std::allocator<unsigned long> > > > > const&)'
../libTNN.so.0.1.0.0: undefined reference to `ngraph::Node::description[abi:cxx11]() const'
../libTNN.so.0.1.0.0: undefined reference to `InferenceEngine::details::InferenceEngineException::InferenceEngineException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `ngraph::node_validation_failure_loc_string[abi:cxx11](ngraph::Node const*)'
../libTNN.so.0.1.0.0: undefined reference to `InferenceEngine::Core::LoadNetwork(InferenceEngine::CNNNetwork const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
../libTNN.so.0.1.0.0: undefined reference to `ngraph::Node::set_friendly_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `InferenceEngine::Core::Core(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `ngraph::op::v0::ROIPooling::ROIPooling(ngraph::Output<ngraph::Node> const&, ngraph::Output<ngraph::Node> const&, ngraph::Shape const&, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `ngraph::CheckFailure::make_what(ngraph::CheckLocInfo const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../libTNN.so.0.1.0.0: undefined reference to `ngraph::Function::Function(std::vector<std::shared_ptr<ngraph::Node>, std::allocator<std::shared_ptr<ngraph::Node> > > const&, std::vector<std::shared_ptr<ngraph::op::v0::Parameter>, std::allocator<std::shared_ptr<ngraph::op::v0::Parameter> > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [test/TNNTest] Error 1
make[1]: *** [test/CMakeFiles/TNNTest.dir/all] Error 2
make: *** [all] Error 2

执行
./build_linux_native.sh
-- Found assembler: /usr/bin/gcc
/home/zhuoran.guo/tnnwork/chart-ai-framework-comparison/TNN_Bench/TNN
/home/zhuoran.guo/tnnwork/chart-ai-framework-comparison/TNN_Bench/TNN
CMake Error at /home/zhuoran.guo/cmake-3.20.0/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
Call Stack (most recent call first):
  /home/zhuoran.guo/cmake-3.20.0/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/zhuoran.guo/cmake-3.20.0/Modules/FindOpenMP.cmake:542 (find_package_handle_standard_args)
  CMakeLists.txt:154 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/zhuoran.guo/tnnwork/chart-ai-framework-comparison/TNN_Bench/TNN/scripts/build_linux_native/CMakeFiles/CMakeOutput.log".
See also "/home/zhuoran.guo/tnnwork/chart-ai-framework-comparison/TNN_Bench/TNN/scripts/build_linux_native/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.

**Comment by Maosquerade** [comment]
可以尝试在 /scripts/build_linux.sh 188行后加上 -DTNN_GLIBCXX_USE_CXX11_ABI_ENABLE=OFF
之后再次运行 build_linux.sh

**Comment by shaundai-tencent** [comment]
请问这个问题修复了吗？
