### ISSUE TITLE
The onnx model is not aligned with tnn model

### ISSUE THREAD

**Issue by abcliguanxi** [Tencent/TNN#960]
**1. 使用环境（environment）**
 - OS: x86 Centos
 - OS Version:CentOS Linux release 7.9.2009

  **2. Github版本**
 - branch：master
 - commit(optional):

  **3. 详细描述bug 情况 (Describe the bug)**
 - issue type: 加了pytorch的pixelshuffle层后出现模型不对齐（model misalignment）问题

 - original model： ONNX
 
[simulate_simplified.zip](https://github.com/Tencent/TNN/files/6494137/simulate_simplified.zip)

  **4. 日志（Log）**
 ```txt
----------  convert model, please wait a moment ----------

converting onnx to tnn
Converter ONNX to TNN Model...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN check_onnx_dim...

Converter ONNX to TNN model succeed!
----------  align model (tflite or ONNX vs TNN),please wait a moment ----------

input: input shape of onnx and tnn is aligned!

Run tnn model_check...
----------   Unfortunately   ----------
The onnx model is not aligned with tnn model
 ```

**Comment by gttiankai** [comment]
已修复，相关代码合并到 master 分支
