### ISSUE TITLE
官方镜像  onnx转tnn  报错 The /workspace/dasiamrpn_model.onnx does not exist! please make sure the file exist!

### ISSUE THREAD

**Issue by niuhaitaofeilong** [Tencent/TNN#961]
windows cmd 命令
cd /d D:\TNN-master 
docker run --volume="%cd%":/workspace -it tnn-convert:latest python3 ./converter.py onnx2tnn /workspace/dasiamrpn_model.onnx -optimize -v v3.0 -align output -input_file /workspace/in.txt -ref_file /workspace/ref.txt

报错：
The /workspace/dasiamrpn_model.onnx does not exist! please make sure the file exist!

**Comment by gttiankai** [comment]
从你的报错信息来看，是模型转换工具找不到需要转换的模型。检查你你是否挂载成功了，并且你执行上面的命令的当前目录有没有dasiamrpn_model.onnx 。

**Comment by niuhaitaofeilong** [comment]
感谢回复，我再试试

**Comment by niuhaitaofeilong** [comment]
非常感谢，听君一席话，珍惜了生命。转换成功了    命令修改为 cd /d D:\TNN-master\workspace,  后面不变， 就成功了
