### ISSUE TITLE
tnn推理结果跟ncnn推理结果不一样

### ISSUE THREAD

**Issue by jiaxiaolong** [Tencent/TNN#968]
您好，我网上下载了一个mobilefacenet（caffe）的模型，分别转换为tnn跟ncnn的模型，运行后得到的128维推理结果不一样，tnn有个参数    
MatConvertParam input_cvt_param;
input_cvt_param.scale = {2.0 / 255, 2.0 / 255, 2.0 / 255, 0};
input_cvt_param.bias  = {-1.0, -1.0, -1.0, 0.0};
在ncnn里是不需要设置的，直接加载模型后就运行得到结果了，tnn我不知道如何设置这个参数。
请问这个参数该如何设置呢？
十分期期待并感谢您的回答。

**Comment by shaundai-tencent** [comment]
这个参数决定了预处理是如何做的，要和ncnn那边意义一致才有可能对齐。参数的意义可以参考：https://github.com/Tencent/TNN/blob/master/doc/en/user/api_en.md#matconvertparam-description

**Comment by jiaxiaolong** [comment]
谢谢回复，我再研究一下
