### ISSUE TITLE
 not support axis = 3 in softmax yet

### ISSUE THREAD

**Issue by adwardlee** [Tencent/TNN#972]
**1. 环境（environment）**
 - Build OS and Version: Ubuntu
 - RunTime OS Version: Android
 - RunTime DEVICE: OPENCL

  **2. Github版本**
v0.3.0

  **5. 详细描述bug 情况 (Describe the bug)**

 virtual tnn::Status tnn::OpenCLSoftmaxLayerAcc::Init(tnn::Context *, tnn::LayerParam *, tnn::LayerResource *, const std::vector<Blob *> &, const std::vector<Blob *> &) [File /home/runner/work/TNN/TNN/source/tnn/device/opencl/acc/opencl_softmax_layer_acc.cc][Line 47] not support axis = 3 in softmax yet!

 Any plans to solve the softmax bug? Thanks.

**Comment by shaundai-tencent** [comment]
目前OpenCL端仅支持在Channel和Height方向做softmax
