### ISSUE TITLE
android下加载多个CRNN模型，模型识别出错的问题

### ISSUE THREAD

**Issue by stephonjou** [Tencent/TNN#974]
在android工程里，加载了两个crnn模型做OCR识别，一个专门是数字、一个专门识别汉字，现在出现的问题是对于同一输入，数字识别模型有时可以正常识别，有时识别问空。请问这是怎么问题？

**Comment by shaundai-tencent** [comment]
可以通过以下步骤一步步排查问题：
1、排查转出来的TNN模型是否正确，具体是跟onnx模型结果做对比。可以通过在模型转换的时候加上 -align 参数来校验，TNN的模型结果是否和onnx模型结果一致。
2、确定具体TNN执行推理的平台结果是否正确。可以通过model_check工具进行排查（https://github.com/Tencent/TNN/blob/master/doc/cn/development/model_check.md），通过-d指定需要运行的平台，最终看此平台结果是否与模型的参考输出结果一致。
3、如果上述都没有问题，那说明问题不在TNN这边，有可能在预处理或者后处理部分。可以参考的工程进行对比，是不是送入模型的数据有问题。或者模型的输出数据的处理有问题。
