### ISSUE TITLE
Does OPENCL support batchsize > 1?

### ISSUE THREAD

**Issue by mayaboker** [Tencent/TNN#977]
1. 环境（environment）

Build OS and Version: Ubuntu
RunTime OS Version: Android
RunTime DEVICE: OPENCL
2. Github版本

branch：Release v 0.3.0
5. 详细描述bug 情况 (Describe the bug)

I'm trying to run inference of a MobileNetV3 model with batch-size bigger than 1.
When running on OPENCL device only when the batch-size is 1, the result are good, when batch > 1, I get wrong output with Nan.
When running on ARM, the output is good for batch > 1.

Model Converted with latest docker tnn-convert.
Torch version: 1.6.0

Please find the tnn models attached. [models.zip](https://github.com/Tencent/TNN/files/6528278/models.zip)

thanks

**Comment by lnmdlong** [comment]
@mayaboker 基于v0.3.0版本和提供的模型，测试的commit是491dfc8，没有复现OPENCL推理结果为Nan的问题，可以基于 https://github.com/Tencent/TNN/blob/master/doc/en/development/model_check_en.md#1-android 跑下model_check，提供下测试结果的截图

**Comment by mayaboker** [comment]
I've looked up for the cause of the issue and found out bug is from the Squeeze and Excite block.
The SE residual branch end with an HardSigmoid op, then there is a final multiplication with the original input to the SE block.
```python
class h_sigmoid(nn.Module):
    def __init__(self, inplace=True):
        super(h_sigmoid, self).__init__()
        self.relu = nn.ReLU6(inplace=inplace)

    def forward(self, x):
        return self.relu(x + 3) / 6

class SELayer(nn.Module):
    def __init__(self, channel, spatial, reduction=4):
        super(SELayer, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.fc = nn.Sequential(
                nn.Conv2d(channel, _make_divisible(channel // reduction, 8), kernel_size=1, padding=0, bias=False),
                nn.ReLU(inplace=True),
                nn.Conv2d(_make_divisible(channel // reduction, 8), channel, kernel_size=1, padding=0, bias=False),
                h_sigmoid()
        )

    def forward(self, x):
        y = self.avg_pool(x)
        y = self.fc(y)
        return x * y
```
This is the original model graph with the bug converted to TNN. The converter interpreted this operation to an HardSwish with 2 inputs which one of them is th SE input. usually HardSwish op receive only one input:
```python
class h_swish(nn.Module):
    def __init__(self, inplace=True):
        super(h_swish, self).__init__()
        self.sigmoid = h_sigmoid(inplace=inplace)

    def forward(self, x):
        return x * self.sigmoid(x)
```

![image](https://user-images.githubusercontent.com/47945073/119838348-03d90880-bf0c-11eb-8443-03ca365ceccc.png)

Again this version wouldn't work with the unique combination of Batch > 1 and OpenCL.
I've tried many versions finaly to solve this problem I've added an Upsample-nearest op after HardSigmoid to reshape from {B,C,1,1} to {B,C,H,W}, to finally multiply two tensor with the same sizes. The new graph look quite different:

```python
class SELayer(nn.Module):
    def __init__(self, channel, spatial, reduction=4):
        super(SELayer, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.fc = nn.Sequential(
                nn.Conv2d(channel, _make_divisible(channel // reduction, 8), kernel_size=1, padding=0, bias=False),
                nn.ReLU(inplace=True),
                nn.Conv2d(_make_divisible(channel // reduction, 8), channel, kernel_size=1, padding=0, bias=False),
                h_sigmoid(),
                nn.Upsample(scale_factor=spatial, mode='nearest')
        )

    def forward(self, x):
        y = self.avg_pool(x)
        y = self.fc(y)
        return x * y
```
![image](https://user-images.githubusercontent.com/47945073/119839752-143db300-bf0d-11eb-9280-705c91ad49ec.png)

**Comment by lnmdlong** [comment]
@mayaboker 
First, the model converter of TNN interpreted your origin model to an HardSwish with 2 inputs. The reason is that TNN fuse HardSigmoid + Mul to HardSwish.
HardSwith with one input: y = x0 * clip(x0 * alpha + beta, 0, 1)
HardSwith with two inputs: y = x0 * clip(x1 * alpha + beta, 0, 1) = x0 * HardSigmoid(x1)
Since one of the inputs is the SE input, it is equivalent to HardSigmoid + Mul in your origin model.

Second, SE block wouldn't work with the unique combination of Batch > 1 and OpenCL. I checked with the OpenCL backend and found that there is an implementation problem. It was fixed on another branch while it hadn't been merged into master. I created a branch which fixed the problem from master. You can have a try. No need to add Upsample op to get a correct result.

Branch: hotfix_issue_977
commit: 7bda74c468605078b61a9e9165d1aae3fba756b9
