### ISSUE TITLE
如何给TNN模型指定的层 设定新的参数

### ISSUE THREAD

**Issue by niuhaitaofeilong** [Tencent/TNN#982]
**1. 环境（environment）**
 - Build OS and Version: Windows
最近再利用TNN 给单目标跟踪算法推理加速。
单目标跟踪模型DaSiamRPN，算法中有这样一步操作：
    Mat cls1 = siamKernelCL1.forward();
    Mat r1 = siamKernelR1.forward();
    std::vector<int> r1_shape = { 20, 256, 4, 4 }, cls1_shape = { 10, 256, 4, 4 };
    //onnx
    siamRPN.setParam(siamRPN.getLayerId("65"), 0, r1.reshape(0, r1_shape));
    siamRPN.setParam(siamRPN.getLayerId("68"), 0, cls1.reshape(0, cls1_shape));

现在已将跟踪模型成功转换为TNN模型，那如何给TNN模型指定的层 设定新的参数，
即等同于 onnx模型的这步操作：
     siamRPN.setParam(siamRPN.getLayerId("65"), 0, r1.reshape(0, r1_shape));
请指教！

**Comment by shaundai-tencent** [comment]
目前TNN模型转换成功之后，支持执行时动态改变输入的shape，对于模型中的参数，没有接口可以动态改变。
