### ISSUE TITLE
是否支持在pytorch进行qat训练呢？

### ISSUE THREAD

**Issue by wangxi123** [Tencent/TNN#990]
请问下现在支持在pytorch框架中做qat训练，然后tnn做ptq这样的量化流程么？
如果支持，如何配置qconfig以及插入量化及反量化层呢

**Comment by gttiankai** [comment]
1. QAT 和 PTQ 不能同时用。 
2. 目前 TNN 只支持 TFLite 的量化模型（int8 ,对称量化），Pytorch 官方导出的QAT 量化模型还不支持。
