### ISSUE TITLE
关于RK NPU的支持(rk 3399Pro)

### ISSUE THREAD

**Issue by TUT-jiayou** [Tencent/TNN#994]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by seanxcwang** [comment]
tnn基于rknpu_ddk，这个不支持3399pro

**Comment by biyuehuang** [comment]
RK3399Pro的NPU 和 RK1808 是同款NPU，TNN应该支持RK3399Pro吧。
https://t.rock-chips.com/forum.php?mod=viewthread&tid=101&extra=&page=5
