### ISSUE TITLE
Does TNN support TensorFlow/PyTorch's QAT model?

### ISSUE THREAD

**Issue by lee-bin** [Tencent/TNN#996]
Does TNN support TensorFlow/PyTorch's QAT model? Does it support 8 bit or 16 bit? int8 or uint8? symmetric or asymmetric?
https://www.tensorflow.org/model_optimization/guide/quantization/training
https://pytorch.org/docs/stable/quantization.html#quantization-aware-training

**Comment by gttiankai** [comment]
TNN supports the QAT TFLite model but does not support the Pytorch QAT model. TNN only support int8 symmetric
