### ISSUE TITLE
unitest opencl not support 

### ISSUE THREAD

**Issue by daming5432** [Tencent/TNN#998]
当我跑unitest程序时，到卷积测试时会有如下情况
[File /Work/Paddle-Lite/TNN_lite/test/unit_test/layer_test/layer_test.cc][Line 336] input blob_converter failed (code: 0x1000 msg: convert type not support yet)
不支持Opencl的单测吗？

**Comment by lnmdlong** [comment]
@daming5432 测试的分支和平台是什么，有修改测试逻辑吗，上面的报错应该是传入的Mat不合法导致的

**Comment by shaundai-tencent** [comment]
此问题已经在最新的Master（commit id: c60acb99a98db43c96bf8e06a65913b301f9cb5e）中修复，可以重新尝试一下.
