### ISSUE TITLE
请教链接RKNPU库编译问题

### ISSUE THREAD

**Issue by jiaxiaolong** [Tencent/TNN#999]
您好，我按照编译步骤设，编译脚本如下设置
SHARED_LIB="ON"
ARM="ON"
OPENMP="ON"
OPENCL="OFF"
RKNPU="ON"
CC=arm-linux-gnueabihf-gcc
CXX=arm-linux-gnueabihf-g++
TARGET_ARCH=arm
下载RKNPU的库放到相应的文件夹下，成功编译出libTNN.so 动态库。
但是将libTNN.so及RKNPU的库链接到工程编译时报如下错误

arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `DeconvFloatO4'
arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `ConvDw3x3FloatSlideW'
arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `GemmBfp16SlidewC3'
arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `ConvFloatO4'
arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `ConvDw5x5Bfp16SlideW'
arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `ConvDw5x5FloatSlideW'
arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `GemmFloatSlidewC3'
arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `ConvBfp16O4'
arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `ConvDw3x3Bfp16SlideW'
arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `GEMM_FLOAT_N4'
arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `GemmInt8Unit4x8'
arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `GEMM_BFP16_N4'
arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `GemmInt8Unit4x4'
arm-linux-gnueabihf/bin/ld: /home/ben/myproject/rv1109/QFacialGate-1.0/tnn/lib//libTNN.so: undefined reference to `DepthwiseI8K3S1Kernel'

我检查了RKNPU的库文件，确实没有这些函数的实现，请问是否我交叉编译libTNN.so时，哪里配置不正确了？
谢谢您的回复帮助。

**Comment by seanxcwang** [comment]
可以把完整的编译log发一下，另外rknpu目前只支持rk1808

**Comment by jiaxiaolong** [comment]
> 可以把完整的编译log发一下，另外rknpu目前只支持rk1808

不好意思，我加上“Add -DTNN_RK_NPU_ENABLE:BOOL=ON to <path_to_tnn>/scripts/build_armhf_linux.sh and execute it”这个重新编译然后可以了，谢谢您。

**Comment by jiaxiaolong** [comment]
> 可以把完整的编译log发一下，另外rknpu目前只支持rk1808

不好意思，我加上“Add -DTNN_RK_NPU_ENABLE:BOOL=ON to <path_to_tnn>/scripts/build_armhf_linux.sh and execute it”这个重新编译然后可以了，谢谢您。

**Comment by seanxcwang** [comment]
> > 可以把完整的编译log发一下，另外rknpu目前只支持rk1808
> 
> 不好意思，我加上“Add -DTNN_RK_NPU_ENABLE:BOOL=ON to <path_to_tnn>/scripts/build_armhf_linux.sh and execute it”这个重新编译然后可以了，谢谢您。

ok，那close了
